### PR TITLE
Github156

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
Github issue 156: https://github.com/Unidata/netcdf-c/issues/156

Modified ncgen to properly handle the L and UL suffixes for integer constants
to keep backward compatibility. Now it is the case the single L suffix
(e.g. 111L) is treated as a 32 bit integer. This makes it consistent with
the fact that NC_LONG (netcdf.h) is an alias for NC_INT.
It is probable that .cdl files now exist that assumed that L prefix was
64 bits. This will cause problems.

Primary changes:
- ncgen.l - fix lexing involving L/LL suffix.
- misc. test cases: either .cdl files, or ncdump reference files or .c files.
- semantics.c: to fix type inference rules for untyped attributes
- ncdump/ncdump.c: the code was dumping constant text using the L prefix.

### CODE REVIEW

**Comment by WardF** [comment]
Ok, I don't know what's going on, all of the tests are working in Docker, but I'm seeing some core dumps on my local platform.  I'm sure it's something specific to my environment. Trying to sort it out now.  In other news, not a lot going on in Arkansas right now.

**Comment by WardF** [comment]
Ok, this issue is only showing up on OSX, but I think I've narrowed it down.  The issue is in `collecttag`, on the following line:  

 ncgen.l:838 strncpy(stag,stag+1,MAXTAGLEN+1);

From `$ man strncpy`

>  The source and destination strings should not overlap, as the behavior is
     undefined.

So, I think we're being hit by this undefined behavior in this instance.  I'm addressing it now and will get everything merged in :).  Thanks again!

**Comment by DennisHeimbigner** [comment]
you could switch to using memmove, just remember to include the trailing nul.

**Comment by WardF** [comment]
Not a bad idea; I patched in a quick fix using a temporary variable and a note to revisit with memmove or similar when I wasn't preoccupied watching kids :). I'm curious what is happening under the hood on Linux. Mechanically this shouldn't be an issue, although I see why the behavior is undefined.

Thanks for the rapid fix, I'm really hoping to get the 4.4 release behind us asap! :). Have a great Thanksgiving.

**Comment by DennisHeimbigner** [comment]
It depends, I suppose, on the direction
of the move (down in this case) and
the algorithm (start at front of string vs end of string).
memmove I guess is the only function guaranteed to operate
correctly.
=Dennis


Ward Fisher wrote:
> Not a bad idea; I patched in a quick fix using a temporary variable and a note to revisit with memmove or similar when I wasn't preoccupied watching kids :). I'm curious what is happening under the hood on Linux. Mechanically this shouldn't be an issue, although I see why the behavior is undefined.
> 
> Thanks for the rapid fix, I'm really hoping to get the 4.4 release behind us asap! :). Have a great Thanksgiving. 
> 
> Sent from my iPhone
>

**Pull request merged**
