### PR TITLE
Remove pointer to NC from open/create in the dispatch table

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #1426 

In this PR I remove pointer to NC from open/create in the dispatch table, and all dispatch layers.

@DennisHeimbigner note the changes in libdap2/libdap4. I have copied the local coding style.

This allows us to provide the dispatch tables without exposing the NC struct. Now, only primitive C types, and a pointer to the dispatch table itself, are found in the dispatch table.

This was quite easy and simple. The dispatch layer creates the ncid (which we sometimes call ext_ncid). Some layers (like the classic netcdf, and pnetcdf) can also use the int_ncid internally. This PR does not touch anything to do with the int_ncid.

This PR includes pending PR #441 

This PR also turns off the currently failing tst_zero_len_var.sh in both autotools and cmake builds (see #1449). Once that issue is resolved I can turn that test back on.

### CODE REVIEW

**Comment by WardF** [comment]
Just FYI, the opendap test server appears to be back up and running as of a few moments ago.

**Comment by edwardhartnett** [comment]
Did a little more refinement to clean up the code.

@WardF thanks for marking this for 4.7.1. These changes will be necessary for PIO integration to work. They also enable much fuller use of the user defined format feature.

**Comment by edwardhartnett** [comment]
@WardF maybe you could relaunch this? The dap test servers seem to be a bit wonky today...

**Comment by edwardhartnett** [comment]
OK, various failures in different jobs each time in ncdap testing. Something is wonky with the server, or else timeouts need to be increased.

Also, @WardF, I suggest you add --disable-dap to some of the travis tests, so the servers don't get so hammered each time.

**Comment by DennisHeimbigner** [comment]
I really wish you had not done this without more discussion.

**Comment by WardF** [comment]
@DennisHeimbigner Is there an issue? We can take a look and address issues now.

**Comment by edhartnett** [comment]
Without this, user-defined format users would have to see the contents of the NC struct.

**Comment by DennisHeimbigner** [comment]
I understand the need for something like this. Well, it is too late now.
It is simpler to move forward with this change in place.

**Pull request merged**
