### PR TITLE
Fix ncgen handling of big data sections

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
The current ncgen does not properly handle very large
data sections. Apparently this is very uncommon because
it was only discovered in testing the new zarr code.

The fix required a new approach to processing data sections.
Unfortunately, the resulting ncgen is slower than before
but at least it is, I think, now correct.

The added test cases are in libnczarr, and so will
not show up until that is incorporated into master.

Note also that fortran code generation changed, but
has not been tested here.

Misc. Changes
1. Cleanup error handling in ncgen -lc and -lb output
2. Cleanup Makefiles for ncgen to remove unused code
3. Added a program, ncgen/ncdumpchunks, to print
   the data for a .nc file on a per-chunk format.
4. Made the XGetOpt change in PR https://github.com/Unidata/netcdf-c/pull/1694
   for ncdump/ncvalidator

### CODE REVIEW

**Comment by WardF** [comment]
Hi Dennis, can you elaborate on "ncgen does not properly handle very large data sections" in terms of what the problem was/how it might manifest?

**Comment by DennisHeimbigner** [comment]
I can, but it would take a lot of space; its complicated.

**Comment by WardF** [comment]
Ok, I'll ask you about it offline; I'm curious, but no need to fill things up here.

**Comment by DennisHeimbigner** [comment]
You are right that the details should be somewhere, but I am not
sure where it should go.

**Comment by WardF** [comment]
A summary in the release notes in terms of how the error would manifest (data corruption, slow writes, etc) wouldn't go amiss, and we can have a discussion about the technical aspects later, maybe?

**Comment by DennisHeimbigner** [comment]
ok

**Comment by DennisHeimbigner** [comment]
See revised RELEASE_NOTES.

**Comment by WardF** [comment]
Thanks Dennis!

**Pull request merged**
