### PR TITLE
new method of using valgrind

### LINKED ISSUE #873: Remove --enable-valgrind-tests, and valgrind test scripts, but continue to support valgrind tools
There is a build option --enable-valgrind-tests. If used (only works with --disable-shared), some extra tests scripts will run. These will rerun a subset of the tests using valgrind, to check for memory leaks.

Currently it is broken, BTW. Some of the tests have been moved or removed. Fixing it would not be hard, but it would still break for parallel builds, unless we also add a bunch of dependency info to the Makefile.am and CMakeLists.txt files.

However, instead of fixing it, I think the valgrind testing should just be removed, including the configure option, the test scripts that run valgrind, and the code in Makefile.am and CMakeLists.txt which deal with it.

I added this to get some automatic memory checking, and it was useful for that. But now we have the address sanitizer built right into gcc. It is more sensitive than valgrind, gives better error messages, and only requires some extra CFLAGS.  - no extra tests scripts to maintain. No dependencies need be tracked, and every new test is automatically added to the memory checking, just by being part of the build. So it is superior in every way.

I am running several address sanitizer runs as part of my CI. So the valgrind tests are not needed.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #873.

This PR introduces a new way to do valgrind.

A macro has been added to acinclude.m4 from the autoconf community, which looks for valgrind on build machines. If present, extra valgrind targets are added. So unlike the old method, this does not change what make check does.

Make check will do the same as it does without valgrind. To use valgrind, make some of the new targets. For example:

`make check-valgrind-memcheck 
`
Will run the memory checking in each directory where testing is enabled.

I have enabled valgrind testing for nctest, nc_test, nc_test4, and hdf4_test.

In order to add the valgrind test targets to a directory, simply add the following to the Makefile.am:

```
# If valgrind is present, add valgrind targets.
@VALGRIND_CHECK_RULES@

```

### CODE REVIEW

**Comment by edhartnett** [comment]
Unfortunately the current trunk fails valgrind for nc_test.

I am running in other directories to see how it does.

**Comment by WardF** [comment]
Thanks, looks great. This appears similar to the various cmake 'MemCheck' targets.

**Comment by DennisHeimbigner** [comment]
Now we need some way to do something similar for programs invoked
in shell scripts. I should be able to add something to test_common.in
to allow this.

**Comment by edhartnett** [comment]
I am seeing several failures currently on master.

I am in favor of increased valgrind testing, but recall that many of the script-based tests use ncdump/ncgen, which will fail. There are a few test programs that are run directly in the shell scripts (i.e. without ncgen/ncdump.)

It would be good to get the current failures fixed, and for you guys to add valgrind testing to your CI system(s) if possible. I am running asan regularly, and will add valgrind, but you'll want to test this in-house I'm sure.

I am looking into the current failures now...

**Pull request merged**
