### PR TITLE
Fix race condition in ncdump (and other) tests.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: Issue https://github.com/Unidata/netcdf-c/issues/2551

[dopplershift](https://github.com/dopplershift) identified the use of a common scratch file (tmp.cdl) across multiple test shell scripts in ncdump directory and the nczarr_test directory.
This sometimes causes errors because of race conditions between those scripts.

I renamed those common files to avoid the race condition.  I also did some further checking and found some additional, similar conflicts and fixed those. Also did some minor cleanup of unused files.

Tests fixed:
ncdump: run_back_comp_tests.sh tst_bom.sh tst_nccopy4.sh tst_nccopy5.sh
nczarr_test: run_nccopyz.sh run_nczarr_fill.sh run_scalar.sh

### CODE REVIEW

**Comment by WardF** [comment]
@DennisHeimbigner A couple of conflicts exist, if you could take a quick look.  Also, is the problem in the test scaffolding (i.e. the tests need to be fenceposted to avoid race states), or is there a problem in the DAP4 code that needs to be fixed? If the former, I'm happy to go in and make the changes so that 'X must run after Y' occurs.  If the latter, what would it take to fix the issue so that we can leave the test on? Turning off failing tests that are reflecting problems in the code isn't ideal, and we aren't in any particular time crunch where we can't fix this.  

Let me know how we should proceed, thanks!

**Comment by WardF** [comment]
Perhaps I've misinterpreted; it looks like DAP4 is being turned off by default, but that doesn't mean we can't explicitly turn them on in the testing.  My apologies if I misread that, my first thought was that we were removing the DAP4 tests from the equation.

**Comment by DennisHeimbigner** [comment]
I merged that other PR into this; I forgot that it shut off DAP4.
So we need to just disable the DAP4 tests, is that correct?

**Comment by WardF** [comment]
@DennisHeimbigner Do we need to turn them off? Ideally we can leave DAP4 on, and the DAP4 tests on.

**Comment by DennisHeimbigner** [comment]
I am working on the conflicts now.

**Comment by DennisHeimbigner** [comment]
I thought the DAP4 tests were not working. If they are ok, then
we can leave DAP4 on. I will restore to the way it was.

**Comment by WardF** [comment]
I'm not noticing DAP4 failures in our workflow or on my local machine, just in the conda-forge stack I think it was? Which means the issue is one we should be able to sort out without turning them off, ideally.  If they *must* be turned off, that should happen in the libnetcdf-feedstock test scaffolding, not here (I would think).  But perhaps I'm conflating issues.

**Comment by WardF** [comment]
@DennisHeimbigner I think I've got it sorted out, the DAP4 tests *were* failing but the fix I back-propagated from `v4.9.1-wellspring.wif` fixed it, so we can leave DAP4 on.  We can still merge this once the tests are passing, because we need the fix for the race conditions, in order for libnetcdf-feedstock to work.

**Comment by DennisHeimbigner** [comment]
Ok.
1. restored DAP4
2. fixed conflicts

**Comment by WardF** [comment]
Sounds good, I'll merge as soon as the tests finish, thanks @DennisHeimbigner !

**Pull request merged**
