### PR TITLE
Fix errors when building on big-endian machine

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes https://github.com/Unidata/netcdf-c/issues/1278
* Fixes https://github.com/Unidata/netcdf-c/issues/876
* Fixes https://github.com/Unidata/netcdf-c/issues/806

* Major change to the handling of 8-byte parameters for nc_def_var_filter.
  The old code was not well thought out.
  * The new algorithm is documented in docs/filters.md.
  * Added new utility file plugins/H5Zutil.c to support
  * Modified plugins/H5Zmisc.c to use new algorithm
  the new algorithm.
  * Renamed include/ncfilter.h to include/netcdf_filter.h
    and made it an installed header so clients can access the
    new algorithm utility.
  * Fixed nc_test4/tst_filterparser.c and nc_test4/test_filter_misc.c
    to use the new algorithm
* libdap4/ fixes:
  * d4swap.c has an error in the endian pre-processing such
    that record counts were not being swapped correctly.
  * d4data.c had an error in that checksums were being computed
    after endian swapping rather than before.
* ocinitialize() was never being called, so xxdr bigendian handling
  was never set correctly.
  * Required adding debug statements to occompile
* Found and fixed memory leak in ncdump.c

Not tested:
* HDF4
* Pnetcdf
* parallel HDF5

### CODE REVIEW

**Comment by t-b** [comment]
@DennisHeimbigner The DAP tests are still failing on MIPS at commit (3a14251dd9561bb419633452bb19716d09f8f939 Merge branch 'master' into bigend.dmh).

Log files: [test-suite-logs.tar.gz](https://github.com/Unidata/netcdf-c/files/2848808/test-suite-logs.tar.gz)

Invocation: 
```bash
#!/bin/sh

./bootstrap
CFLAGS="`pkg-config --cflags hdf5`" LDFLAGS="`pkg-config --libs-only-L hdf5`" ./configure

make

make check

logfiles=`find . -iname test-suite.log`
tar czf test-suite-logs.tar.gz $logfiles
```

**Comment by DennisHeimbigner** [comment]
It looks like some of the changes I made on qemu did not
get propagated to github. Fixed now.

**Comment by WardF** [comment]
Thanks @DennisHeimbigner reviewing now!

**Comment by t-b** [comment]
Updated test log. I'm still seeing one error in `test_remote.sh`.

[test-suite-logs.tar.gz](https://github.com/Unidata/netcdf-c/files/2855652/test-suite-logs.tar.gz)

**Comment by DennisHeimbigner** [comment]
Unfortunately, I was never able to get networking to work under qemu,
so I did not test this.

**Comment by DennisHeimbigner** [comment]
I think I see the problem. Can you test it out for me?
Try this on qemu"
1. edit the file libdap4/d4meta.c
2. about line 833, change the line
	converter->i8[0] = s[0];
   to
	converter->i8[7] = s[0];

**Comment by t-b** [comment]
@DennisHeimbigner I've made that change. Let's see what we get.

**Comment by t-b** [comment]
@DennisHeimbigner I think that worked. [test-suite-logs.tar.gz](https://github.com/Unidata/netcdf-c/files/2861729/test-suite-logs.tar.gz)

**Comment by DennisHeimbigner** [comment]
Ok, I will PR this shortly.

**Comment by DennisHeimbigner** [comment]
Fixed by PR https://github.com/Unidata/netcdf-c/pull/1321

**Pull request merged**
