### PR TITLE
Max var dim

### PR DESCRIPTION
**Pull request by gsjaardema**
Related to the discussion in #148.

Adds two defines "NC_IGNORE_MAX_DIMS" and "NC_IGNORE_MAX_VARS" which can be passed in the cmode argument of the nc_open call.  If present, then the application is verifying that it knows that it is creating a non-standard netcdf classic file which may not work correctly with some tools.  If one or both of the defines are present, then the checks when adding a new dimension or variable will not abort if the dimension count exceeds NC_MAX_DIMS or the variable count exceeds NC_MAX_VARS.

Note that any tools that cannot handle a classic file with dimensions or variables exceeding the NC_MAX_VARS or NC_MAX_DIMS values will likely also fail if given a non-classic file with the same dimension and/or variable count, so I don't think that this patch is as bad as it may seem initially.

The alternative of just creating non-classic netcdf-4 based files (using hdf5) is not always desireable due to file sizes, output speed, need to use parallel-netcdf, or that fact that some of our clients want just the netcdf library without the issues involved in also building hdf5.  (This is not a complaint about netcdf-4 based on hdf5; we use it a lot and like the added functionality it gives us).

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
I still object to any form of IGNORE.
=Dennis Heimbigner


Greg Sjaardema wrote:

**Comment by WardF** [comment]
This will bear some internal discussion; my previous thoughts on the matter haven't changed, but we have our netcdf meeting later this week (I think), so I will have to refresh my memory before then.

**Comment by gsjaardema** [comment]
Just to be clear -- The number of "non-standard" netcdf files that will be created will not change as a result of this patch.  If the patch is not accepted, users of exodus and moab libraries will continue to pull the netcdf source code, modify the NC_MAX_VARS and NC_MAX_DIMS defines in netcdf.h and then compile their own local version of the netcdf library.  Hopefully they will have their dynamic library paths set correctly so that their modified library is used instead of the system-installed library.  They will then generate potentially non-standard netcdf files.

The primary reason for submitting this patch is make it possible for exodus and moab users to be able to use the system-installed netcdf library which will hopfully reduce confusion as to why multiple libraries are needed...  In the past when static libraries were the most common use, this wasn't as big a problem; however, with the increased use of dynamic libraries, the possibility of using the wrong library becomes more common.

I agree that this isn't optimal, but the approach of increasing NC_MAX_VARS and NC_MAX_DIMS was also rejected even though the only backward compatibility issue is a potential increase in memory usage and many other changes over the years have increased the size of the library also causing potential memory increases.  I would prefer this option since it would alleviate issues of tools potentially not being able to access the files.

If you have other suggestions, (other than don't use classic) please let me know and I will provide a patch.

**Comment by WardF** [comment]
If I were convinced this was the path we wanted to take, I'd still have concerns about accepting this pull request.  It doesn't capture the state of whether or not the defines were ignored in the metadata of the resultant files.  This could result in netcdf being unable to read certain netcdf files, with no indication as to why the file is apparently corrupt.   For this reason, I'd think we'd need to capture this information as a global attribute for diagnostic/forensic issues that might arise.

Ignoring global attributes and leaving these maximum values to be limited by the machine architecture, with no information captured regarding what those maximums might be, could also lead to files which are now machine/platform/architecture dependent.   Going back to our previous conversation, this isn't something we can do.

It seems like we would need to define a new data type, `NC_NOLIMITS` for example, that we could safely use for this purpose.  It would be similar to the existing file type, except it wasn't defined by these limits (whether they are enforced or not).

**Comment by gdsjaar** [comment]
I agree that there should be some indication that a file has a variable or dimension count which exceeds the values of NC_MAX_VARS or NC_MAX_DIMS.  My thoughts were that the values in the *READING* library would be used for that warning.  In that case, the file itself would have no indication, but when it was opened for reading it would check the variable and dimension count; compare those against the NC_MAX_VARS and NC_MAX_DIMS values and if either was exceeded, a warning or error could/would be returned from the ex_open command.

This isn't optimal though since a reading application could easily be written to handle this case, so it shouldn't error out just because of the counts being exceeded.  A warning being printed would probably be better.  An application that didn't want the warning to be output could pass the NC_IGNORE_MAX_DIMS and NC_IGNORE_MAX_VARS flags to the ex_open call similarly to the ex_create calls.

I haven't looked at the computational cost of counting the dims and vars, but if it is relatively cheap, it could be done during ex_open to provide this check.

I'm not sure I understand the paragraph about the maximum values being limited by machine architecture.  As I see it, the only limit would theoretically be the maximum value of an integer which is used to return the counts.  There are some potential memory issues, but I can currently generate a netcdf file that is too large to be read on certain machines even if I don't exceed the dimension and variable counts.  If you could explain further what you mean in that paragraph, it would be helpful.

The other benefit of the counts being compared at read time is that this would open the possibility of changing the values of NC_MAX_VARS and NC_MAX_DIMS in the future; it also fits in better with the value of NC_MAX_VARS being a *suggested* maximum instead of an absolute maximum as it states in the documentation and the source code.

If you want me to pursue a pull request that prints the warning on read, let me know.
..Greg


--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by WardF** [comment]
Hi Greg,

I spent some time last night thinking about how I would tackle this problem; it is a sticky one and I am not unsympathetic.  I would like very much to see the issue resolved for the exodus database.  It occurred to me that I have solved a similar problem in the past by wiring in some preprocessing (via a shell script) into my build system.  To this end, I've taken some time this morning to write a script that I feel might be a good compromise for what you need, and what we're able to offer.  You can view the script at the following link, and I'll describe it below:

* https://gist.github.com/WardF/8366f813ab6bd136285f#file-build-custom-netcdf4exodus-sh

This script takes 3 arguments:

* -d [custom max dims value]
* -v [custom max vars value]
* -t [custom target name]

e.g.,

    $ ./build-custom-netcdf4exodus.sh -d 65536 -v 8192 -n exodus-netcdf

> This would result in a new directory, `exodus-netcdf/`, in the same directory from which the script was run.  Inside `exodus-netcdf/lib/`  you would find `libexodus-netcdf.a`.  `exodus-netcdf/include/` would contain `netcdf.h` as expected.  More on that below.


This script downloads the latest release, `v4.3.3.1`, modifies the NC_MAX values as specified, and then modifies the build system to build `libcustomname.a` instead of `libnetcdf.a`.  It *then* configures and builds this custom netcdf as static a static library, without netcdf4, without dap, and without the utilities. The custom library is finally installed in `current-directory/$(customname)`, with the usual `lib/`, `include/`, `man/`, directories.

The idea is that this script could be bundled into the Exodus source code.  It would be used to build the modified version of netcdf which Exodus depends on, *and* use a different library name to avoid collisions.  Exodus could then be told to use the library in this directory instead of searching out a system-wide netcdf to link against.

Note that there is room for improvement; I have simply run out of time to work on refining it further.  For example, `v4.3.3.1` is currently the latest release, but it is hard-coded and would be updated to keep in sync with netcdf releases, for example.  Also, it still installs `netcdf.h` instead of `customname.h`.  This may actually be desirable.  Finally, the utilities do not build because their `Makefile.am` files would need to be preprocessed to link against the customized `.la` files.  I simply didn't have time to take the script that far this morning.

So, does this look like it might be useful?

**Comment by WardF** [comment]
Naturally, my example above fails due to the `-` in `exodus-netcdf`.  Exclude the dash, clearly the script isn't as polished and bullet-proof as I'd like, but it's what I could do in a couple of hours :).

**Comment by gsjaardema** [comment]
I definitely appreciate your work on this, but I am still a little confused
as to why there cannot be a solution in the NetCDF canonical library.

Maybe you could restate for me what backwards compatibility will be broken
by changing the NC_MAX_VARS and NC_MAX_DIMS values which was the start of
this entire issue.

..Greg

**Comment by WardF** [comment]
Hi Greg,

The main issue is that it's just not a change we're likely to make anytime soon; the existing, historical values were chosen for a reason and I am loathe to change them for existing formats without being convinced absolutely that it benefits the netCDF/Unidata community, and that we aren't going to break any existing projects which currently rely on NC_MAX_VARS and NC_MAX_DIMS retaining their historic constant values.  

To reverse the question, what problem does this approach not address for you? The main issue you have raised is that with the broader spread of netcdf, it is becoming difficult to have avoid collisions between the hand-tweaked custom netcdf you rely on and the canonical library.  Integrating this script (which could be made transparent to the end user) into a build system seems to address that, as there is no longer a conflict unless there is a project which links against exodus and netcdf. In this case, they could make due with exodus and the statically-linked custom netcdf library, and drop the canonical version altogether.

**Comment by gdsjaar** [comment]
A clarification.  When I say "break" below, I am referring to codes reading a netcdf file that has a dimension/variable count which exceeds NC_MAX_VARS or NC_MAX_DIMS.  None of the codes I looked at would break if they were linked against a netcdf library in which NC_MAX_VARS and NC_MAX_DIMS were increased to match or exceed the vars/dims count in the files they were reading.

..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

From: "Sjaardema, Gregory D" <gdsjaar@sandia.gov<mailto:gdsjaar@sandia.gov>>
Date: Wednesday, December 9, 2015 at 12:49 PM
To: Unidata/netcdf-c <reply@reply.github.com<mailto:reply@reply.github.com>>, Unidata/netcdf-c <netcdf-c@noreply.github.com<mailto:netcdf-c@noreply.github.com>>
Subject: Re: [EXTERNAL] Re: [netcdf-c] Max var dim (#166)

The main issue is as you mentioned below - there are projects that use exodus which may also use netcdf.  The Paraview visualization package is one of these.  I guess they are probably willing to use a modified netcdf since they have been doing so in the past.

I will look into your suggestions, but I think that the issues you mention are going to hit users anyway.  The netcdf-4 non-classic has no limits, so any tool that accepts netcdf-4 is potentially going to break unless they go through their code and fix all uses of NC_MAX_VARS and NC_MAX_DIMS.  Several that I have looked at will have that issue.

Also, the NC_MAX_VARS comment states that it is a suggested value but then it is checked as absolute.  Maybe the fix is to change the comment and the documentation, but something should be changed there - either the comment or the code.

The NC_MAX_VARS hasn't been checked correctly in netcdf-4-classic.  Does backward compatibility allow that to be fixed, or will that break client code?

I also don't see (other than potential memory issues) why a code will break if you change the values of NC_MAX_DIMS and NC_MAX_VARS.

Sorry if I appear to be frustrated, but I guess I don't see why netcdf can't evolve in this manner when it has definitely evolved in many other ways over the years.  I don't think there was any deep reason for choosing the values other than they were a little bigger than what was needed at the time.  My guess (totally a guess) is that many users have either had to not use netcdf or have had to munge there use of netcdf in order to respect these arbitrary values.  I worked with Ed many years ago to remove all uses of the values from the library; I guess I should have pushed to have the values not used for the CDF2 format and all would be good today.

I guess we will agree to disagree and we will continue to use a patched version of netcdf.  At least now when users ask me why we have to use a patched version, there is a thread that I can point to to answer their questions.

Thanks,
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by gdsjaar** [comment]
I guess the other issue I have with your suggested fix (alternate exodus-only netcdf library) is:

  *   It is more work than either of the other suggested fixes (ignore or change NC_MAX_VARS/DIMS)
  *   The number of "non-standard" netcdf files created is the same in either case

If the IGNORE fix causes a client to break when reading a file, then the "alternate library" solution will cause the same breakage.

The only difference, as I see it, is that if the IGNORE fix is done correctly inside the canonical library, then there is a much better chance that the reason for the breakage can be diagnosed/triaged.  By "correctly" I mean that there is a check on dim/var count on open.

I personally think that the IGNORE solution is probably the best overall if coupled with some checking on open:

  *   NC_MAX_VARS and NC_MAX_DIMS is unchanged so clients relying on those values can still read/write their files with no issues.
  *   If a code uses the IGNORE to create a "non-standard" file and gives it to a client that isn't expecting the large dim/var count, then a warning will be output at the nc_open call.
  *   Without the IGNORE fix, when someone with an exodus file feeds it to a client not expecting large dim/var counts, it will fail with no diagnostic and debugging will be much harder.
  *   With the IGNORE fix, netcdf documentation can be updated to make it clear what is happening and what are the suggested uses and caveats for using or not using the option.
  *   Files created with netcdf-4/non-classic will probably also break these clients already, so changing exodus to only use netcdf-4/nonclassic will cause the same issues.
  *   It makes the issue of dim and var count more visible and maybe some clients that didn't realize that netcdf-4-non-classic have no limits on  dimension or var counts will remove this limitation from their code or at least change their code to check the dim and var count and proceed only if safe for their code.

My bottom line is that the IGNORE solution makes it easier to debug potential issues with an exodus or moab user providing a netcdf file to a generic netcdf client which is better for all of us (exodus developers and netcdf developers and client developers) since there will be a warning issued for all non-large-dim/var-enabled clients.

..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Pull request closed without merging**
