### PR TITLE
Merge first batch of nczarr related changes

### LINKED ISSUE #1609: Missing percent sign in format docs
There is a typo in the on-line NetCDF User's Guide, [NetCDF Classic Format Specification](https://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html).  In the specs for netCDF object names, the percent sign is missing in this line:

`special2 = ' ' | '!' | '"' | '#'  | '$' | '' | '&' | '\'' |`

Notice that the sixth item currently shows as two single quotes.  In "older documentation", this position has a percent sign inside the quotes:  `'%'`.  It looks like this was somehow accidentally deleted.  Please restore.  Thanks.

### PR DESCRIPTION
**Pull request by WardF**
* Fixes #1609 

Fix a minor issue that doesn't merit a dedicated PR, also merges all the changes from #1598 plus resolves a few conflicts that arose.

### CODE REVIEW

**Comment by t-b** [comment]
@WardF Can you supply some details for the zarr support? Is it planned to be fully supported reading and writing also using compression and chunking? Which zarr version? Which Stores (Zip, Directory, S3)?

Thanks!

**Comment by DennisHeimbigner** [comment]
> Can you supply some details for the zarr support?
Let me take a stab at this.

> Is it planned to be fully supported reading and writing
Yes, I  am working on that right now.

> also using compression and chunking?
Chunking is a part of the read/write, so it is inherent
in the work I am doing now.

Compression is an open issue because there is some disagreement
about how to handle compression.

> Which zarr version?
Currently we are targeting version 2, but will move to version 3
when it is sufficiently stable.

> Which Stores (Zip, Directory, S3)?
This is an open issue. We need to build store code
conforming to a specific map API I have developed
as a subset of the Python map interface.
Currently I am testing using a hack store.

**Comment by DennisHeimbigner** [comment]
What is the state of this PR? It says it passes checks, but there is that warning
about conflicts.

**Comment by WardF** [comment]
I thought this had been merged.  I will take a look at the conflicts now and get it merged in.

**Comment by WardF** [comment]
Interestingly enough these don't appear to be 'conflicts' as we usually see them, but rather just flagging that the files need to be double-checked.  I'll merge this momentarily

**Comment by WardF** [comment]
Looking at this, I believe this PR was obviated (with the exception of the change for @t-b) with a subsequent PR.  Certainly, the conflicts reflect that functions in this branch have since been updated in a different PR.  I'm going to close this out and address the change for @t-b, unless that is (as I suspect) the PR I saw come across for the file over in Unidata/netcdf

**Pull request closed without merging**
