### PR TITLE
Removed a use of sprintf that required changing a function signature

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
How does NetCDF deal with deprecating and replacing APIs? i.e. for this part:

```diff
-extern void cdRel2Iso(cdCalenType timetype, char* relunits, int separator, double reltime, char* chartime);
+extern void cdRel2IsoNew(cdCalenType timetype, char* relunits, int separator, double reltime, char* chartime, size_t chartime_size);
+extern void cdRel2Iso(cdCalenType timetype, char* relunits, int separator, double reltime, char* chartime); // deprecated
```

What shall we call the new API?  `cdRel2IsoNew` is just a placeholder.

Do you have a deprecation macro that does similar to [C23's [[deprecated]]](https://en.cppreference.com/w/c/language/attributes/deprecated)?  If not, I can add one.

Thanks.

**Comment by DennisHeimbigner** [comment]
I do not think this function change is a problem.
The change has no material affect on its operation.
The function is not part of the netcdf API (as defined in the
include/netcdfXXX.h files).

**Comment by seanm** [comment]
Ah, I thought it might have been public API.  Patch updated.

**Comment by DennisHeimbigner** [comment]
There is one other point. If memory serves, the nctime code was taken from some other site.
It is possible that if this site is still being updated, that we should consider updating out code
to match. This might obviate the need for this change.

**Comment by seanm** [comment]
I've done and searching and tried to find an upstream, but most searches just bring me to netcdf.

**Comment by seanm** [comment]
@DennisHeimbigner I've just tried again, but can't find any upstream. Closest I got is: https://cdat.llnl.gov/

if that's it, they aren't maintaining it anymore anyway.

**Comment by seanm** [comment]
Rebased with latest `main`.

@WardF @DennisHeimbigner this one is ready to merge IMHO, pending your reviews.

**Review by WardF — APPROVED** [review]

**Pull request merged**
