### PR TITLE
Set default fill/no_fill behavior on newly defined variable (nc4)

### PR DESCRIPTION
**Pull request by gsjaardema**
In nc4 mode, the variables were ignoring the default "database" fill/no_fill mode set via a call to nc_set_fill().  This sets the no_fill mode on the variable to match the default database setting at the time the variable is defined.

### CODE REVIEW

**Comment by gsjaardema** [comment]
It might be good to apply this patch in conjunction with the other fill-related patches that you have been applying to make sure they still work correctly once this fix is applied.

**Comment by WardF** [comment]
Reviewing now, will merge as soon as all the local checks pass (as I expect they will, but the surest way to make tests fail, in my experience, is to skip them :)).

**Comment by gsjaardema** [comment]
Thanks.  I appreciate the work you do on NetCDF.

**Comment by WardF** [comment]
Thanks Greg, and likewise; since our move to GitHub, we've seen a fantastic uptick in contributions from the developers in our community, such as yourself! Your work and contributions are very much appreciated, especially your perseverance in the face of potential lengthy review times.  I had just added a paragraph to that effect in the status report to our user community, actually, when I saw the notification from your comment. Thanks again!

**Pull request merged**
