### PR TITLE
Move hid_t from NC_FILE_INFO_T to new struct NC_HDF5_FILE_INFO_T

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #856.

In this PR I remove the hid_t field hdfid from the NC_FILE_INFO_T structure. It is relocated to a new NC_HDF5_FILE_INFO_T struct, which exists only in libhdf5.

Similarly, all the hid_t types of the other metadata structs are going to move to new structs which will not be seen in libsrc4.

This PR is ready to merge.

### CODE REVIEW

**Comment by edhartnett** [comment]
appveyor builds failing like this:

```
"C:\projects\netcdf-c\build\ncdump\ocprint.vcxproj" (default target) (110) ->
       (ClCompile target) -> 
         c:\projects\netcdf-c\ncdump\ocprint.c(18): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory [C:\projects\netcdf-c\build\ncdump\ocprint.vcxproj]
```

I believe you just added ocprint to the CMake build. Probably you should just take it out. 

What seems to be happening is that it's expecting strings.h and not finding it in the Microsoft environment. Apparently it's found on Unix.

**Comment by WardF** [comment]
I expect you may be right but I need to reconcile it with the lack of a failure on my dev platform e.g. where is it finding strings.h on my system and how do I bring this in line with a ‘standard’ install.

**Comment by DennisHeimbigner** [comment]
That one is easy. Change
#include <strings.h>
to 
#ifdef HAVE_STRINGS_H
#include <strings.h>
#endif

**Comment by edhartnett** [comment]
@WardF can we get this merged? There are many more changes waiting in the queue...

Thanks!

**Comment by edhartnett** [comment]
@WardF can we get this merged please?

**Pull request merged**
