### PR TITLE
Update selected documentation

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
Update the following documentation files:

## docs/FAQ.md
* Discuss the use of UTF-8 names under Windows 10+.

## docs/filters.md
* Add documentation about NCzarr filters.
  * Specifically Codec support and HDF5 <-> Codec translation
* Add documentation about standard filters

## docs/dispatch.md
* Convert from .dox format to .md (markdown) format.
* Add discussion about the user defined dispatch tables.
* Update the example.
* Abbreviate the NC_infermodel documentation and move the more detailed discusion to the companion *dinternal.md* documenation.

## docs/internal.md

This is a (mostly) new file that attempts to provide detailed
descriptions about how various features are implemented inside
the netcdf-c library. The topics currently covered the
following.

### Including C++ Code in the netcdf-c Library {#intern_c++}

The state of C compiler technology has reached the point where
it is possible to include C++ code into the netcdf-c library
code base. The document describes how to do this.

### Managing instances of complex data types

The document describes how to properly handle instances of
complex types (those with variable length).  This involves
having functions that can recursively walk instances of such
types to perform various actions on them.  These new functions
are intended to replace the *nc_free_vlen*, *nc_free_vlens* and
*nc_free_string* functions in *netcdf.h*.

### Inferring File Types

As described in the companion document -- docs/dispatch.md --
when *nc\_create()* or *nc\_open()* is called, the library must
figure out what kind of file is being created or opened.  Once it
has figured out the file kind, the appropriate "dispatch table"
can be used to process that file.

As a result of the introduction of remote data access to the netcdf-c
library, the path arguments to *nc\_open()* and *nc\_create()* have
been extended to support URLs as paths. Processing URLs requires
some significant changes to the file inference algorithm. The
details of that processing are recorded in the document.

### CODE REVIEW

**Comment by dopplershift** [comment]
At some point the NCZarr docs should probably move to the language-agnostic netcdf docs.

**Comment by DennisHeimbigner** [comment]
I am not sure I agree. Perhaps [Ethan](https://github.com/ethanrd) has an opinion?

**Comment by WardF** [comment]
At a high-level, I think the document containing information that independent developers would use to create ncZarr files should be with the other specification documents, most likely in the NUG. The point of this information is "these are the elements of the file, how they get there doesn't matter, as long as your software creates Data stores that account for this information, the language you use is immaterial. You are writing valid ncZarr files/data."

**Comment by WardF** [comment]
> At some point the NCZarr docs should probably move to the language-agnostic netcdf docs.

I think there will be API documentation that should stay in the developer documentation, specific to "how to do this with libnetcdf", and also documentation that can go in the NUG.  I will schedule with @ethanrd to figure out the current state of affairs with the NUG so that we can move forward. @DennisHeimbigner and @dopplershift I will include you on the meeting invite as optional attendee's, feel free to attend or not as the spirit moves you.

**Comment by WardF** [comment]
Also, thank you very much for all of this documentation work @DennisHeimbigner !!

**Review by WardF — DISMISSED** [review]

**Comment by ethanrd** [comment]
Yup, I agree with @WardF 's summary: details of NCZarr in NUG; how to use libnetcdf for [NC]Zarr in C docs; how to use nc-java for [NC]Zarr in nc-java docs.

+1 for scheduling a meeting.
Thanks all!

**Comment by DennisHeimbigner** [comment]
What I dislike is for a user to have to go read two different documents (one in NUG,
one in netcdf-c/docs) in order to understand some feature like filters or nczarr.
The alternative is too duplicate the NUG material in the netcdf-c/docs material,
but that means the two need to be synchronized.

**Review by WardF — APPROVED** [review]

**Comment by edwardhartnett** [comment]
It is possible to refernce the NUG from the netcdf-c documentation, and that's what I've done in some recent PRs.

I agree that you've got your work cut out for you separating the NUG from the C library. Best of luck and I will help as I can...

**Pull request merged**
