### PR TITLE
chore: unset executable flag

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
What is the point of this PR?

**Comment by akrherz** [comment]
> What is the point of this PR?

To correct the file permissions of repo content...

**Comment by e-kwsm** [comment]
Yes, the files have execute permission wrongly.

**Comment by DennisHeimbigner** [comment]
Does having execute permission set cause any failures or problems?

**Comment by alippai** [comment]
I don't think it causes any problems. I can compare this to having a dozen unused empty files checked in a repo. It won't cause any problems, but also it's clear it shouldn't be there. This is true for the extra permissions too (git default permissions are 644, you have explicit change setting it to 755).

**Comment by dopplershift** [comment]
Honestly, there's no IP here, so the CLA isn't really necessary. @WardF feel free to merge without it.

**Pull request merged**
