### PR TITLE
Add legacy macro option

### LINKED ISSUE #3029: Add `enable-legacy-macros` option.
As observed in #3017 and #3018, the change introduced in #2911 (discussed in #2858), re: refactoring the macro `_FillValue` to `NC_FillValue` has caused some issues for projects; it is easily fixed, but it is a problem when the issue potentially requires changing a projects code.  While it is tempting to say it is the problem of downstream projects, we should provide a mechanism to ameliorate the inconvenience and also recognize that for larger projects, there are often processes in place which make 'just change your code' more difficult than it sounds.

I'll add an option, 'enable-unsafe-macros', which will be off by default but, when true, will define `_FillValue` in parallel with `NC_FillValue`.

### PR DESCRIPTION
**Pull request by WardF**
* Fixes #3029 

Adds legacy macro option to enable `_FillValue`, any other macros which may reveal themselves. As discussed in #2858, the issue with `_FillValue` is that it can, in some circumstances, conflicts with a symbol `libc++18`.  While `_FillValue` is historically important and widely used, (and technically tricky to move away from), we can't avoid the fact that `_` is a reserved identifier and will potentially cause problems for users as `libc++18` and later become more common in the wild.

We replaced `_FillValue` with `NC_FillValue` in #2858, and we encourage users to adjust their software to account for this.  But not all of our users are maintaining software they rely upon, and we do not (and cannot) put people in a position where software they rely upon but are not equipped to modify will not compile.  

Invoking `--enable-legacy-macros` (autotools) or `-DNETCDF_ENABLE_LEGACY_MACROS=TRUE` (cmake) will define the `_FillValue` macro, for use when building netCDF as part of a larger, un-modified technical ecosystem.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I believe this should have the opposite default setting, as the number of users who will encounter problems with _FillValue is tiny compared to the number that will have problems with its absence.

At least give users a few releases with the new macros available but not yet mandatory.

**Comment by WardF** [comment]
@edwardhartnett It would be great if we could get more release candidate exposure so that we had a better feel for this.  Flipping it (as you suggest) doesn't do any harm and could (as pointed out) be better in the short run.  I have documentation to add before I was going to merge this, so I'll flip the polarity for the next rc.  [No harm in changing a considered opinion](https://github.com/Unidata/netcdf-c/issues/2858#issuecomment-1954862465), after all ;).

**Comment by gsjaardema** [comment]
For some customer input, I am fine with either option.  We have already added code to test whether `NC_FillValue` is defined and if it isn't, then use the old `_FillValue`

**Comment by czender** [comment]
Echoing @gsjaardema , I just amended NCO to use `NC_FillValue`, which NCO `#define`s if/when netCDF does not.

**Pull request merged**
