### PR TITLE
Make certain tests conditional on dependencies

### PR DESCRIPTION
**Pull request by nehaljwani**
`tst_h_rdc0` depends on `ncdump_tst_netcdf4`, which isn't build if `HAVE_BASH`
isn't true. But CMake errors out with:
```
-- Bash shell not found; disabling shell script tests.
CMake Error at CMakeLists.txt:1521 (SET_PROPERTY):
  SET_PROPERTY given TEST names that do not exist:

tst_h_rdc0
```
There are also some tests which `cdl_do_maps` depends on, but it is
also not defined if `HAVE_BASH` isn't true. CMake errors out with:
```
CMake Error at examples/CDL/CMakeLists.txt:10 (SET_TESTS_PROPERTIES):
  SET_TESTS_PROPERTIES Can not find test to add properties to:
cdl_do_comps
```
This patch makes these tests conditional, making CMake happy.

### CODE REVIEW

**Comment by WardF** [comment]
Thank you very much; it looks like there is some overlap between this and some recent work done to parallelize the tests.  I will take a look and get this merged! Thank you very much.

**Comment by WardF** [comment]
Waiting for Travis-ci to complete and then I will merge this (there were a couple of conflicts which I merged by hand).

**Comment by nehaljwani** [comment]
@WardF Thank you for reviewing this!

**Comment by WardF** [comment]
No problem, thank you very much for the contribution!! Sorry for the delay!

**Pull request merged**
