### PR TITLE
bypass NcML non-classic model abort and turn into a warning

### PR DESCRIPTION
**Pull request by ebo**
I am working with a bunch of GOES-R ABI satellite imagery which uses a non-classic NcML schema which trips an abort in ncdump when generating XML metadata output for versions greater than netcdf-4.1.3.  To facilitate an update I have added a command line switch which bypasses the abort code when attempting to dump non-classic model NcML data, and turns it into a warning.  This can be verified by downloading any GOES-R ABI imagery and running "ncdump -x <image>" using both version 4.1.3 and anything newer.

I am requesting that this patch be reviewed for inclusion as others may be interested in dumping XML metadata from the GOES-R satellite imagery using newer versions of NetCDF.

Please note, that I have spot checked the XML output for imagery using an offline version of netcdf-4.7.3 containing this modification against what is generated on the Ground System using netcdf-4.1.3 and found them to be consistent.  I will be reviewing the NcML documentation to see if the schema will trigger any known bugs, but any changes at that level will take a very long time to update.

### CODE REVIEW

**Comment by ebo** [comment]
Sorry for the delay.  Since this is related to things I/we are doing at work I had to ask permission to sign the licensing document.  BTW, I actually asked permission before the original submission, but did not know the details of the licensing before submitting.

Anyway, they do not care about the changes I submitted, or even doing what is asked to change the -Z to a -Xx, etc., but normally this kind of work is done by a different group we work with.  My bosses boss is concerned me starting down a slippery slope and that something that I do impacts the other groups or is seen as a conflict of interest.  As such I have been asked to write an internal bug report / white paper detailing the issues and seeing who wants to do what internally before committing resources upstream...  So, I should be able to get permission to sign the licensing agreement to hand over that code I have submitted, but I may have some pushback getting permission to make the -Xx change even if it is on my own time.

I do not mind advocating to sign the licence and be allowed make the -Xx change, but before I push that rock up the hill, what are the chances this would be accepted?

Once again, sorry for the delay.

**Comment by WardF** [comment]
Hello @ebo, I too apologize for the delay; recent events have overtaken us, as I'm sure you can imagine.  I think this would be a good change and certainly a PR we would accept.  @DennisHeimbigner , any thoughts?

**Comment by DennisHeimbigner** [comment]
> non-classic NcML schema which trips an abort in ncdump when generating XML
It should not abort; that is our error. But I have no problem
with this change.

**Comment by czender** [comment]
@ebo another workaround to `ncdump`'s XML output for non-classic files is `ncks --xml in.nc`.

**Comment by ebo** [comment]
On Mar 31 2021 7:11 AM, Charlie Zender wrote:
> @ebo another workaround to `ncdump`'s XML output for non-classic
> files is `ncks --xml in.nc`.

Thank you.  I will have to check to see if that will work for us, but I 
doubt it as NCO is not installed on the ground system, and I am not sure 
if we can get that installed without a very long review process.  It 
might be easier to get the netcdf version updated to one that includes 
the patch.

Thanks again for the information, and if there is a problem upgrading 
netcdf then I can look into having NCO installed.

   EBo --

**Comment by ebo** [comment]
as a note, I thought I already signed the CLA a year ago.  It took a bit of back and forth, but they allowed me to submit this, but limited my further involvement.  Was some fix added, and if so what release or version was it included?

**Comment by DennisHeimbigner** [comment]
I am not sure I understand this problem. Is that the file is netcdf-4, but does not
use any netcdf-4 specific features -- in effect it is a netcdf-4 classic file?

**Comment by DennisHeimbigner** [comment]
Sorry, I was not clear. If your file uses features of netcdf-4 data model for which
no translation to XML exists, then the result will be incorrect. So converting
the error to a warning would not fix that incorrect result. What am I missing?

**Comment by ebo** [comment]
On Mar 31 2021 12:16 PM, Dennis Heimbigner wrote:
> Sorry, I was not clear. If your file uses features of netcdf-4 data
> model for which
> no translation to XML exists, then the result will be incorrect. So 
> converting
> the error to a warning would not fix that incorrect result. What am I 
> missing?


Ahhh...  I compared the output from the old version we are using to the 
new version I modified off-line, and they were essentially identical.  
So, for the case of the 26 different products coming out of GOES, we 
should be OK.  The correct fix would be for us to fix the schema, but 
that would take getting it signed off by no less that 3 federal 
agencies.  I will make a suggestion that we look into that, but I will 
not hold my breath.

**Comment by ebo** [comment]
On Mar 31 2021 12:44 PM, Dennis Heimbigner wrote:
> ok, I see. I am not sure about using -Z, so let me think about this a 
> bit.

re: thinking a bit on -Z

of course.  To me I do not care about the specifics of the 
implementation, just a non abort and some way to move ahead.  There was 
some discussion on using other CMDL mechanisms which would likely be 
more acceptable or appropriate.

**Pull request closed without merging**
