### PR TITLE
patch related to Issue258

### PR DESCRIPTION
**Pull request by wkliao**
This patch addresses the special case when calling _uchar APIs to access NC_BYTE attributes or variables in CDF-1 and CDF-2 files.

The special case description can be found in http://www.unidata.ucar.edu/software/netcdf/docs_rc/data_type.html#type_conversion
Quoted here: "In netcdf-3, we treat NC_BYTE as signed for the purposes of conversion to short, int, long, float, or double. (Of course, no conversion takes place when the internal type is signed char.) In the _uchar functions, we  treat NC_BYTE as if it were unsigned. Thus, no NC_ERANGE error can occur converting between NC_BYTE and unsigned char."

In other words, if called from signed APIs, NC_BYTE variables are treated as signed. If called from unsigned APIs (i.e. _uchar APIs, the only unsigned APIs in netCDF-3) they are unsigned. NetCDF-3 specifically makes an exception to skip NC_ERANGE check when calling _uchar APIs to access NC_BYTE variables.

However, in netCDF-4 and CDF-5, because of the introduction of the new data type NC_UBYTE, an unsigned 8-bit integer, which makes NC_BYTE an signed 8-bit integer and thus renders the above exception less sense. In this patch, regular NC_ERANGE check is performed in all APIs that access NC_BYTE variables for CDF-5 files.

On the other hand, it still honors the above exception for CDF-1 and 2 files.

Note PnetCDF 1.7.0 does not handle this exception completely. The fix will appear in the next release 1.7.1. If netCDF decides to incorporated this patch in its next release, please suggest users to use PnetCDF 1.7.1.

### CODE REVIEW

**Comment by WardF** [comment]
Seeing some failures on 32-bit ARM.

* http://my.cdash.org/viewBuildError.php?buildid=1062141

**Comment by wkliao** [comment]
I don't understand the issue of arm.
There is a long discussion in issue 159.
Could you briefly explain why we need to care about char being unsigned by default?

Wei-keng

**Comment by WardF** [comment]
I don't think that this has anything to do with issue #159, or char being unsigned by default.  In the link I provided to the test failures here, I'm seeing the following:

````
Error	
 netcdf-c/libsrc/ncx.c:19279:1: error: conflicting types for ‘ncx_getn_text’
  ncx_getn_text(const void **xpp, size_t nelems, char *tp)
````

I have not had any time to investigate this and the error will likely be easy enough to resolve.  I was simply making a note here of the failure on a platform which isn't part of the travis-ci checks, so that I didn't merge before resolving the issue.

**Comment by wkliao** [comment]
In master branch, the definition of ncx_getn_text in ncx.m4 is
wrapped around by #ifdef __arm__, I think it has something to
do with #159.

 
Wei-keng

**Comment by WardF** [comment]
Ok, that does indeed tie it back to #159, thanks; I hadn't started poking into it yet.  I'll have to refer back to my notes.  The `unsigned by default` ended up being a red herring for #159 as I recall, however; the main issue was undefined behavior manifesting in one way on intel chips and another on ARM.  I don't recall specifics, but will when I have a chance to dig into it later this week :).

**Comment by wkliao** [comment]
Hi, Ward,

I noticed your comments on Dec 23, 2015.
https://github.com/Unidata/netcdf-c/issues/159#issuecomment-166999781

You indicates the cause of problem is "on ARM, the cast results in a value of 0"
instead of -1 or 255.

    while(nelems-- != 0)
    {
        if(*tp > X_UCHAR_MAX || *tp < 0)
            status = NC_ERANGE;
        *xp++ = (uchar)*tp++;  //<- THIS IS THE PROBLEM.
    }

When *tp < 0, the if condition above has already detected NC_ERANGE.
However, but the assignment below it is still got executed.

So, the question is "why did it not stop there to break the loop to
skip the assignment?"

If it goes ahead with the assignment, then the outcome of this assignment
should not matter, i.e. nc_test should not check the contents of elements
that cause NC_ERANGE.

I may not fully understand the ARM issue, but I feel the issue is more in
nc_test than in the ncx.m4. Wish I had an access to an ARM machine
to test for other possible errors.


Wei-keng

**Comment by edhartnett** [comment]
As I recall the ERANGE error is different, in that if it occurs, the data will still be copied, but the error will be returned.

These were the rules built into netCDF-3.

**Comment by wkliao** [comment]
Should we revisit that rule for netCDF-4?

It does not make much sense to me to copy an ERANGE value to the datatype with smaller range, as the outcome on the copied buffer or file may be system dependent (for example on ARM). On the other hand, it makes more sense to leave the original data untouched and report the error.

**Comment by edhartnett** [comment]
The netCDF project is pretty committed to backward compatibility, which has many practical benefits. For example, by exactly duplicating netCDF-3 behavior (when the NC_CLASSIC flag is used), netCDF is able to recycle the extensive netCDF-3 test suite (and even the netCDF-2 tests). So the reason to change the behavior must be pretty strong. 

Since a non-zero error code is returned, the user is warned that something has gone wrong. Only a reckless user will disregard return code for netCDF functions.

**Comment by wkliao** [comment]
I believe skipping the copy does not affect the backward compatibility, as NC_ERANGE is still returned in either case. When NC_ERANGE occurs, the contents of those data points are undefined. Users are responsible for the outcome if they insist to use those data points. This fact does not change.

**Comment by wkliao** [comment]
Just to clarify, my suggestion is to skip the copying only for those data points that cause NC_ERANGE. The while loop mentioned above in ncx.m4 can continue for the rest data points.

The suggested change does not affect the netCDF test suite because the suite only checks the contents of data points when their values are within allowable ranges (i.e. protected by nInExtRange, nInIntRange, or inRange3).

**Comment by edhartnett** [comment]
The documentation says:

> In general, if a function returns an error code, you can assume it didn't do what you hoped it would. The exception is the NC_ERANGE error, which is returned by any of the reading or writing functions when one or more of the values read or written exceeded the range for the type. (For example if you were to try to read 1000 into an unsigned byte.)
> 
> In the case of NC_ERANGE errors, the netCDF library completes the read/write operation, and then returns the error. The type conversion is handled like a C type conversion, whether or not it is within range. This may yield bad data, but the netCDF library just returns NC_ERANGE and leaves it up to the user to handle. 

So it is clearly documented that the copying of data does take place even when NC_ERANGE is returned, and that it is up to the user to decide what to do. 

Somewhere, your change *should* affect the test suite. Perhaps it does not currently, but it did when I was writing netCDF-4, since otherwise I would never have known about ERANGE. I only found it because some netCDF-3 test failed for me. ;-)

**Comment by wkliao** [comment]
I understand the NC_ERANGE convention in netCDF-3 but am arguing whether we
should keep it for netCDF-4, particularly, when we (or at least I) found it
making less sense. Here are my two arguments.

Forcing an out-of-bound data type conversion will result in different values
on different systems. See the ARM case pointed out by Ward. This will render
different file contents on different systems, even the same ERANGE data is
written to files. This outcome is (or may be most likely) against the
portability netCDF is designed to achieve.

Another reason is there is no way for a user to know which data points are
causing NC_ERANGE if the current rule is used. If we keep the data points
untouched and the fill mode is on, then finding the ERANGE data points can
be done by checking the fill values (a common practice by netCDF users).

I don't know whether or not you agree the suggested change does not affect
the backward compatibility. If you do, then I think it is better to define
a definite outcome than to leave user to decide. Also, we should not let
nc_test suite to affect the decision on NC_ERANGE behavior. To me, nc_test
is very thorough and a great effort, but sometimes you still find a little
room to improve or adjust (often with sore eyes afterward :).

Wei-keng

**Comment by WardF** [comment]
Sorry for the relative silence on my end from this; we were doing the Unidata python workshop and I'm just getting caught up on this and other things.

**Comment by wkliao** [comment]
Add a relevant discussion on NC_ERANGE that out-of-range type conversions can cause core dump when using NAG Fortran compiler.
http://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg13327.html

**Comment by wkliao** [comment]
I think I am done with updating this patch. Below please find a summary of this patch.

1. address issue #258 that handles uchar APIs for NC_BYTE variables as a special case in CDF 1/2 file formats
2. test and fix the "arm" case #159 on a Big Endian machine where char is unsigned
3. add a new configure option --disable-erange-fill. This patch uses fill values for variable elements that cause NC_ERANGE. The default is enabled. You can use this option to disable it and go back to typecast the data. The corresponding cmake option is ENABLE_ERANGE_FILL. I advocate this option as coredump is observed when using NAG Fortran compiler.
4. add a new configure option --enable-relax-coord-bound to enable a more relaxed boundary error check NC_EINVALCOORDS to allow coordinate start argument equal to dimension size when argument count is zero. The default is disabled. This feature was proposed by Greg Sjaardema in #243. The corresponding cmake option is ENABLE_RELAX_COORD_BOUND.
5. configure.ac and CMakeLists.txt have been modified to check PnetCDF settings on the above two settings and adjusted if a mismatch were found.
6. The following files are sync-ed with PnetCDF: libsrc/ncx.m4, nc_test/test_put.m4, nc_test/test_get.m4, nc_test/test_write.m4, nc_test/test_read.m4

I have tested this patch against the nightly build of PnetCDF. I plan to release a new PnetCDF version (a pre-release of 1.8.0) based on this patch today.  Any feedback is welcomed and let me know if you encounter a problem.

**Comment by gsjaardema** [comment]
Thanks for the addition of the ENABLE_RELAX_COORD_BOUND.  Is there a way to query an installed library and determine whether or not it used this option during the build?

**Comment by wkliao** [comment]
In the next release of PnetCDF, a macro PNETCDF_RELAX_COORD_BOUND is defined in pnetcdf.h to be either 0 or 1 which indicates whether this option is disabled or enabled. For earlier versions, this macro is of course undefined and hence disabled. A shell file pnetcdf-config will also be available in the new release of PnetCDF. You can run "pnetcdf-config --relax-coord-bound" to check at run time.

**Comment by gsjaardema** [comment]
@wkliao Awesome, that will work great.

**Comment by WardF** [comment]
@wkliao, @DennisHeimbigner and I have just reviewed this; things look mostly good but I need to dive in and do a code review and answer a few questions we had (for example, what is the explicit behavior  exhibited when erange fill values are enabled).  If I have any questions I can't answer via code review I'll follow up with you.

In the meantime, let's **freeze code changes in this pull request** until we can complete our review.  Also, we notice you've included a patch for relaxed coordinates in this pull request; in the future it will make things easier on our end (and, I suspect, ultimately on your end) if we organize pull requests such that they address a specific issue each. :).

**Comment by WardF** [comment]
Correcting a conflict arising out of a recent bug fix, and then focusing on resolving and hopefully merging this.

**Comment by WardF** [comment]
Created a branch, `ghpull-319`, to resolve some conflicts which arose from a recent set of changes I made.  Reviewing that branch now.

**Comment by WardF** [comment]
note to self: still seeing issues on ARM (as expected due to code freeze), start here.

**Comment by WardF** [comment]
Status: Debugging ARM platform checks.  Found some cmake-based errors in how the hdf5 libraries are detected in non-standard locations, so fixed those too.

**Comment by wkliao** [comment]
Hi, Ward
I have tested netCDF on a BGQ whose char is unsigned.
Is the issue on ARM not just limited to char being unsigned?
I am very interested in learning the issue, as PnetCDF may needs a similar fix.

**Comment by WardF** [comment]
As I recall, the "char unsigned by default on ARM" ended up being a minor issue and was in fact a red herring to a larger issue, which was netCDF relying on undefined-but-consistent-on-other-platform behavior.  I'm still hashing out the issue on my local raspberry pi; I am seeing some errors in `nc_test()`, and the cause is starting to come back to me.  I'm still familiarizing myself with the code changes in your comprehensive pull request, however, so there is still diagnostic work to be done.  

As an aside; thanks again for this pull request, and my apologies for the length of time it has languished.  We have not been idle, but pressing issues have taken our attention, and with Russ' departure we have certainly had our hands full.  

I'm running a test now that will be uploaded to a web dashboard; since it's running on a raspberry pi, it is going to take a little while, but as soon as it is finished I will post the link here.  That will provide a snapshot of what I'm seeing, specifically when it comes to the test failures.

**Comment by WardF** [comment]
The dashboard info is ready. 

The details of the failed `nc_test` can be found here: http://my.cdash.org/testDetails.php?test=29753742&build=1128702

The broader details of the build can be found here: http://my.cdash.org/buildSummary.php?buildid=1128702

Any insight anybody can provide will be appreciated; I will be debugging this but I have to look at a different issue for a little bit.  My changes, and merging of `master` into this pull request, can currently be found on the branch `ghpull-319-arm`.

**Comment by wkliao** [comment]
I tried branch ghpull-319-arm on a ppc64 whose char is unsigned.
When using autotools, nc_test ran without errors.
When using cmake, nc_test spewed out lots of errors, more than what we see on my.cdash.org.

Here are some of the errors.
*** testing nc_get_var_short ... 
	FAILURE at line 1716 of /home/wkliao/NetCDF/GIT/Unidata.netcdf-c/nc_test/test_get.c: value read not that expected
...
*** testing nc_get_var_int ... 
	FAILURE at line 1820 of /home/wkliao/NetCDF/GIT/Unidata.netcdf-c/nc_test/test_get.c: value read not that expected
...
*** testing nc_get_var1_short ... 
	FAILURE at line 433 of /home/wkliao/NetCDF/GIT/Unidata.netcdf-c/nc_test/test_get.c: expected: -5, got: -1025
...
*** testing nc_get_var1_int ... 
	FAILURE at line 539 of /home/wkliao/NetCDF/GIT/Unidata.netcdf-c/nc_test/test_get.c: expected: -20, got: -3.18767E+08
*** testing nc_get_var1 ... 
	FAILURE at line 1044 of /home/wkliao/NetCDF/GIT/Unidata.netcdf-c/nc_test/test_read.c: expected: -5, got: -1025
...

**Comment by WardF** [comment]
What happens if you try branch 'master' on the ppc64?

**Comment by wkliao** [comment]
Same.
Using configure passed.
Using cmake failed, with the same errors.

**Comment by WardF** [comment]
Well, that may be unrelated to this issue and will warrant its own issue most likely. Master passes without problem on arm.

**Comment by WardF** [comment]
Thanks for testing and confirming!

**Comment by WardF** [comment]
I've confirmed that an autotools based build fails with the same error as cmake, when nc_test is run. Will attach output tomorrow.

**Comment by wkliao** [comment]
The problem I am having turns out is related to the Endianness checking in cmake.
File libsrc/ncx.m4 depends on the define macro WORDS_BIGENDIAN and in autoconf, this is checked and defined on big Endian machines. But  I could not find this macro set/checked in CMakeLists.txt. I assume this is an easy fix. However, I am still learning cmake, noy sure how to make this into config.h.cmake.in.

**Comment by wkliao** [comment]
Just figure it out. Now both branches master and ghpull-319-arm passed "make test" when built with cmake on the ppc64 machine. Here is the patch.

```diff --git a/CMakeLists.txt b/CMakeLists.txt
 index b43407e..5283796 100644
 --- a/CMakeLists.txt
 +++ b/CMakeLists.txt
 @@ -101,6 +101,11 @@ INCLUDE(${CMAKE_ROOT}/Modules/GetPrerequisites.cmake)
  INCLUDE(CheckCCompilerFlag)
  FIND_PACKAGE(PkgConfig QUIET)
  
 +TEST_BIG_ENDIAN(BIGENDIAN)
 +IF(${BIGENDIAN})
 +  SET(WORDS_BIGENDIAN "1")
 +ENDIF(${BIGENDIAN})
 +
  # A macro to check if a C linker supports a particular flag.
  MACRO(CHECK_C_LINKER_FLAG M_FLAG M_RESULT)
    SET(T_REQ_FLAG "${CMAKE_REQUIRED_FLAGS}")
 diff --git a/config.h.cmake.in b/config.h.cmake.in
 index 5039d95..c892c33 100644
 --- a/config.h.cmake.in
 +++ b/config.h.cmake.in
 @@ -635,6 +635,8 @@ are set when opening a binary file on Windows. */
      #endif
  #endif
  
 +#cmakedefine WORDS_BIGENDIAN
 +
  #include "ncconfigure.h"
  
  #endif
```

**Comment by WardF** [comment]
@wkliao Thanks for the patch! I'm incorporating it into my working branch now and continuing to try to figure out what the issue is on ARM.

**Comment by WardF** [comment]
Note to self/issue: I've spent the day working on this, and will continue to do so. I am generating sample files on ARM and in a Linux VM to attach to this issue for future reference, but it appears that the problem is related to creating the test files, not reading them.  The issue is in `nc_test`, and appears to be related when casting to/from char/double, which is problematic at the best of times.  Once this issue is fixed, code/change review will continue.

**Comment by wkliao** [comment]
I notice that a change to X_CHAR_MIN and X_CHAR_MAX in nc_test/tests.h was made to branch ghpull-319-arm. My understanding is all constants with prefix "X_" in tests.h are for external data types. Therefore, their values should not depend on whether the memory type char is signed or unsigned. Do let me know if this makes sense.

**Comment by WardF** [comment]
CHAR_MAX/MIN vary depending on whether the chat data type is signed or unsigned on the target platform. I am on my phone so cannot reference limits.h on the pi, but https://www.tutorialspoint.com/c_standard_library/limits_h.htm provides a reference.

**Comment by wkliao** [comment]
I understand the values of CHAR_MAX/MIN (names without prefix "X_") depends on platform, but my argument was for X_CHAR_MIN and X_CHAR_MAX. The constants with prefix name "X_" are intended for netCDF external data types. In this case, the external data type is for NC_CHAR and, I believe, should be independent from platforms.

**Comment by DennisHeimbigner** [comment]
I am not sure I agree. Because we use utf8, the range for an
individual char must be the ascii subset, namely 0-127.
Remember, that semantically char != byte.
=Dennis

**Comment by WardF** [comment]
# Configuration Information

* The files were generated by running `nc_test`
* "Good" files were generated on a 64-bit Ubuntu 16.04 VM using the `ghpull-319-arm` branch.  
* "Bad" files were generated on a Raspberry Pi using the `ghpull-319-arm` branch.
* "Master-VM" files were generated on 64-bit Ubuntu 16.04 VM using the `master` branch
* "Master-ARM" files were generated on a Raspberry Pi 3 using the `master`.
* File 'nc_test_classic_bad_binary_good_platform.cdl' was generated on the Ubuntu VM, using the binary file generated on ARM. **This suggests that the problem is in writing the file, not reading the file.**
* All platforms were configured using cmake, with the same options:
  * -DENABLE_DAP=OFF -DENABLE_NETCDF_4=OFF
  * No parallel HDF5 or pnetcdf was used.

[comp.zip](https://github.com/Unidata/netcdf-c/files/761374/comp.zip)

**Comment by WardF** [comment]
You can see a difference related to this issue by examining variable `c1` in the good (VM) and bad (ARM) runs.

**Comment by wkliao** [comment]
Just checked your nc files and the nc_test source codes, I believe the content difference of c1 between two platforms is because the constant X_CHAR_MIN was set differently on ARM and Ubuntu, which also supports my argument that X_CHAR_MIN should be kept platform independent.
Note c1's value was set in util.c#L892 which calls has() which returns value of X_CHAR_MIN at line 429.

**Comment by WardF** [comment]
My apologies for the previous comment; both 'good' and 'bad' files were generated on the ARM platform.  'Good' was the master branch, 'bad' was the ghpull-319-arm branch I'm working on.

**Comment by WardF** [comment]
Ok. I've thoroughly confused myself and the discussion; I should not post whilst in meetings.

From a practical standpoint, we can either do a platform-specific check in `tests.h` or re-write `nc_test` to not try to try to use X_CHAR_MAX=255 as a test value when testing `char` when the platform uses signed chars by default.  The mechanism of the test with X_CHAR_MAX=255 (floating point variable = 255 is cast to char, which is signed on ARM;  the result of this operating is undefined according to C99) is at the root of the problem.  On Intel systems the resultant value is 'wrapped' due to overflow.  On ARM, the value is discarded and '0' is the result of the cast. I will continue working on `nc_test`, but in the meantime this redefinition is a fix that I can do in a reasonable amount of time.  

To clarify the confusion I introduced above, I have double checked the generated files here.  

## ARM file, master branch
````
wfisher@mort:~/Desktop/gitprojects/netcdf-c/build/ncdump$ ncdump -v c1 ~/Desktop/t/comp/nc_test_classic_master-arm.nc
netcdf nc_test_classic_master-arm {

(...)

data:

 c1 = "\200" ;
}
````


## ARM file, ghpull-319-arm branch

`````
wfisher@mort:~/Desktop/gitprojects/netcdf-c/build/ncdump$ ncdump -v c1 ~/Desktop/t/comp/nc_test_classic_bad.nc

netcdf nc_test_classic_bad {

(...)

data:

 c1 = "" ;
}
````

**Comment by wkliao** [comment]
I found the issue of type casting for NC_CHAR is confusing. There should never be any type conversion/casting performed for variables in NC_CHAR external type, because of the only legal APs that can read/write NC_CHAR variables are "_text" APIs. Otherwise, NC_ECHAR error code will be thrown and should be thrown way before any attempt of type casting. To me, NC_CHAR variables should be specially taken care in nc_test, like the code block of util.c#L891.
891        if (var_name[i][0] == 'c') {

I will check on the ppc64 machine the latest branches master and ghpull-319-arm to see if I get the same issue as you observed. Will get back to you soon.

**Comment by wkliao** [comment]
I am seeing a lot of errors when running nc_test on ppc64. It turns out that my WORDS_BIGENDIAN patch is not applied to the master branch, but only ghpull-319-arm.

**Comment by WardF** [comment]
Correct. It will be merged into master eventually but for the moment it is only on the branch.

**Comment by wkliao** [comment]
Is you ARM raspberry pi a big Endian?

FYI, after applying the WORDS_BIGENDIAN patch to the master branch, the contents of c1 are the same between the two branches. They are:

 c1 = "\200" ;

**Comment by wkliao** [comment]
Just notice this from format specification.
> Note on char data: Although the characters used in netCDF names must be encoded as UTF-8, character data may use other encodings. The variable attribute “_Encoding” is reserved for this purpose in future implementations.

So, UTF-8 is only limited to names. As for NC_CHAR variables, their content values in a netCDF file can range from 0 to 255, as long as the attribute “_Encoding” is properly set. Question is whether such encoding attribute feature has been supported by netCDF or not.

**Comment by WardF** [comment]
The Raspberry Pi is little endian.

**Comment by DennisHeimbigner** [comment]
_Encoding is AFAIK ignored at the moment.
Which means that it should default IMO to 7-bit ascii
subset of utf8. This, I suppose is why X_CHAR...
is not definable in general.

**Comment by wkliao** [comment]
Hi, Ward
Other than the content difference in c1 variable between the 2 branches, do you still get errors when running nc_test on ARM?

**Comment by wkliao** [comment]
Here is my analysis.
In put_vars() of utils.c, variable c1's content is set by a call to hash(). The value returned by hash() is -128, X_CHAR_MIN, which is then type-casted from double to char to text[j], resulting text[j] being 128.
The value 128 of NC_CHAR type is printed by ncdump into "\200" on screen.
Now the question is why ghpull-319-arm branch writes "\0" instead of "\200" on ARM.
You might want to add some printf statement to check.

**Comment by wkliao** [comment]
One question. Is the following setting from nc_test/tests.h intended?
```
#ifdef` __CHAR_UNSIGNED__
#define X_CHAR_MIN	SCHAR_MIN
#define X_CHAR_MAX	SCHAR_MAX
#else
#define X_CHAR_MIN	CHAR_MIN
#define X_CHAR_MAX	CHAR_MAX
#endif //__unsigned_char__
```
I assume on ARM, SCHAR_MIN is -128 which makes X_CHAR_MIN negative.

**Comment by WardF** [comment]
>  NC_ECHAR error code will be thrown and should be thrown way before any attempt of type casting.

As I recall from a conversation with Russ, NC_ECHAR is returned, but the conversion is still attempted, at least in the netcdf library.   Regarding nc_test, it was written long before my involvement, and I have not had the resources to go through and do any serious revisions to it yet.  Perhaps that will change soon!

> Now the question is why ghpull-319-arm branch writes "\0" instead of "\200" on ARM.

That is my conclusion as well. I haven't had a chance to come back to this issue yet, but I will try to do some more debugging later today or tomorrow. When this issue was last observed, it was the result of casting from a double to an unsigned char; undefined behavior which, on ARM, results in a '0'.

**Comment by wkliao** [comment]
If you check netcdf-3.6.1/src/libsrc/putget.c, NC_ECHAR is thrown right after a call to NC_lookupvar() for both put and get APIs, and the API returns immediately. (This  also leads to the issue of ERANGE_FILL I raised earlier in this discussion thread.)

As for type casting from a double to an unsigned char on ARM, The same casting is done for both master and ghpull-319-arm branches (I checked that part of codes and they are the same). I am puzzled why casting 128 results in '\0' on ghpull-319-arm but "\200" on master. Only a printf can confirm the case.

**Comment by wkliao** [comment]
I just found a serious bug that needs to be fixed. Sorry to break the promise not to touch branch issue258.

**Comment by WardF** [comment]
Merged patch into local branches, continuing to debug.

**Comment by WardF** [comment]
Step one (things compile and run across platforms) nearly complete; dealing with some visual studio related issues right now.  Then the next step will be to take a step back and evaluate what is going on, adjust tests as need be, and look at the broader scope of the pull request.

**Comment by wkliao** [comment]
Hi, Ward
I wonder if I can have an account to access your raspberry pi and help with debugging.

**Comment by WardF** [comment]
Thanks for your help debugging this. Hope to have the issues resolved today, then will review functionality and hopefully be able to resolve the pull request and move on to the full release!

**Comment by wkliao** [comment]
FYI.
I just created a new branch based on your ghpull-319-arm branch and incorporated the fix.
https://github.com/wkliao/netcdf-c/tree/ghpull-319-arm

Tested it on a Redhat box and your raspberry pi without errors.
Two tests were carried out on both machines:
1. built without netcdf-4, without PnetCDF
2. build without netcdf-4, but with PnetCDF

**Comment by WardF** [comment]
Seeing a build failure under Visual Studio/Windows with the ghpull-319-arm branch from @wkliao but at a glance it looks straight forward to fix.  Will address and hopefully put this to bed by early next week. Confirmed tests work on ARM and Linux and OSX.

**Comment by wkliao** [comment]
Can you point me to the build outputs on the Visual Studio/Windows?

**Comment by wkliao** [comment]
Just found a bug in ncx.m4 and the bug is due to the way config.h is included. See 7aa8fc3.
I also removed all special treatment for ARM architecture, i.e. __arm__, in 08aef9a.
All run passed on raspberry pi and redhat.

**Comment by WardF** [comment]
Can you open a new pull request based on your new branch and I will evaluate as soon as I can, as well as get the visual studio output posted somewhere.

**Comment by wkliao** [comment]
Done. The new pull request is #375

**Comment by WardF** [comment]
Dennis and I have discussed this (in terms of pull request #375 and we are going to accept it with the following caveats), based on the summary [in this comment](https://github.com/Unidata/netcdf-c/pull/319#issuecomment-260723753):
* The default for `erange-fill` will be switched to `disabled` from enabled, to retain default behavior.
* Options for relaxed coordinate will be renamed to something along the lines of enable zero length coords or similar; based on the comments in #243 we want to narrow the implications of the name. 

@wkliao a quick question; while we were going back through the issues you reference, it appears that the relaxed coordinate bounds option is specific to pnetcdf related use cases.  Is there any reason you can think of not to make this option conditional on pnetcdf support? I.e., this option is not available if you aren't linking against pnetcdf?

Thanks again for your patience and help with this; once this is done we can start looking at additional pull requests; we really appreciate the series of smaller pull requests you've been issuing, it makes things much faster on our end with our limited resources :).

**Comment by wkliao** [comment]
> The default for erange-fill will be switched to disabled from enabled, to retain default behavior.

FYI, if a user is building netCDF using PnetCDF with erange-fill enabled, then netCDF will automatically enable it (I believe I added that in configure.ac and CMakeList.txt).

> it appears that the relaxed coordinate bounds option is specific to pnetcdf related use cases. Is there any reason you can think of not to make this option conditional on pnetcdf support? I.e., this option is not available if you aren't linking against pnetcdf?

I believe RELAX_COORD_BOUND feature is also available for netCDF when built without PnetCDF. Try "git grep RELAX_COORD_BOUND". You will see it is used in libsrc and libsrc4.

**Comment by WardF** [comment]
Merged upstream, see #375 comments for more info.

**Pull request closed without merging**
