### PR TITLE
32bit lfs

### PR DESCRIPTION
**Pull request by wkliao**
This patch can silence the error messages reported in #1017.

### CODE REVIEW

**Comment by WardF** [comment]
@DennisHeimbigner I know you're working on a fix as well so I'll wait for your ok to merge this. @wkliao thank you very much! I just don't want to get wires crossed with both fixes crossing paths, so to speak.

**Comment by DennisHeimbigner** [comment]
Ok, I reviewed this PR and I think we are in agreement with one exception.
In var.c, line 486, you removed this:

    /* No variable size can be > X_INT64_MAX - 3 */
    if (0 == NC_check_vlen(varp, X_INT64_MAX-3))
	return NC_EVARSIZE;
Can you explain why?

**Comment by wkliao** [comment]
The commit message explains it.

**Comment by DennisHeimbigner** [comment]
The point is this. It is better for the user if errors are caught as early as possible.
As the code stands, the error will not be reported until nc_enddef is called.
At that point, the user has no context to figure out which variable failed.
If the check is done in def_var, then the user gets much more context about
which variable is in error.

**Comment by WardF** [comment]
Reviewing now as part of an aggregation to try to get caught up on PRs

**Pull request merged**
