### PR TITLE
Adding nc_def_var_quantize()/nc_inq_var_quantize() - second attempt

### LINKED ISSUE #1548: Provide a way to do bit grooming before compression
In the NOAA GFS data files they are doing something neat to get better compression. They are zeroing out a bunch of bits they don't care about in the float.

For this to work, all we need to know is the number of bits. So we could have:

`nc_def_var_smoothing(ncid, varid, nbits);
`

to turn this on.

For some code from Jeff Whitaker see #1543. (They call this "quantizing" and maybe that's a better name. I'm not sure if "smoothing" is correct.)

This is part of #1545

### PR DESCRIPTION
**Pull request by edwardhartnett**
Adding nc_def_var_quantize()/nc_inq_var_quantize() as discussed in recent meeting.

This is a second try, after #2081. In this version I add the inq function directly to the dispatch table, as suggested by @DennisHeimbigner , instead of extending inq_var_all(). This leads to a cleaner implementation, with fewer changes in the other dispatch layers.

This is now complete and fully documented and tested. Comments and questions welcome.

Fixes #1548

Fortran changes can be found in https://github.com/Unidata/netcdf-fortran/pull/304.

I have issue open to determine where this should be documented in the language-neutral docs: https://github.com/Unidata/netcdf/issues/46.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@WardF this is currently failing in appvayor with this error:

```
CMake Error at ncdap_test/CMakeLists.txt:38 (SET_TESTS_PROPERTIES):
  SET_TESTS_PROPERTIES Can not find test to add properties to:
  ncdap_tst_ncdap3
CMake Error at ncdap_test/CMakeLists.txt:62 (SET_TESTS_PROPERTIES):
  SET_TESTS_PROPERTIES Can not find test to add properties to:
  ncdap_tst_remote3

```

Any idea why?

**Comment by edwardhartnett** [comment]
@ethanrd the name of the attribute is an area of active discussion. 

My understanding is that this is something that @czender is going to discuss at the CF meeting in September. If the CF community can agree on an attribute name for this, we will happily use that in netcdf-c.

**Comment by DennisHeimbigner** [comment]
See this comment.
https://github.com/Unidata/netcdf-c/pull/2089#issuecomment-906708660

**Comment by edwardhartnett** [comment]
@DennisHeimbigner I made the change you suggested but am now seeing another failure:
`FAIL: test_manyurls`

**Comment by DennisHeimbigner** [comment]
Two choices:
1.apply PR https://github.com/Unidata/netcdf-c/pull/2091
2. --disable-dap-long-tests

**Comment by edwardhartnett** [comment]
@DennisHeimbigner perhaps --disable-dap-remote-tests should be used, but this is the Unidata CI, so that's up to @WardF .

I already have the updated master that includes manyurls. So I'm not sure what is going on...

**Pull request merged**
