### PR TITLE
Classic h5  -- Fix compliance with classic model when using netcdf-4-classic

### PR DESCRIPTION
**Pull request by gdsjaar**
Fix compliance with classic model -- The check to determine whether NC_MAX_VARS has been 
exceeded was using h5->nvars which seems to be unused.  The variable count instead is maintained
in grp->nvars for each group (in classic mode, there is only one group)

It may be that the real bug is that h5->nvars is not being incremented correctly and it is supposed
to contain the global var count (sum of the groups var counts).

If h5->nvars is not supposed to be used and grp->nvars is the new way of maintaing the count, then perhaps "nvars" should be removed from the h5 struct to avoid future confusion.

### CODE REVIEW

**Comment by WardF** [comment]
Hi Greg, thanks for this and the cmake pull request :).  I need to get some writing out of the way this morning and then I will take a look at them both!

**Comment by WardF** [comment]
Seems reasonable, unless @dmh or @russrew have some historic context to explain it I will merge this in.  I'm also not sure off the top of my head about the duplication of `nvars` between `grp` and `h5`, so I'm not inclined to remove `h5->nvars` until I'm certain that it's completely unnecessary.

**Comment by DennisHeimbigner** [comment]
Why is cmakelists.txt being change? Should this not be a separate pull request?
The observation about nvars seems correct. But, just switching to grp->nvars
does not seem correct. I would assume that the NC_MAX_VARS limit should apply
to all variables in all groups, hence, the test needs to be agains the recursive sum of grp->nvars. Better is to make h5->nvars be that recursive sum and compare against that. Am I missing something?

**Comment by WardF** [comment]
CMakeLists.txt appears to contain the changes submitted separately under pull request https://github.com/Unidata/netcdf-c/pull/154.  I'm not 100% on how GitHub will handle that part of this pull request since I've merged 154, but I assume it will either be handled, or I'll untangle it manually.

As to your comment about the rest of the pull request, I'm the one who was missing something, as that's the sort of insight I was hoping for.   Let me get a better handle on it, thanks!

**Comment by gdsjaar** [comment]
I don't think the NC_MAX_VARS limit should apply to all groups- The limit should only apply for netcdf-4 when in classic mode and when you are in classic mode, you will only have a single group.

..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Pull request closed without merging**
