### PR TITLE
fix leak of HDF5 typeids

### LINKED ISSUE #1571: growing memory in netCDF library?
@epourmal reported that netCDF has some memory problem, where memory use grows over time.

I don't want to forget to look into this important issue. Elena, can you provide any more info?

### LINKED ISSUE #1575: possible memory leak opening and closing the same file in a loop
details in https://github.com/Unidata/netcdf4-python/issues/986

possibly related to issue #1571

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #1575
Fixes #1571

This fixes a memory leak related to typeids.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@WardF this PR should definitely be merged before the next release. If fixes an important memory leak.

**Comment by WardF** [comment]
Thanks Ed

**Comment by jblarsen** [comment]
Sounds great. Do you already know when the next release is due?

**Comment by WardF** [comment]
@jblarsen I'm hoping to put the 4.7.4 release out by the end of next week; we have an issue on big-endian systems I'm trying to debug currently, but this memory leak fix may motivate a quick maintenance release before it is finished.

**Pull request merged**
