### PR TITLE
libxml2 capability 

### PR DESCRIPTION
**Pull request by WardF**
This PR contains #2135 plus fenceposting options for `cmake` and `configure`, `-DENABLE_LIBXML2` or `--enable/disable-libxml2`.

### CODE REVIEW

**Comment by WardF** [comment]
Encountering an error on OSX where a couple of additional "legacy" includes need to be included in addition to `unistd.h` in order for the `read()` function in `ezxml.c` to work.  I've also encountered an issue in `ncbytes[*]()` function; gcc reports mismatch type errors, because `size_t` != `unsigned long` on ARM 32 bit.  Looking at that as well.

**Comment by DennisHeimbigner** [comment]
If you make changes to ezxml.c, see if those changes can be codified
in the rebuild task near the bottom of libncxml/Makefile.am

**Comment by WardF** [comment]
@DennisHeimbigner Will do, thanks!

**Comment by e4t** [comment]
> If you make changes to ezxml.c, see if those changes can be codified in the rebuild task near the bottom of libncxml/Makefile.am

I wonder how relevant this still is today: The 'upstream' tarball has last been updated in June 2006. Meanwhile, the code here has picked up a number of security patches. While the upstream project is seeing a surprising number of downloads, nobody seems to feel inclined to pick it up.

**Comment by DennisHeimbigner** [comment]
I noticed that the amazon s3 sdk uses tinyxml, so I am going to infestigate that as a replacement.

**Pull request merged**
