### PR TITLE
Eliminate NC_MAX_VARS|DIMS|ATTRS limits

### PR DESCRIPTION
**Pull request by gsjaardema**
Eliminate all checks for exceeding the NC_MAX_VARS, NC_MAX_DIMS, and NC_MAX_ATTRS defines during the output (write) of a netcdf classic file.   Various options for this have been discussed in #371 and earlier in #148.

Dennis suggested the addition of a new function which would return the number of dims, vars, and attrs; but I think that the capability already exists in the `nc_inq_ndims()`and similar functions, so I didn't add that function to this PR.  

Other details related to this topic are discussed in the referenced issues.  If this PR is seen as too radical, I can modify as needed.

### CODE REVIEW

**Comment by gsjaardema** [comment]
@nmhamster, @wkliao, @roblatham00, @edhartnett, @jedwards4b

Add others who were involved or mentioned in the original issue discussion.

**Comment by wkliao** [comment]
Removing the codes that check the max constant can be a problem.
The number of dims/vars/atts in are of type `int` in many NetCDF APIs, such as `nc_inq`.
`int nc_inq (int ncid, int *ndimsp, int *nvarsp, int *ngattsp, int *unlimdimidp);`
So in theory, their max values are NC_MAX_INT.
But in NetCDF implementation, the member `nelems` in `NC_vararray`, `NC_dimarray`, and `NC_attrarray` are of type `size_t`, which can be unsigned int32 or int64.

In PnetCDF, I updated NC_MAX_VARS|DIMS|ATTRS to NC_MAX_INT in the header file and kept the checking intact.

**Comment by gsjaardema** [comment]
@wkliao The setting of NC_MAX_VARS|DIMS|ATTRS to NC_MAX_INT is an interesting idea, but I think that it might cause more problems than it is intended to solve.  First, if any user code is dimensioning any array to NC_MAX_*, then the code will probably start failing due to memory allocation errors.  Although this is a good way to determine who is doing this, it probably isn't good from a backward-compatible aspect.

I also think that there are other areas in the code that would fail if the dims, vars, attrs count reached or exceeded NC_MAX_INT and setting NC_MAX_* to NC_MAX_INT might provide a false sense of security that as long as these limits don't trigger, then everything is OK.  In other words, if that is implemented, there are likely many other changes required to make these checks exhaustive.  For example, should the checks now be active in non-classic mode?

**Comment by edhartnett** [comment]
I note that NC_MAX_VARS is used in the dispatch code:

```
ed@mikado:~/tmp/netcdf-c/nc_test4$ find ../libdispatch -name '*.c'|xargs grep NC_MAX_VARS
../libdispatch/dvar.c:\returns ::NC_EMAXVARS NC_MAX_VARS exceeded
../libdispatch/dv2i.c:	rs = (size_t*)malloc(sizeof(size_t)*NC_MAX_VARS);
../libdispatch/derror.c:      case NC_EMAXVARS:	 return "NetCDF: NC_MAX_VARS exceeded";
```
So maybe this should be changed too, since we can no longer count on NC_MAX_VARS to be the limit of the number of vars.

**Comment by gsjaardema** [comment]
That usage is in the version 2 interface code.  I think it could be eliminated relatively easily since it is only passed down to `nc_inq_rec` and the space is used to store `nrvars` which I think is the number of record variables.  It is only used internally, so I think you could query number of nrvars and then allocate that much space instead of just allocating `NC_MAX_VARS`.

**Comment by DennisHeimbigner** [comment]
I think this issue is likely to become academic soon. I have a new branch
that is intended to improve the speed of opening a file when processing 
its metadata. I believe that it renders NC_MAX_VARS|DIMS|ATTRS moot.
[Actually, I think they already are moot in looking at the code].

**Comment by gsjaardema** [comment]
They are moot if this pull request is applied ;-)

**Comment by DennisHeimbigner** [comment]
Not sure it is a good idea to remove error codes even if they are no longer used.
Ward- do you have an opinion on this? Might break user code that tests for this case.

**Comment by DennisHeimbigner** [comment]
SInce we are moving in this direction, I think we can do this pr.

**Comment by gsjaardema** [comment]
```
diff --git a/libdispatch/dv2i.c b/libdispatch/dv2i.c
index 0110d35c..8481674c 100644
--- a/libdispatch/dv2i.c
+++ b/libdispatch/dv2i.c
@@ -1154,7 +1154,8 @@ ncrecinq(
        size_t *rs = NULL;
        int status = NC_NOERR;

-       rs = (size_t*)malloc(sizeof(size_t)*NC_MAX_VARS);
+       nc_inq_rec(ncid, &nrv, NULL, NULL);
+       rs = (size_t*)malloc(sizeof(size_t)*nrv);
        if(rs == NULL)
            return NC_ENOMEM;
```

**Comment by WardF** [comment]
Updating with Master then will merge.

**Comment by gsjaardema** [comment]
Thank you very much!  My life is now complete... ;-)

Now I just have to get everyone to update to 4.5.1...

**Pull request merged**
