### PR TITLE
CMake: Find HDF5 header we can safely include for other checks

### PR DESCRIPTION
**Pull request by ZedThree**
I was a bit hasty in #2757: some linux distros rename `H5pubconf.h` so we need to potentially check a few headers. I've wrapped this up to keep things clean in the main CMake file.

### CODE REVIEW

**Comment by WardF** [comment]
Interesting, thanks. Out of curiosity, what is one of the Linux distros which does this? I'd be curious to run some tests.

**Comment by ZedThree** [comment]
"Enterprise Linux" (RedHat, Fedora, etc). I checked [pkgs.org](https://pkgs.org/search/?q=hdf5) for others. I encountered this trying to build netCDF inside the `manylinux_2_28` container for Python

**Comment by ZedThree** [comment]
Further reference, this is what the built-in [`FindHDF5.cmake` module](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindHDF5.cmake?ref_type=heads#L976) does too:

```cmake
      foreach(_hdr "${_dir}/H5pubconf.h" "${_dir}/H5pubconf-64.h" "${_dir}/H5pubconf-32.h")
```

So could even drop `H5public.h` here?

**Comment by WardF** [comment]
Thanks!

**Pull request merged**
