### PR TITLE
Simplify libhdf5/nc5info.c to move to avoid parsing

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes https://github.com/Unidata/netcdf-c/issues/1352

When nc4info.c encounters an _NCProperties attribute
with a version number it does not recognize, it does not
show it correctly.

Solution chosen is to arrange so that accessing the attribute
returns the raw value of the Attribute from the file. This way,
even if the version is unrecognized, it will return something
usable.

The changes were primarily to never attempt to parse the value
of _NCProperties.

Also modified ncdump/tst_fileinfo.sh to include some extra testing

I tested the original failure by changing the value of NCPROPS to 3.
However, there is no way to test this at build time.

Misc. Changes
* Inlined the provenance info in the NC_FILE_INFO_T structure
* Centralized stuff from elsewhere into include/nc_provenance.h

Misc. Unrelated Changes
* Removed/turned off some misc debug output left on by accident
* Fix CPPFLAGS name error in libhdf5/Makefile.am

### CODE REVIEW

**Comment by WardF** [comment]
Addressing conflicts and then merging.

**Comment by WardF** [comment]
Resolved conflicts from `master`, seeing a failure in `ncdump/tst_fileinfo`.

**Comment by DennisHeimbigner** [comment]
ok, will check.

**Comment by DennisHeimbigner** [comment]
I must be losing my mind. I swear the code used to work, but looking at it,
it is seriously incorrect and could not have ever worked. Anyway, I am repairing it.
Will have fix shortly.

**Pull request merged**
