### PR TITLE
Use the built-in HDF5 byte-range reader, if available.

### LINKED ISSUE #1848: Poor performance downloading using byte-range requests
So if I try to get the data for a variable using byte-range requests, it performs pretty terribly:
```
❯ time ncdump -v temperature_anomaly 'https://coawst-public.s3-us-west-2.amazonaws.com/testing/HadCRUT.4.6.0.0.median.nc#mode=bytes' > /dev/null
ncdump -v temperature_anomaly  > /dev/null  8.89s user 0.83s system 7% cpu 2:05.89 total
```
During this transfer, my system showed it was sustaining about 180 kB/s. If I instead just download the whole file:

```
❯ time wget https://coawst-public.s3-us-west-2.amazonaws.com/testing/HadCRUT.4.6.0.0.median.nc
--2020-09-23 11:07:42--  https://coawst-public.s3-us-west-2.amazonaws.com/testing/HadCRUT.4.6.0.0.median.nc
Resolving coawst-public.s3-us-west-2.amazonaws.com (coawst-public.s3-us-west-2.amazonaws.com)... 52.218.185.201
Connecting to coawst-public.s3-us-west-2.amazonaws.com (coawst-public.s3-us-west-2.amazonaws.com)|52.218.185.201|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21541372 (21M) [application/x-netcdf]
Saving to: ‘HadCRUT.4.6.0.0.median.nc’

HadCRUT.4.6.0.0.median.nc         100%[=============================================================>]  20.54M  7.45MB/s    in 2.8s    

2020-09-23 11:07:45 (7.45 MB/s) - ‘HadCRUT.4.6.0.0.median.nc’ saved [21541372/21541372]

wget   0.06s user 0.16s system 7% cpu 3.101 total
```
I get that there's some overhead with byte range requests, but a difference of 40x is so slow as to make the byte-range support useless.

Do we know what chunk size is being requested?

See Unidata/netCDF4-python#1043 for the original issue that provoked this.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes #1848 

re: Issue https://github.com/Unidata/netcdf-c/issues/1848

The existing Virtual File Driver built to support byte-range
read-only file access is quite old. It turns out to be extremely
slow (reason unknown at the moment).

Starting with HDF5 1.10.6, the HDF5 library has its own version
of such a file driver. The HDF5 developers have better knowledge
about building such a driver and what incantations are needed to
get good performance.

This PR modifies the byte-range code in hdf5open.c so
that if the HDF5 file driver is available, then it is used
in preference to the one written by the Netcdf group.

Misc. Other Changes:

1. Moved all of nc4print code to ncdump to keep appveyor quiet.

### CODE REVIEW

**Review by WardF — APPROVED** [review]
Looks good, thank you Dennis! Running the edge case tests and will get merged when they pass. Thanks!

**Comment by dopplershift** [comment]
So to be clear...that driver from HDF5 only works on S3, right? So we’ll still see the pathological behavior on e.g. THREDDS servers?

Also, I’m not sure you really want to rely on that HADCrut data that’s sitting in a file on S3. @rsignell-usgs can correct me if I’m wrong, but the URL even says testing so I’m not sure how long it will live there.

**Comment by DennisHeimbigner** [comment]
Note also that the HDF5 driver will work against any server that supports
byte-range. See the test case nc_test/test_byterange.sh.

**Comment by DennisHeimbigner** [comment]
re: HADCrut data that’s sitting in a file on S3.
Is there a  good and more permanent file that is also netcdf-4?

**Comment by dopplershift** [comment]
Well, at this one points to a server we control: https://thredds-test.unidata.ucar.edu/thredds/fileServer/casestudies/harvey/goes16/CONUS/Channel03/20170827/GOES16_CONUS_20170827_001717_0.87_1km_33.3N_91.4W.nc4

**Pull request merged**
