### PR TITLE
Remove need for HDF5-1.6 API being defined

### PR DESCRIPTION
**Pull request by gsjaardema**
There are a few HDF5 api version-related symbols or requirements in the current netCDF source code and build system.  There is an explicit setting of the `H5_USE_16_API` define which triggers some defines in the hdf5 `H5Version.h` include file.  There is also a check for the `H5Literate_Macro` and if it isn't found, then a warning about building hdf5 with the `--with-default-api-version=v18` define.

There is also a requirement that the HDF5 version be at least 1.8.10 which means that unless hdf5 is built with deprecated symbols deleted, the symbols from v16 and v18 exist -- typically by appending a `1` to the function name. 

This PR removes these checks for a specific API version and explicitly calls out all deprecated functions that are being used by appending the `1` to the function name.

Later, we can modify the calling arguments wehre needed to be able to convert from the deprecated function to the currently recommended function (some of which are already being used (for example there is a mix of `H5Gopen1` and `H5Gopen2` function calls throughout the code base.

The motivation for this change is to make it easier to use netCDF with installed versions of HDF5 which may not have been built with the v18 API.  There is also a need to be able to compile with recent development versions of HDF5 which need some patching to enable v16 and v18 api macros.  One other potential issue is that I'm not sure how safe it is to redefine an HDF5 define (`H5_USE_16_API`) which was not defined during the build; probably safe, but just seems dangerous.

### CODE REVIEW

**Comment by gsjaardema** [comment]
This has been tested with HDF5-1.10.7, HDF5-1.12.0, and the HDF5 development version from the hpc-io github repository for testing the use of VOL [async, cache, provenance] with netCDF/HDF5.

**Review by edwardhartnett — APPROVED** [review]
Excellent idea. There are a lot of files involved, but most of them are tst_h_ files, which are test files.

I've inspected the changes, taking extra care with the non-test changes. They all look good.

**Comment by gsjaardema** [comment]
sorry for the churn.  I guess I missed a couple in my 1.8.21 builds...

**Comment by WardF** [comment]
Thanks, and no worry! It is passing all the tests, which looks great, but given the number of files it touches I'm just reviewing it now and should get it merged (I suspect) in fairly short order. Thanks, as always!

**Comment by WardF** [comment]
Thank you @gsjaardema as always!!

**Comment by gsjaardema** [comment]
You're welcome.  Glad I can contribute

**Pull request merged**
