### PR TITLE
cause nc_create to return NC_ENOTBUILT if used with NC_NETCDF4 on non-netcdf4 library

### LINKED ISSUE #392: Try create a NetCDF4 file using NetCDF ibrary built with --disable-netcdf-4
A question.
When using NC_NETCDF4 mode to create a file using a netCDF library built without netcdf4 enabled (i.e. --disable-netcdf-4), should the nc_create function return NC_EINVAL?

FYI. I tested this using the latest master branch and the file is created without error, but the file is in the classic format.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #392.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Would it be better to return NC_ENOTNC4?

**Comment by edhartnett** [comment]
I thought of that but the NOTNC4 error message is  "Attempting netcdf-4 operation on netcdf-3 file" which is not what is happening, so I think INVAL is probably good.

**Comment by DennisHeimbigner** [comment]
I disagree. This seems to me to be exactly what is happening. I would have said that
the fact that the file does not yet exist is irrelevant.

**Comment by gsjaardema** [comment]
I agree with @DennisHeimbigner.  Maybe if the error text were modified to add " or with library that does not support netcdf-4" it would be better.  

I just had a similar issue with a parallel build that did not include pnetcdf support.  The return error kept saying "not a netcdf file" which wasn't helpful. If it would have said something about not supporting the capability, I would have caught on faster as to issue.

**Comment by edhartnett** [comment]
OK, I will change. Stand by...

**Comment by wkliao** [comment]
FYI. In PnetCDF, two error codes NC_ENOTENABLED and NC_ENOTSUPPORT have been created to better describe the errors. Maybe NetCDF folks would like to consider to do the same.

**Comment by DennisHeimbigner** [comment]
Good idea; I will talk to Ward about it.

**Comment by edhartnett** [comment]
I am adding NC_ENOTENABLED. @wkliao, what is the difference between NC_ENOTENABLED and NC_ENOTSUPPORT?

**Comment by edhartnett** [comment]
I also just noticed that we already have error NC_ENOTBUILT "Attempt to use feature that was not turned on when netCDF was built."

So that seems better then adding NC_ENOTENABLED. Anyone disagree?

**Comment by edhartnett** [comment]
OK, I have changed the error to NC_ENOTBUILT. If anyone can make a strong case for a different error code, please do so. ;-)

**Comment by wkliao** [comment]
In PnetCDF, the error message corresponds to NC_ENOTENABLED is "Feature is not enabled at configure time." So this is equivalent to your NC_ENOTBUILT.

For NC_ENOTSUPPORT, it is "Feature is not yet supported." It is for a feature to be added in the future, or a feature is only available in one format, but not others. For instance, data compression or APIs related to NC_STRING.

NC_ENOTENABLED was added since PnetCDF 1.5.0.
NC_ENOTSUPPORT was 1.3.0.

**Comment by edhartnett** [comment]
I am going to take down this PR until we resolve discussion in the issue and all agreed-upon changes are complete. Then I'll put up a new PR.

**Pull request closed without merging**
