### PR TITLE
large files on 32-bit machines

### PR DESCRIPTION
**Pull request by wkliao**
This PR may fix the problem in #629.

On 32-bit machines, data type long is of size 4 bytes and both fseek()/ftell() return a value of type long. This PR replaces long with off_t, fseek/ftell with lseek, and includes unistd.h to get correct file size when it is > 4GB.

### CODE REVIEW

**Comment by edhartnett** [comment]
Awesome catch. Funny thing is, I remember Russ Rew making this exact same fix long, long ago. Somehow it was lost.

**Comment by edhartnett** [comment]
@wkliao can we get a test for this?

**Comment by wkliao** [comment]
A test? Not sure what you meant.

**Comment by edhartnett** [comment]
Every change to the source code should be accompanied by a test for the new functionality. If it's to fix a bug, then the test should exercise the bug so that the code fails without the fix being applied. So give me some test code that fails on 32-bit machines without this fix.

I am putting together a branch with several combined outstanding PRs, then we are going to run that through testing and merge to master. I didn't include this PR because there is no test. I will swing around and pick it up on the next pass, if you have a test. Otherwise I have to write one. ;-)

**Comment by wkliao** [comment]
OK. I see you meant a test program.

This PR was created because of the failure of 3 test programs reported in #629.
Those programs are short and sweet, particularly nc_test/tst_big_var.c
I could not come up with a better one. Could you use that one?

**Comment by edhartnett** [comment]
Yes, I just didn't know that we already had test code failing for this. ;-)

Thanks, looks like this might make it into master soon if we can confirm this...

**Comment by edhartnett** [comment]
@russrew do you remember making a fix like this in the code?

**Comment by rkrew** [comment]
I certainly made a fix like this, but there were several fixes to get big
files working on 32-bit platforms. We added tests that demonstrated some
problems were then fixed on 32- bit platforms, but it's possible that the
tests weren't complete enough to catch every problem.

I think that was before moving netCDF to github ...

**Comment by WardF** [comment]
Looks good so far @wkliao thank you very much! Will roll this into the 4.6.0 release.

**Comment by edhartnett** [comment]
Was this change in the 4.6.0 release?

**Comment by WardF** [comment]
It was not as there were some failures I was seeing.  I am working on it now.

**Comment by WardF** [comment]
Issue resolved, will merge as this one next.

**Comment by WardF** [comment]
Ok, pretty sure this one had been merged, looking into it.

**Pull request merged**
