### PR TITLE
Some fixes for configure.ac

### LINKED ISSUE #1195: autoconf problems for builds with static HDF5 library
This is similar to #324 but in the autotools build.

When shared libraries are used, the HDF5 shared library knows where to find the libraries it needs, so these problems do not occur.

With static only builds, if the HDF5 library is built with szlib, then the netCDF configure will fail like this:

```
checking for library containing H5Fflush... no
configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.

```

A look in config.log reveals this:

```
configure:17782: gcc -o conftest  -I/usr/local/wrf_io_serial_static/include -L/usr/local/wrf_io_serial_static/lib conftest.c -lhdf5  -lm -lz -lcurl  >&5
/usr/local/wrf_io_serial_static/lib/libhdf5.a(H5Z.o): In function `H5Z__init_package':
H5Z.c:(.text+0x75c): undefined reference to `SZ_encoder_enabled'
/usr/local/wrf_io_serial_static/lib/libhdf5.a(H5Zszip.o): In function `H5Z_filter_szip':
H5Zszip.c:(.text+0x126): undefined reference to `SZ_BufftoBuffDecompress'
H5Zszip.c:(.text+0x2df): undefined reference to `SZ_BufftoBuffCompress'
/usr/local/wrf_io_serial_static/lib/libhdf5.a(H5PLint.o): In function `H5PL__close':
H5PLint.c:(.text+0x4f8): undefined reference to `dlclose'
/usr/local/wrf_io_serial_static/lib/libhdf5.a(H5PLint.o): In function `H5PL__open':
H5PLint.c:(.text+0x552): undefined reference to `dlopen'
H5PLint.c:(.text+0x56d): undefined reference to `dlsym'
H5PLint.c:(.text+0x605): undefined reference to `dlerror'
/usr/local/wrf_io_serial_static/lib/libhdf5.a(H5PLplugin_cache.o): In function `H5PL__find_plugin_in_cache':
H5PLplugin_cache.c:(.text+0x32a): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
configure:17782: $? = 1
```

The problem here is that -lsz does not appear in the compile line, so the static only HDF5 library can't find it.

The configure.ac is supposed to be checking for the szlib when necessary:

  ```
 # The user may have built HDF5 with the SZLIB library.
   enable_szlib=no
   if test "x$ac_cv_func_H5Z_SZIP" = xyes; then
    enable_szlib=yes
    AC_SEARCH_LIBS([ SZ_Compress], [szip sz], [], [])
  	AC_DEFINE([USE_SZIP], [1], [if true, compile in szip compression in netCDF-4 variables])
   fi

```

But this happens too late.

Also, the HDF5 library uses the dynamic loading libraries. (See this post from Elena on the HDF forum: http://hdf-forum.184993.n3.nabble.com/Errors-compiling-against-Static-build-HDF5-1-8-11-Need-for-ldl-added-to-linker-arguments-td4026300.html)

I have a fix for these problems and will put up a PR shortly.

### LINKED ISSUE #1197: In autotools build, make dist does not generate correct tarball name
make dist generates a tarball like this:

netcdf-4.6.3-development.tar.gz

Instead of:

netcdf-c-4.6.3-development.tar.gz

(Note the "-c".) This is because the package name is netCDF, not netCDF-C, in the configure.ac file.

Since I don't want to change the package name, I have taken advantage of an optional parameter of AC_INIT to specify that the tarballs should use the "-c". I will submit the PR shortly.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #1195.
Fixes #1197.

Some fixes to configure.ac.

### CODE REVIEW

**Comment by WardF** [comment]
I agree, and I'm not sure what the broader reaching implications would be for linux distributions, automated workflows, etc..  We can leave the issue open but for the time being while we sort that out, but lets (for the moment at least) leave the distribution name as it has historically been.

**Comment by edhartnett** [comment]
The distribution name did not change. Only the tarball name is changed, as it should be.

**Comment by edhartnett** [comment]
To elaborate further, it seems that @WardF is using the github-generated distributions, which use the name of the repo, "netcdf-c" as the base of the name.

(Actually this is not a great method, which involved committing a lot of generated files to the repo. A better way would be to use `make dist,` not to use the github generated binaries, and attach the binaries generated by `make dist`. But that's another topic.)

Before this PR, `make dist` will generate distributions with "netcdf" as a base, not "netcdf-c". This leads to the confusing and incorrect situation that the `make dist` releases have an incorrect name.

With this PR, the `make dist` releases will have "netcdf-c" as the base of their name, which will match what has been happening for many releases with the github generated releases. This can have no effect on any downstream user workflow, since they are not generating netcdf releases.

This is useful to me and other netcdf developers, because I often create a dist tarball from a branch, to install and test on an HPC system, to see if the changes in my branch work, even if I don't have a full development environment on that machine.

**Comment by edhartnett** [comment]
@WardF possibly you want to include these changes in the release, so that static library builds work.

Rightly or wrongly, there is a perception in some HPC centers that shared libraries are not a good thing, and so static libraries are preferred.

**Pull request merged**
