### PR TITLE
Revert "Revert "Fix nczarr-experimental: improve build support, disengage hdf5 vs netcdf4 flags, and find AWS libraries""

### PR DESCRIPTION
**Pull request by WardF**
Reverting this reversion in a branch to observe something about github behavior.

### CODE REVIEW

**Comment by WardF** [comment]
Ok, the issue appears to be in `ncgen`; when running

    $ ncgen  -b -4 -N ref_tst_nans -o file://test.nzf#mode=nczarr,nzf ../../ncdump/cdl/ref_tst_nans.cdl

on OSX, the variable attributes created are `fvar:att = Infinity, NaNf, Infinityf ;` and `dvar:att = Infinity, NaN, Infinity ;`.  

On Linux, we see the *expected* values of `fvar:att = -Infinity, Nanf, Infinityf ;` and `dvar:att = -Infinity, Nan, Infinity ;` are generated.

Invoking ncdump on the file in OSX returns the proper output if the file was generated on linux, which leads me to believe that the attribute values are being encoded incorrectly on OSX.  Note that the data values are properly `-Infinity` even when generated on OSX.

**Comment by WardF** [comment]
Testing with `ncgenb -b -4 -N ref_tst_nans -o tst_nc4.nc ../../ncdump/cdl/ref_tst_nans.cdl` generates the expected attribute values.  Any ideas off the top of your head as I continue to diagnose this, @DennisHeimbigner ?

**Comment by WardF** [comment]
Examining the test.nzf directory structure, the .zattrs file associated with the variables does contain the json [Infinity,NaN,Infinity] instead of the expected [-Infinity,NaN,Infinity].  Sorting through to see if I can find where this file is being written.

**Comment by DennisHeimbigner** [comment]
Do not hold be to it, but, I ran into this error a while back.
The file is created by ncgen in tst_nan,sh(?)
The problem as I recall was the ncgen lexer was not properly recognizing
the value of infinity.
The thing to do is to run h5dump (I think its an NC4 file) and see what
value is actually in  the generated file. If it is netcdf-3, then maybe
ncvalidator can show it, or use an old version of ncdump.

**Comment by DennisHeimbigner** [comment]
It is probable that the problem is the handling of infinity in the zjson file.

**Comment by DennisHeimbigner** [comment]
The conversions occur in libnczarr/zcvt.c:
One possibility is near line 299
> case NC_DOUBLE: {
>     snprintf(s,sizeof(s),"%lg",zcvt.float64v); /* handles NAN? */
>	} break;
Note the comment; perhaps this snprintf does not handle -Infinity on OSX?

**Comment by dopplershift** [comment]
Nope, that's not it:
```c
#include <math.h>
#include <stdio.h>

int main(int argc, const char* argv[])
{
    char buf[256];
    double val = -INFINITY;

    snprintf(buf, sizeof(buf), "%lg", val);
    printf("%s\n", buf);

    return 0;
}
```

```
❯ ./a.out
-inf
```
(It felt good for just a couple minutes to write some C.)

**Comment by WardF** [comment]
I think I've found the issue.  On OSX (and according to `man isinf` on linux, any system using glibc 2.01 and earlier), isinf() returns 1 if the argument is `Inf` *or* `-Inf`.  So my guess is that the check for `isinf(d) < 0` at zcvt.c:359 needs to be modified somewhat to use the `fpclassify()` macro.  I'll make that change and see what happens.

**Comment by WardF** [comment]
On closer reading of `fpclassify()`, it doesn't offer a macro for positive or negative infinity.  But, I still think this is where the issue is, so taking a closer look here.

**Comment by WardF** [comment]
Checking for isinf(d) and whether `d` is < or > than 0 has done the trick on OSX.  Let me test that this didn't break things on linux.

**Comment by WardF** [comment]
Ok, I've pushed in a fix with this, everything appears to be working on OSX and Linux and Windows.  Thanks @DennisHeimbigner I'll clear this out and then go through the backlog.  Thanks for bearing with me!

**Comment by dopplershift** [comment]
So because I was curious and had to know, apparently by the C99 spec `isinf(x)` only has to return non-zero if x is pos or neg  infinity. It's not required to indicate which:
image

**Comment by DennisHeimbigner** [comment]
Interesting; the original of this code in dap2/dap4 is pretty old at this point.
That is probably why it was the way it was. I will have to look at libdap2
and libdap4 to make sure they do not fail in the same way.

**Pull request merged**
