### PR TITLE
Combined nc_test/tst_large.c and nc_test/tst_large_cdf5.c

### LINKED ISSUE #621: tst_large.c and tst_large_cdf5.c are mostly the same and should be combined...
tst_large.c and tst_large_cdf5.c are mostly the same and should be combined... 

I wll put the CDF5 tests from tst_large_cdf5.c into tst_large.c, protected by #ifdef ENABLE_CDF5. Then I will remove tst_large_cdf5.c.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #621.

Combined these two very similar tests. Now the test works for all available formats.

### CODE REVIEW

**Comment by edhartnett** [comment]
I will take a look and resubmit this one.

**Comment by WardF** [comment]
I was just coming to comment when you closed; the reason this was originally separated out was to make debugging a CDF5 failure in large files easier.  The large file tests take a long time, particularly on ARM.  I would honestly prefer to keep them separate, but am open to counter arguments.

**Comment by WardF** [comment]
*particularly on Raspberry Pi, I should say, not ARM inherently.

**Comment by DennisHeimbigner** [comment]
You are both right :-)
The CDF5 code is still relatively new and we need to be able
to do some specific tests. Eventually, the cDF5 code will be
considered stable enough that we do not need to keep
separate tests.

**Comment by edhartnett** [comment]
I was not arguing. I will rework this to keep them separate but not duplicate so much test code.

**Pull request closed without merging**
