### PR TITLE
No longer attempting to use MPI_COMM_WORLD as default anywhere in library code

### LINKED ISSUE #989: We should not use MPI_COMM_WORLD as a default in parallel code
I may have started this when I first wrote the parallel I/O code, but sometimes in the code we default to MPI_COMM_WORLD. For example:

```
int
NC4_open(const char *path, int mode, int basepe, size_t *chunksizehintp,
         int use_parallel, void *parameters, NC_Dispatch *dispatch, NC *nc_file)
{
   int res;
#ifdef USE_PARALLEL4
   NC_MPI_INFO mpidfalt = {MPI_COMM_WORLD, MPI_INFO_NULL};
#endif
#if defined USE_PARALLEL4
   int inmemory = ((mode & NC_INMEMORY) == NC_INMEMORY);
#endif

   assert(nc_file && path);

   LOG((1, "%s: path %s mode %d params %x",
        __func__, path, mode, parameters));

#ifdef USE_PARALLEL4
   if (!inmemory && use_parallel && parameters == NULL)
      parameters = &mpidfalt;
#endif /* USE_PARALLEL4 */
```

This is not a correct thing to do. It's likely to work in all our tests and toy cases, but cause a  hang in a real-world HPC system.

When a user is using parallel I/O, they simply must pass in an MPI communicator. This will not be a problem, as they must have a communicator, and all MPI programmers already understand that they must provide a communicator to open/create a disk file.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #989.

We can, should, and do use MPI_COMM_WORLD in our tests, but not in the library code. We must only operate on the communicator specified in the open/create, otherwise we risk hanging the users MPI code.

### CODE REVIEW

**Comment by WardF** [comment]
Going to play catchup and aggregate a few including this one and the hdf5.h one today.

**Comment by edhartnett** [comment]
Thanks!

Actually this one already includes the hdf5.h one, as do a bunch of others, since I need it to pass my own CI system. So you can just merge one of the others and I will close the hdf5.h one. ;-)

#980 is the one I am waiting for. The rest are just me closing tickets while I wait for #980. ;-)

#967 should not be merged until after Dennis' #558, to avoid stepping on our toes with some of the generated files that are checked into the repo. Once #558 is merged, I need to update #967 before it gets merged.

**Comment by edhartnett** [comment]
@WardF also note that Dennis' current inmemory PR is merged into a bunch of my open PRs, in order to pass CI. This makes the code review confusing, since it looks like I messed about with the diskess settings in configure and makefiles. Once Dennis' PR is merged, many of mine will get simpler, so perhaps you should start with his.

**Comment by edhartnett** [comment]
@WardF one of the travis tests timed out trying to load. But these changes pass my full CI and are ready to merge.

**Comment by edhartnett** [comment]
OK, all travis builds passed. This PR is ready for merging.

**Comment by WardF** [comment]
Code review of this and the other open @edhartnett PR is in progress now.

**Pull request merged**
