### PR TITLE
Replaced ancient K&R function declarations to be C23 compatible

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@WardF @DennisHeimbigner The codebase has a lot of old K&R function declarations.  I thought it would just be just a few, so I started fixing them, but I soon realized there were many. So I stopped to share what I started, so it can be discussed. Is it just historical cruft that there are so many?

This syntax is no longer compiles with C23.

**Comment by DennisHeimbigner** [comment]
The code where this is occurring is indeed very old; from the first incarnations of the netcdf-c library.

**Comment by DWesl** [comment]
Another option, if you don't mind setting up doxygen, would be:
```C++
/** delete attribute iatt in the netcdf test
 *
 * \param varid variable id
 */
void
del_att (struct netcdf *test, int varid, att *iatt)
```
It [looks like adding `\private` at the end will leave the function out of the public documentation](https://www.doxygen.nl/manual/commands.html#cmdprivate).
Alternately,
```C++
/** delete attribute iatt in the netcdf test */
void
del_att(struct netcdf *test,
            int varid /**< variable id */,
            att *iatt)
```
combines doxygen with the second style [above](https://github.com/Unidata/netcdf-c/pull/2801#issuecomment-1811649221)

**Comment by seanm** [comment]
@DWesl almost all the affected files are test files... not sure using doxygen makes sense there...?

**Review by WardF — APPROVED** [review]

**Comment by WardF** [comment]
No particular preference; Doxygen would be great (even in test files), but the lack of doxygen wouldn't prevent adoption of a PR.  Thanks! We're focused on working through the backlog, and making good progress.

**Comment by seanm** [comment]
>No particular preference

OK, this is done then IMHO.

**Review by WardF — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Thanks for this!

**Pull request merged**
