### PR TITLE
WIP: Allow users to set data alignment within netcdf4 files

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/Unidata/netcdf-c/issues/2177

I'm really not sure how to make this "backward" compatible with older versions.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
A couple of immediate questions.
1. What is the use case(s) for this?
2. Can this be done by a separate (new) API function that must be called after nc_create, but before anything is written to the file?

**Comment by hmaarrfk** [comment]
The main usecase for this is to memorymap large arrays in an alligned fashion. This enables efficient transfer of data between SSDs, network interfaces, and RAM.

I'll look to see if i can do this later after opening.

**Comment by hmaarrfk** [comment]
I honestly tried to look through the documentation, it isn't clear that you can change the FAPL after creation.

From the examples, they seem to open a file, copy the FAPL, then close it, then reopen it with a different FAPL.

I also posted the question on the forum, but I need to get moderated. It should appear
https://forum.hdfgroup.org/c/hdf5
in a few days i guess

**Comment by hmaarrfk** [comment]
Sorry, looking at the source, it is clear that it is a "copy" of the FAPL.
https://github.com/HDFGroup/hdf5/blob/develop/src/H5F.c#L152
image

**Comment by DennisHeimbigner** [comment]
I will have to think about this.

**Comment by edwardhartnett** [comment]
As we discussed in the other thread, alignment has to be set before the file open. When netcdf-c opens a file, it will use the alignment setting to call the HDF5 alignment function when it creates the FAPL...

**Comment by hmaarrfk** [comment]
On the HDF5 forum, it is confirmed that it must be specified at open time:
https://forum.hdfgroup.org/t/dynamically-change-the-file-access-property-list/9314/3

**Pull request closed without merging**
