### PR TITLE
Added detail about _FillValue being undefined.

### PR DESCRIPTION
**Pull request by pelson**
**Executive summary**:
It is my understanding is that it is not possible to declare a variable without the concept of a fill value. This is a consequence of the implied "default" fill value. The implications of this are:
- We can't use the full range of the variable's datatype
  - We currently have to special-case byte data to get around that
- There is a performance penalty at variable data load because we need to scan the data to see if any of the values match the (default) fill value
- There is a(n implied) performance penalty at variable data save because we should probably scan the data to determine whether the saved values would collide with the (default) fill value

The proposal is therefore to avoid the use of a "default fill value" altogether. Should a fill value be required for a particular purpose, it is necessary to explicitly save the ``fill_value`` on the variable. There is nothing stopping variable creation from using a default fill value, but it should be possible to declare a variable to have **no** ``fill_value``.

--------

The change itself is somewhat basic - I didn't go to town with making it perfect as I wanted to have the conversation first (as per the [CONTRIBUTING](https://github.com/Unidata/netcdf-c/blob/master/CONTRIBUTING.md) guidelines).

Given I'm modifying long paragraphs, I've included the before and after in the PR description:

Existing docs:

>  The _FillValue attribute specifies the fill value used to pre-fill disk space allocated to the variable. Such pre-fill occurs unless nofill mode is set using nc_set_fill(). The fill value is returned when reading values that were never written. If _FillValue is defined then it should be scalar and of the same type as the variable. If the variable is packed using scale_factor and add_offset attributes (see below), the _FillValue attribute should have the data type of the packed data.
> 
>  It is not necessary to define your own _FillValue attribute for a variable if the default fill value for the type of the variable is adequate. However, use of the default fill value for data type byte is not recommended. Note that if you change the value of this attribute, the changed value applies only to subsequent writes; previously written data are not changed.
> 
>  Generic applications often need to write a value to represent undefined or missing values. The fill value provides an appropriate value for this purpose because it is normally outside the valid range and therefore treated as missing when read by generic applications. It is legal (but not recommended) for the fill value to be within the valid range.
> 

Proposed docs:

> The _FillValue attribute specifies the fill value used to pre-fill disk space allocated to the variable. Such pre-fill occurs unless nofill mode is set using nc_set_fill(). The fill value is returned when reading values that were never written. If _FillValue is defined then it should be scalar and of the same type as the variable. If the variable is packed using scale_factor and add_offset attributes (see below), the _FillValue attribute should have the data type of the packed data.
> 
> If _FillValue is undefined, it is assumed that there are no unwritten data-values. Generic applications needing to write a value to represent undefined or missing values may use either `_FillValue` or `missing_value` for this purpose. It is legal (but not recommended) for the fill value to be within the valid range of the data.
> 
> 
> Note that if you change the value of this attribute, the changed value applies only to subsequent writes; previously written data are not changed.

----------

Cheers,

### CODE REVIEW

**Comment by pelson** [comment]
I just wanted to add that I'm looking at this from the perspective of a consumer of netcdf4-python and going through the details at https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L3874-L3999.

I'm also completely comfortable for this to be closed if there has already been a decision made on this / it would break compatibility.

**Comment by DennisHeimbigner** [comment]
> It is my understanding is that it is not possible to declare a variable without the concept of a fill value.
I think this is incorrect.
It is possible to turn fill mode on/off globally using nc_set_fill().
It is also possible to use nc_def_var_fill to turn fill on/off for a specific variable. 
As far as I know, this behavior has not changed.
Can you elaborate your concerns?

**Comment by pelson** [comment]
> It is my understanding is that it is not possible to declare a variable without the concept of a fill value.

>> I think this is incorrect.
>> It is possible to turn fill mode on/off globally using nc_set_fill().

So my concern is that this is a software flag to change the interpretation of the file. I'm looking to make this a fundamental part of the metadata, not the implementing software. Without this, the NetCDF files are open to different interpretations - and are therefore not self-describing.

**Comment by edhartnett** [comment]
I agree with Phil that the current behavior implies a fill value.

If I get a mysterious file with one NC_INT variable, when reading that
variable, I must be aware that NC_FILL_INT may have a special meaning. Even
if the variable was written with no_fill mode, I have no way of knowing
that when I read the file.

But to change the current use of default fill values would be a large API
change. I don't see how that could be backward compatible with existing
code.

Perhaps, Phil, you want to think about a new convention. Perhaps the
attribute "NoFill" could be attached to variables to indicate that there
are no fill values in use?

Ed Hartnett

**Comment by pelson** [comment]
Agreed about the backwards compatibility. As I see it, there are a couple of options:

* ``_FillValue`` is explicitly used to denominate "no fill value"
  * For example, IEEE NaN could be used (for all dtypes). However, this would mean that non-float data would have a floating point ``_FillValue`` attribute 
* A new attribute ``(_)NoFill`` denominates "no fill value"
  * What should the behaviour be when "no fill value" and ``_FillValue`` are both defined?

**Comment by DennisHeimbigner** [comment]
There already is a _NoFill special attribute available.
But, I see that somehow the documentation on it and a
bunch of other special attributes got lost somewhere.
It is mentioned in the documentation for ncgen,,
but AFAIK, nowhere else.

**Comment by WardF** [comment]
I will see if I can dig it out of the 'historic' documentation; a lot of what is in that directory has yet to make the leap to doxygen ( hence why it's retained for now). Maybe it's in there?  If not, we should definitely get it added to the current documentation.

**Comment by DennisHeimbigner** [comment]
Or maybe it was never documented.

**Comment by WardF** [comment]
Merged into 4.5.0 release branch instead of master, so closing manually. Thank you!

**Comment by pelson** [comment]
Thanks @WardF. I don't see any documentation about the `_NoFill` attribute. Has this been done elsewhere?

**Comment by WardF** [comment]
Reopening to make sure I revisit this. I had added something but I don't see it either.

**Comment by pelson** [comment]
I was just checking up on the fill_value docs after this conversation, and I notice that my proposed changes have been merged despite the concern raised by @edhartnett regarding:

> But to change the current use of default fill values would be a large API
change. I don't see how that could be backward compatible with existing
code

The latest version (on master) can be found at: https://github.com/Unidata/netcdf-c/blob/master/docs/attribute_conventions.md

I just wanted to be very explicit that this has happened before the 4.5.0 release is finalised, just in case corrective action needs to take place.

Note that, as a result of merging this change, it has not been necessary to document the ``_NoFill`` attribute - if it were to be decided that the change that was merged here isn't OK for release, I'd greatly appreciate seeing ``_NoFill`` included in the docs.

Thanks,

**Comment by DennisHeimbigner** [comment]
I believe that Ed's concerns are sufficient to reject this change. But I confess at this point, I still
do not have a concise set of bullet points about what is being proposed. More specifically
what are the complete consequences of this change.

**Comment by WardF** [comment]
I am reverting the change now, and adding details about `_NoFill`.  After discussing this with Dennis, it needs to be made clear that `_NoFill` is used specifically by `ncgen` when converting .cdl to binary.  Otherwise, it is unused.  Once reverted and documentation is updated, we will revisit the broader proposal.

**Comment by pelson** [comment]
Thanks all. Sorry for any confusion caused. If ``_NoFill`` is used by ncgen is it good enough to be documented in general? I'd like to make use of this convention to avoid the need for the expensive validation in the no-fill-necessary case.

**Comment by WardF** [comment]
I've added some documentation describing the use, and Dennis and I have spoken this morning. We're going to really clarify this documentation once the 4.5.0 push is over, and decide if there are any functional changes to be made.

**Pull request merged**
