### PR TITLE
ported rename fix changes from branch ejh_fill_values for easy merging

### LINKED ISSUE #741: Passing NULL as new name to NC4_rename_var() causes segfault
NC4_rename_var() neglects to check for null parameter. I will add...

### LINKED ISSUE #746: When dim renamed, optional attribute _Netcdf4Dimid is not deleted from original coord var
In tst_rename.c we have the following test code:
```
int
create_test_file(char *path, int format)
{
   int ncid, varid, var2id;
   int dims[VAR_RANK];

   if (nc_set_default_format(format, NULL)) ERR;
   if (nc_create(path, 0, &ncid)) ERR;
   if (nc_def_dim(ncid, LAT, DIM_LEN, &dims[0])) ERR;
   if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, dims, &varid)) ERR;
   if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, dims, &var2id)) ERR;
   if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
   if (nc_put_var_int(ncid, varid, lats)) ERR;
   if (nc_put_var_float(ncid, var2id, rh)) ERR;
   if (nc_close(ncid)) ERR;
   return 0;
}
```

and

```
         if (create_test_file(file_names[format], formats[format])) ERR;
         if (nc_open(file_names[format], NC_WRITE, &ncid)) ERR;
         if (nc_inq_dimid(ncid, LAT, &dimid)) ERR;
         if (nc_inq_varid(ncid, LAT, &varid)) ERR;
         if (nc_inq_varid(ncid, RH, &var2id)) ERR;
         if (check_file(ncid, LAT, RH, LAT)) ERR;
         if (nc_redef(ncid)) ERR;

         /* Rename the dim. */
         if (nc_rename_dim(ncid, dimid, TAL)) ERR;
         if (nc_close(ncid)) ERR;

```

This results in the following HDF5 file:

```
HDF5 "tst_rename_fix3.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 67;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.5.1-development|hdf5libversion=1.10.1"
      }
   }
   DATASET "lat" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): -90, 90
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 6160 /tal )
         }
      }
      ATTRIBUTE "_Netcdf4Dimid" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
   }
   DATASET "rh" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0.25, 0.75
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 6160 /tal )
         }
      }
   }
   DATASET "tal" {
      DATATYPE  H5T_IEEE_F32BE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0, 0
      }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
            STRSIZE 16;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "DIMENSION_SCALE"
         }
      }
      ATTRIBUTE "NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 64;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "This is a netCDF dimension but not a netCDF variable.         2"
         }
      }
      ATTRIBUTE "REFERENCE_LIST" {
         DATATYPE  H5T_COMPOUND {
            H5T_REFERENCE { H5T_STD_REF_OBJECT } "dataset";
            H5T_STD_I32LE "dimension";
         }
         DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
         DATA {
         (0): {
               DATASET 331 /lat ,
               0
            },
         (1): {
               DATASET 635 /rh ,
               0
            }
         }
      }
   }
}
}

```

Note that the _Netcdf4Dimid attribute is incorrectly attached to dataset "lat". This is incorrect. It should have been removed in the rename, when "lat" went from being a coordinate variable to just a regular variable.

### LINKED ISSUE #749: Renaming dim and var may change var order in file...
This code:

```
int
create_test_file(char *path, int format)
{
   int ncid, varid, var2id;
   int dims[VAR_RANK];

   if (nc_set_default_format(format, NULL)) ERR;
   if (nc_create(path, 0, &ncid)) ERR;
   if (nc_def_dim(ncid, LAT, DIM_LEN, &dims[0])) ERR;
   if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, dims, &varid)) ERR;
   if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, dims, &var2id)) ERR;
   if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
   if (nc_put_var_int(ncid, varid, lats)) ERR;
   if (nc_put_var_float(ncid, var2id, rh)) ERR;
   if (nc_close(ncid)) ERR;
   return 0;
}
```

and

```

      {
         int ncid, varid, var2id;
         int dimid;
         
         if (nc_set_default_format(formats[format], NULL)) ERR;
         if (nc_create(file_names[format], 0, &ncid)) ERR;
         if (nc_def_dim(ncid, LAT, DIM_LEN, &dimid)) ERR;
         if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, &dimid, &varid)) ERR;
         if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, &dimid, &var2id)) ERR;
         if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
         if (nc_redef(ncid)) ERR;    /* not necessary for netCDF-4 files */

         /* Now rename the dim. */
         if (nc_rename_dim(ncid, dimid, TAL)) ERR;
         if (nc_rename_var(ncid, varid, TAL)) ERR;
         if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
         
         if (nc_put_var_int(ncid, varid, lats)) ERR;
         if (nc_put_var_float(ncid, var2id, rh)) ERR;
         if (nc_close(ncid)) ERR;

         /* Reopen and check. */
         if (nc_open(file_names[format], NC_WRITE, &ncid)) ERR;
         if (check_file(ncid, TAL, RH, TAL)) ERR;
         if (nc_close(ncid)) ERR;
      }

```
Produces this data file. 
```
netcdf tst_rename_fix3 {
dimensions:
	tal = 2 ;
variables:
	float rh(tal) ;
	int tal(tal) ;
data:

 rh = 0.25, 0.75 ;

 tal = -90, 90 ;
}
```

Note that the vars are out of order. What has happened is that the variable was re-created when renamed, and then shown in HDF5 create order. 

The h5dump of the file:

```
HDF5 "tst_rename_fix3.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 67;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.5.1-development|hdf5libversion=1.10.1"
      }
   }
   DATASET "rh" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0.25, 0.75
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 331 /tal )
         }
      }
   }
   DATASET "tal" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): -90, 90
      }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
            STRSIZE 16;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "DIMENSION_SCALE"
         }
      }
      ATTRIBUTE "NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 4;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "lat"
         }
      }
      ATTRIBUTE "REFERENCE_LIST" {
         DATATYPE  H5T_COMPOUND {
            H5T_REFERENCE { H5T_STD_REF_OBJECT } "dataset";
            H5T_STD_I32LE "dimension";
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): {
               DATASET 635 /rh ,
               0
            }
         }
      }
      ATTRIBUTE "_Netcdf4Dimid" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
   }
}
}

```

### PR DESCRIPTION
**Pull request by edhartnett**
This PR contains the changes to the rename code from unmerged PR #755.

There are also a bunch of comments that I added as I figured out what the code was doing and why.

Not all rename issues are fixed, but some are.

Part of #597.
Fixes #741.
Fixes #746.
Fixes #749.

Rename work will continue for next release, but we wanted to get these changes into 4.6.0.

### CODE REVIEW

**Comment by czender** [comment]
Ed, I am trying to test this branch as requested. However, my Git-fu is weak. I normally just test netcdf-c/master:
```
zender@skyglow:/data/zender/tmp/netcdf-c$ git branch
  list
* master
  v4.5.0-release-branch
```
I don't know how to check-out the branch you ask me to test:
```
zender@skyglow:/data/zender/tmp/netcdf-c$ git checkout ejh_rename2
error: pathspec 'ejh_rename2' did not match any file(s) known to git.
zender@skyglow:/data/zender/tmp/netcdf-c$ git checkout NetCDF-World-Domination-Council:ejh_rename2
error: pathspec 'NetCDF-World-Domination-Council:ejh_rename2' did not match any file(s) known to git.
```
Suggestions would be welcome.

**Comment by edhartnett** [comment]
Howdy Charlie!

You need to clone my fork of netCDF first:

```
git clone https://github.com/NetCDF-World-Domination-Council/netcdf-c.git
cd netcdf-c
git checkout ejh_rename2
```

**Comment by edhartnett** [comment]
@WardF it would probably be good to get this into 4.6.0 if it is not too late. It contains an important rename fix for the AR6 people...

**Comment by WardF** [comment]
@czender any feedback on this?

**Comment by czender** [comment]
I just tested Ed's branch as per instructions above. Good news is that it now passes the test case I sent you, which means the CMIP6 usage might work. Bad news is that it still fails the NCO regression test (ncrename #31) which is more stringent. The rename command in that test succeeds but it creates a corrupt file. Corrupt in the sense that it has duplicate dimension IDs for distinct dimensions. ncdump can print the resulting file, but ncks cannot, presumably because ncks does an elaborate consistency check of file metadata prior to printing. So I think this counts as overall progress and Ed's patch should be merged. He has said all along that his work has not yet caught all rename bugs, and this patch did not increase the number of regression failures. 

For the record, test ncrename #31 essentially does this:
```
ncrename -O -d lev,z -d lat,y -d lon,x ~/nco/data/in_grp.nc ~/foo.nc # succeeds
ncks ~/foo.nc # fails
```
and the NCO failure diagnostic is 
```
 zender@skyglow:~$ ncks ~/foo.nc
ncks: INFO nco_bld_dmn_ids_trv() reports variable </g5/one_dmn_rec_var> with duplicate dimensions
ncks: ERROR netCDF file with duplicate dimension IDs detected. Please use netCDF version at least 4.3.0.
ncks: INFO reports group information
/: 11 subgroups, 7 dimensions, 1 record dimensions, 5 attributes, 18 variables
#3 dimension: 'coord'(2)
 #4 record dimension: 'time'(10)
 #5 dimension: 'vrt_nbr'(2)
 #6 dimension: 'gds_crd'(8)
 #7 dimension: 'y'(2)
 #8 dimension: 'x'(4)
 #9 dimension: 'z'(3)
 #7 record dimension: 'time51'(2)
 #8 record dimension: 'time52'(10)
```
which is pretty inscrutable but once deciphered means that the dimensions "y" and "x" in the output file have the same dimension IDs as dimensions "time51" and "time52", respectively, even though they are different sizes and in different groups and generally not related at all.

**Comment by edhartnett** [comment]
Thanks Charlie! We are going to try and get the outstanding PR merged, along with the others, and then I will tackle the rename problem more completely.

**Comment by WardF** [comment]
@edharnett since I’m focusing on the windows nccopy issue before looking at other prs, feel free to take a look at this if you find yourself at loose ends. If it is fixed by the 4.6.0 release we can evaluate it on our end as well :).

**Comment by edhartnett** [comment]
@WardF not sure what you mean.

I need to get this PR merged to master, along with the other outstanding PRs that mess with this code. Then I will take a look at the rename problem again. RIght now, it's hard to know what the master will be.

**Comment by WardF** [comment]
Ah, I misunderstood; I'll take a look at it merging it into the master with the rest of the PR's when I have time to focus on that! Then we can get everything in sync.

**Comment by edhartnett** [comment]
These changes are now part of #788 so I will close this PR.

**Pull request closed without merging**
