### PR TITLE
added fill mode and var rename tests

### LINKED ISSUE #379: Is nc_inq_var_fill() returning the correct answer for parameter no_fill for classic file?
I run this code to create a netcdf file with 1 dim, 1 var, and I write 1 value:

```
#define NDIM1 1
#define DIM_LEN 4
#define DIM_NAME "my_dim"
#define VAR_NAME "my_var"

       int ncid;
        int dimid;
        int varid;
        int cmode = 0;
        char testfile[] = "test.nc";
        size_t index = 2;
        int test_val = 42;
        int no_fill;
        int ret;
        
        if ((ret = nc_create(testfile, cmode, &ncid)))
            return ret;
        if ((ret = nc_def_dim(ncid, DIM_NAME, DIM_LEN, &dimid)))
            return ret;
        if ((ret = nc_def_var(ncid, VAR_NAME, NC_INT, NDIM1, &dimid, &varid)))
            return ret;
        if ((ret = nc_enddef(ncid)))
            return ret;
        if ((ret = nc_put_var1_int(ncid, varid, &index, &test_val)))
            return ret;
        if ((ret = nc_inq_var_fill(ncid, varid, &no_fill, NULL)))
            return ret;
        printf("in netcdf test no_fill = %d\n", no_fill);
        if ((ret = nc_close(ncid)))
            return ret;

```
As expected I get a file like this:

```
netcdf test {
dimensions:
	my_dim = 4 ;
variables:
	int my_var(my_dim) ;
data:

 my_var = _, _, 42, _ ;
}

```

But my print statement is telling me that no_fill is set for this variable:

`in netcdf test no_fill = 1
`

Since I have not changed the fill mode, I expect this value to be 0, indicating that fill mode is on, which is the default. And indeed it does seem to be on. But nc_inq_var_fill is telling me that it is not.

Am I missing something?

(Note I do get the correct answer when I change cmode to NC_NETCDF4.)

### LINKED ISSUE #742: New var name in nc_rename_var() is not normalized for utf8. Should it be?
In nc_rename_dim() the new name is run through nc_utf8_normalize().

But this doesn't happen with nc_rename_var().

Shouldn't it?

### LINKED ISSUE #800: Reserved attribute names should be mentioned in the docs
There are some reserved attribute names. They should be mentioned in the documentation of nc_put_att/nc_get_att.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #379.
Fixes #742.
Fixes #800.

The fill mode issue has actually been fixed for some time thanks to @wkliao. This PR adds a test which confirms that this works and continues to work.

The other test confirms that names are utf8 normalized during variable renames.

Also added documentation of attribute reserved names to users guide.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Isn't this already in docs/attribute_conventions.md

**Comment by edhartnett** [comment]
Fair enough. Want me to remove what I just added to the user manual?

**Comment by DennisHeimbigner** [comment]
Assuming the attribute-conventions is not referenced in the guide,
perhaps this should be changed to refer to the attribute conventions
document.

**Comment by edhartnett** [comment]
I have just left the documentation alone, in the end.

This PR is ready to merge. There are some failures in travis due to the HDF5 plugin file copy issue.

**Comment by DennisHeimbigner** [comment]
it is out of date wrt to master. Can you fix?

**Comment by edhartnett** [comment]
@DennisHeimbigner have updated with master, will keep an eye on Travis tests to make sure they succeed...

**Pull request merged**
