### PR TITLE
Fix NCclosedir in dpathmgr.c

### LINKED ISSUE #1999: dpathmgr.c: error: ‘path’ undeclared when cross-compiling netCDF 4.8.0
I am trying to update the netCDF Julia package to the current version. 

* the version of the software with which you are encountering an issue
NetCDF 4.8.0

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
Cross-compilation from Linux to Windows (x86_64-w64-mingw32) in Julia's build tree [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil). 

* a description of the issue with the steps needed to reproduce it

NetCDF is cross-compiled using the following steps (line 26-46)
https://github.com/JuliaPackaging/Yggdrasil/blob/7a37fabb2eb7c680766aea06af77a055183c92f1/N/NetCDF/common.jl#L26

In addition, we used the option `CPPFLAGS=-DH5_USE_110_API`.
(https://github.com/Unidata/netcdf-c/issues/1978#issuecomment-817224097 )

Compiliation succeeds on Linux and Mac OS, but fails on Windows with the error:
```
2021-05-17T15:55:38.3906619Z [15:55:38] dpathmgr.c: In function ‘NCclosedir’:
2021-05-17T15:55:38.3907622Z [15:55:38] (first use in this function)
2021-05-17T15:55:38.3908452Z [15:55:38]      char* cvtname = NCpathcvt(path);
2021-05-17T15:55:38.3909108Z [15:55:38]                                ^
2021-05-17T15:55:38.3909968Z [15:55:38] dpathmgr.c:359:31: note: each undeclared identifier is reported only once for each function it appears in
```
For reference the full log files is attached. I am not sure if this error is related to the option `-DH5_USE_110_API`.
Do you have any idea what could be the issue?
Thanks a lot for any insight!

[44.txt](https://github.com/Unidata/netcdf-c/files/6496519/44.txt)

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes #1999 

re: Issue https://github.com/Unidata/netcdf-c/issues/1999

NCclosedir code is incorrect. Fix.
Note that this issue crops up when using a non-VisualStudio windows build
such as Mingw because Mingw defines dirent.h, but Visual Studio does not.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Thank you for updating `NCclosedir`.
For your information, I get the following additional errors on `x86_64-w64-mingw32`:

```
In file included from zmapio.c:17:0:
../include/XGetopt.h:38:24: error: conflicting types for ‘getopt’
 GTOPT_EXTRA extern int getopt(int argc, TCHAR *argv[], TCHAR *optstring);
                        ^~~~~~
In file included from /usr/share/mingw-w64/include/unistd.h:12:0,
                 from zmapio.c:11:
/usr/share/mingw-w64/include/getopt.h:29:12: note: previous declaration of ‘getopt’ was here
 extern int getopt(int nargc, char * const *nargv, const char *options);
            ^~~~~~
In file included from ncdumpchunks.c:14:0:
../include/XGetopt.h:38:24: error: conflicting types for ‘getopt’
 GTOPT_EXTRA extern int getopt(int argc, TCHAR *argv[], TCHAR *optstring);
                        ^~~~~~
In file included from ncdumpchunks.c:10:0:
/usr/share/mingw-w64/include/getopt.h:29:12: note: previous declaration of ‘getopt’ was here
 extern int getopt(int nargc, char * const *nargv, const char *options);
            ^~~~~~
In file included from zmapio.c:21:0:
../include/ncpathmgr.h:122:39: warning: ‘struct stat’ declared inside parameter list will not be visible outside of this definition or declaration
 EXTERNL int NCstat(char* path, struct stat* buf);
                                       ^~~~
In file included from ncdumpchunks.c:18:0:
../include/ncpathmgr.h:122:39: warning: ‘struct stat’ declared inside parameter list will not be visible outside of this definition or declaration
 EXTERNL int NCstat(char* path, struct stat* buf);
                                       ^~~~
Makefile:936: recipe for target 'zmapio.o' failed
make[2]: *** [zmapio.o] Error 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
Makefile:936: recipe for target 'ncdumpchunks.o' failed
make[2]: *** [ncdumpchunks.o] Error 1
In file included from zs3parse.c:15:0:
../include/XGetopt.h:38:24: error: conflicting types for ‘getopt’
 GTOPT_EXTRA extern int getopt(int argc, TCHAR *argv[], TCHAR *optstring);
                        ^~~~~~
In file included from /usr/share/mingw-w64/include/unistd.h:12:0,
                 from zs3parse.c:9:
/usr/share/mingw-w64/include/getopt.h:29:12: note: previous declaration of ‘getopt’ was here
 extern int getopt(int nargc, char * const *nargv, const char *options);
            ^~~~~~
In file included from zs3parse.c:19:0:
../include/ncpathmgr.h:122:39: warning: ‘struct stat’ declared inside parameter list will not be visible outside of this definition or declaration
 EXTERNL int NCstat(char* path, struct stat* buf);
                                       ^~~~
Makefile:936: recipe for target 'zs3parse.o' failed
```

These error are related to https://github.com/Unidata/netcdf-c/issues/1737.
The following patch solves this:

```diff
diff --git a/nczarr_test/ncdumpchunks.c b/nczarr_test/ncdumpchunks.c
index 2eecc425..b17461c4 100755
--- a/nczarr_test/ncdumpchunks.c
+++ b/nczarr_test/ncdumpchunks.c
@@ -10,7 +10,7 @@
 #include <getopt.h>
 #endif
 
-#ifdef _WIN32
+#ifdef _MSC_VER
 #include "XGetopt.h"
 #endif
 
diff --git a/nczarr_test/zmapio.c b/nczarr_test/zmapio.c
index 70f13ed0..35448e6a 100644
--- a/nczarr_test/zmapio.c
+++ b/nczarr_test/zmapio.c
@@ -13,7 +13,7 @@
 #ifdef HAVE_GETOPT_H
 #include <getopt.h>
 #endif
-#ifdef _WIN32
+#ifdef _MSC_VER
 #include "XGetopt.h"
 #endif
 
diff --git a/nczarr_test/zs3parse.c b/nczarr_test/zs3parse.c
index 9ec5476c..6ff97a40 100644
--- a/nczarr_test/zs3parse.c
+++ b/nczarr_test/zs3parse.c
@@ -11,7 +11,7 @@
 #ifdef HAVE_GETOPT_H
 #include <getopt.h>
 #endif
-#ifdef _WIN32
+#ifdef _MSC_VER
 #include "XGetopt.h"
 #endif
 ```

**Comment by DennisHeimbigner** [comment]
Ok, I have modified this PR to include above fixes plus fix the struct stat warning.

[Also merged current master to remove conflicts]

**Comment by WardF** [comment]
@DennisHeimbigner I'm going through the backlog. I don't want to jump the gun, however, are there more fixes to be made or is this one ready?

**Comment by DennisHeimbigner** [comment]
I think it is ready; it was a pretty ugly PR.

**Comment by Alexander-Barth** [comment]
On current master (427166f02d3da6924d02a4713c1ffe50bb92a36c), the getopt issue seems to be re-surfaced in ncgen3:

```
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from main.c:19:0:
../include/XGetopt.h:38:24: error: conflicting types for 'getopt'
 GTOPT_EXTRA extern int getopt(int argc, TCHAR *argv[], TCHAR *optstring);
                        ^~~~~~
In file included from /usr/share/mingw-w64/include/unistd.h:12:0,
                 from main.c:11:
/usr/share/mingw-w64/include/getopt.h:29:12: note: previous declaration of 'getopt' was here
 extern int getopt(int nargc, char * const *nargv, const char *options);
            ^~~~~~
Makefile:748: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
make[2]: Leaving directory '/home/abarth/src/netcdf-c/ncgen3'
```

It can be reproduced on Linux with:

```bash
# sudo apt install gcc-mingw-w64-x86-64 # on Ubuntu 20.04
 ./configure CC=x86_64-w64-mingw32-gcc --disable-hdf5  --disable-dap  --host=x86_64-w64-mingw32  &&  make -j4
```
Let me know if this should rather be a separate issue. Sorry for all these troubles! Thanks for your help!

**Comment by DennisHeimbigner** [comment]
Odd; the #include <XGetopt.h> is encased in _WIN32 on my master. Is it the case
in ncgen3/main.c for you?

**Comment by DennisHeimbigner** [comment]
Look in your netcdf-c/config.h file and see if HAVE_GETOPT_H is turned on.
I notice that you are getting you getopt definition from unistd.h.

**Comment by Alexander-Barth** [comment]
Yes, <XGetopt.h> is encased in _WIN32:

```
#ifdef _WIN32
#include "XGetopt.h"
#define snprintf _snprintf
#endif
```
In `config.h`, `HAVE_GETOPT_H` is indeed 1. I attach `config.h` and `config.log` in case it is helpful.

[config.h.txt](https://github.com/Unidata/netcdf-c/files/6534708/config.h.txt)
[config.log.txt](https://github.com/Unidata/netcdf-c/files/6534709/config.log.txt)

**Comment by Alexander-Barth** [comment]
The compilation of ncgen3 succeeds with this change:

```diff
index 263bd699..ccb8acd5 100644
--- a/ncgen3/main.c
+++ b/ncgen3/main.c
@@ -13,10 +13,11 @@
 #include <string.h>
 #ifdef HAVE_GETOPT_H
 #include <getopt.h>
+#else
+#include "XGetopt.h"
 #endif
 
 #ifdef _WIN32
-#include "XGetopt.h"
 #define snprintf _snprintf
 #endif
```
(including XGetopt.h only if HAVE_GETOPT_H is not defined). 
But I have similar issue in `ncgen/main.c`.

**Comment by DennisHeimbigner** [comment]
Ok, mingw headers appear to be very non-standard.
My guess is that you the use of mingw should be tested for explicitly.
Something like this:
#if defined _WIN32 && ! __MINGW32__

**Comment by Alexander-Barth** [comment]
Here is an updated version of your suggestion that I tested:

```diff
index 263bd699..6f9c5f5d 100644
--- a/ncgen3/main.c
+++ b/ncgen3/main.c
@@ -15,7 +15,7 @@
 #include <getopt.h>
 #endif
 
-#ifdef _WIN32
+#if defined(_WIN32) && !defined(__MINGW32__)
 #include "XGetopt.h"
 #define snprintf _snprintf
 #endif
```

It would be really nice to have a CI testing of the mingw compiler (used by e.g. R, Octave and Julia on Windows). 
On Ubuntu, cross-compiling can be done quite easily (disabling HDF5), using for example:
```bash
 ./configure CC=x86_64-w64-mingw32-gcc --disable-hdf5   --host=x86_64-w64-mingw32  && make
```
If it is helpful, I can try to find the equivalent command in CMake.

**Comment by DennisHeimbigner** [comment]
Did that change work? If so, then I need to propagate it to all uses of xgetopt.
I will talk to Ward about testing Mingw.

**Comment by Alexander-Barth** [comment]
Yes, I tested it `ncgen3` and it fixed the compiler error.

```
cd ~/src/netcdf-c/ncgen3
make
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo load.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT load.o -MD -MP -MF $depbase.Tpo -c -o load.o load.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo escapes.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT escapes.o -MD -MP -MF $depbase.Tpo -c -o escapes.o escapes.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo getfill.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT getfill.o -MD -MP -MF $depbase.Tpo -c -o getfill.o getfill.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo init.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT init.o -MD -MP -MF $depbase.Tpo -c -o init.o init.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo genlib.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT genlib.o -MD -MP -MF $depbase.Tpo -c -o genlib.o genlib.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo ncgeny.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include     -MT ncgeny.o -MD -MP -MF $depbase.Tpo -c -o ncgeny.o ncgeny.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc     -o ncgen3.exe main.o load.o escapes.o getfill.o init.o genlib.o ncgeny.o ../liblib/libnetcdf.la -lm 
libtool: link: x86_64-w64-mingw32-gcc -o .libs/ncgen3.exe main.o load.o escapes.o getfill.o init.o genlib.o ncgeny.o  ../liblib/.libs/libnetcdf.a
abarth@work:~/src/netcdf-c/ncgen3 (master) 
$ ls -l .libs/ncgen3.exe
-rwxrwxr-x 1 abarth abarth 1755014 Mai 26 15:04 .libs/ncgen3.exe
```

Thanks a lot! And also thank to speak to Ward about the CI testing of mingw. It would help a lot to give a more updated NetCDF version to Julia and R users (I think @mjwoods, author of RNetCDF, would agree).

**Comment by DennisHeimbigner** [comment]
Fixed by https://github.com/Unidata/netcdf-c/pull/2009

**Pull request merged**
