### PR TITLE
The max dimension sizes do not take CDF-5 format into account.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
NetCDF-c Github issue #185

The code in libsrc/dim.c has not been upgraded to support
CDF-5 format.

Rule we are implementing sets the max dimension sizes as follows:

Classic:	CDF-1	NC_MAX_INT - 3    = 2147483647 - 3
64 bit Offset:	CDF-2	NC_MAX_UINT - 3	  =  4294967295 - 3
64 bit Data:	CDF-5	NC_MAX_UINT64 - 3 = 18446744073709551615 - 3

The -3 is to handle rounding.

### CODE REVIEW

**Comment by WardF** [comment]
@dmh I'm not sure if you get automatic notifications, but it looks like there were some failures when this pull request was checked by travis.  I'll investigate in a bit as well, unless the solution pops right out at you; currently I'm working on #186.

**Comment by DennisHeimbigner** [comment]
I got it, but cannot figure out yet why it works
when I run cmake, but fails under travis.
=Dennis


Ward Fisher wrote:

**Comment by WardF** [comment]
Poking around on this a bit, the failure on travis is in the `tst_dimsizes.sh` test when run via autotools/make check.  It appears that in CMake, the tst_dimsizes.c file is compiled and run, but the tst_dimsizes shell script does not.  I'm going to wire that in by hand (it's easy to do) and see if the test then starts to fail on cmake as well.

**Comment by WardF** [comment]
The first issue appears to be that tst_dimsizes.sh does not have the executable bit set; other errors are reported once it runs, but that at least is the initial problem :).

**Comment by WardF** [comment]
I'm also seeing, in the docker container, the following when I run the script:

````.sh
./tst_dimsizes.sh: 24: test: ../ncdump/ncdump: unexpected operator
````

So perhaps `test` doesn't like how it is being invoked? Not sure.

**Comment by WardF** [comment]
Looks good, thanks for your help with this @dmh.  #186 Is corrected as well, so hopefully we're in position to get `4.4.0` pretty quickly.

**Pull request merged**
