### PR TITLE
Refactor common code between DAP2(oc2) and DAP4

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
This pr should probably be delayed until after Version 4.5.

Primary change is to cleanup code and remove duplicated code
across the DAP protocol implementations.

1. Unify the rc file reading into libdispatch/drc.c. Eventually extend
   if we need rc file for netcdf itself as opposed to the dap code.
2. Unify the extraction from the rc file of DAP authorization info.
3. Misc. other small unifications: make temp file, read file.
4. Avoid use of libcurl when reading file:// because
   there is some kind of problem with the Visual Studio version.
   Might be related to the winpath problem.
   In any case, do direct read instead.
5. Add new error code NC_ERCFILE for errors in reading RC file.
6. Complete documentation cleanup as indicated in this comment
   https://github.com/Unidata/netcdf-c/pull/472#issuecomment-325926426
7. Convert some occurrences of #ifdef _WIN32 to #ifdef _MSC_VER

### CODE REVIEW

**Comment by WardF** [comment]
This is failing for me because there's no `occlientparams.c` or `occlientparams.h` as part of the branch.  I can remove `occlientparams.c` from the `CMakeLists.txt` file, but oc.c still has an include for `occlientparams.h` which I don't know if it should just be removed. @DennisHeimbigner

**Comment by DennisHeimbigner** [comment]
If you merge urlparams.dmh first, this problem should go away.

**Comment by DennisHeimbigner** [comment]
wai, it looks like you already did that. This is probably a delete/keep conflict.
In any case, occlientparams.[ch] should be removed ifyou have already merged
urlparams.dmh

**Comment by WardF** [comment]
Ok sounds good, thanks for clarification!

**Pull request merged**
