### PR TITLE
Expand the NC_INMEMORY capabilities 

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: esupport MQO-415619
and https://github.com/Unidata/netcdf-c/issues/708

Expand the NC_INMEMORY capabilities to support writing and accessing
the final modified memory.

Three new functions have been added:
nc_open_memio, nc_create_mem, and nc_close_memio.

The following new capabilities were added.
1. nc_open_memio() allows the NC_WRITE mode flag
   so a chunk of memory can be passed in and be modified
2. nc_create_mem() allows the NC_INMEMORY flag to be set
   to cause the created file to be kept in memory.
3. nc_close_mem() allows the final in-memory contents to be
   retrieved at the time the file is closed.
4. A special flag, NC_MEMIO_LOCK, is provided to ensure that
   the provided memory will not be freed or reallocated.

Note the following.
1. If nc_open_memio() is called with NC_WRITE, and NC_MEMIO_LOCK is not set,
   then the netcdf-c library will take control of the incoming memory.
   This means that the original memory block should not be freed
   but the block returned by nc_close_mem() must be freed.
2. If nc_open_memio() is called with NC_WRITE, and NC_MEMIO_LOCK is set,
   then modifications to the original memory may fail if the space available
   is insufficient.

Documentation is provided in the file docs/inmemory.md.
A test case is provided: nc_test/tst_inmemory.c driven by
nc_test/run_inmemory.sh

WARNING: changes were made to the dispatch table for
the close entry. From int (*close)(int) to int (*close)(int,void*).

### CODE REVIEW

**Comment by WardF** [comment]
This pull request **introduces 1 alert** when merging ccc70d640baa27206f78efbc0086d7ab9bb59cbc into fc6ab9881f285f45d406fe07d906a63f5d02f713 - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-484a6b83f5e6df9eb9d1599c6d59e5862a4dcc1f)

**new alerts:**

* 1 for Comparison result is always the same

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by edhartnett** [comment]
In order to complete #856 some of this code (all HDF5 calls) must be relocated to libhdf5 out of libsrc4. libsrc4 will not have access to HDF5 header files. (See the discussion in #856 for more details.)

What would be helpful would be to start functions with nc4_ for code that is not hdf5 dependent (i.e. will remain in libsrc4), and with hdf5_ for functions that use HDF5 data structs and functions. That will make it easier to separate without changing function names. This is the convention I adopted when separating the code in my prototype. Happy to use some other convention if that is preferred. (I used the same convention for file names, for example hdf5file.c and nc4file.c, to handle HDF5 file functions and internal metadata file functions, respectively.

Perhaps the inmemory code deserves it's own dispatch directory?

Can you have inmemory without HDF5? Or is HDF5 always going to be required when building inmemory capabilities?

**Comment by DennisHeimbigner** [comment]
Ward- I cannot fix the alert because that lgtm page is failing to load for me.
I will fix as soon as I can access it, or you can send me the text of the failure.

**Comment by WardF** [comment]
I will send that shortly, thanks Dennis!

**Comment by DennisHeimbigner** [comment]
The inmemory code for netcdf4 uses two parts of hdf5 library.
1. "core" driver which allows the use of memory for storing the file contents
2. the image operations (see https://support.hdfgroup.org/HDF5/doc1.8/Advanced/FileImageOperations/HDF5FileImageOperations.pdf) to set and get the
initial and final contents of the inmemory file.

The netcdf-3 and cdf5 code use a modified ncio subclass: memio.c

As far as I know, HDF4 does not support inmemory operation, so if that flag
is set for hdf5 open/create, then it should be an error.

**Comment by WardF** [comment]
This pull request **introduces 1 alert** when merging 25045b78ce5b21921d98fbd0ebb31d573b6f423d into fc6ab9881f285f45d406fe07d906a63f5d02f713 - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-afe71fb08b0d1e58b0d345168e76e252958d6b59)

**new alerts:**

* 1 for Comparison result is always the same

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by WardF** [comment]
lgtm is something Ryan turned on across the board for Unidata projects; I will figure out how to get you access to the results, but it is a minor thing that can be potentially ignored.  I will share with you shortly in person.

**Comment by DennisHeimbigner** [comment]
Ok, this appears to be ready to go again. So it should be merged.

**Comment by WardF** [comment]
This will be the next one merged!

**Comment by mlandiech** [comment]
Hello,

I have some issue with InMemory buffer returned in case of write mode.
First, if I create a new file with InMemory and write mode, when I close it, the returned buffer is not valid. When I try to open buffer with InMemory open function it does not work because version is missing on first bytes.
Second, if I open a file with InMemory and write mode, then I modify its content , when I close it, the returned buffer does not contain modifications. When I try to open buffer with InMemory open function, values do not match

Do you have an idea about what can happen? 
I think that returned buffer is the initial one.

Regards,

**Comment by DennisHeimbigner** [comment]
Do you have a simple program to show this bug?

**Comment by mlandiech** [comment]
Yes I modified your test file. You can find modified file in attached archive.
I added 2 sections prefix with :
// [ADD mlandiech]

One try to reopen a newly created buffer.
Second try to reopen and check a modified buffer.

Regards

[tst_inmemory.zip](https://github.com/Unidata/netcdf-c/files/2136536/tst_inmemory.zip)

**Pull request merged**
