### PR TITLE
Add support for HDF5 transient types

### LINKED ISSUE #267: NetCDF unable to read some HDF5 enums
h5py stores boolean data using an HDF5 enum: http://docs.h5py.org/en/latest/faq.html

The attached file is a such an example: [test.nc.zip](https://github.com/Unidata/netcdf-c/files/276807/test.nc.zip)

However, the netCDF-C library doesn't report these variables at all:

```
$ ncdump test.nc
netcdf test {
}
```

This is somewhat unfortunate.

Here's the output of h5dump on the file, along with a file created via netCDF4:

```
$ h5dump test.nc  $ made with h5py
HDF5 "test.nc" {
GROUP "/" {
   DATASET "foo" {
      DATATYPE  H5T_ENUM {
         H5T_STD_I8LE;
         "FALSE"            0;
         "TRUE"             1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): TRUE
      }
   }
}
}
$ h5dump test2.nc  # made with netCDF4-python
HDF5 "test2.nc" {
GROUP "/" {
   DATATYPE "boolean" H5T_ENUM {
      H5T_STD_I8LE;
      "FALSE"            0;
      "TRUE"             1;
   };
   DATASET "foo" {
      DATATYPE  H5T_ENUM {
         H5T_STD_I8LE;
         "FALSE"            0;
         "TRUE"             1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): TRUE
      }
   }
}
}
```

Scripts to produce these files:

``` python
import h5py
import numpy as np

with h5py.File('test.nc') as f:
    f.create_dataset('foo', data=np.array(True))
```

``` python
import netCDF4
import numpy as np
with netCDF4.Dataset('test2.nc', 'w') as ds:
    dt = ds.createEnumType('i1', 'boolean', {'FALSE': 0, 'TRUE': 1})
    v = ds.createVariable('foo', dt, ())
    v[:] = True
```

ncdump reports "netcdf library version 4.4.0"

### LINKED ISSUE #2651: Add support for transient HDF5 datatypes
As raised in #267 and #2650, with HDF5 it is possible to store user-defined datatypes within a variable, for example:

```
HDF5 "test.h5" {
GROUP "/" {
   DATASET "x" {
      DATATYPE  H5T_COMPOUND {
         H5T_IEEE_F64LE "r";
         H5T_IEEE_F64LE "i";
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): {
            1,
            0
         }
      }
   }
}
}
```
or
```
HDF5 "test.nc" {
GROUP "/" {
   DATASET "foo" {
      DATATYPE  H5T_ENUM {
         H5T_STD_I8LE;
         "FALSE"            0;
         "TRUE"             1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): TRUE
      }
   }
}
}
```

NetCDF can already read these datatypes if they have been committed to the file with a name (just in the root group, or in any group?), so presumably it's just the type-lookup logic that needs to be modified?

### PR DESCRIPTION
**Pull request by ZedThree**
These are compound or enum datatypes stored directly in the dataset itself, and so aren't read as standalone objects during the initial metadata gathering when the file is opened

Closes #2651 
Fixes #267 

I've added a fairly simple test, maybe it should be expanded to include transient types on attributes, and other types (like enums, as in #267)

~This change unfortunately also causes `nc_test4_tst_h_refs` to fail, and I've not managed to work out why.~ Fixed

### CODE REVIEW

**Comment by ZedThree** [comment]
The appveyor build is failing, I guess because it's not using a C99 compliant compiler and the new test uses `double complex`. I can change the test to use a struct instead.

The failing MacOS build has this error:

```
Error:curl error: Couldn't connect to server
curl error details: 
Warning:oc_open: Could not read url
/Users/runner/work/netcdf-c/netcdf-c/build/ncdump/ncdump: [cache][prefetch]https://remotetest.unidata.ucar.edu/dts/test.07?types.f32: NetCDF: I/O failure
```

It looks like a network failure? But everything else works, so that's a bit odd

**Comment by DennisHeimbigner** [comment]
You could use your hdf5 test program to create the test file and then see what happens when
netcdf-java tries to open it.

**Comment by ethanrd** [comment]
@ZedThree - The netCDF-Java library uses its all Java implementation to read nc-4/HDF5 files. Writing, on the other hand, is done through the netCDF-C library.

**Comment by DennisHeimbigner** [comment]
Right, but it must be able to read the file created by your hdf5 program.

**Comment by ZedThree** [comment]
I don't have a Java development environment set up, but I was able to use the ToolsUI utility to view the file created by this test, and it was able to view the presence of the variables at least:

image

**Comment by DennisHeimbigner** [comment]
Try the ncdump tab also on toolsui

**Comment by ZedThree** [comment]
I tried the ncdump tab on a few files, and it didn't work for any of them. It doesn't produce any error messages, so I can't debug it

**Comment by ZedThree** [comment]
Is it possible for someone with access to re-run the [nc-cmake-tests-oneoff-parallel (1.12.2)](https://github.com/Unidata/netcdf-c/actions/runs/4404151098/jobs/7713416895?pr=2655#logs) build to see if it is an intermittent failure, please?

**Comment by ZedThree** [comment]
Oh, I've just seen #2555  and #2558, could the test failure be related to them?

**Comment by WardF** [comment]
Re-running jobs.  I'll echo what @ethanrd and @DennisHeimbigner mentioned above; if netCDF-Java can read these out of the box, great, if not, we'll need to have that broader conversation.  But first things first, I've started the tests.  Thanks!

**Comment by ZedThree** [comment]
Hello, is there anything I can do to help move this along? It would be a very useful feature to enable greater compatibility between different netCDF implementations: netCDF-Java and h5netcdf can both already read these kinds of files.

**Review by WardF — APPROVED** [review]
@ZedThree thanks for the ping!

**Comment by DennisHeimbigner** [comment]
This PR needs to be reversed. It is creating types with empty names and that violates the netcdf-4
specification. Plus it will cause various programs to crash.

**Comment by WardF** [comment]
It passed all the tests; do we need to update our test suite in a way that will test for the failures you're observing?

**Comment by DennisHeimbigner** [comment]
The test is bogus. It never checks for the type name.

**Comment by ZedThree** [comment]
> It is creating types with empty names and that violates the netcdf-4 specification.

This is absolutely not the case, it only adds the ability to read such types. From my comment above:

> There's also no issues of backwards compatibility that I can see -- no previously valid files will become invalid. It also only affects reading, so newer versions of netCDF won't make possibly invalid files for older versions.
More files written by other tools (such as h5netcdf with invalid_netcdf=True) would be able to be read using this feature.

NetCDF-Java can already read such types, so this only brings netCDF-C functionality in line with the Java library.

It's also not clear that it _is_ against the spec. Is there a more formal spec than [this page](https://docs.unidata.ucar.edu/netcdf-c/current/file_format_specifications.html#netcdf_4_spec) in the docs? In relation to user-defined types, it says:

> Each user-defined data type in an HDF5 file exactly corresponds to a user-defined data type in the netCDF-4 file. Only base data types which correspond to netCDF-4 data types may be used.

I don't see the issue here.

> Plus it will cause various programs to crash.

If you can provide a minimal reproducer, I will be happy to fix any bugs I've introduced and expand the test suite. As it is, the entire existing test suite passes along with the additional tests I wrote. As you requested, I also verified that netCDF-Java can already correctly read files with unnamed types in them.

**Comment by DennisHeimbigner** [comment]
> This is absolutely not the case, it only adds the ability to read such types. From my comment above:
Modify your test program to print the type name.

**Comment by DennisHeimbigner** [comment]
> NetCDF-Java can already read such types, so this only brings netCDF-C functionality in line with the Java library.

netcdf-java assigns names to those types. your code does not.

**Comment by DennisHeimbigner** [comment]
> As it is, the entire existing test suite passes along with the additional tests I wrote.

But no other tests operate on a transient type. The only test that does is your test case.

**Comment by DennisHeimbigner** [comment]
The spec requires type names to be unique within a group. Your code produces types all with the same empty name.

**Comment by DennisHeimbigner** [comment]
The right thing to do here is to make sure that these transient types have proper names.
So, your suggestion above about using "var_XXX" seems a good starting point.
We have a precedent WRT anonymous dimensions in DAP2. I would suggest that we add a counter that is incremented whenever a transient type is created. Then we create the name of the type as, say, "anonamousN".
Also, it is possible to encounter transient types associated with attributes?

**Pull request merged**
