### PR TITLE
changed macro STREQ to NCSTREQ to avoid name collusion with HDF4 library

### LINKED ISSUE #834: STREQ from utils.h duplicates a macro in HDF4 header file
In a compile with HDF4 I see that ncdump.c includes a pre-processor macro that is already defined in hdf4: STREQ().

Our version should be renamed NCSTREQ() to eliminate the warning and avoid potential bugs if we change the order of headers.

```
In file included from /usr/local/hdf-4.2.13/include/mfhdf.h:27:0,
                 from ../include/nc4internal.h:34,
                 from ncdump.c:52:
/usr/local/hdf-4.2.13/include/hdf.h:106:0: warning: "STREQ" redefined
 #define STREQ(s, t) (HDstrcmp((s), (t)) == 0)
 
In file included from ncdump.c:39:0:
utils.h:14:0: note: this is the location of the previous definition
 #define STREQ(a, b) (*(a) == *(b) && strcmp((a), (b)) == 0)

```

### LINKED ISSUE #959: new test tst_inmemory.c uses hdf5.h in an unguarded manner...
This showed up in my CI testing.

In new test nc_test/tst_inmemory.c we have:

```
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#include "netcdf.h"
#include "netcdf_mem.h"
#include "ncbytes.h"
#include "nc_tests.h"
#include "err_macros.h"

#include <hdf5.h>

#ifdef USE_NETCDF4
extern int H5Eprint1(FILE * stream);
#endif
```
Note that hdf5.h is included even if netcdf-4 is turned off.

Looks like the rest of the test properly guards for USE_NETCDF4. The fix is just to move the include. I will have a PR up shortly.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #834.

Since the same macro is used in ncgen, I changed it there as well. This required regeneration of the built files in the ncgen directory with make makeparser. Since my version of flex/bison is more new than those used to generate the files last time, there are some changes in the generated files.

FYI:
```
ed@mikado:~/tmp/netcdf-c$ flex --version
flex 2.6.1
ed@mikado:~/tmp/netcdf-c$ bison --version
bison (GNU Bison) 3.0.4
```

(This PR also include Fixes #959 in order to pass my CI system.)

### CODE REVIEW

**Comment by edhartnett** [comment]
@WardF this should not be merged until after PR #558. Merge that one first, then I will update this one. Thanks!

**Comment by DennisHeimbigner** [comment]
Ncgen should be relatively insensitive to flex+bison version as long
as no features are obsoleted..

**Comment by edhartnett** [comment]
@DennisHeimbigner yes, I get that ncgen should not be dependent on the versions of the tools. I just wanted to point out the changes since a bunch of the autogenerated files do have changes that have nothing to do with the STREQ macro, but are just changes coming from new versions of the tools.

@WardF it still makes sense to merge PR #558 before this PR, since both are changing the same generated files. Once #558 is merged, I can update this PR, and regenerate the files, to ensure we have a correct and consistent set of generated code files.

**Comment by edhartnett** [comment]
One test failed due to travis timeout.

**Comment by edhartnett** [comment]
OK, this us up to date with latest merges and Dennis' latest work, and can be merged at any time.

**Comment by edhartnett** [comment]
I will take this down and put it back up after some more important PRs get merged.

**Comment by edhartnett** [comment]
Thanks!

**Pull request merged**
