### PR TITLE
Assorted Static Analysis cleanup

### PR DESCRIPTION
**Pull request by WardF**
Cleaning up assorted issues identified via static analysis.

### CODE REVIEW

**Comment by t-b** [comment]
@WardF Can you share the tool you have used? Maybe also the setup?

**Comment by WardF** [comment]
@t-b Sure thing!  There is no particular setup/configuration you need to use ahead of time; this can all be done pretty easily.

I'm working on OSX but the same instructions will work on Linux.  I believe there is a way to do this on Windows as well, but I have not explored that.

I'm using the `clang` static analyzer, `scan-build`.  You can use it with either `configure` or `cmake`, but I'm using cmake.  I'm sure you'll be able to adjust my example to `configure` if you want to.

From the top-level `netcdf-c/` directory:

    $ mkdir build-analyze && cd build-analyze
    $ scan-build -o tmp cmake .. -DENABLE_TESTS=OFF    //Ignore any errors reported at this step.
    $ scan-build -o tmp -V make -j 10

This final command will run the analysis; it will take longer than a normal build, by quite a bit, and my system chokes if I allocate too many threads to it (`-j`).  The `-V` command tells `scan-build` to open the results in a web browser automatically when it finishes.  This does not always work properly for me; in this case, you'll use the command-line tool `scan-view`, where you pass the path to the analysis results as the argument.

**Comment by WardF** [comment]
Further reference: http://clang-analyzer.llvm.org/

**Comment by t-b** [comment]
@WardF Thanks a lot!

**Pull request merged**
