### PR TITLE
Now use H5Literate2() instead of H5Literate() when its available

### LINKED ISSUE #2714: Undefined reference to `H5Literate' with IBM XL compiler
I'm trying to compile netcdf-c for WRF and I get the following error during compilation:
```
...
/bin/sh ../libtool  --tag=CC   --mode=link /opt/ibm/spectrum_mpi/bin/mpicc -std=gnu11  -I/home/wtrojak/.local/pkg/hdf5/1.14.0/include -fno-strict-aliasing   -L/home/wtrojak/.local/pkg/hdf5/1.14.0/lib -L/home/wtrojak/.local/pkg/zlib/1.2.13/lib -o ncgen3 main.o load.o escapes.o getfill.o init.o genlib.o ncgeny.o ../liblib/libnetcdf.la -lhdf5_hl -lhdf5 -lm -lz -lsz -lbz2 -lzstd -lxml2 -lcurl 
libtool: link: /opt/ibm/spectrum_mpi/bin/mpicc -std=gnu11 -I/home/wtrojak/.local/pkg/hdf5/1.14.0/include -fno-strict-aliasing -o .libs/ncgen3 main.o load.o escapes.o getfill.o init.o genlib.o ncgeny.o  -L/home/wtrojak/.local/pkg/hdf5/1.14.0/lib -L/home/wtrojak/.local/pkg/zlib/1.2.13/lib ../liblib/.libs/libnetcdf.so -lhdf5_hl -lhdf5 -lm -lz -lsz -lbz2 -lzstd -lxml2 -lcurl -Wl,-rpath -Wl,/home/wtrojak/.local/pkg/netcdf-c/4.9.2/lib
../liblib/.libs/libnetcdf.so: undefined reference to `H5Literate'
make[2]: *** [ncgen3] Error 1
make[2]: Leaving directory `/autofs/home/wtrojak/install/netcdf-c-4.9.2/ncgen3'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/autofs/home/wtrojak/install/netcdf-c-4.9.2'
make: *** [all] Error 2
```
I was wondering if anyone could provide help getting to a fix for this?

Here is the configuration command I used for netcdf-c:
```
export H5DIR=$HOME/.local/pkg/hdf5/1.14.0
export ZDIR=$HOME/.local/pkg/zlib/1.2.13
FC=$( which mpif90 ) \
CC=$( which mpicc ) \
CXX=$( which mpic++ ) \
./configure \
  --prefix=$HOME/.local/pkg/netcdf-c/4.9.2 \
  --disable-byterange \
  --disable-dap \
  --enable-parallel-tests \
  --enable-shared \
  --enable-hdf5
```

When compiling HDF5 I've tried a few different configs/cmake setups, all gave the same error during compilation. What I used in this was 1.14.0 with the following cmake command:
```
CC=$( which mpicc ) \
FC=$( which mpif90 ) \
CXX=$( which mpic++ ) \
cmake ../. \
  -DCMAKE_INSTALL_PREFIX=$HOME/.local/pkg/hdf5/1.14.0 \
  -DCMAKE_BUILD_TYPE=Release \
  -DHDF5_BUILD_FORTRAN=ON \
  -DHDF5_BUILD_HL_LIB=ON \
  -DHDF5_ENABLE_PARALLEL=ON \
  -DHDF5_ENABLE_Z_LIB_SUPPORT=ON \
  -DZLIB_LIBRARY=$HOME/.local/pkg/zlib/1.2.13/lib/libz.so \
  -DZLIB_INCLUDE_PATH=$HOME/.local/pkg/zlib/1.2.13/include/ \
  -DDEFAULT_API_VERSION:STRING=v110
```

The compiler I'm using is XL V16.1.1.3 with Spectrum MPI on RHEL 7.6.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #2714 

Now use H5Literate2() when available, avoiding the compatibility macro.

In HDF5 releases prior to 1.12.0, H5Literate2() will not be present and the original H5Literate() will be used.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I'm not sure the failures here have anything to do with my changes...

**Comment by WardF** [comment]
The failures looked like something related to Github infrastructure/failure to fetch something from cache. I've triggered them to run again.

**Comment by WardF** [comment]
Digging into it, I'm seeing an error that the cache can't be saved because another job is creating the cache. So it's nothing with this PR, but it feels like something is stuck in the pipes somewhere. I'll poke around some more.

**Review by WardF — APPROVED** [review]

**Comment by WardF** [comment]
Thanks!

**Pull request merged**
