### PR TITLE
fix problem of setting the default file format

### PR DESCRIPTION
**Pull request by wkliao**
According to [an earlier C user guide](https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-c/nc_005fset_005fdefault_005fformat.html), the default format is used when no format specific flag is used when creating a new file. This PR fixes to respect the rule. A test program `nc_test/tst_default_format.c` added in this PR can be used to detect the error.

See commit message for detailed changes.

I also notice that API `nc_set_default_format` is missing from to C user guide.

### CODE REVIEW

**Comment by WardF** [comment]
Pulling into a combined PR request to set the stage for larger merges early next week.

**Comment by WardF** [comment]
Exploring an issue observed on 32-bit mpich systems, will post more details when I get it nailed down.

**Comment by WardF** [comment]
This PR is on hold due to failures observed in an mpich32 system.  Details here:

* http://cdash.unidata.ucar.edu/testDetails.php?test=206110&build=5378

I'll look into this further after I get some of the PR's merged.

**Comment by wkliao** [comment]
The test error is due to netCDF library does not support CDF-5 on 32-bit machines.
I added some preprocessor conditions to skip CDF-5 tests to the program that failed.
It should work now.

**Comment by WardF** [comment]
Excellent, thank you very much @wkliao!

**Pull request merged**
