### PR TITLE
add missing note about CDF-5 format

### PR DESCRIPTION
**Pull request by wkliao**
The PR adds information about the CDF-5 format in user documents.
I also propose to use "classic format" to refer CDF-1, 2, and 5 format.
Hope this is acceptable for the NetCDF community.

### CODE REVIEW

**Comment by edhartnett** [comment]
In all the other docs, "classic" means CDF-1 only.

**Comment by wkliao** [comment]
It is a proposal. If we agree, those documents can be revised accordingly.
Any suggestion that we don't end up saying "classic, 64-bit offset, and CDF-5" all over the places?

**Comment by edhartnett** [comment]
I guess I would call those the CDF formats, if I were referring to them collectively.

**Comment by wkliao** [comment]
That is  a good suggestion. We can use it when referring a file format.
As for referring models, I can see "classic model" is used to refer CDF-1 and 2 (vs. "enhanced model" for HDF5). Do we want to keep "classic model" and include CDF-5 or just replace it with "CDF model"?

**Comment by edhartnett** [comment]
Well I noticed that the CDF5 model is not actually the classic model, it includes some data types from the enhanced model.

So I would say that CDF1 and 2 used the classic model, and CDF5 uses classic model plus extra atomic types.

**Comment by wkliao** [comment]
To me, a data model is about the objects/structures that can be represented in a file.

In NetCDF-C tutorial, [The NetCDF Data Model](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_model.html) points out the classic model consists of variables, dimensions, and attributes, while the enhanced model adds two additional components: groups and user-defined types. The CDF-5 shares the same 3 components with the classic model and none from the enhanced model.

**Comment by WardF** [comment]
I think this represents a point we're going to need to clarify in the documentation; since the variable types represented with CDF5 are different than those in the 'classic' model, we have to differentiate and make it clear that those files using CDF5-enabled variable types are not 'classic netcdf model' in the typical use of the term.  To that end, we need to come up with a new identifier; perhaps classic+CDF5? I'm just back from PTO, sorry, that isn't very good, let me warm my brain up.  But the larger point, I think, is that we do need to differentiate and not just lump CDF5 in with 'classic'.

**Pull request merged**
