### PR TITLE
fix musl build

### LINKED ISSUE #1700: Building with musl fails
* the version of the software with which you are encountering an issue
current git master

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
linux, musl, x86_64

* a description of the issue with the steps needed to reproduce it

Building with musl-gcc fails with 
```
CMake Error at CMakeLists.txt:881 (MESSAGE):
  Unable to find the math library.
```

To reproduce:
```sh
env CC=musl-gcc cmake .. -DENABLE_DAP=OFF
```

### PR DESCRIPTION
**Pull request by magnusuMET**
musl does not have a dedicated math library (it is a stub), and is not properly detected. This PR adds a fallback option for when a math function (exp) is available among the system libraries.

execinfo is also unavailable on musl, so a check is added in the CMakeLists for the "execinfo.h" header

Fixes #1700 

This allows netCDF to be built fully statically on musl targets

### CODE REVIEW

**Comment by thesamesam** [comment]
This is a pretty reasonable fix. Could it be merged please?

**Comment by magnusuMET** [comment]
Musl build is more broken than this PR fixes right now. I will have another look and see what can be done to fix it

**Comment by DennisHeimbigner** [comment]
Does this also need to be fixed in configure.ac?

**Comment by magnusuMET** [comment]
Yes, `HAVE_EXECINFO_H`needs to be emitted

**Comment by listout** [comment]
@magnusuMET Can you please explain the changes in CMakeLists.txt and config.h.cmake.in? I came up with a patch for gentoo (musl) with just the HAVE_EXECINFO_H checkin libhdf5/hdf5debug.c, and it worked.

**Comment by magnusuMET** [comment]
This is the dockerfile which I am testing the build with @listout 
```dockerfile
FROM alpine:3.16

RUN apk add cmake make gcc g++ hdf5-dev zlib musl-dev curl-dev m4

COPY . /netcdf
RUN mkdir /build && cd /build && \
    cmake /netcdf \
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON \
    -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTS=ON -DENABLE_HDF5=ON && \
    make

RUN apk add bash
RUN cd /build && make test
```

There is a problem with multiple definitions of functions defined by the json functionality. I am not sure why there are duplicates between `ncjson.c`/`ncjson.h`/`netcdf_json.h` and how to resolve this to the intent wanted

**Comment by DennisHeimbigner** [comment]
This is fixed in PR https://github.com/Unidata/netcdf-c/pull/2448
Sorry for the inconvenience.

**Comment by brahmajit** [comment]
> This is fixed in PR #2448 Sorry for the inconvenience.

Which one? I don't see anything related to execinfo on that PR

**Comment by DennisHeimbigner** [comment]
Sorry, I meant that PR fixed the duplicate json problem, not the execinfo problem.

**Comment by DennisHeimbigner** [comment]
BTW if you check the tests above, this PR appears to fail on OSX.

**Comment by thesamesam** [comment]
I can't seem to view the macOS results, it just says "This check failed"?

**Comment by DennisHeimbigner** [comment]
To the right of that failure line, it should say "details:"

**Comment by thesamesam** [comment]
Screenshot 2022-07-16 at 21 20 54

**Comment by DennisHeimbigner** [comment]
Have not seen that before. Not sure what happened.

**Comment by DennisHeimbigner** [comment]
Also, __int64 is a windows definition; will changing it fail on windows?

**Comment by listout** [comment]
> Right, but after clicking that link: Screenshot 2022-07-16 at 21 20 54

Can confirm, same here too.

**Comment by magnusuMET** [comment]
Seems the mac failure might have been spurious.

`stdint.h` should be available back to VS2015: https://docs.microsoft.com/en-us/cpp/c-runtime-library/standard-types?view=msvc-140

Applying the json-fix from the mentioned PR ensures compilation works and all tests works as they are supposed to

**Comment by DennisHeimbigner** [comment]
Ok, once the json fix is merged, we can merge this one.

**Comment by magnusuMET** [comment]
@DennisHeimbigner It is now rebased and passing all tests

**Comment by magnusuMET** [comment]
PR #2129 can be closed after merging this PR

**Review by WardF — APPROVED** [review]

**Comment by WardF** [comment]
Thanks!

**Pull request merged**
