### PR TITLE
CMake: Enable plugins on MinGW

### PR DESCRIPTION
**Pull request by MehdiChinoune**
They could be built on MinGW.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Sorry, I can't give my phone number

**Comment by DWesl** [comment]
Are you planning to add CMake to [the MinGW CI run](https://github.com/MehdiChinoune/netcdf-c/blob/mingw-plugins/.github/workflows/run_tests_win_mingw.yml)?

You could borrow from [the Linux CMake workflow](https://github.com/Unidata/netcdf-c/blob/main/.github/workflows/run_tests_ubuntu.yml#L395), or from [my most recent attempt to get CMake working on MinGW (compile fails)](https://github.com/DWesl/netcdf-c/blob/patch-3/.github/workflows/run_tests_win_mingw.yml#L102).

**Comment by MehdiChinoune** [comment]
> Are you planning to add CMake to [the MinGW CI run](https://github.com/MehdiChinoune/netcdf-c/blob/mingw-plugins/.github/workflows/run_tests_win_mingw.yml)?
> 
> You could borrow from [the Linux CMake workflow](https://github.com/Unidata/netcdf-c/blob/main/.github/workflows/run_tests_ubuntu.yml#L395), or from [my most recent attempt to get CMake working on MinGW (compile fails)](https://github.com/DWesl/netcdf-c/blob/patch-3/.github/workflows/run_tests_win_mingw.yml#L102).

I was planning, but I prefered to add it in a separate PR.

**Comment by DWesl** [comment]
That's a sensible concern

**Comment by MehdiChinoune** [comment]
> That's a sensible concern

I don't understand?

**Comment by DWesl** [comment]
Trying to keep a PR focused on a single change, rather than allowing its scope to expand to include many tangentially-related things, is a sensible concern.

**Comment by MehdiChinoune** [comment]
I think WIN32 is not set to true on CYGWIN by CMake.

**Comment by DWesl** [comment]
Cygwin CMake spent a few years telling me it no longer set `_WIN32` on Cygwin, so I suspect it's a separate thing.

A small `CMakeLists.txt` set to output messages if `WIN32` or `CYGWIN` is defined outputs the Cygwin message but not the Windows one.

**Comment by DennisHeimbigner** [comment]
Are we talking about "WIN32" or "_WIN32"? The latter is set by the compiler.
As far as I know, we never use "WIN32" anywhere in our code; we only use "_WIN32".
Also, specifying MSVC is sometimes the correct test (vs _WIN32) when the issue is
building on windows using gcc or clang vs building using the visual studio compiler.

**Comment by MehdiChinoune** [comment]
We are talking about WIN32 in CMake language.

**Review by WardF — APPROVED** [review]

**Pull request merged**
