### PR TITLE
Add autogen.sh script for helping novice users

### PR DESCRIPTION
**Pull request by t-b**
For novice autotools users it is convenient to have just a script to
execute.

### CODE REVIEW

**Comment by t-b** [comment]
@edhartnett @WardF Well a lot of projects I'm using have a autogen.sh script. But if you think this is overkill, okay let's not do it.

**Comment by WardF** [comment]
Let me take a look; if this is a standard thing autoconf based projects typically have, that is different than the home-brew solution I originally thought it was. I’m tying up some loose ends on other projects and then will turn back to NetCDF-C stuff shortly :)

**Comment by WardF** [comment]
Ok, looking at [gnu.org](https://www.gnu.org/software/automake/faq/autotools-faq.html#What-does-_002e_002fbootstrap-or-_002e_002fautogen_002esh-do_003f) it appears this is indeed a standard thing, although they recommend the name `bootstrap` over `autogen.sh`. Reopen if you like and I’ll merge when I do then next round of PR’s, and after I check that there isn’t already a bootstrap file (I’m on my phone at the moment).

**Comment by t-b** [comment]
The name of the script is up to you. I'm fine with bootstrap as well.

**Comment by DennisHeimbigner** [comment]
I must confess a certain amount of confusion. I would have that that
someone capable of installing automake would have sufficient knowledge
to run it. But maybe not :-) In any case, there seems no harm
in adding it -- it is known not to be a security risk, correct?

**Comment by t-b** [comment]
@DennisHeimbigner Well I used not need that for a long time. And I usually just do `apt-get install build-essential`, https://packages.debian.org/stretch/build-essential, on a new machine which brings in all you need for compiling C programs.

**Comment by WardF** [comment]
Thanks! Merging via `pr-aggregation.wif`, #1283.

**Pull request merged**
