### PR TITLE
Fix variable bounds check for parallel output

### PR DESCRIPTION
**Pull request by gsjaardema**
The following code is in nc4hdf.c, function `nc4_put_vara`.

```
  /* Check dimension bounds. Remember that unlimited dimnsions can
   * put data beyond their current length. */
  for (d2 = 0; d2 < var->ndims; d2++)
    {
      dim = var->dim[d2];
      assert(dim && dim->dimid == var->dimids[d2]);
      if (!dim->unlimited)
        {
          if (start[d2] >= (hssize_t)fdims[d2])
            BAIL_QUIET(NC_EINVALCOORDS);
          if (start[d2] + count[d2] > fdims[d2])
            BAIL_QUIET(NC_EEDGE);
        }
    }
```

There is an issue when the process with the highest rank has zero items to output.  As an example, if I have 4 mpi processes which are each writing the following amount of data:
 * rank 0: 0 items
 * rank 1: 2548 items
 * rank 2: 4352 items
 * rank 3: 0 items.

I will define the variable to have a length of 6900 items (0 + 2548 + 4352 + 0).  When I am outputting data to the variable, each rank will call nc_put_vara_longlong with the following start and count values:
 * rank 0: start = 0, count = 0
 * rank 1: start = 0, count = 2548
 * rank 2: start = 2548, count = 4352
 * rank 3: start = 6900, count = 0.

In each case, the `start` for rank N is equal to `start` for rank N-1 + `count` for rank N-1.  This all works ok until the highest rank is writing 0 items.  In that case, the `start` value for that rank is equal to the total size of the variable and the check in the code fragment shown above fails since `start[] == fdims[]`.

This could be fixed in the application code by checking whether the `count` is zero and if so, then set `start` to 0 also, but I think that is a kluge that should not be required. 

Note that this test appears three times in this file.  In one case, the check for non-zero count already exists, but not in the other two.  This pull request adds the check to the other two tests.

### CODE REVIEW

**Comment by WardF** [comment]
This looks like an absolutely great fix, and is very welcome, thanks! We suffer from a dearth of parallel I/O expertise, currently (I'm coming up to speed but it's slow going), and this sort of contribution is greatly appreciated.  There are intermittent failures we see in some of our parallel tests, and I'm optimistic that this might be at the root of the problem.

Unfortunately I can't accept this pull request as-is, since the travis-ci checks are failing across the board.  I took a look at one of the logs, and it appears that the issue is in `nc_test`.  There is a lot of output, but a representative snippet follows:

````
*** testing nc_put_vara_text ... 

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5002 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

 179 good comparisons. 

	### 48 FAILURES TESTING nc_put_vara_text! ###

*** testing nc_put_vara_uchar ... 

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

	FAILURE at line 5172 of /root/netcdf-c/nc_test/test_put.c: bad start: status = 0

 264 good comparisons. 

	### 236 FAILURES TESTING nc_put_vara_uchar! ###
````

**Comment by WardF** [comment]
The full log that the above snippet was taken from is here:

* https://s3.amazonaws.com/archive.travis-ci.org/jobs/119868699/log.txt

The travis dashboard for the failing tests may be viewed here:

* https://travis-ci.org/Unidata/netcdf-c/builds/119868698

**Comment by gsjaardema** [comment]
Yes, I see that and am getting it in my own builds also.  All failures are in nc_test/nc_test. I will look into this and see what I can find out.

**Comment by gsjaardema** [comment]
The comment on all failing tests is 
> "check correct error returned even when nothing to put" (or "get").  

I'm not sure why these tests were added, so it is difficult to know what problems would arise if they were disabled or changed.  

I tried a more pedantic version of the test that would only "not fail" if the start did not exceed fdims[], but that didn't change the results.  In all failures, start[i] == fdims[i] and count == 0.

**Comment by gsjaardema** [comment]
Additional discussion with pnetcdf group:

> Hi, Greg

> Thanks. We will see how this request is taken by netCDF group.

> Just would like to know more of your view to this problem.
Technically, the start value of the last process in your case
is out of bound. Because the request size is zero, it makes
sense to skip the request. However, what happens to other
arguments, should they be ignored as well? Not just arguments
of stride and imap, but also ncid and varid. In other words, should
an API ignore or report an error if an invalid ncid or varid is
used? I wonder if there is any application relying on netCDF
error report of NC_EINVALCOORDS for their internal checking
for any particular purpose.

> Wei-keng

My response:

I don’t think the other arguments should be skipped or ignored — specifying an invalid `varid` or `dimid` or `ncid` should be an error no matter what the request size is.

I think that the `start` value is a special case (and not really that special depending on how you look at it). In a parallel case, each rank will typically be handling a certain number of values in the “field” or variable.  The total size of the variable is the sum of the number of values handled by each rank and the “start” value for each rank is the sum of the number of values handled by previous ranks.

As an example, assume there are four ranks and each handles 10 values.  Then the total size of the variable is 40 and the start values are 0, 10, 20, 30 with request sizes of 10, 10, 10, 10. 

Now, if  we have a similar variable which only has values on ranks 0 and 3 with request sizes of 20, 0, 0, 20. The total size is still 40 and the start values are 0, 20, 20, 20 and everything works fine.

If we now have a similar variable which only has values on ranks 1 and 2, and request sizes of 0, 20, 20, 0.  The total size is still 40 and the start values are 0, 0, 20, 40.  

This uses consistent logic and no special cases in the users application code.  However, this causes a failure in the `nc_put_vara` call due to the error check that “error if start >= size”.  There should be no issue if the error check were instead changed to “start > size” since the following check would still catch the overflow case — “start + count > size”
```
if (start[d2] >= (hssize_t)fdims[d2])
   BAIL_QUIET(NC_EINVALCOORDS);
if (start[d2] + count[d2] > fdims[d2])
   BAIL_QUIET(NC_EEDGE);
```
I don’t see a similar argument for ignoring invalid ncid and varid.  I would also still throw an error if start > size even if request size is 0; I’m just suggesting that it should not be an error for “start == size”.

**Comment by WardF** [comment]
Running through pull request backlog, evaluating this now.

**Comment by WardF** [comment]
The patch from this pull request has just been merged, but GitHub isn't catching it so closing manually.

**Comment by wkliao** [comment]
This patch only changed the NC_EINVALCOORDS behavior for netCDF-4 files, but not classical CDF-1/2/5 files. Below is a test code that shows the failure.

In addition, I am wondering why don't we just skip the NC_EINVALCOORDS checking when the request size is zero. What is the implication of getting NC_EINVALCOORDS for start > size when request size is 0?

I notice that the changes in test programs (nc_test/test_get.m4 and nc_test/test_put.m4) only removed the checking for start == size, but did not check for start > size, if the above new error reporting behavior takes effect.

One last point, I hope this change in error reporting behavior does not cause a problem for existing netCDF application programs that rely on such error checking. I hope none of them do.


#include <stdio.h>
#include <netcdf.h>

#define ERR { \
if (err != NC_NOERR) \
    fprintf(stderr, "Error at line %d: %s\n", __LINE__, nc_strerror(err)); \
}

#define LAT_LEN 3
#define LON_LEN 2

int main() {
   int err, ncid, cmode, varid, dimids[2];
   float temp[LAT_LEN*LON_LEN];
   size_t start[2], count[2];

   cmode = NC_CLOBBER|NC_64BIT_DATA;   /* CDF-5 */
   cmode = NC_CLOBBER|NC_64BIT_OFFSET; /* CDF-2 */
   cmode = NC_CLOBBER;                 /* CDF-1 */
   err = nc_create("short.nc", cmode, &ncid); ERR

   err = nc_def_dim(ncid, "latitude",  LAT_LEN, &dimids[0]); ERR
   err = nc_def_dim(ncid, "longitude", LON_LEN, &dimids[1]); ERR
   err = nc_def_var(ncid, "temp", NC_FLOAT, 2, dimids, &varid); ERR
   err = nc_enddef(ncid);

   start[0] = LAT_LEN;
   start[1] = LON_LEN;
   count[0] = 0;
   count[1] = 0;
   err = nc_put_vara_float(ncid, varid, start, count, temp); ERR

   err = nc_close(ncid); ERR
   return 0;
}

**Pull request closed without merging**
