### PR TITLE
updated release notes

### LINKED ISSUE #2391: Add info about quantize, zstandard, and parallel I/O logging to RELEASE_NOTES
This last release, I forgot to add anything to the RELEASE_NOTES!

So, unfortunately the release notes for the 4.9.0 release fail to mention three very important new features:
* quantize for lossy compression
* support for zstandard
* logging in one file per processor for parallel I/O cases when --enable-logging is used

Whoops!

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #2391 

Added info about quantize, zstandard, and parallel I/O logging to RELEASE_NOTES.

@WardF it would be great if these could be added to the GitHub release notes for 4.9.0.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Failing due to remote tests:

```
*** NetCDF: DAP server error
Opening: https://www.ncei.noaa.gov/thredds-coastal/dodsC/us_east/us_east_20091119_to_20130404/20100101/ncom_relo_useast_u_2010010100_t000.nc?water_u[0][0:39][751][287],water_v[0][0:39][751][287]
0% tests passed, 1 tests failed out of 1
Total Test time (real) =  60.[39](https://github.com/Unidata/netcdf-c/runs/6843824720?check_suite_focus=true#step:12:40) sec
The following tests FAILED:
	205 - ncdap_test_manyurls (Failed)
Error: Process completed with exit code 8.
```

**Comment by WardF** [comment]
@DennisHeimbigner Any chance we can see if this is server side/have somebody kick the machine?

**Comment by edwardhartnett** [comment]
I have a PR up (#2313) which turns off the remote tests in the CMake CI run. Not sure if that's what you want to do...

**Comment by DennisHeimbigner** [comment]
We should probably separate --disable-remote-tests into
* --disable-remote-tests which shuts off use of remotetestserver
* --disable-external-tests which shuts off use of external data sources (like www.ncei.noaa.gov/)

Disabling remote tests altogether is a bad idea since being able to exercise true network access is important.

**Comment by DennisHeimbigner** [comment]
The failing tests all reference the server
> "https://www.ncei.noaa.gov/thredds-coastal"

BTW, you might try again and see if it was intermittent..

**Comment by DennisHeimbigner** [comment]
I just ran it and it worked, so I think this is an intermittent failure.

**Comment by edwardhartnett** [comment]
Retried, failed again, different place:

```
99% tests passed, 2 tests failed out of 202
Total Test time (real) =  33.53 sec
The following tests FAILED:
	 40 - ncdump_tst_output (Failed)
	 41 - ncdump_tst_nccopy3 (Failed)
```

**Comment by DennisHeimbigner** [comment]
I have seen that pair of tests fail occasionally. As a rule, re-running causes it to go away.
My speculation is that there is some kind of race condition such that some files created
by each test interfere with each other. So far I have not found that interference.

**Review by WardF — APPROVED** [review]

**Pull request merged**
