### PR TITLE
Add H5FD_http_finalize function and call on hdf5 finalize

### PR DESCRIPTION
**Pull request by lostbard**
Fixes Unidata#2617

### CODE REVIEW

**Review by DennisHeimbigner — COMMENTED** [review]
I do not think this is correct. You are replacing H5FD_http_term with H5FD_http_finalize (BTW why the name change?). But there are other occurrences of H5FD_http_term that you missed e.g. near line 173 of H5FDhttp.c.

**Comment by lostbard** [comment]
H5FD_http_finalize is added to unregister the class - the terminate call in the class structure is still there, just it doesnt need to do anything in this case

It looks like the terimnate call is called as class shoytsdown, which is normally when HDF5 closes. In a case where netcdd AND hdf5 are closing at the same time, this is ok.

In the case like octave where H5 is still around after netcdf has closed, it is a problem and the h5 library still has references to classes from netcdf.

Hence the new function intended on just unregistering the class that was regisitered via H5FD_http_init

**Comment by DennisHeimbigner** [comment]
But wouldn't it work to add the unregister to H5fD_http_term?

**Comment by lostbard** [comment]
> But wouldn't it work to add the unregister to H5fD_http_term?

Possibly? But you would also need to call H5fD_http_term from within hdf5dispatch and provide it as an external function within libhdf5/H5FDhttp.h

That also assumes that calling unregister from that function when its being as terminate() on a shutdown in the class is also ok.

**Comment by lostbard** [comment]
I did a quick test and calling unregister from H5FD_http_term causes a crash unless it is removed  from being a reference in the H5FD_http_g struct.

If you would rather keep the function as that and call it from dispatch, but remove from the class as terminate, I can change it

**Review by DennisHeimbigner — APPROVED** [review]

**Pull request merged**
