### PR TITLE
More informative release note for time zone bug fix, Github #1866.

### PR DESCRIPTION
**Pull request by Dave-Allured**

### CODE REVIEW

**Comment by WardF** [comment]
Thanks @Dave-Allured, getting this merged as soon as the Travis CI checks complete (there was a non-impactful conflict in RELEASE_NOTES.md, but correcting that still triggers travis-ci to re-run).

**Comment by Dave-Allured** [comment]
@WardF, you are welcome.  Two days ago, I resync'ed to master in my previous private repo, changed one file, then submitted this PR.  I was trying to avoid deleting my entire private repo, then re-forking it.  If there is a better way to do this for simple PR's, please let me know.

**Comment by Dave-Allured** [comment]
@WardF, this did not merge correctly.  This PR #1870 was supposed to delete the following release note and replace it with new wording.  Now the old note is still present, so there is in effect a duplicate release note.  Please keep the new note, and remove the following old note.  Let me know if I should file a new PR or something.

**REMOVE:**
 * [Bug Fix] Fix time zone parser bug. See more information at Github #1866 for more information.

**Comment by WardF** [comment]
Thank you.  I'll correct this.

**Comment by Dave-Allured** [comment]
@WardF, that looks good.  Thanks.

**Pull request merged**
