### PR TITLE
Unify definition of NC_DISPATCH_VERSION

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: Issue

The netcdf dispatch table version was defined in several places.
Modify to only require defining it in CMakeLists.txt and configure.ac.

Fix entailed the following changes:
* Up the NC_DISPATCH_VERSION from 2 to 3 in configure.ac and CMakeLists.txt
* Create include/netcdf_dispatch.h.in and use it to configure include/netcdf_dispatch.h
* For CMAKE, make it search CMAKE_CURRENT_BINARY_DIR so code can locate the configured netcdf_dispatch.h
* Add entry to config.h.cmake.in for NC_DISPATCH_VERSION
* Move NCerror from include/ncdispatch.h to libdap2/nccomon.h
* Fix an API problem re nchttp.h
* Fix a conversion warning in libdispatch/dinfermodel.c

### CODE REVIEW

**Comment by WardF** [comment]
Hi Dennis, I'm taking a look at the AppVeyor build to see why it failed; would you mind adding a note to the Release notes document about the changes here, particularly the dispatch version being bumped from 2 to 3? Thanks!

**Comment by WardF** [comment]
This PR fails to compile for me under Windows 10 and Visual Studio, but the error is unclear:

    1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\minwindef.h(157): error C2632: 'int' followed by 'int' is illegal

This error shows up all over the place, so I'm assuming perhaps a missing semicolon or some other small issue is fouling the build on Windows. This error does not occur on the current `master` branch, so it is something in this PR.  I will go look at the other PR's opening to make sure I'm doing everything in the correct order, and will continue to try to debug this.

**Comment by DennisHeimbigner** [comment]
THought I had fixed that. The problem is that BOOL is being twice defined,
once by typedef and once by #define
so 'typedef int BOOL' becomes 'typedef int int'

**Comment by DennisHeimbigner** [comment]
See if its fixed now.

**Comment by WardF** [comment]
It does not appear to be.

**Comment by DennisHeimbigner** [comment]
Does it fail using any particular set of CMake options?

**Comment by DennisHeimbigner** [comment]
If you look at line 157 of this file:
>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\minwindef.h

you can see that it is using typedef to create BOOL type. So somewhere else,
there must be a line of the form:
> #define BOOL int

**Comment by DennisHeimbigner** [comment]
Appveyor seems to work ok now.

**Comment by WardF** [comment]
Including into the `4.8.0-wellspring.wif` branch for inclusion in the 4.8.0 release. It will percolate back into `main` shortly after the `4.8.0` release is pushed.

**Pull request merged**
