### PR TITLE
Modify DAP2 and DAP4 to optionally allow Fillvalue/Variable mismatch

### LINKED ISSUE #1151: ncdump fails to open a particular file
As reported by @rsignell-usgs, the following command fails using either netCDF `4.6.2-rc1` or the older `4.4.1`.  

    $ ncdump -h https://stellwagen.er.usgs.gov/thredds/dodsC/TSdata/MVCO_15/10571whV-a.nc

It returns an invalid argument error.  Grabbing the file and opening it locally works just fine.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes #1151 

(Added bullet above so that #1151 is automatically closed when this is merged - @WardF)

re: issue https://github.com/Unidata/netcdf-c/issues/1151

Modify DAP2 and DAP4 code to handle case when _FillValue type is not
same as the parent variable type.

Specifically:
1. Define a parameter [fillmismatch] to allow this mismatch;
   default is to disallow.
2. If allowed, forcibly change the type of the _FillValue to match
   the parent variable.
3. If allowed Convert the values to match new type
4. Generate a log message
5. if not allowed, then fail

Implementing this required some changes to ncdap_test/dapcvt.c
Also added test cases.

Minor Unrelated Changes:
1. There were a number of warnings about e.g.
   assigning a const char* to a char*. Fix these
2. In nccopy.1, replace .NP with .IP "n"
   (re PR https://github.com/Unidata/netcdf-c/pull/1144)
3. fix minor error in ncdump/ocprint

### CODE REVIEW

**Comment by WardF** [comment]
I'm about to merge this, just following up a weird thing I saw on ARM, but it may have been a symptom of a local network issue.

**Comment by WardF** [comment]
I'm seeing failures with `tst_filter.sh` under autotools with this.  @DennisHeimbigner do you see a failure?

**Comment by WardF** [comment]
Filter tests weren't occurring as part of the travis CI tests. Turned them on and rerunning tests.

**Comment by DennisHeimbigner** [comment]
I don't normally run with filters enabled. Let me try it.

**Comment by DennisHeimbigner** [comment]
I am seeing a memory error inside HDF5. It is occurring in the internal hdf5 memory
allocator/verifier.

**Comment by DennisHeimbigner** [comment]
I ran again using the master branch and it appears to fail for me in the same way,
so this PR may not be the problem. We may have to do a bisect.

**Comment by WardF** [comment]
I will run a bisect in the morning and see what I can track down. In the meantime I will merge this in, as it does not contain the root error.

**Comment by DennisHeimbigner** [comment]
This may be a deeper problem than we thought. I just ran the same test
on the 4.6.1 release tar and it fails also in the same way. Can you verify?

**Comment by DennisHeimbigner** [comment]
Just ran with netcdf version 4.6.0 and failed same way.
I think the problem is with the hdf5 library and not netcdf.

**Comment by DennisHeimbigner** [comment]
Ok, it works with HDF5 version 1.8.20, but fails with 1.10.2 and 1.10.3

**Comment by WardF** [comment]
Interesting.  I have 1.10.1, but it feels like there was either an API change, or perhaps there is a bug or we are misusing the API somehow.  I won't complete the bisect, but I will open a new issue for this and merge this. Ah, I see you just opened #1156.  I will merge this and then try to catch up on the other pull requests and start work on the upcoming workshop materials.

**Pull request merged**
