### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Not sure I see the point in the string changes. Why would one replace strncpy
with strcpy, which is less safe?

**Comment by mathstuf** [comment]
Clang is warning that these calls are essentially doing:

```c
size_t len = strlen(src);
char* dst = (char*)malloc(len + 1);
strncpy(dst, src, len); // len is computed from `src`, not `dst`
```

Now, it *could* see that `len` is tied to the `dst` allocation, but it doesn't. Maybe these are just better replaced with `char* dst = strdup(src);` since that is basically what these things are trying to do (just in a very verbose way).

**Comment by mathstuf** [comment]
Actually, `strncpy(dst, src, strlen(src))` is wrong *anyways* because this guarantees that the NUL terminator will not be added to `dst` since, as `strncpy(3)` states:

> If there is no null byte among the first n bytes of src, the string placed in dest will not be null-terminated.

This terrible API is why `strlcat` was made in the first place.

**Comment by DennisHeimbigner** [comment]
I see and you are correct; the correct change is to use strdup.
The strlcat ->snprintf is also reasonable. At one point, we made a general change
to get rid of strncpy generally, but I see at least one slipped thru.
The change generically was to convert all the strncpy calls to strlcat, including
the one you note above. There are probably many instances where a sequence
of strlcats can be converted to snprintf, but it is probably not worth the effort
do make a general sweep. Anyway thanks for catching this.

**Comment by WardF** [comment]
Thanks for the review and the explanation! I’ll get the merge in soon!

**Comment by mathstuf** [comment]
I'll rework the str* commit to make the code actually more readable instead of the current "silence the warnings" change :) .

**Pull request merged**
