### PR TITLE
Test code for parallel I/O issue, enum issue, and some other issues

### LINKED ISSUE #710: nc_def_var_extra() error checking not appropriate for how it is called...
nc_def_var_extra() is called by nc_def_var_deflate(), nc_def_var_chunking(), etc.

It checks errors incorrectly. It assumes that all parameters are present, when only a subset ever are. So the checks don't work.

For example, this code should not succeed, but it does:

```
         /* Create a netcdf-4 file. */
         if (nc_create(FILE_NAME, mode, &ncid)) ERR;
         if (nc_def_dim(ncid, DIM8_NAME, TEST_VAL_42, &dimids[0])) ERR;
         if (nc_def_var(ncid, VAR_NAME8, NC_INT, NDIMS6, dimids, &varid)) ERR;

         /* Set the var to contiguous. */
         if (nc_def_var_chunking(ncid, varid, NC_CONTIGUOUS, NULL)) ERR;

         /* Now defalte can't be set. */
         if (nc_def_var_deflate(ncid, varid, 0, 1, 4)) ERR;

         if (nc_close(ncid)) ERR;
```

nc_def_var_extra() checks for this condition like this:

```
   /* Can't turn on contiguous and deflate/fletcher32/szip. */
   if (contiguous)
      if ((*contiguous != NC_CHUNKED && deflate) ||
          (*contiguous != NC_CHUNKED && fletcher32))
         return NC_EINVAL;

```

This check does not work because first contiguous is set, then deflate in a separate call. So in the call from nc_def_var_deflate(), the contiguous pointer is NULL so the check is not run.

(What ends up happening with the code above is that def_var_deflate() silently changes the contiguous setting to chunked when it turns on deflation. Instead it should return an NC_EINVAL error.)

I will clean this up.

### LINKED ISSUE #978: need tests for some untested parallel code
In nc4hdf5.c we have the following code:

```
#ifdef USE_PARALLEL4 /* Start block contributed by HDF group. */
      /* For collective IO read, some processes may not have any element for reading.
         Collective requires all processes to participate, so we use H5Sselect_none
         for these processes. */
      if(var->parallel_access == NC_COLLECTIVE) {

         /* Create the data transfer property list. */
         if ((xfer_plistid = H5Pcreate(H5P_DATASET_XFER)) < 0)
            BAIL(NC_EHDFERR);

         if ((retval = set_par_access(h5, var, xfer_plistid)))
            BAIL(retval);

         if (H5Sselect_none(file_spaceid)<0)
            BAIL(NC_EHDFERR);

         /* Since no element will be selected, we just get the memory space the same as the file space.
          */
         if((mem_spaceid = H5Dget_space(var->hdf_datasetid))<0)
            BAIL(NC_EHDFERR);
         if (H5Sselect_none(mem_spaceid)<0)
            BAIL(NC_EHDFERR);

         /* Read this hyperslab into memory. */
         LOG((5, "About to H5Dread some data..."));
         if (H5Dread(var->hdf_datasetid, var->type_info->native_hdf_typeid,
                     mem_spaceid, file_spaceid, xfer_plistid, bufr) < 0)
            BAIL(NC_EHDFERR);
      }
#endif /* End ifdef USE_PARALLEL4 */

```

This code is not tested in netcdf,.

This code is also causing a hang in the PIO library.

### LINKED ISSUE #985: eliminate unused HDF5_CONVERT and related code in nc4hdf5.c
In nc4hdf5.c we have some code like this:

```
#ifndef HDF5_CONVERT
   int need_to_convert = 0;
   size_t len = 1;
#endif
#ifdef HDF5_CONVERT
   hid_t mem_typeid = 0;
#endif

```
This occurs with a lot of code in nc4hdf5.c, but no where else.

The HDF5_CONVERT macro is never set anywhere.

At first I wrote the netccdf-4 code so that HDF5 did data conversions on reads/writes. But it was impossible to get HDF5 to follow the exact rules of netCDF with regard to some of the corner cases. So I re-wrote the netcdf-4 code to convert the data as needed.

The HDF5 team told me they would put in fixes so that HDF5 could correctly handle the corner cases. Then I could remove the conversion code in netCDF-4. But that went the way of most good intentions.

So for all this time, we have been converting the data, and I guess we are going to continue to do so. The HDF5_CONVERT code does not even compile at this point. I will take it all out and clean up the code.

### LINKED ISSUE #993: Test gaps for hdf5file.c
While waiting for PRs to be merged, I took a look at the test coverage for hdf5file.c. We need tests for:

1 - syncing a file that is not in define mode (with and without classic model).
2 - nc_set_chunk_cache with bad preemption value.
3 - nc_get_chunk_cache with NULL parameters.
4 - nc_set_chunk_ints/nc_get_chunk_ints have no tests at all.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #978.
Fixes #985.
Part of #679.
Fixes #993.
Fixes #710.

This is a combined PR.

This PR contains mostly new test code. It contains new parallel I/O tests which are important. We believe we have found a bug in HDF5 1.10.1 and 1.10.2 parallel I/O related to collective writes in which some processes have a count of 0. The tests in this PR are an important part of narrowing in on this bug.

Also included are tests of the enum functionality when a fill value is not specified, or is not a valid member of the enum.

There are also some pre-approved, minor code changes, including checking of some return codes, and the removal of dead, legacy code that was never used (ex. HDF5_CONVERT code).

### CODE REVIEW

**Comment by edhartnett** [comment]
@WardF can I get this merged soon?

I am basing the vars parallel I/O tests and work on some work in this branch, so it would be easiest if it were merged before I present the next PR.

**Comment by WardF** [comment]
It will probably be next week before I circle back around to code review and merging; I'll try to make it earlier in the week.

**Comment by WardF** [comment]
I'll take a look at it early this week; there is other work going on that needs my attention at the moment.

**Comment by WardF** [comment]
Reviewing now.

**Comment by edhartnett** [comment]
Thanks @WardF , next PR is up. ;-)

**Pull request merged**
