### PR TITLE
Fix plugin building for filter tests and add filter example

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
1. Keep up to date by merging master
2. Fixed plugin building (nc_test4/hdf5plugins)
   to be done properly by cmake and automake.
4. Duplicated part of the nc_test4 filter test code
   in examples/C

An incomplete and untested set of hooks exist
for OS-X in nc_test4/findplugins.in. They need testing.

### CODE REVIEW

**Comment by WardF** [comment]
Thanks! Once this is done checking I'll start getting the 4.6.0 release out the door.

**Comment by WardF** [comment]
Repairing my windows VM so I can create distribution installs.

**Comment by WardF** [comment]
Seeing a failure on OSX, investigating.  The failing test is `nc_test4_tst_filter`.

**Comment by WardF** [comment]
I think I have it sorted.

**Comment by DennisHeimbigner** [comment]
Interesting.  So OSX uses .so and not .dylib?
Also what is extra_PROGRAMS vs check_PROGRAMS?

**Comment by WardF** [comment]
extra_PROGRAMS, from scanning the documentation (and I need to recheck this but it is working, for the moments) allows us to use `make check -j` and ensure that the extra programs are built before the test program is run.  When using `check_PROGRAMS` I was running into errors with the filter test script, as it would run before the check programs were built.

OSX uses .dylib for the most part, but the check programs in this instance are being built as .so instead.  I don't know why the behavior is different, I've been splitting my attention and need do some investigation. For the moment I've been focusing on what appears to work, and then I will confirm why.

**Comment by WardF** [comment]
Seeing a failure where -F is not being reflected in the metadata (-s) when nccopy is invoked on Windows, resulting in a test failure.  Continuing to investigate.

**Comment by WardF** [comment]
I'm seeing the following error on Windows.  Any idea why `nccopy` on Windows wouldn't generate `_Filter`, @DennisHeimbigner ?

````{.C}
*** Testing dynamic filters parameter passing
test1: compression.
test: nparams=14: params= 1 4294967279 23 4294967271 27 77 93 1145389056 3287505826 1097305129 1 2147483648 4294967295 4294967295
 chunks=4,4,4,4
test1: decompression.
data comparison: |array|=256
no data errors
*** Pass: parameter passing
*** Testing dynamic filters using ncgen
*** Pass: ncgen dynamic filter
*** Testing dynamic filters using nccopy
16d15
<               var:_Filter = "307,9,4";
````

**Comment by DennisHeimbigner** [comment]
Is there any chance you can get to the compressed .nc file
and do an 'h5dump -p' on it to see if the file is in fact compressed?
Also can you get to the 'build/Testing/Temporary/LastTest.log' file?

**Comment by DennisHeimbigner** [comment]
When I run with those lines commented out, I get this
> *** Testing ncgen3 for netCDF-4.
> *** creating netCDF-4 file c0_4.nc from c0.cdl...
> D:/git/netcdf-c/build/ncgen3/ncgen3.exe: error while loading shared libraries: netcdf.dll: cannot open shared object file: No such file or directory
> <end of output>
> Test time =   0.28 sec
(from build/Testing/Temporary/LastTest.log)

**Comment by DennisHeimbigner** [comment]
And the reason it fails is that netcdf.dll
is in the wrong place: namely build/liblib/Release/netcdf.dll
rather than build/liblib/netcdf.dll.
The commented out code was to force netcdf.dll to be in the right place.

**Comment by WardF** [comment]
Go ahead and restore the commented out code and I will modify my environment.

**Comment by DennisHeimbigner** [comment]
What is the environment thatyou need to change?

**Comment by WardF** [comment]
It is an environment specific to my local machine; it's not related to netcdf or cmake.  I can work around this pretty easy.  Also, h5dump -p shows that the `filtered.nc` created on Windows is not being compressed.  I will attach the last log shortly.

**Comment by WardF** [comment]
[LastTest.log](https://github.com/Unidata/netcdf-c/files/1640440/LastTest.log)

**Comment by DennisHeimbigner** [comment]
What ./configure options are you using?

**Comment by WardF** [comment]
For netCDF? I'm using cmake; `--DENABLE_FILTER_TESTING=TRUE --DENABLE_CDF=TRUE --DENABLE_HDF4=TRUE`.  For hdf5? Also cmake, `-DHDF5_ENABLE_FORTRAN=OFF -DHDF5_BUILD_HL_LIB=TRUE -DHDF5_ENABLE_Z_LIB_SUPPORT=ON -DBUILD_SHARED_LIBS=TRUE -DHDF5_BUILD_TOOLS=ON`

**Comment by DennisHeimbigner** [comment]
Is it possible for you to run the VS that is failing, but with hdf4 disabled?

**Comment by WardF** [comment]
Yes, I will test momentarily.

**Comment by WardF** [comment]
I've observed the same failure when building without HDF4 support.

**Comment by DennisHeimbigner** [comment]
I have added some temporary debugging output to try to help resolve this.
Please try again and send me the LastTest.log file

**Comment by edhartnett** [comment]
Guys would you consider holding this PR until the next release, and getting 4.6.0 out now with all the PRs that are ready and are passing?

I have more changes to put up but I need to wait until most of the outstanding PRs are merged so that I know what I am working with. ;-)

**Comment by WardF** [comment]
We need to have this feature functional for the windows users, or at least understand what is going on. We can’t back out the filter code easily at this point (and I don’t think we need to), so easier to press forward.

**Comment by WardF** [comment]
I do think we can sort this out pretty quickly but if nccopy isn’t respecting the new -F flag on Windows, we need to sort out why :). I’m at a doctors appointment but will generate the new logfile when I get to the office shortly. Dennis, does this test pass in your environment?

**Comment by WardF** [comment]
@DennisHeimbigner did you push your update with the additional logging? I'm not seeing anything on the plugins.dmh branch since a small change I made yesterday.

**Comment by WardF** [comment]
@DennisHeimbigner I've run as you suggested above, and still see the error.  Does the error occur for you?  I'm using hdf5 1.8.20.  

I've created a branch based on `plugins.dmh`; the new branch is `nccopy-logging`.  The only difference is the addition of a new option, `-L[log level]`, which sets a log level when logging has been enabled.  I'll merge it back into `plugins.dmh` (where it will eventually percolate up into `master`) unless you have an objection?

**Comment by DennisHeimbigner** [comment]
No objection. I never see the error no matter what I do.
I see I forgot to do a push on my version of plugins.dmh.
I will instead merge the nccopy debug changes into nccopy-logging
ok?

**Comment by DennisHeimbigner** [comment]
Wait, where did you creatre that nccopy-logging branch. It is simplest for me
if you create it in the unidata/netcdf-c repo.

**Comment by WardF** [comment]
@DennisHeimbigner I created it in the unidata/netcdf-c repo.  I will merge it back into plugins.dmh.

I will continue to troubleshoot on my end.  Using the nccopy command from tst_filters.sh w/ an additional logging 5 argument, I've generated the two log files attached below.  At line **174**, we can see in the OSX log file, a call to `NC4_inq_var_all` followed by a call to `NC4_def_var_filter`.  In the Windows log file, we see two calls to `NC4_inq_var_all`. 

I will keep working on this, but since it is working on your end, I am more confident that this is something environmental.  Are you using a prebuilt HDF5 or did you build and install it yourself?

* [filter_windows.txt](https://github.com/Unidata/netcdf-c/files/1644696/filter_windows.txt)
* [filter_osx.txt](https://github.com/Unidata/netcdf-c/files/1644697/filter_osx.txt)

**Comment by DennisHeimbigner** [comment]
I am not seeing that branch. Have you pushed it to origin yet?

**Comment by WardF** [comment]
I had, yes, but it is merged back into plugins now.

**Comment by WardF** [comment]
@DennisHeimbigner  are you working in a cygwin environment?

**Comment by DennisHeimbigner** [comment]
Ok, I ran with 32-bit hdf5 1.8.20 and all the tests passed.

**Comment by DennisHeimbigner** [comment]
I have pushed some extra nccopy debug output code. Please run
your tests and give me the LastTest.log file

**Comment by WardF** [comment]
Note to self: failure is in nc4_rec_write_metadata somewhere, continuing to dig.

**Comment by edhartnett** [comment]
@WardF if you turn on logging and post the log messages from nc4_rec_write_metadata(), I may be able to help...

**Comment by WardF** [comment]
@DennisHeimbigner Here is the latest log:

* [nccopy_log.txt](https://github.com/Unidata/netcdf-c/files/1648135/nccopy_log.txt)

The error seems to be more clear, but I'm not sure *why* it is occurring.

**Comment by WardF** [comment]
Oh, hadn't seen your copy @edhartnett wasn't trying to exclude you from debugging, knock yourself out.  This feels environmental, perhaps, but until I can point to exactly what is happening (and can thus advise others who encounter this) I'm a bit nervous about putting it in the wild.  However, if we can establish it's something esoteric and unlikely to happen (given that it works on @DennisHeimbigner 's system) I'd be happy adding a release note and punting on the eventual fix until later.

**Comment by edhartnett** [comment]
OK, had a look and clearly it's filter-related. So good luck @DennisHeimbigner I will raise a beer to your efforts shortly! ;-)

**Comment by DennisHeimbigner** [comment]
Ok, I went digging into the hdf5 source code,
and I have a pretty good idea what the problem is.
The filter interface has some per-filter functions that test
if the filter can be applied to a specific dataset+type.
It looks like the bzip filter is returning an improper value for one of these.
This causes HDF5 to claim the filter cannot be applied.
So my hypothesis is that running this in my environment is accidentally
returning the ok signal while running this in your environment is accidentally
returning the not ok signal.
I will review the bzip2 code to see if I see anything.

**Comment by WardF** [comment]
If I can do anything on my end to help debug this, let me know.  We should also synchronize (for debugging this at least) on a common version of hdf5.  Were you able to find an installer for the latest version?

**Comment by DennisHeimbigner** [comment]
The critical error in the above log was this:
> #010: C:\Users\Ward\Desktop\deploy-dev-environment\build-shared-VS15-64\hdf5-src\src\H5Z.c line 899 in H5Z_can_apply(): unable to apply filter
I just checked in a change to make the so-called "can_apply" function
be explicit.  Please run your VS again and see if this solves the problem.
If not, then send me the new nccopy log file.

**Comment by WardF** [comment]
@DennisHeimbigner 

* New nccopy log: [new_windows_log.txt](https://github.com/Unidata/netcdf-c/files/1653716/new_windows_log.txt)

**Comment by DennisHeimbigner** [comment]
It looks like my fix fixed one problem, but exposed a second. If you compare the two
nccopy_logs, the previous one had errors in it. The newest one does not.
So, my current speculation is that I used two different filter string parsers between
ncgen and nccopy, which is why ncgen works and nccopy does not. I am going to merge
the parsers and see what effect that has.

**Comment by WardF** [comment]
I've been focused on Windows, so testing your fix on Unix and OSX now gives a new failure.  `tst_filters.sh` runs fine, apparently (I've double checked by turning on -x), but trying to run `nccopy` from the command line gives the following:

````{.C}
../ncdump/nccopy -L5 -F /g/var,307,9,4 unfiltered.nc tmp.nc
NetCDF: Filter error: bad id or parameters or filter library non-existent
Location: file /home/tester/netcdf-c/ncdump/nccopy.c; line 1678
````

The same command exits properly on Windows.

**Comment by edhartnett** [comment]
Guys, can I suggest again that we defer this PR and release 4.6.0 as is?

4.6.0 contains some very important fixes for fill values that have nothing to do with filters. Those changes need to get out there to replace 4.5.0 which is quietly generating corrupted files with incorrect fill values. 

Is there an equally urgent reason to hold the release until the filter changes are ready?

I suggest you release 4.6.0 now, and we immediately start on 4.7.0 which will include filters and all other currently outstanding PRs, and gets released in March. Then we can do a 4.8.0 in the early Summer with the PIO/HPC changes. 

I do not want you guys to rush, and put in bad code. But I also don't want users to have to keep waiting for a fill value fix. It's urgent and it's been broken for a long time - too long. So let's get that fix out there immediately, and take as much time as you need to develop and test new features after that.

**Comment by DennisHeimbigner** [comment]
Let me have another day on this.

**Comment by WardF** [comment]
@DennisHeimbigner So I've spent time thinking about this; the filter code is already in `master` so I can't do just a 4.5.1 maintenance release (as I set out to do this morning).  I do agree we need to get something out fairly quickly.  If it continues to work on your end, I may merge this in and we will just have to address the `nccopy` issue ASAP, or at least be able to describe the shape of the issue if it comes up in support.  Having the documentation and such available will make our lives easier, moreso than this specific issue will make it harder.  So, I am going to spend the rest of the day cherry picking smaller PR's that seem innocuous enough, and will focus on 4.6 tomorrow.  

Does that sound ok with you?

**Comment by edhartnett** [comment]
I agree that an nccopy filter problem is not worth holding the release for.

@Ward, I have already pull many PRs into the merge PR I have up now. But I wanted to give Denis a chance to merge his code first. So if he is going to merge to master, then let me bring my merged PR up to date, and let's run it through testing, and merge that next. That will close a bunch of open PRs and tickets.

**Comment by WardF** [comment]
It will be merged into 4.6.0 release branch first, and then bubble up to `master` from there.

**Comment by WardF** [comment]
I will be cherry picking merges that go into 4.6.0 as well.

**Comment by edhartnett** [comment]
@WardF I suggest that you forgo merging anything else into 4.6.0 and get it out. Merging in something that seems innocuous can still cause bugs and delay.

**Comment by DennisHeimbigner** [comment]
I have a separate branch named 'tmp' that has my proposed plugin fixes in it.
If possible, you might see if that fixes everything or not.
=Dennis

**Comment by WardF** [comment]
I will give it a test here shortly, thanks @DennisHeimbigner

**Comment by WardF** [comment]
@DennisHeimbigner `tmp` still fails, unfortunately.  I will pass along the verbose log file in just a bit.

**Comment by DennisHeimbigner** [comment]
I give up; I cannot duplicate it and I can see no way to get enough information
about what is going wrong. Generate and test is not working.

**Comment by WardF** [comment]
I will merge into the 4.6.0 release and we can address this issue down the road.  Besides a meeting tomorrow, the focus will be on the 4.6.0 release out the door.

**Comment by DennisHeimbigner** [comment]
Ok, But send me the relevant log. I may still be able to fix some things.

**Comment by edhartnett** [comment]
Guys, thanks for pushing through this issue. I look forward to the release...

**Pull request merged**
