### PR TITLE
hdf5set_format_compatibility.c: Update new function documentation.

### PR DESCRIPTION
**Pull request by Dave-Allured**
* Comment change only.  Add one paragraph.  Explain the reason for the third argument to H5Pset_libver_bounds.  Simplifies experimental code using advanced features.

This updates the original function added in PR Unidata#2176.

### CODE REVIEW

**Comment by WardF** [comment]
I am a bit puzzled how this is failing the checks given the nature of the change.  Testing by hand to try to shed some light on it.

**Comment by Dave-Allured** [comment]
I have been noticing random CI failures here and there, for several days.  In the single reported failure above, in the CI logs, I saw two timeouts during test suite execution, and nothing else I think.

I think these are probably CI problems unrelated to this PR.  You must admit that the simple change in this PR is unlikely to cause any code execution problems.

**Comment by Dave-Allured** [comment]
Um, make that **three** timeouts.  It appears that test no. 87, nc_test_run_mmap, may not be reporting its results properly.  The fail was in the log, but not in the fail summary at the end.

**Comment by WardF** [comment]
@Dave-Allured Yeah, I'll take a look at this tomorrow and make sure it's something in the back-end infrastructure and isn't the result of something on our end that I'll need to track down/correct.

**Pull request merged**
