### PR TITLE
Github issue 152: https://github.com/Unidata/netcdf-c/issues/152

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
User request to have all orphaned DAP2 attributes kept as netcdf
global attributes. This is primarily a change in the oc code
nplus testcase dataset changes.

Result may be inconsistent with netcdf-Java output.

### CODE REVIEW

**Comment by WardF** [comment]
Is the fact that this is inconsistent with netcdf-java a showstopper? Copying @lesserwhirls , @johnlcaron for their input.

**Comment by DennisHeimbigner** [comment]
I don't know. The effect is to make attributes appear
that previously did not exist. If someone should rely on
these attributes and then expect them for java, there might be
a problem. I will take a quick look at the java code to see
what happens to such attributes. In any case,  I doubt that
this is a show-stopper.
=Dennis


Ward Fisher wrote:

**Comment by DennisHeimbigner** [comment]
I checked the java code and it turns out that it already handles these
kinds of attributes, so in fact, this change to the netcdf-c will make
the c and java more consistent, not less.

**Comment by WardF** [comment]
Fantastic :). Merging shortly.

**Pull request merged**
