### PR TITLE
fix codes might break strict-aliasing rules

### LINKED ISSUE #500: nc_test fail in 4.5.0 with CMake
```
 70/177 Test  #70: nc_test ...............................***Failed   26.31 sec
```

It works without -DCMAKE_BUILD_TYPE=Release (i.e. DEBUG build), but not with it.

### PR DESCRIPTION
**Pull request by wkliao**
This should fix #500

### CODE REVIEW

**Comment by edhartnett** [comment]
Thanks for finding this! I was not looking forward to digging into this one!!

Only suggestion is that you resubmit without the #if 1 / #else / #endif.

Just take out the old code and put in the new.

**Comment by WardF** [comment]
Thanks, testing now w/ the updated `master`.

**Comment by WardF** [comment]
Passed on ARM as expected, also expect it will pass the Windows tests.  Once it does will merge.

**Comment by wkliao** [comment]
Hi @Ward, I assume your testing (on Travis CI, etc.) is using -O3 and gcc, as the error only appears when -O3 is used.

**Comment by WardF** [comment]
Travis is not by default but that is fine; I am testing manually with -O3 and gcc on ARM and also testing on Windows with Visual Studio; the tests help ensure nothing that worked has unexpectedly broken in addition to making sure that what was broken is now fixed :).

**Pull request merged**
