### PR TITLE
Resolve license issue with the utf8proc code.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
Re: Github issue https://github.com/Unidata/netcdf-c/issues/349.

Update utf8proc.[ch] to use the version now
maintained by the Julia Language project
(https://github.com/JuliaLang/utf8proc/blob/master/LICENSE.md).
The license for the previous version was
unacceptable for the Debian and Ubuntu release
systems. The new version both updates the code
and addresses the license issue.

It turns out that the utf8proc software we are using
was turned over to the Julia Language developers
and the license terms changed to allow modification.
(https://github.com/JuliaLang/utf8proc/blob/master/LICENSE.md).

So the fix here is as follows:
1. Wrap the library with a fixed interface: libdispatch/dutf8.c
   and include/ncutf8.h.
2. Replace the existing utf8proc code with the new version
   from https://github.com/JuliaLang/utf8proc.
3. Add a couple more test cases: nc_test/tst_utf8_validate.c
   and nc_test_utf8_phrases.c.  If/when I can find a usable
   normalization test, I will incorporate that later.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Sorry, I always forget to test with cmake.
=Dennis

**Comment by WardF** [comment]
Not a problem.  The root of the issue is described here, and should be easy enough for me to fix. Attending to it now.  

* https://msdn.microsoft.com/en-us/library/62688esh.aspx

**Comment by DennisHeimbigner** [comment]
For what its worth, I only use a couple of the functions in utf8proc. None of the others
need to be exported.

**Comment by WardF** [comment]
Propagating changes from `master` into branch, then working on resolving this.

**Pull request merged**
