### PR TITLE
Combination of 11 outstanding non-controversial PRs

### PR DESCRIPTION
**Pull request by edhartnett**
This PR is a merge of a bunch of non-controversial PRs that are currently in the PR list. This is part of an effort by @WardF and me to clear the PR backlog.

There were some minor conflicts that I resolved. @DennisHeimbigner I changed some of your .sh test code to use tmp directory and file spefic to the test. (That is, /tmp_TEST_NAME vs. /tmp). This is helpful now that we are using parallel builds.

This includes:
@wkliao PR #466
@DennisHeimbigner PRs #558, #619, #703.
@gdsjaar #764, #765, #766 
And from me, #763, #769, #780, #786.

After this has passed through testing @WardF will merge it and close the PRs listed above. (I will close mine now).

After this merge we will take another pass through the remaining PRs to see what can be merged.

Thanks to all for your contributions to netCDF. Some of us do it as a job, some of use because we are billionaires who program netCDF in our spare time from our private space station. But we all agree that it is worth improving! ;-)

### CODE REVIEW

**Comment by WardF** [comment]
This pull request introduces 2 alerts - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-4f308b709dbc555fb31dd1fe861dab6c02c5d34b)

**new alerts:**

* 1 for Duplicate include guard
* 1 for Missing return statement

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by WardF** [comment]
Won't have time to investigate or check this across the board until next week, but a quick test returned 7 failures on OSX:

* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=22

**Comment by edhartnett** [comment]
OK, these are ncgen failures. I will try a less ambitious merge and see how it goes...

**Comment by edhartnett** [comment]
@WardF does the experimental CDash testing happen on all PRs? Or do you manually submit it?

**Pull request closed without merging**
