### PR TITLE
Cause nc_create() to return NC_ENOTBUILT if user requests un-built feature like netCDF4 or CDF5

### LINKED ISSUE #392: Try create a NetCDF4 file using NetCDF ibrary built with --disable-netcdf-4
A question.
When using NC_NETCDF4 mode to create a file using a netCDF library built without netcdf4 enabled (i.e. --disable-netcdf-4), should the nc_create function return NC_EINVAL?

FYI. I tested this using the latest master branch and the file is created without error, but the file is in the classic format.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #392.

This PR changes some behavior. Incorrect create mode flags that were previously ignored will now trigger errors.

For example, attempting to use NC_NETCDF4 in a library built with --disable-netcdf4 will currently be ignored. A classic file will be created.

After this PR, an NC_ENOTBUILT error is returned instead.

I am not married to these changes, I only put them in in response to user ticket and discussion. So if you don't want to make this change, just explain that in #392 and close the ticket.

This PR was inadvertantly closed when my last batch of changes were merged, but these changes were not part of that batch. I want to make sure that @WardF and @DennisHeimbigner have a good understanding of how library behavior will change with this PR.

### CODE REVIEW

**Comment by edhartnett** [comment]
@WardF and @DennisHeimbigner you guys OK with these changes?

If so I will merge this PR into my next mega-PR.

**Comment by WardF** [comment]
Looks good to me, what do you think @DennisHeimbigner?

**Comment by DennisHeimbigner** [comment]
I am ok with it.

**Comment by edhartnett** [comment]
OK, I will merge this into my other open PR so they can be done at the same time.

Thanks!

**Comment by edhartnett** [comment]
I have merged this into #711. I will take this PR down now.

**Pull request closed without merging**
