### PR TITLE
Support installation of standard pre-built filters into user-specified location

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: https://github.com/Unidata/netcdf-c/issues/2294

https://github.com/edwardhartnett suggested that the netcdf library installation process be extended to install the standard filters into a user specified location. The user can then set HDF5_PLUGIN_PATH to that location.

This PR provides that capability using:
````
configure option: --with-plugin-dir=&lt;absolute directory path&gt;
cmake option: -DPLUGIN_INSTALL_DIR=&lt;absolute directory path&gt;
````

Currently, the following plugins are always installed, if available: bzip2, zstd, blosc.

If NCZarr is enabled, then additional plugins are installed: fletcher32, shuffle, deflate, szip.

Additionally, the necessary codec support is installed for each of the above filters that is installed.

## Changes:
1. Cleanup handling of built-in bzip2.
2. Add documentation to docs/filters.md
3. Re-factor the NCZarr codec libraries
4. Add a test, although it can only be exercised after the library is installed, so it cannot be used during normal testing.
5. Cleanup use of HDF5_PLUGIN_PATH in the filter test cases.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Does this default to the default HDF5 plugin dir? It should...

Most users will have no idea where to install filters, and will not care. They just want them to work. ;-)

**Comment by DennisHeimbigner** [comment]
Remember, HDF5_PLUGIN_PATH is not necessarily a single directory; it is a list
of directories separated by ':' or ';', like the PATH environment variable.

**Comment by edwardhartnett** [comment]
Sure but in most cases it will just be one directory, the default one...

**Comment by DennisHeimbigner** [comment]
Remember, this is an issue with the builder of the library; not necessarily the user.
If the builder uses this option then he is likely to understand the role
of its argument vis-a-vis HDF5_PLUGIN_PATH.

**Comment by edwardhartnett** [comment]
Yes, it should default to the HDF5 default, but be settable at build time. That's what I have in CCR.

**Comment by edwardhartnett** [comment]
@WardF I sincerly hope this PR is going to make it into the 4.9.0 release. It is essential for zstadard support.

Once it is merged I will run a bunch of tests, so merging it soon would be very helpful.

**Review by WardF — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Awesome! I will start some testing today...

**Pull request merged**
