### PR TITLE
Misc. source comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Some are user-facing. Found via `codespell` and through the downstream FreeCAD.

### CODE REVIEW

**Comment by luzpaz** [comment]
Tried to sign the CLA and see an empty screen when I click the link.

**Comment by luzpaz** [comment]
@WardF I found several more typos. Can i push a new commit or should I open another PR ?

**Comment by WardF** [comment]
Pushing is fine!

**Comment by luzpaz** [comment]
FYI, screenshot of attempting to load the CLA link:
image

**Comment by WardF** [comment]
Thanks for the heads up re: the CLA.  Let me try to figure out what is happening.

**Comment by WardF** [comment]
@luzpaz Trying to narrow things down, since I don’t think it’s a server side issue.  What browser are you using?  I wouldn’t think it would matter in this day and age, but who knows?  Do you have any content blockers enabled by default? I wonder if something is being blocked, maybe?  I will look into this further.  @dopplershift any ideas what might be causing the CLA behavior shown above?

**Comment by dopplershift** [comment]
This definitely seems like a browser problem--I'm not having any problems interacting with the site.

@luzpaz Does that disable javascript? Because the page looks like it requires it.

**Comment by luzpaz** [comment]
I can't find the setting at this time. Can I just make a declaration that I waive my right of ownership of these trivial typos fixes? :smile:

**Comment by WardF** [comment]
Would it be possible to sign in with a different browser to ok this?  A quick search suggests that Tor/Tor-based browsers don’t make enabling JavaScript easy, due to their focus on anonymity.  If the number of files changed were relatively small I’d say no problem, and create my own PR, but with 79 files it would take a while to go through and recreate this fix :).

**Comment by luzpaz** [comment]
signed and rebased

**Comment by WardF** [comment]
Thanks!

**Pull request merged**
