### PR TITLE
Allow parallel writes to use zlib

### LINKED ISSUE #1580: Allow parallel I/O writes to use zlib
Allow users to use zlib on parallel writes. This feature is needed urgently by NOAA. No doubt it is desired by many other large data producers.

Large data producers like NOAA are turning to netCDF-4 due to built-in compression. On HPC applications especially, they are writing very large files (10s of GB per file is normal, even with compression).

Since these files are produced on a HPC system, the data start on many processors. Due to the current limitation of the netcdf-c library, they must move all data to one processor, and have that one processor do all compression and writing sequentially. This slows down their very expensive machine!

More importantly, it means that compromises must be made in what is saved. Instead of saving every value that the science team wants, only a subset of values and data are saved. This makes the science harder but makes operations work.

Allowing users to write data compressed with parallel I/O will save them the step of moving all data to one processor, and will also allow the compression to be spread to many processors, instead of just one. This will improve their write time by almost an order of magnitude.

Decrease in I/O time leads to increased time for computation, allowing the science team to increase resolution or use more intensive algorithms, and still meet operational requirements. 

Thus improving the I/O times directly impacts the science.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #1580

### CODE REVIEW

**Comment by WardF** [comment]
Is there a minimum version of HDF5 required to support this? Or is it a feature that just has been available in parallel HDF5 but not enabled in netCDF?

**Comment by gsjaardema** [comment]
I know that 1.10.3 and 1.10.4 had bugs that caused "Too many communicators" failures that was fixed in 1.10.5.

**Comment by gsjaardema** [comment]
Looks like parallel compression output was released in 1.10.2:
```
In the past, HDF5 parallel applications could read compressed data, but couldn’t create and write data using compression and other filters like Fletcher32 for raw data checksum. This restriction was removed in HDF5 1.10.2. 
```

**Comment by WardF** [comment]
@gsjaardema thanks! @edwardhartnett I think we need to find a way to fencepost this so that it doesn't break builds for people still using older versions of libhdf5.

**Comment by edwardhartnett** [comment]
Yes, I should have made it clear that this PR is not quite ready to merge. I just wanted to try it on the CI.

I would like to:
* Add more tests.
* Better handle cases of older HDF5
* See if this also applies to fletcher32 (for completeness - I don't think many people use fletcher32.)

**Comment by edwardhartnett** [comment]
I'm just going to take this down while I work on it a bit more. I will put up a complete PR in a bit.

**Pull request closed without merging**
