### PR TITLE
Fixed plugin compilation using MSVC

### LINKED ISSUE #1245: Filter Testing with MSVC fails to build.
When `-DENABLE_FILTER_TESTING=TRUE` is passed to cmake on Windows using MSVC, we fail with missing symbols during linking in the `plugins/` directory.  I'll paste the errors in a bit.

### PR DESCRIPTION
**Pull request by WardF**
* Fixes #1245

### CODE REVIEW

**Comment by WardF** [comment]
@DennisHeimbigner Seeing a weird failure in `nc_test4/tst_filter.sh`, but only on windows.

On linux and OSX, I see the following:

    $ nccopy -M0 -F /g/var,307,9,4 unfiltered.nc filtered.nc
    $ ncdump -sh filtered.nc

As expected, the `ncdump` command shows me the special attributes, including (for `float var(dim0, dim1, dim2, dim3)` in `group: g`)

````
var:_Filter = "307,9,4" ;
````

If I follow the same series of commands in a bash shell on Windows, however, I do not see the `_Filter` attribute when I query the resultant filtered.nc file.  This is causing an error in the subsequent `diff` command invoked in the `tst_filter.sh` script.  Any ideas why `nccopy` under Windows would not be Filtering as expected?

**Comment by DennisHeimbigner** [comment]
Let me see if I can duplicate.

**Comment by DennisHeimbigner** [comment]
It seems to work for me.
Does the file build/Testing/Temporary/LastTest.log show anything?

**Comment by WardF** [comment]
You can see the failure here:

* http://cdash.unidata.ucar.edu/testDetails.php?test=273805&build=7069

**Comment by DennisHeimbigner** [comment]
Is this possibly a mingw problem rather than visual studio (which is what I used)?
In any case, we need to see the complete output from the last
ncdump command:
+ /d/netcdf-c/build/ncdump/ncdump.exe -s filtered.nc
Can you modify the tst_filter.sh to cat out the output from that command?

**Comment by WardF** [comment]
Hi Dennis, I used Visual Studio as well; I'm not using mingw.  I'll follow up with the output.  

For reference, I'm using Visual Studio 2017 w/ HDF5 1.10.4.

**Comment by WardF** [comment]
I *am* using MSYS which gives me a `bash` shell but it is still using the MSVC and standard Windows libraries.

**Comment by WardF** [comment]
@DennisHeimbigner here is the output captured from `tst_filter.sh` as per your request.

* [msvc_tst_filter.txt](https://github.com/Unidata/netcdf-c/files/2696701/msvc_tst_filter.txt)

**Comment by DennisHeimbigner** [comment]
I am completely baffled.

**Comment by DennisHeimbigner** [comment]
BTW, note that the _NCProperties attribute of that file says it was created
with hdf5 1.8.20.

**Comment by WardF** [comment]
I am installing hdf5 1.10.4 right now to see if that makes a difference.  What version of hdf5 are you testing with?

**Comment by DennisHeimbigner** [comment]
Apparently I am using 1.8.17 when I do a visual studio build.

**Comment by WardF** [comment]
I downgraded to 1.8.17 and saw the same error.  Are you running from a windows CMD window, or a cygwin window?  Also, do you see no error if you upgrade to a later (1.8.x or 1.10.x) version?

**Comment by t-b** [comment]
@WardF This PR can be closed as it is already merged.

**Pull request closed without merging**
