### PR TITLE
Lazy read of attributes

### LINKED ISSUE #1025: --enable-metadata-perf does not work for me on master
Seems like the bash script that runs the test has the wrong permissions.

Also, when I do run the script, I don't get any useful performance output.

When I change the script to have:

```
PROF=1
DEBUG=1
MEM=1

```

I get this output:

```
ed@mikado:~/tmp/n2/nc_test4$ ./perftest.sh 
+ set -e
+ echo Testing performance of nc_create and nc_open on file with large metadata
Testing performance of nc_create and nc_open on file with large metadata
+ ARGS=--treedepth=6 --ngroups=2 --ngroupattrs=100 --ndims=100 --ntypes=10 --nvars=100 --varrank=2 --nvarattrs=500
+ echo timing bigmeta:
timing bigmeta:
+ /home/ed/tmp/n2/nc_test4/bigmeta --treedepth=6 --ngroups=2 --ngroupattrs=100 --ndims=100 --ntypes=10 --nvars=100 --varrank=2 --nvarattrs=500
--treedepth=6
--ngroups=2
--ngroupattrs=100
--ndims=100
--ntypes=10
--nvars=100
--varrank=2
--nvarattrs=500
create delta=87
+ echo timing openbigmeta:
timing openbigmeta:
+ /home/ed/tmp/n2/nc_test4/openbigmeta
open delta=22
+ test x1 = x1
+ rm -f perftest.txt
+ gprof openbigmeta gmon.out
gmon.out: No such file or directory


```

So not sure what is supposed to be happening here.

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #857.
Part of #489.
Fixes #1025.

In this PR I change attribute reading to lazy. No attributes are read at open. Whenever the user gets/puts/inqs an attribute for a var or group, then all atts for that var or group are read. If atts in a var/group are never touched by the user, they are never read.

This helps a lot with slow open times for files with many attributes.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Did this get merged? Why is it closed?

**Comment by edhartnett** [comment]
This is in the queue. When #1023 gets merged this will be next.

**Comment by edhartnett** [comment]
nc4_set_default_vars does not have a place any more. It used to call the vara versions of the function. But now there is no vara version of the function. The vara calls also call the vars functions.

So to see the difference between breaking up the write/read into varas instead of vars, you can call NCDEFAULT_vars, but it will still end up calling the vars functions under the hood.

**Comment by DennisHeimbigner** [comment]
Then I will put back NC4_get/put_vara and NC4_get/put_vars

**Comment by edhartnett** [comment]
OK, you may wish to simply unwind the most recent PR that was merged, which included those changes.

Be advised that although I didn't enter tickets for it, I believe there were some additional issues in that version of the vars functions. Handling of zero counts did not work until I made some changes to the vars code. I suspect there are simply more and better tests for the vara code.

I will take down this PR while all this is resolved.

**Comment by edhartnett** [comment]
OK, Dennis and I have resolved the request for changes, and this PR is ready to merge.

**Comment by WardF** [comment]
@DennisHeimbigner can you remove your request for changes? Thanks!

**Pull request merged**
