### PR TITLE
Make public a limited API for programmatic access to internal .rc tables

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: https://github.com/Unidata/netcdf-c/issues/2337
re: https://github.com/Unidata/netcdf-c/issues/2407

Add two functions to netcdf.h to allow programs to get/set
selected entries into the internal .rc tables. This should fix
the above issues by allowing HTTP.CAINFO to be set to the
certificates directory.  Note that the changes should be
performed as early as possible in the program because some of
the .rc table entries may get cached internally and changing the
entry after that caching occurs may have no effect.

The new signatures are as follows:

1. Get the value of a simple .rc entry of the form "key=value".
Note that caller must free the returned value, which might be NULL.
````
char* nc_rc_get(char* const * key);

@param key table entry key
@return value if .rc table has entry of the form key=value
@return NULL if no such entry is found.
````

2. Insert/Overwrite the specified key=value pair in the .rc table.
````
int nc_rc_set(const char* key, const char* value);

@param key table entry key -- may not be NULL
@param value table entry value -- may not be NULL
@return NC_NOERR if no error
@return NC_EINVAL if error
````

Addendum:

re: https://github.com/Unidata/netcdf-c/issues/2407

Modify dhttp.c to use the .rc entry HTTP.CAINFO if defined.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
I am wondering if `"HTTP.CAINFO"` should not be `"HTTP.SSL.CAINFO"`in `dhttp.c` ?

With this change:
```diff
diff --git a/libdispatch/dhttp.c b/libdispatch/dhttp.c
index 6b707969..72988516 100644
--- a/libdispatch/dhttp.c
+++ b/libdispatch/dhttp.c
@@ -492,9 +492,9 @@ setupconn(NC_HTTP_STATE* state, const char* objecturl)
 	ncuriparse(objecturl,&uri);
 	if(uri == NULL) goto fail;
 	hostport = NC_combinehostport(uri);
-	value = NC_rclookup("HTTP.CAINFO",hostport,NULL);
+	value = NC_rclookup("HTTP.SSL.CAINFO",hostport,NULL);
 	if(value == NULL)
-	    value = NC_rclookup("HTTP.CAINFO",NULL,NULL);
+	    value = NC_rclookup("HTTP.SSL.CAINFO",NULL,NULL);
 	if(value != NULL) {
 	    cstat = CURLERR(curl_easy_setopt(state->curl, CURLOPT_CAINFO, value));
 	    if (cstat != CURLE_OK) goto fail;
```

The first test passes (otherwise I have the same error as in the original issue #2407), but then I have the following HDF error:

```
 # ./test_byterange.sh 
*** Testing reading NetCDF-3 file with http
***Test remote classic file
***Test remote netcdf-4 file: non-s3
/workspace/srcdir/netcdf-c/ncdump/.libs/lt-ncdump: https://thredds-test.unidata.ucar.edu/thredds/fileServer/irma/metar/files/METAR_20170910_0000.nc#bytes&aws.profile=none: NetCDF: HDF error
test_http: -k flag mismatch: expected=netCDF-4 have=
```

**Comment by DennisHeimbigner** [comment]
Above commit should fix errors:
1. I accidentally used ncrc_initialize instead of nc_initialize.
2. Change HTTP.CAINFO to HTTP.SSL.CAINFO

**Comment by Alexander-Barth** [comment]
Thanks for the update. If I just place a `.ncrc` is the HOME directory, then the first byte range test fails:

```
sandbox:${WORKSPACE}/srcdir/netcdf-c/nc_test # ls $HOME/.ncrc
/root/.ncrc
sandbox:${WORKSPACE}/srcdir/netcdf-c/nc_test # cat $HOME/.ncrc
HTTP.SSL.CAINFO=/etc/ssl/certs/ca-certificates.crt
sandbox:${WORKSPACE}/srcdir/netcdf-c/nc_test # ./test_byterange.sh 

*** Testing reading NetCDF-3 file with http
***Test remote classic file
curlcode: (60)SSL peer certificate or SSH remote key was not OK : Cert verify failed: BADCERT_NOT_TRUSTED
/workspace/srcdir/netcdf-c/ncdump/.libs/lt-ncdump: https://thredds-test.unidata.ucar.edu/thredds/fileServer/pointData/cf_dsg/example/point.nc#mode=bytes&aws.profile=none: NetCDF: libcurl failure
test_http: -k flag mismatch: expected=classic have=
```

If I put the `.ncrc` file in the current work directory, the first test passes, but the second fails with the HDF error:

```
sandbox:${WORKSPACE}/srcdir/netcdf-c/nc_test # echo 'HTTP.SSL.CAINFO=/etc/ssl/certs/ca-certificates.crt' > .ncrc
sandbox:${WORKSPACE}/srcdir/netcdf-c/nc_test # ./test_byterange.sh 

*** Testing reading NetCDF-3 file with http
***Test remote classic file
***Test remote netcdf-4 file: non-s3
/workspace/srcdir/netcdf-c/ncdump/.libs/lt-ncdump: https://thredds-test.unidata.ucar.edu/thredds/fileServer/irma/metar/files/METAR_20170910_0000.nc#bytes&aws.profile=none: NetCDF: HDF error
test_http: -k flag mismatch: expected=netCDF-4 have=
```

While testing the new API from Julia, I no longer have a failed assertion, but I have still a SSL error (this time for OPENDAP over https):

```
julia> ENV["JULIA_DEBUG"] = "NCDatasets"; using NCDatasets; NCDataset("https://opendap.puertos.es/thredds/dodsC/tidegauge_alge/2022/06/MIR2Z_Algeciras_Alge_3541_202206_analysis_event.nc4")
[ Info: nc_rc_set: set HTTP.SSL.CAINFO to /etc/ssl/certs/ca-certificates.crt
┌ Debug: ncmode: 0
└ @ NCDatasets ~/.julia/dev/NCDatasets/src/dataset.jl:184
┌ Debug: nc_open https://opendap.puertos.es/thredds/dodsC/tidegauge_alge/2022/06/MIR2Z_Algeciras_Alge_3541_202206_analysis_event.nc4 with mode 0
└ @ NCDatasets ~/.julia/dev/NCDatasets/src/netcdf_c.jl:264
Error:curl error: SSL peer certificate or SSH remote key was not OK
curl error details: 
Warning:oc_open: Could not read url
ERROR: NetCDF error: Opening path https://opendap.puertos.es/thredds/dodsC/tidegauge_alge/2022/06/MIR2Z_Algeciras_Alge_3541_202206_analysis_event.nc4: NetCDF: I/O failure (NetCDF error code: -68)
Stacktrace:
 [1] nc_open(path::String, mode::UInt16)
```

As far as I can tell, the certificate should be valid (at least the command line curl does not complain):

```
$ curl https://opendap.puertos.es/thredds/dodsC/tidegauge_alge/2022/06/MIR2Z_Algeciras_Alge_3541_202206_analysis_event.nc4.das > tmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7661    0  7661    0     0  34822      0 --:--:-- --:--:-- --:--:-- 34665
```

When I run this C program (similar to the Julia code above) within the build environment:

```c
#include <stdlib.h>
#include <stdio.h>
#include <netcdf.h>

#define ERRCODE 2
#define ERR(e) {printf("Error: %s\n", nc_strerror(e)); exit(ERRCODE);}

int main()
{
   int ncid, varid;
   int retval;

   if ((retval = nc_rc_set("HTTP.SSL.CAINFO","/etc/ssl/certs/ca-certificates.crt")))
      ERR(retval);

   if ((retval = nc_open("https://opendap.puertos.es/thredds/dodsC/tidegauge_alge/2022/06/MIR2Z_Algeciras_Alge_3541_202206_analysis_event.nc4", NC_NOWRITE, &ncid)))
      ERR(retval);

   printf("*** SUCCESS opening URL!\n");
   return 0;
}
```

I also get the same error:

```
sandbox:${WORKSPACE}/srcdir/netcdf-c # gcc -o test_ncrc test_ncrc.c $(nc-config --cflags --libs) && ./test_ncrc
Error:curl error: SSL peer certificate or SSH remote key was not OK
curl error details:
Warning:oc_open: Could not read url
Error: NetCDF: I/O failure

# ls -l /etc/ssl/certs/ca-certificates.crt
-r--r--r--    1 root     root        203223 May  3 11:15 /etc/ssl/certs/ca-certificates.crt
```

Maybe there is an issue how I use the new API?

**Review by WardF — APPROVED** [review]

**Comment by Alexander-Barth** [comment]
Sorry if this is confusing. This is now on ubuntu, using the julia build environment BinaryBuilder but with native compilation.

**Comment by DennisHeimbigner** [comment]
See https://github.com/Unidata/netcdf-c/pull/2416

**Pull request merged**
