### PR TITLE
add CMAKE_C_FLAGS_RELEASE in specify_static_crt_flag

### PR DESCRIPTION
**Pull request by Jin-Whu**
In CMakeLists.txt, add **CMAKE_C_FLAGS_RELEASE** in **specify_static_crt_flag**. So, when building **Release** using MSVC, the **CRT** flag is **MT**.

### CODE REVIEW

**Comment by WardF** [comment]
Looks good, if you sign the CLA we should be able to proceed with this, thanks!

**Comment by WardF** [comment]
Thanks! Would you mind signing the CLA so that we can merge this?

**Comment by Jin-Whu** [comment]
I am really sorry that I have singed the CLA just now.

**Comment by WardF** [comment]
Merging into 4.6.2 release branch and then `master`.

**Pull request merged**
