### PR TITLE
fixed documentation warnings in filters.md

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #2329.

Fix the last few doxygen warnings.

I believe once all my outstanding PRs on doxygen are merged, we will get a warning-free doxygen build, and can then turn on automatic warning checking in CI to prevent any more doxygen warnings from occurring.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
This is failing, but this PR contains only documentation changes, so I don't know what is happening...

```
The following tests FAILED:
	 75 - nczarr_test_run_specific_filters (Failed)
```

**Comment by edwardhartnett** [comment]
OK, I turned on set -x and everything worked. Let me turn it off and try again...

**Comment by edwardhartnett** [comment]
OK, this error is happening in a Cmake build in which ENABLE_HDF5 is OFF:

**Comment by edwardhartnett** [comment]
OK, I'm stumped.

**Comment by DennisHeimbigner** [comment]
I just ran cmake (3.22.2) on Unbuntu21 with flags (see below) and all tests passed.
As for the set -x, I was unclear, I need to have you put the set -x back,  run the tests
and send me the content of build/Testing/Temporary/LastTest.log

**Comment by edwardhartnett** [comment]
Well I am not encountering the problem on my machine, it was on the CI system, so if you look where it failed you can see what there is to see. When I put set -x in, it didn't fail...

**Comment by edwardhartnett** [comment]
https://github.com/Unidata/netcdf-c/runs/6686454267?check_suite_focus=true

**Comment by DennisHeimbigner** [comment]
This failure is very odd. Looking at the actions log, the failure appears to be this line:
> 75: find: /Users/runner/work/netcdf-c/netcdf-c/build/plugins/save: No such file or directory

But the use of the save file was moved to tst_unknown.sh (aka run_unknown.sh).
It no longer occurs in tst_specific_filters.sh/run_specifice_filters.sh.
Could there be a problem with caching under actions?

**Comment by edwardhartnett** [comment]
Maybe...

**Pull request merged**
