### PR TITLE
Alias stringlength url parameter and maxstrlen

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: esupport AVS-567793

Some parameters like stringlength actually affect a dimension
named maxStrlen.  So, add some aliasing so maxstrlen can be
specified as a parameter and as an alias for stringlength.

The affected parameters (case insensitive):
stringlength has alias maxstrlen
stringlength_<varname> has alias maxstrlen_<varname>

Also:
1. added a test case in ncdap_test/testurl.sh
2. added note to documentation

### CODE REVIEW

**Comment by WardF** [comment]
Still need to diagnose the issue, but I am seeing a *lot* of coredumps when I try to run tests on this branch.  I'd suggest it's relatively low priority to get this in, but this is why it's currently languishing.  I'll see if I can get a cdash output submitted and, if so, will post a link to the verbose results.

**Comment by WardF** [comment]
Output is here: http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=2491

It is not particularly useful; the failures stem from failed `diff` comparisons.  The underlying cause for the `diff` failure is a core dump/crash when the underlying script invokes one of the utilities (I haven't tracked it down yet, just trying to get this info written down).

**Comment by DennisHeimbigner** [comment]
Last travis output seems to indicate a memory allocation error.

**Comment by DennisHeimbigner** [comment]
There was some kind of duplicated code problem that was causing all sorts of
problems. Anyway, sorted it out and merged master.

**Comment by WardF** [comment]
Excellent, thanks Dennis!

**Pull request merged**
