### PR TITLE
Now setting deflate_level of 0 is interpreted to mean no deflate.

### LINKED ISSUE #2155: setting deflate to zero is not the same as turning off deflate
Running a benchmark of different compression settings:

```
comp, level, nsd, shuffle, data wr rate (MB/s), file size (MB)
none, 0, 0, 0, 685.143, 7266.68
zlib, 0, 0, 0, 407.153, 7577.2
zlib, 1, 0, 0, 105.689, 2006.82
zlib, 2, 0, 0, 75.5917, 2333.75
zlib, 3, 0, 0, 51.7839, 2311.46
zlib, 4, 0, 0, 58.6335, 1849.85
zlib, 5, 0, 0, 39.4662, 1849.58

```

Note that the first line, with compression "none" means that nc_def_var_deflate() is not called for the variable.

The second line, with compression "zlib", level 0, calls nc_def_var_deflate() with a level of zero. Note that the output file is actually larger, and the write rate is 407 instead of 685, as it is when no compression is used.

These times are consistently showing up for me. Compression with level 0 is obviously not the same as no compression.

The problem is, Fortran programmers are just assuming 0 turns off zlib compression. But it does not seem to.

It should.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #2155 

Now setting deflate_level of 0 is interpreted to mean no deflate.

Also added a benchmarking programming that helped me figure this problem out...

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
This should have caused nc_test4/tst_vars.c to fail. But it apparently does not.

**Comment by edwardhartnett** [comment]
@DennisHeimbigner what did you expect to fail in tst_vars.c?

**Comment by DennisHeimbigner** [comment]
The version of nc_test4/tst_vars.c I have at line about 907 has this loop:

    for (i = 0; i < NVARS5; i++)
    deflate_level[i] = i;

Note that the deflate level of 0 is being used and later tested at line 937.

**Comment by edwardhartnett** [comment]
The reason this does not fail is that setting it to 0 is the same as not setting it, and when you do a nc_inq_var_deflate(), and deflate is not turned on, it will return a deflate level of 0. ;-)

BUT, when testing with zlib-ng, this test fails (with my recent change). I am investigating.

I will add some more test code to this PR...

**Comment by DennisHeimbigner** [comment]
Refresh my memory. What is the use case for removing deflate from a variable
after it has already been added?

**Comment by edwardhartnett** [comment]
There is not a good use case for removing deflation after it is already added.

But what often happens is that Fortran programmers, in an effort to run without compression, will set the deflate_level to 0 and recompile. So their code will create a new file, and they don't want compression, so the deflate_level will be 0.

In F90 this works. In F77 and C it doesn't. But it might as well...

**Comment by WardF** [comment]
Working through that backlog, happy new year!

**Pull request merged**
