### PR TITLE
Adds fuzz target for oss-fuzz integration

### PR DESCRIPTION
**Pull request by catenacyber**
@WardF would you agree to merge this fuzz target upstream ?
cf https://github.com/google/oss-fuzz/pull/5389#discussion_r604596718

### CODE REVIEW

**Comment by catenacyber** [comment]
Dennis, this adds a fuzz target to test netcdf, especially `nc_open_mem`
It will allow integration with oss-fuzz cf https://github.com/google/oss-fuzz/pull/5389 and https://google.github.io/oss-fuzz/
It gets compiled if `LIB_FUZZING_ENGINE` environment variable is defined
For instance LIB_FUZZING_ENGINE=-fsanitize=fuzzer with clang
Is that clearer ?

**Comment by DennisHeimbigner** [comment]
ok, but I have a couple of other questions/comments:

1. This is a reference to an environment variable I assume: $ENV{LIB_FUZZING_ENGINE}. Can we instead do this as a cmake option flag?
2. Is this CMake only? Should we be adding this to Automake as well?

**Comment by DennisHeimbigner** [comment]
I was thinking more about having a FINDFUZZ package for cmake.
As for Automake, we tend to use that much more than cmake for our
testing. But I can certainly use the CMAke fixes to add it to automake.

Also, is this clang/llvm specific? We use gcc as a rule.

**Comment by catenacyber** [comment]
> having a FINDFUZZ package for cmake

I do not know that much about cmake...
Could you point me to some example ?

> As for Automake, we tend to use that much more than cmake for our
testing.

I can also make it for automake instead of cmake...

> Also, is this clang/llvm specific? We use gcc as a rule.

I think you can compile with gcc.
But if you want to have libfuzzer as a fuzzing engine, you need to compile it into a static library first

**Comment by catenacyber** [comment]
Friendly ping @DennisHeimbigner 
What is the status for this ?
Do I need to do something ?

**Pull request merged**
