### PR TITLE
Merge 4.7.4 wellspring back upstream.

### PR DESCRIPTION
**Pull request by WardF**
Merging a subset of the file changes from 4.7.4 preparation back upstream.

### CODE REVIEW

**Comment by BtbN** [comment]
Was the soname bump done by this intentional?
It struck me as quite odd how a micro-versio-bump caused a soname bump, making it very hard to backport this version and some of its important bug-fixes.

I can't seem to see any ABI break from 4.7.3 to 4.7.4?

**Comment by opoplawski** [comment]
While I agree that ideally soname bumps should be accompanied by a similar semantic versioning bump (e.g. 4.7.3 -> 4.8.0), there were indeed ABI breaks:
```
SONAME changed from 'libnetcdf.so.15' to 'libnetcdf.so.18'

6 Removed function symbols:

  NC_filterfix8
  NC_inq_var_all
  nc4_filter_action
  nc_filter_inq
  nc_filter_register
  nc_filter_unregister
```

**Comment by DennisHeimbigner** [comment]
I think I have a different notion of what is an ABI break.
For me the ABI is defined by the files:
include/netcdf.h
include/netcdf_filter.h
include/netcdf_mem.h
include/netcdf_par.h
include/netcdf_dispatch.h
include/netcdf_aux.h

It is true, that changes to other files might change the semantics of some of
the above files. But that has to be determined on a case by case basis
and I doubt that any tool could discover those effects.
Perhaps we need a more formal method of indicating when changes
not visible in those files affect their semantics.

**Comment by BtbN** [comment]
The ABI generally refers to the symbols of the libraries, not headers files.
So if the symbols that have been removed were not part of the public API, they should have probably never been exported in the first place.

The Debian packaging tools certainly have discovered that symbols went missing and thus refuse to build the package.

An ABI break occurs when running an already compiled program against the newer version of a lib will potentially cause errors. This mandates a soversion bump.
An API break occurs when compiling code against a newer version of the lib will cause errors.

The two are generally fully independent of one another, since API can be changed with measures in place to keep the ABI intact (see glibc for example).
And obviously you can also change the ABI without changing the API, by turning a function into an inline header-only one, or even a macro for example.

**Comment by DennisHeimbigner** [comment]
As you will recall, it is impossible to build a multi-file C library without
making symbols visible that are for internal use only. Not much we can do about it.
But I must be missing something. You say
> An ABI break occurs when running an already compiled program against the newer > version of a lib will potentially cause errors.
My assumption has been that this is impossible unless the API itself changes
or the semantics change. Is it the latter you are referring to?

**Comment by BtbN** [comment]
It absolutely is possible to break the ABI while keeping the API intact.
Just think what happens if you turn a function that was formally a regular function with an exported symbol into a macro that calls some other function instead.
The API would still be unchanged, all code will compile normally. But already compiled binaries will be missing their symbol.


But in either case, if only private symbol were removed from the library, why was the soversion bumped?

And also, it's absolutely possible to not export private symbols, all compilers have measures for that. Windows/MSVC has its dllexport/dllimport and GCC/LLVM have __attribute__((visibility ("hidden"))) you can put on symbols you don't want to export from the DSO but still share between separate files.
Granted, it's a bit annoying to deal with the inconsistencies, but it's far from impossible.

**Comment by DennisHeimbigner** [comment]
I see the macro example (and we have done that).
But hiding internal symbols makes it essentially
impossible to do unit testing. Which is why we do not
run our unit tests under visual studio.

**Comment by edwardhartnett** [comment]
Most of our tests are not unit tests, and only use the public APIs, refraining from calling internal code.

But could we make a function like NC4_def_var() private? Would that work?

**Comment by BtbN** [comment]
On gcc or related tools, yes. On Windows, it being private is the default even, unless explicitly dllexported.
Just put an `__attribute__((visibility ("hidden")))` on it, and it should vanish from the library, while not breaking any code that's part of the library using the symbol.

**Comment by DennisHeimbigner** [comment]
I should note that there are some 1500 such functions (did a rough count
using nm libnetcdf.a).

**Comment by edwardhartnett** [comment]
Well @DennisHeimbigner what are we here for if not to program. ;-)

Of perhaps greater concern is the fact that this would only work with GNU C? Many netCDF users use intel compilers, and there are other compilers as well, so anything done would have to account for that.

What I think would end up happening is another macro like EXTERNL. (Shall we call it INTERNL as a working name?). Here's EXTERNL:

```
/* Declaration modifiers for DLL support (MSC et al) */
#if defined(DLL_NETCDF) /* define when library is a DLL */
#  if defined(DLL_EXPORT) /* define when building the library */
#   define MSC_EXTRA __declspec(dllexport)
#  else
#   define MSC_EXTRA __declspec(dllimport)
#  endif
#  include <io.h>
#else
#define MSC_EXTRA  /**< Needed for DLL build. */
#endif  /* defined(DLL_NETCDF) */

#define EXTERNL MSC_EXTRA extern /**< Needed for DLL build. */

```

So an INTERNL macro would be defined and then applied in all the .h files. That doesn't actually sound that hard, even though there's a lot of functions. With emacs, this could be done in 15 minutes with macros.

The questions are:
* What does the INTERNL macro look like?
* Is this worth doing at all?

**Comment by edwardhartnett** [comment]
Also, it seems like to get the windows build to work, we often have to insert EXTERNL in front of its prototype. So would this work with the windows build?

**Comment by BtbN** [comment]
All relevant compilers like icc, gcc and clang derivates should support the -fvisibility=hidden option, which by default hides all symbols requiring you to explicitly mark the ones you want to export.
This is equivalent to how Windows behaves by default, so no new macro might be needed, just a different value for the EXTERNL one for non-msvc.

**Comment by DennisHeimbigner** [comment]
> -fvisibility=hidden 
That is useful to know. Thanks for pointing it out.

**Comment by DennisHeimbigner** [comment]
I am trying to figure out this would all work with unit testing -- BTW
currently there are a number of unit tests hiding in the dap code and elsewhere
that have not yet been moved to the unit_test directory.

I think we would have to have a special configure flag, --enable-unit-testing, say.
This would modify the prefix (EXTERNL or such) to export what is needed for
unit tests. This would be run under, travis, say, as a special case. But normally
would be set to --disable-unit-testing.

**Comment by edwardhartnett** [comment]
I already have a --disable-unit-testing flag, so unit testing can be turned off for test coverage analysis. (Which I want to do to find unused code blocks to be eliminated).

**Comment by DennisHeimbigner** [comment]
Ok, I would probably negate that flag so that disable was the norm. But otherwise,
that should do.

**Comment by dopplershift** [comment]
> My assumption has been that this is impossible unless the API itself changes
> or the semantics change. Is it the latter you are referring to?

Things that can break ABI without breaking API: 
* Symbol visibility
* Changing size/layout/member types of structures
* Changing global variable types

Basically, anything you need to recompile for things to work, but don't need to change code for that compile to succeed.

**Comment by WardF** [comment]
> While I agree that ideally soname bumps should be accompanied by a similar semantic versioning bump (e.g. 4.7.3 -> 4.8.0), there were indeed ABI breaks:
> 
> ```
> SONAME changed from 'libnetcdf.so.15' to 'libnetcdf.so.18'
> 
> 6 Removed function symbols:
> 
>   NC_filterfix8
>   NC_inq_var_all
>   nc4_filter_action
>   nc_filter_inq
>   nc_filter_register
>   nc_filter_unregister
> ```

A quick note about this, (I've only just seen this thread), we follow the rules outlined at https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html when updating the SO version.  As @opoplawski notes, there were some symbol removals, hence the change for the bump in 4.7.4.

**Pull request merged**
