### PR TITLE
renamed NC_HDF5_FILE_INFO to NC_FILE_INFO

### LINKED ISSUE #1024: Need to change NC_HDF5_FILE_INFO_T to NC_FILE_INFO_T
This is part of #856 but I wanted to call this out in its own issue since it will change so many files.

When we separate the libsrc4 internal data model from the HDF5 implementation, we will end up with a bunch of NC_* types for libsrc4, and a bunch of NC_HDF5_* types for libhdf5.

For example, we have NC_TYPE_INFO_T, which contains both the libsrc4 and libhdf5 fields. This will become NC_TYPE_INFO_T for the libsrc4 fields, and NC_HDF5_TYPE_INFO_T for the libhdf5 fields. (And the NC_HDF5_TYPE_INFO_T is available in NC_TYPE_INFO_T as a void pointer).

This works well with our current naming, except for NC_HDF5_FILE_INFO_T, which must become NC_FILE_INFO_T to match the rest of the nomenclature.

Since this affects so much code, I will do this change a stand-alone PR, after my current (and next) PR is merged, and before doing any further separation of libsrc4 and libhdf5 code.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #1024.
Part of #856.

To end up with consistent nomenclature, this PR changes NC_HDF5_FILE_INFO_T to NC_FILE_INFO_T.

No code changes, just the rename. Many files are touched.

### CODE REVIEW

**Comment by WardF** [comment]
Is there a reason you closed this? It was about to be merged.

**Comment by edhartnett** [comment]
Waiting for #1023 to be merged.

**Comment by edhartnett** [comment]
This is in line behind #1026...

**Comment by edhartnett** [comment]
OK, this PR is ready to merge.

**Comment by WardF** [comment]
Up next to merge when the tests complete.

**Pull request merged**
