### PR TITLE
better detection of corrupted HDF5 file headers

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re e-support (UBS-599337)
 Ncdump is aborting on reading damaged HDF5 file.
 The problem was that the file magic number test code
 in both nc4file.c and dfile.c are not testing the full
 hdf5 magic header. They only look for the "XHDF"
 where X is any character. The test should be for the full
 eight characters of "\211HDF\r\n032\n".

Also, to avoid inconsistency, I have removed the check code from=
nc4file.c and made it use NC_check_file_type in dfile.c

Also added a test case.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Further header changes:
The NC_check_file_type code does not do the forward search required by hdf5 files. It currently only
looks at file position 0 instead of 512, 1024, 2048,... Also, it turns out that the HDF4 magic number is
assumed to always be at the beginning of the file (unlike HDF5).
Change is localized to libdispatch/dfile.c
See https://support.hdfgroup.org/release4/doc/DSpec_html/DS.pdf
HatTip: cwardgar

**Comment by DennisHeimbigner** [comment]
Hold this pull request until 4.5 is released

**Comment by WardF** [comment]
Some conflicts, @DennisHeimbigner will resolve conflicts, merge into 4.5.0 release branch instead of `master`.

**Comment by WardF** [comment]
Working through the pull requests on the branch `pr-mass-merge`, I'm seeing an error with`ncdump/tst_hdf5_offset`.  Details here:

http://cdash.unidata.ucar.edu/testDetails.php?test=66314&build=3580

**Comment by WardF** [comment]
The travis.ci tests aren't catching this and I'm not sure why.  More work on my end to narrow down what's going on.  I've observed it on OSX and Linux so far.

**Comment by WardF** [comment]
Ok, somehow on my system, the file `L512.txt` contains the `-n` in addition to the appropriate number of spaces.  I have no idea why. I will sort this out.

**Comment by WardF** [comment]
Ok, changing the shell to `bash` from `sh` fixed this issue on my end.  Is there a reason not to use `bash` in these circumstances?

**Comment by DennisHeimbigner** [comment]
Bash is the right choice. Probably should check other .sh files to see if they
are using sh instead of bash.

**Comment by DennisHeimbigner** [comment]
Perhaps that test case should not try to construct the l64 file but rather
include it as an EXTRA_DIST. I suspect that would fix the problem.

**Comment by DennisHeimbigner** [comment]
Modified the offset test case so
that it used a pre-constructed
binary file rather than using echo
to create it on the fly. This should
ensure that there are no extraneous
newlines or such.

**Comment by WardF** [comment]
@DennisHeimbigner Did you still want to take a look at these conflicts?

**Comment by DennisHeimbigner** [comment]
yes.

**Comment by DennisHeimbigner** [comment]
ok, conflicts resolved; not sure why so many spurious modifications, but oh well.

**Comment by WardF** [comment]
This needs to be reopened and fixed, as it is causing issues with parallel tests, particularly when pnetcdf is enabled.  I've reverted the merge locally and will push to github shortly.

See #445 for more info.

**Comment by WardF** [comment]
Ok. Reverting this merge doesn't negate the merge. I think I see how to get back to where we're at so this branch (`magic.dmh`) can be fixed and re-merged. It needs to be rebased against v4.5.0-release-branch, perhaps? I think?

**Comment by WardF** [comment]
Ok.  I'm going to issue a new pull request since this one is closed, but I won't merge until we get these parallel failures sorted out.

**Pull request merged**
