### PR TITLE
file header padding

### PR DESCRIPTION
**Pull request by wkliao**
According to the Classic Format Specification, Header padding uses null (\x00) bytes.
```
padding      = <0, 1, 2, or 3 bytes to next 4-byte boundary>
                                  // Header padding uses null (\x00) bytes.  In
                                  // data, padding uses variable's fill value.
                                  // See "Note on padding", below, for a special
                                  // case.
```
This pull request helps netCDF library respect the above specification.

### CODE REVIEW

**Comment by wkliao** [comment]
This issue was found when I used PnetCDF to read files created by NetCDF and vice versa.
A test subroutine named `test_nc_against_pnetcdf()` was added to nc_test/util.c in my pull request #319 or branch https://github.com/wkliao/netcdf-c/commits/issue258

**Comment by WardF** [comment]
Thanks; the 4.4.1.1 release fixed a pretty serious bug, so I had to get that out before I could take a look at the other large pull request.  I'm focusing on that this week, in addition to my AGU poster; support as always remains a wildcard :).

**Comment by jedwards4b** [comment]
Hi,  I have just run into this bug - please consider incorporating this PR in your next release.  Thanks

**Comment by WardF** [comment]
This looks good, thanks! Waiting for #374 then will merge this in on the heels of that.

**Comment by WardF** [comment]
Getting caught up now that the big issues are taken care of.  Bumping this to 4.5.1, as I need to get 4.5 out ASAP.

**Comment by WardF** [comment]
Currently there is a conflict and what appears to be an orphaned `#else/#endif` stanza.  Will review outside the web interface.

**Comment by WardF** [comment]
It appears that this is merged, but was not automatically closed.  Closing now to reflect that status.

**Pull request closed without merging**
