### PR TITLE
Fixed a bunch of rename issues, including Charlie Zender's reported problem...

### LINKED ISSUE #727: Attempt to create NC_STRING var with fill value off causes HDF5 error
I have been adding some systematic tests for fill values in nc_test/tst_formats.c, in branch ejh_fill_values.

When trying to create an NC_STRING var with fill mode turned off I get this interesting error:

```
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5D.c line 145 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 490 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1695 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1939 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: H5Gtraverse.c line 867 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 639 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1742 in H5L_link_cb(): unable to create object
    major: Object header
    minor: Unable to initialize object
  #007: H5O.c line 3178 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: H5Doh.c line 291 in H5O__dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #009: H5Dint.c line 1256 in H5D__create(): can't update the metadata cache
    major: Dataset
    minor: Unable to initialize object
  #010: H5Dint.c line 864 in H5D__update_oh_info(): Dataset doesn't support VL datatype when fill value is not defined
    major: Dataset
    minor: Feature is unsupported
```

Looks like HDF5 is just not cool with turning off fill mode for NC_STRING.

### LINKED ISSUE #732: nc_inq_var_fill() doesn't work for NC_STRING if a fill value is set - segfault results
Studying the code coverage report, I noticed that there were no tests for nc_def_var_fill() for string type with a fill value set.

When I set up the test, I got a seg fault. Turns out there is a pointer dereference problem with the fill type of NC_STRING in nc4var.c.

There is a line of code like this:

```
               if (!(fill_valuep = calloc(1, sizeof(char *))))
                  return NC_ENOMEM;

```
But it should be:

```
               if (!(*(char **)fill_valuep = calloc(1, sizeof(char *))))
                  return NC_ENOMEM;
```

The malloced space needs to go where fill_valuep is pointing, not overwrite fill_valuep itself, which is a parameter of the function.

With the fix, the test works, and it is possible to set an NC_STRING fill value, and retrieve it with nc_inq_var_fill().

### LINKED ISSUE #736: CMake and Autotools builds broken when V2 API is disabled
Thanks @gsjaardema for bringing this to light. Greg submitted a fix in a PR, but it introduces a new header file which is not needed. config.h should have all the information needed to determine if V2 is built.

Here's the error:
```
nc_test4/CMakeFiles/nc_test4_tst_vars2.dir/build.make:62: recipe for target 'nc_test4/CMakeFiles/nc_test4_tst_vars2.dir/tst_vars2.c.o' failed
make[2]: *** [nc_test4/CMakeFiles/nc_test4_tst_vars2.dir/tst_vars2.c.o] Error 1
CMakeFiles/Makefile2:4131: recipe for target 'nc_test4/CMakeFiles/nc_test4_tst_vars2.dir/all' failed
make[1]: *** [nc_test4/CMakeFiles/nc_test4_tst_vars2.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
The autotools build fails like this:

```
tst_vars2.c: In function ‘main’:
tst_vars2.c:568:14: warning: implicit declaration of function ‘nccreate’; did you mean ‘nc_create’? [-Wimplicit-function-declaration]
       ncid = nccreate(FILE_NAME, NC_NETCDF4);
              ^~~~~~~~
              nc_create
tst_vars2.c:571:18: warning: implicit declaration of function ‘ncdimdef’; did you mean ‘nc_redef’? [-Wimplicit-function-declaration]
       dimid[0] = ncdimdef(ncid, LAT, LAT_LEN);
                  ^~~~~~~~
                  nc_redef
tst_vars2.c:571:33: error: ‘LAT’ undeclared (first use in this function)
       dimid[0] = ncdimdef(ncid, LAT, LAT_LEN);
                                 ^~~
tst_vars2.c:571:33: note: each undeclared identifier is reported only once for each function it appears in
tst_vars2.c:571:38: error: ‘LAT_LEN’ undeclared (first use in this function); did you mean ‘DIM1_LEN’?
       dimid[0] = ncdimdef(ncid, LAT, LAT_LEN);
                                      ^~~~~~~
                                      DIM1_LEN
tst_vars2.c:572:33: error: ‘LON’ undeclared (first use in this function)
       dimid[1] = ncdimdef(ncid, LON, LON_LEN);
                                 ^~~
tst_vars2.c:572:38: error: ‘LON_LEN’ undeclared (first use in this function); did you mean ‘LAT_LEN’?
       dimid[1] = ncdimdef(ncid, LON, LON_LEN);
                                      ^~~~~~~
                                      LAT_LEN
tst_vars2.c:575:15: warning: implicit declaration of function ‘ncvardef’; did you mean ‘nc_redef’? [-Wimplicit-function-declaration]
       varid = ncvardef(ncid, CXX_VAR_NAME, NC_FLOAT, VAR_DIMS2, dimid);
               ^~~~~~~~
               nc_redef
tst_vars2.c:578:7: warning: implicit declaration of function ‘ncclose’; did you mean ‘nc_close’? [-Wimplicit-function-declaration]
       ncclose(ncid);
       ^~~~~~~
       nc_close
tst_vars2.c:581:14: warning: implicit declaration of function ‘ncopen’; did you mean ‘nc_open’? [-Wimplicit-function-declaration]
       ncid = ncopen(FILE_NAME, 0);
              ^~~~~~
              nc_open
tst_vars2.c:582:7: warning: implicit declaration of function ‘ncinquire’; did you mean ‘nc_inq_var’? [-Wimplicit-function-declaration]
       ncinquire (ncid, &ndims, &nvars, &natts, &recdim);
       ^~~~~~~~~
       nc_inq_var
```

The config.h in both cases does include this:
```
/* do not build the netCDF version 2 API */
#define NO_NETCDF_2 1

```

The macro name is awkward, but it's a historical oddity, so we tolerate it, like the Roman-style robes we make graduates wear.

Greg also very thoughtfully submitted a fix (PR #656), but it unnecessarily introduces the netcdf_meta.h file, which is not needed and should not be used in tests.

I have fixed this on my current branch by using NO_NETCDF_2 where necessary in tst_vars2.c. I have also added some disable-v2 builds to my CI system to prevent it breaking again. ;-)

I will put my branch up for merge sometime next week.

### LINKED ISSUE #738: tst_put_vars.c and tst_elatefill.c are netCDF-4 only tests, and should be moved to nc_test4 from nc_test
These two tests are straight-up netCDF-4 tests. They were contributed by users who did not follow the convention of putting netCDF-4 only tests in nc_test4.

I will move them.

### LINKED ISSUE #741: Passing NULL as new name to NC4_rename_var() causes segfault
NC4_rename_var() neglects to check for null parameter. I will add...

### LINKED ISSUE #743: NC4_def_var() has some unnecessary HDF4 checks...
No need to check in the code for HDF4 stuff. HDF4 files will be errored out as EPERM at the top of the function.

### LINKED ISSUE #746: When dim renamed, optional attribute _Netcdf4Dimid is not deleted from original coord var
In tst_rename.c we have the following test code:
```
int
create_test_file(char *path, int format)
{
   int ncid, varid, var2id;
   int dims[VAR_RANK];

   if (nc_set_default_format(format, NULL)) ERR;
   if (nc_create(path, 0, &ncid)) ERR;
   if (nc_def_dim(ncid, LAT, DIM_LEN, &dims[0])) ERR;
   if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, dims, &varid)) ERR;
   if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, dims, &var2id)) ERR;
   if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
   if (nc_put_var_int(ncid, varid, lats)) ERR;
   if (nc_put_var_float(ncid, var2id, rh)) ERR;
   if (nc_close(ncid)) ERR;
   return 0;
}
```

and

```
         if (create_test_file(file_names[format], formats[format])) ERR;
         if (nc_open(file_names[format], NC_WRITE, &ncid)) ERR;
         if (nc_inq_dimid(ncid, LAT, &dimid)) ERR;
         if (nc_inq_varid(ncid, LAT, &varid)) ERR;
         if (nc_inq_varid(ncid, RH, &var2id)) ERR;
         if (check_file(ncid, LAT, RH, LAT)) ERR;
         if (nc_redef(ncid)) ERR;

         /* Rename the dim. */
         if (nc_rename_dim(ncid, dimid, TAL)) ERR;
         if (nc_close(ncid)) ERR;

```

This results in the following HDF5 file:

```
HDF5 "tst_rename_fix3.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 67;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.5.1-development|hdf5libversion=1.10.1"
      }
   }
   DATASET "lat" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): -90, 90
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 6160 /tal )
         }
      }
      ATTRIBUTE "_Netcdf4Dimid" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
   }
   DATASET "rh" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0.25, 0.75
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 6160 /tal )
         }
      }
   }
   DATASET "tal" {
      DATATYPE  H5T_IEEE_F32BE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0, 0
      }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
            STRSIZE 16;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "DIMENSION_SCALE"
         }
      }
      ATTRIBUTE "NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 64;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "This is a netCDF dimension but not a netCDF variable.         2"
         }
      }
      ATTRIBUTE "REFERENCE_LIST" {
         DATATYPE  H5T_COMPOUND {
            H5T_REFERENCE { H5T_STD_REF_OBJECT } "dataset";
            H5T_STD_I32LE "dimension";
         }
         DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
         DATA {
         (0): {
               DATASET 331 /lat ,
               0
            },
         (1): {
               DATASET 635 /rh ,
               0
            }
         }
      }
   }
}
}

```

Note that the _Netcdf4Dimid attribute is incorrectly attached to dataset "lat". This is incorrect. It should have been removed in the rename, when "lat" went from being a coordinate variable to just a regular variable.

### LINKED ISSUE #749: Renaming dim and var may change var order in file...
This code:

```
int
create_test_file(char *path, int format)
{
   int ncid, varid, var2id;
   int dims[VAR_RANK];

   if (nc_set_default_format(format, NULL)) ERR;
   if (nc_create(path, 0, &ncid)) ERR;
   if (nc_def_dim(ncid, LAT, DIM_LEN, &dims[0])) ERR;
   if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, dims, &varid)) ERR;
   if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, dims, &var2id)) ERR;
   if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
   if (nc_put_var_int(ncid, varid, lats)) ERR;
   if (nc_put_var_float(ncid, var2id, rh)) ERR;
   if (nc_close(ncid)) ERR;
   return 0;
}
```

and

```

      {
         int ncid, varid, var2id;
         int dimid;
         
         if (nc_set_default_format(formats[format], NULL)) ERR;
         if (nc_create(file_names[format], 0, &ncid)) ERR;
         if (nc_def_dim(ncid, LAT, DIM_LEN, &dimid)) ERR;
         if (nc_def_var(ncid, LAT, NC_INT, VAR_RANK, &dimid, &varid)) ERR;
         if (nc_def_var(ncid, RH, NC_FLOAT, VAR_RANK, &dimid, &var2id)) ERR;
         if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
         if (nc_redef(ncid)) ERR;    /* not necessary for netCDF-4 files */

         /* Now rename the dim. */
         if (nc_rename_dim(ncid, dimid, TAL)) ERR;
         if (nc_rename_var(ncid, varid, TAL)) ERR;
         if (nc_enddef(ncid)) ERR;    /* not necessary for netCDF-4 files */
         
         if (nc_put_var_int(ncid, varid, lats)) ERR;
         if (nc_put_var_float(ncid, var2id, rh)) ERR;
         if (nc_close(ncid)) ERR;

         /* Reopen and check. */
         if (nc_open(file_names[format], NC_WRITE, &ncid)) ERR;
         if (check_file(ncid, TAL, RH, TAL)) ERR;
         if (nc_close(ncid)) ERR;
      }

```
Produces this data file. 
```
netcdf tst_rename_fix3 {
dimensions:
	tal = 2 ;
variables:
	float rh(tal) ;
	int tal(tal) ;
data:

 rh = 0.25, 0.75 ;

 tal = -90, 90 ;
}
```

Note that the vars are out of order. What has happened is that the variable was re-created when renamed, and then shown in HDF5 create order. 

The h5dump of the file:

```
HDF5 "tst_rename_fix3.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 67;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.5.1-development|hdf5libversion=1.10.1"
      }
   }
   DATASET "rh" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): 0.25, 0.75
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 331 /tal )
         }
      }
   }
   DATASET "tal" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): -90, 90
      }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
            STRSIZE 16;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "DIMENSION_SCALE"
         }
      }
      ATTRIBUTE "NAME" {
         DATATYPE  H5T_STRING {
            STRSIZE 4;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "lat"
         }
      }
      ATTRIBUTE "REFERENCE_LIST" {
         DATATYPE  H5T_COMPOUND {
            H5T_REFERENCE { H5T_STD_REF_OBJECT } "dataset";
            H5T_STD_I32LE "dimension";
         }
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): {
               DATASET 635 /rh ,
               0
            }
         }
      }
      ATTRIBUTE "_Netcdf4Dimid" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
   }
}
}

```

### LINKED ISSUE #750: nc4_vararray_add() calls ignore return value...
The function nc4_vararray_add() in nc4var.c may return error codes. Yet these are ignored when the function is called:

```
 find .. -name '*.c'|xargs grep nc4_vararray_add
../libsrc4/nc4file.c:extern int nc4_vararray_add(NC_GRP_INFO_T *grp, NC_VAR_INFO_T *var);
../libsrc4/nc4file.c:   nc4_vararray_add(grp, var);
../libsrc4/nc4file.c:      nc4_vararray_add(grp, var);
../libsrc4/nc4var.c:nc4_vararray_add(NC_GRP_INFO_T *grp, NC_VAR_INFO_T *var)
../libsrc4/nc4var.c:   nc4_vararray_add(grp, var);
```

I will fix.

### LINKED ISSUE #757: include/rnd.h missing header guard
```
Missing header guard
Source root/include/rnd.h
1
/*



This header file should contain a header guard to prevent multiple inclusion (the macro _RNDUP is checked for, but is not defined).
2
 *      Copyright 1996, University Corporation for Atmospheric Research
3
 *      See netcdf/COPYRIGHT file for copying and redistribution conditions
```

(Same warning for some other files in ncdump: vardara.h, utils.h, nctime0.h, isnan.h, indent.h. I have fixed these as well.)

### LINKED ISSUE #758: ncdump.c alert in lgtm for missing parameter
I will fix on my current branch:

```
Source root/ncdump/ncdump.c
        return "netCDF-4 classic model";
    default:
        error("unrecognized file format: %d");

Format expects 1 arguments but given 0

```

### PR DESCRIPTION
**Pull request by edhartnett**
This PR is the result of additional testing for nc4var.c to increase code coverage in the tests.

It includes a fix for Charlie Zender's rename issue (#597), as well as another important rename issue.

It also include some less-critical fixes which prevent segfaults for strings and fill values.

Also much more testing and internal documentation. @WardF I suspect you might want to include this in 4.6.0 due to the fix for the rename issues. If so, I suggest you do the other PRs first and let me adjust this one against any merge issues as you proceed. Then when you are ready to merge it, there will be no conflicts.

Fixes #758.
Fixes #757.
Fixes #750.
Fixes #749.
Fixes #746.
Fixes #743.
Fixes #741.
Fixes #738.
Fixes #736.
Fixes #732.
Fixes #727.
Part of #702.
Part of #597.

### CODE REVIEW

**Comment by WardF** [comment]
This pull request fixes 1 alert - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-029dc38cbb4a10050bc0ff2d8c4f23eab8de5198)

**fixed alerts:**

* 1 for Missing header guard

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by WardF** [comment]
This pull request fixes 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-5187cc9b1c0c5c3812cbd25b9d039540da374320)

**fixed alerts:**

* 1 for Missing header guard
* 1 for Duplicate include guard
* 1 for Wrong number of arguments to formatting function

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by WardF** [comment]
This pull request fixes 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-cf6fe49caef9b3f924ef07e16318b2351ea6ad35)

**fixed alerts:**

* 1 for Missing header guard
* 1 for Duplicate include guard
* 1 for Wrong number of arguments to formatting function

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by WardF** [comment]
This pull request fixes 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-9ff0585ecf4e7783c0bb5ec9d1fcbc0a751f6bee)

**fixed alerts:**

* 1 for Missing header guard
* 1 for Duplicate include guard
* 1 for Wrong number of arguments to formatting function

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by DennisHeimbigner** [comment]
I think we need to hold off on this pr.
I think it causes major conflicts with my proposed
performance improvements branch (newhash.dmh).

**Comment by edhartnett** [comment]
@DennisHeimbigner do your merge first and I will adjust the PR...

**Comment by WardF** [comment]
I'll bump this back down to `4.6.0` when the issue between @DennisHeimbigner branch and this are resolved; I tagged it `future` to minimize the chances I'll accidentally merge it in the meantime. Thanks! :).

**Comment by DennisHeimbigner** [comment]
Ed- what is the git clone argument for the
NetCDF-World-Domination-Council
repository. I cannot locate it on github.

**Comment by edhartnett** [comment]
git@github.com:NetCDF-World-Domination-Council/netcdf-c.git

But you can also just wait.

This PR contains a lot of changes all over the code, because as I wandered
through the code, I made fixes, added tests, and added documentation. I
also took out lines of code that were unnecessary.

So probably the best approach is for Ward to go ahead and make his merges.
Then I will prepare a new PR with just the rename fixes, the
string/fillvalue fixes, and all the extra tests (and maybe the
documentation). This should not cause you much trouble.

Then after your merge, I can swing back around and get everything else that
is still outstanding in my PR.

**Comment by WardF** [comment]
@DennisHeimbigner @edhartnett Is your (Dennis) branch ready to be merged?

**Comment by DennisHeimbigner** [comment]
Apparently I do not have read access to that repo.

**Comment by edhartnett** [comment]
@DennisHeimbigner it is a public repo: 
https://github.com/NetCDF-World-Domination-Council/netcdf-c

You can't see the code from there?

**Comment by DennisHeimbigner** [comment]
I got it; it was a ssh key problem.

**Comment by WardF** [comment]
This pull request fixes 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-2e6fd1003d9651337fb7bbb57af0180f462923a1)

**fixed alerts:**

* 1 for Missing header guard
* 1 for Duplicate include guard
* 1 for Wrong number of arguments to formatting function

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by edhartnett** [comment]
I'm going to take this PR down and let you guys catch up a little bit.

When 4.6.0 is closer to release I will see if I can isolate some of my changes in a way that don't disrupt Dennis' work. I will keep an eye on the repo and jump back in sometime later this week or next week, when you have done some merges.

**Pull request closed without merging**
