### PR TITLE
changed/removed references to jetstream remotetest instance.

### PR DESCRIPTION
**Pull request by oxelson**
- Removed or replaced all remaining references to 149.165.169.123 remotetest server.  
- URLS updated to reference remotetest.unidata.ucar.edu.  
- A temporary redirect has been put into place to redirect 149.165.169.123:8080/* to corresponding remotetest host url.

### CODE REVIEW

**Comment by oxelson** [comment]
Travis check failed because the dap4 servlet is giving a 400 server response code with this error: specified root directory is not a directory: /usr/local/apache-tomcat-8.5.50-remotetest/webapps/d4ts/WEB-INF/testfiles 

Waiting for error in d4ts.war to be fixed.

**Comment by DennisHeimbigner** [comment]
You need to copy the d4ts.war from 149.165.169.123
to remotetest.unidata.ucar.edu

**Comment by oxelson** [comment]
Copied the d4td.war and thredds.war from 149.165.169.123 to remotetest.unidata.ucar.edu.
dap4_tests still failing.

**Comment by WardF** [comment]
Tagging @DennisHeimbigner for input.  Let me take a look as well.

**Comment by WardF** [comment]
This might be something in the travis setup, as I'm not seeing the same failure when running locally.  Let me look into it and follow up.

**Comment by WardF** [comment]
Just checked .travis.yml; no remote tests should be run in the first place, although when I run with remote tests from my laptop, there aren't any issues.  Let me see if I can figure out why this remote test is running.

**Comment by WardF** [comment]
My mistake; I see they're passing on travis for cmake-based builds, but failing for autoconf-based builds.   Taking a further look.

**Comment by WardF** [comment]
I see now that for whatever reason, that test was commented out in CMakeLists.txt. So, the failure is not autotools-only.

**Comment by DennisHeimbigner** [comment]
Ok. I see one problem. The _NCProperties attribute has a trailing nul
character and this is causing the XML parsing of the DMR to fail.

**Comment by WardF** [comment]
@oxelson if you have the chance, can you resolve the conflict and re-run the tests to see if we can move past this? Thanks :)

**Comment by oxelson** [comment]
@WardF looks like we're good to go!  Be aware that we need to be moving our code to be compliant with https.  (Let me know if I can provide any needed info or help in any way.)

Did you want to do the final Merge pull request?  :-)

**Comment by WardF** [comment]
Thanks!

**Pull request merged**
