### PR TITLE
Explicitly disallow variable length type compression

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: https://github.com/Unidata/netcdf-c/issues/2189

Compression of a variable whose type is variable length
fails for all current filters. This is because at some point,
the compression buffer will contain pointers to data instead
of the actual data. Compression of pointers of course is meaningless.

The PR changes the behavior of nc_def_var_filter so that it will
fail with error NC_EFILTER if an attempt is made to add a filter
to a variable whose type is variable-length.

A variable is variable-length if it is of type string or VLEN
or transitively (via a compound type) contains a string or VLEN.

Also added a test case for this.

## Misc Changes
1. Turn off a number of debugging statements

### CODE REVIEW

**Comment by WardF** [comment]
Thanks very  much, Dennis. The Release Notes conflict was introduced by me, I can fix that really quick and get this merged in. Thanks!

**Comment by sval-dev** [comment]
Just a note that this shows up as a regression of working code for us.

Previously working code which universally tries to enable zlib compression for the variables it creates was broken by the update.
See [Unidata/netcdf4-python#1205](https://github.com/Unidata/netcdf4-python/issues/1205) for more information.

As I mention in the ticket, I believe it would be preferable to keep previously working code working and make this a warning or otherwise not make this a hard error.

**Comment by DennisHeimbigner** [comment]
You do realize that compressing variable length data results in compressing
the pointers to that data and not the data itself. That means that the compressed
data is meaningless.

**Comment by sval-dev** [comment]
To be clear, are you saying that the data itself is (silently) corrupted if compression is enabled for variable length datasets?

My experience is that the data makes the write/read round-trip okay and reading the same variable results in the same data that was written even when (zlib) compression was enabled.

From python, using the netCDF4 module version 1.5.8 from PyPi with underlying netcdf-c library version 4.7.4 results in successful reads after writing the field, and h5ls shows the compression was applied:
```
$ h5ls -v /tmp/tmp.nc/tmp
Opened "/tmp/tmp.nc" with sec2 driver.
tmp                      Dataset {180/180}
    Attribute: DIMENSION_LIST {1}
        Type:      variable length of
                   object reference
    Location:  1:685
    Links:     1
    Chunks:    {180} 1440 bytes
    Storage:   1440 logical bytes, 264 allocated bytes, 545.45% utilization
    Filter-0:  shuffle-2 OPT {16}
    Filter-1:  deflate-1 OPT {5}
    Type:      variable-length null-terminated UTF-8 string
```

Reproducing python code that shows the round-trip is successful:
import netCDF4
num_blocks = 180
writer = netCDF4.Dataset("/tmp/tmp.nc", "w")
comp_kwds = dict(zlib=True, shuffle=True, complevel=5)
writer.createDimension('Block_Dim', num_blocks)
tmp = writer.createVariable("tmp", str, ('Block_Dim',), **comp_kwds)
for block_num in range(num_blocks):
    tmp[block_num] = 'x' * block_num
writer.close()
reader = netCDF4.Dataset("/tmp/tmp.nc")
assert tmp[10] == 'x' * 10

I can generate equiv. C code to show this is a regression if it helps.

**Comment by DennisHeimbigner** [comment]
I have moved this to a [discussion](https://github.com/Unidata/netcdf-c/discussions/2554). Please comment there.

**Pull request merged**
