### PR TITLE
check against NC_MAX_VAR_DIMS

### PR DESCRIPTION
**Pull request by wkliao**
The NetCDF does not seem to check the number of dimensions in nc_def_var against NC_MAX_VAR_DIMS. This PR adds such check and returns NC_EMAXDIMS. I cannot find the right error code. The closest is NC_EMAXDIMS. Maybe consider adding a new error code, like NC_EMAXVARDIMS?

A test program nc_test/tst_max_var_dims.c is added for this PR.

### CODE REVIEW

**Comment by WardF** [comment]
Soon? Possibly.  Got a lot going on here and, sadly, netCDF isn't the only project I'm on :).  Reviewing PR's now, we had a lot back up while preparing the 4.5.0 release.

**Comment by edhartnett** [comment]
But now I see that this PR conflicts with the spirit of #443.

**Comment by DennisHeimbigner** [comment]
I am not sure I understand what you mean by:
> But now I see that this PR conflicts with the spirit of #443.
That is discussing e.g. NC_MAX_DIMS, not NC_MAX_VAR_DIMS

**Comment by edhartnett** [comment]
Never mind, my mistake.

**Pull request merged**
