### PR TITLE
Add hash field to dim and var to facilitate fast name compare

### PR DESCRIPTION
**Pull request by gsjaardema**
In non-classic netcdf-4 models, it is allowable to have
    large numbers of dims and vars.  In many operations, the
    entire list of dims or vars is searched for a dim/var matching
    a specific name which results in *lots* of strncmp or strcmp
    calls.

    If we add a hash field to the var and dim structs similar to what
    has already been done for the netcdf-3 formats, then we can hash the
    name being searched for and numerically compare that value with
    the var/dim hash value.  If they match, then do a more expensive
    strncmp call to ensure that the names truly match.

### CODE REVIEW

**Comment by gsjaardema** [comment]
Again, I need to figure out the pull request better.  There aren't really 9 commits on this pull requst, there is only a single one -- 1a84a6a

**Comment by WardF** [comment]
This looks really interesting, and sounds like a great idea.  Let me consider it a bit to make sure I'm not missing something.  @DennisHeimbigner, what do you think? 

Don't worry about the pull request thing; they can be tricky.  Honestly, I'd rather have lots of smaller commits than one or two large commits, for a pretty basic reason.  In the event I have to use `git bisect` to track down when a bug was introduced, I *hate* it when the culprit is one commit containing lots and lots of changes.  In any event, the `Files changed` tab only shows the diff between the `master` branch and your code, so the number of commits between them become irrelevant :).

**Comment by gsjaardema** [comment]
We did something similar to the netcdf-3 dim/var several years ago.

**Comment by DennisHeimbigner** [comment]
2 thoughts.
1. this means that we need to be careful about using normalized uts-8 strings
2. in the face of e.g. large numbers of vars, we might be better off using a single centralized
    hashtable to replace the list search.

**Comment by gdsjaar** [comment]
Yes, the centralized hash table would be good.  I have a couple other pull-requests coming, but even those still have some overhead due to traversing the linked lists of vars and dims.   I thought about the hash table, but didn't do anything about it yet.

I think the normalized uts-8 strings is handled, but I may have missed some...

One of the other pull requests will be to use the var->dim field (that already exists) instead of the var->dimids field and then do linear searches of the dim list to find a matching dimid when we already know the dim (assuming the field is consistent).  This should be coming soon.

There is another pull request possible that would maintain the end of the linked lists so appending is quick instead of traversing the entire list each time need to add a new var/dim/attribute.  That one needs some work due to removals from the list.  It works for what I need, but doesn't support all of what netcdf supports yet.

Again though the centralized hashtable would be GREAT.
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by WardF** [comment]
So, do we want to punt on this until we have a centralized hashtable, or do we want to merge this pull request until such time as we want to implement this as a centralized hashtable?

I'm ok pulling this in for now, since I'm not sure when we'd get the latter implemented, and it doesn't seem like it would be a big deal to replace this with that.  

On a side note, the travis-ci checks are going pretty slow, so I'm going to merge this pull request (unless I hear that we want to wait), and #230, into a side-branch where I can merge them in parallel, as well as the changes from `master`.  This will preserve the individual commits, but will let us test everything with a single travis-ci check.

**Comment by WardF** [comment]
These probably won't be addressed until Monday, but for the novelty of it, here's an API/ABI compatibility report (generated via Docker using `unidata/ncabi`) for the development branch vs. development branch + #229 and #230.

*  [compat_report.html.zip](https://github.com/Unidata/netcdf-c/files/159477/compat_report.html.zip)

**Comment by DennisHeimbigner** [comment]
I thought Russ did a hashtable implementation in libsrc. Can we steal that?
=Dennis

**Comment by gsjaardema** [comment]
There is a hashmap in libdispatch.  I'm not sure it is used anywhere though...

**Comment by DennisHeimbigner** [comment]
No, that is different. It would be in libsrc directory.

**Comment by gsjaardema** [comment]
There is the `hash_fast` in lookup3 which is what is used to generate the hash values for the variable and dimension names for both the code in this patch and for the similar capability in netcdf-3.

**Pull request merged**
