### PR TITLE
 whitespace changes only

### PR DESCRIPTION
**Pull request by edhartnett**
Some while ago Dennis asked that we go to a tab indent of 4 instead of 3. Well there's never a good time, but let's do that now. In this PR the code files in the libhdf5, libhdf4, and libsrc are re-indented, untabified, and delete-trailing-whitespaced.

No other code changes in this PR.

### CODE REVIEW

**Comment by gsjaardema** [comment]
Were the changes done using clang-format?  If so, would it be possible to add the clang-format settings file to the repository so other developers could then use it to make sure their patches or code contributions were formatted correctly.  If some other tool was used, if possible, it would be good to add some information on the wiki or README or somewhere to make it easier to format our patches.

**Comment by edhartnett** [comment]
Howdy Greg! I am just using emacs with these settings:
```
(setq c-default-style "linux"
      c-basic-offset 4)
(setq-default indent-tabs-mode nil)

```

**Comment by gsjaardema** [comment]
OK thanks.

**Comment by edhartnett** [comment]
Thanks!

**Pull request merged**
