### PR TITLE
whitespace changes only

### PR DESCRIPTION
**Pull request by edhartnett**
Testing whether travis works.

### CODE REVIEW

**Comment by edhartnett** [comment]
tst_remote.sh is failing in various builds. @WardF I can't get any PRs to pass Travis. ;-(

**Comment by DennisHeimbigner** [comment]
See if the remote test server is up by putting the url:
149.165.169.123:8080/dts
into your web browser.

**Comment by edwardhartnett** [comment]
Well I put that into my web browser and a page of links comes up. Is that what is supposed to happen?

However, the test is clearly not working reliably. Every travis run is failing on a different test from the time before. It's just sometimes tst_remote fails, and sometimes it succeeds. Probably it is timing out because all the tests are hitting it at the same time.

**Comment by DennisHeimbigner** [comment]
Yes, that page of links is what you should see.
Can you do two things?
1. put "set -x" into tst_remote.sh 
2. get travis to dump the test-suite.log file?

**Comment by WardF** [comment]
I'll take a look as well on the travis logs and see if I can sort out if it is an infrastructure issue.

**Comment by WardF** [comment]
It looks like an intermittent failure, I've restarted the two tests which failed.  Lets see what happens now.  I'll be reviewing PR's today and will go through all the automated testing and looking for one-offs.

**Comment by DennisHeimbigner** [comment]
When you say intermittent, do you mean that it is sometimes
failing to find the server, or are some specific datasets failing?

**Comment by WardF** [comment]
@DennisHeimbigner correct.  Restarting the 2 tests that failed resulted in successes.  I'll play whack-a-mole while we resolve this.

**Comment by WardF** [comment]
Closing instead of merging, but all checks have passed.

**Pull request closed without merging**
