### PR TITLE
Fix infinite loop in file inferencing

### LINKED ISSUE #2573: nc_create("file://foo.zarr#mode=nczarr,noxarray", 0, &ncid) consumes all memory
We are seeing this with netcdf 4.9.0 and current git main head on Fedora Rawhide.  The following is a simple reproducer:
```
#include <netcdf.h>

int main(int argc, char **argv) {
   int ncid;
   nc_create("file://foo.zarr#mode=nczarr,noxarray", 0, &ncid);
}
```
This is derived from a test in python-xarray - an issue was initially raised there: https://github.com/pydata/xarray/issues/6854

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes #2573 

re: Issue https://github.com/Unidata/netcdf-c/issues/2573

The file type inferencer in libdispatch/dinference.c has a simple forward inference mechanism so that the occurrence of certain mode values in a URL fragment implies inclusion of additional mode values. This kind of inference is notorious for leading to cycles if not careful. Unfortunately, this occurred in the one in dinference.c.

This was fixed by providing a more complicated, but more reliable inference mechanism.

## Misc. Other Changes
* Found and fixed a couple of memory leaks.
* There is a recent problem in building HDF4 support on github actions. Fixed by using the internal HDF4 xdr capability.
* Some filter-related code was not being properly ifdef'd with ENABLE_NCZARR_FILTERS.

### CODE REVIEW

**Review by WardF — APPROVED** [review]

**Comment by opoplawski** [comment]
I'm seeing some test failures with this patch applied to 4.1.4:
```
FAIL: run_purezarr.sh
=====================
findplugin.sh loaded
final HDF5_PLUGIN_DIR=/builddir/build/BUILD/netcdf-c-4.9.0/build/plugins/.libs
*** Test: pure zarr write then read; format=file
*** Test: xarray zarr write then read; format=file
*** Test: pure zarr reading nczarr; format=file
6c6
< 		v:_FillValue = -1 ;
---
> 		v:_FillValue = -1b ;
10,17c10,17
<   _, _, _, _, _, _, _, _,
<   _, _, _, _, _, _, _, _,
<   _, _, _, _, _, _, _, _,
<   _, _, _, _, _, _, _, _,
<   _, _, _, _, 0, 1, 2, 3,
<   _, _, _, _, 4, 5, 6, 7,
<   _, _, _, _, 8, 9, 10, 11,
<   _, _, _, _, 12, 13, 14, 15 ;
---
>   -1, -1, -1, -1, -1, -1, -1, -1,
>   -1, -1, -1, -1, -1, -1, -1, -1,
>   -1, -1, -1, -1, -1, -1, -1, -1,
>   -1, -1, -1, -1, -1, -1, -1, -1,
>   -1, -1, -1, -1, 0, 1, 2, 3,
>   -1, -1, -1, -1, 4, 5, 6, 7,
>   -1, -1, -1, -1, 8, 9, 10, 11,
>   -1, -1, -1, -1, 12, 13, 14, 15 ;
FAIL run_purezarr.sh (exit status: 1)
```
Are there additional patches I need to apply?

**Comment by DennisHeimbigner** [comment]
What underlying version of netcdf-c are you using, 4.9.0?

**Comment by opoplawski** [comment]
Sorry, yes - 4.9.0

**Comment by DennisHeimbigner** [comment]
The diff error you show is because there was a fix for handling fill values
in some other PR.
But I cannot find which one it was.

**Comment by opoplawski** [comment]
So, not quite sure what I should do here.  I'd like to release a patched version on 4.9.0 in Fedora ( assuming 4.9.1 with this fix is a ways off - is it?) but am worried that this test failure indicates that it may be breaking something else.

**Comment by DennisHeimbigner** [comment]
That "error" you is technically not an error since it is just showing the
fillvalue instead of "_". The problem was probably with ncdump.

**Comment by DennisHeimbigner** [comment]
A number of changes were made in 4.9.1 to fix JSON constant handling.
Among other things, this affected the type of _FillValue for certain tests.

So, to fix this in 4.9.0, do the following:
1. only use the following changed files from this PR:
    * dinfermodel.c
    * nclist.c
    * ncbytes.c
  2.  Edit nczarr_test/ref_quotes.cdl and change the following line:
````
		fractional_snow_cover:ID = 68b ;
to
		fractional_snow_cover:ID = 68 ;
````
 3.  Edit the file zsync.c and replace the function mininttype with the following:
````
static int
mininttype(unsigned long long u64, int negative)
{
    long long i64 = (long long)u64; /* keep bit pattern */
    if(!negative && u64 >= NC_MAX_INT64) return NC_UINT64;
    if(i64 < 0) {
	if(i64 >= NC_MIN_INT) return NC_INT;
	return NC_INT64;
    }
    if(i64 <= NC_MAX_INT) return NC_INT;
    if(i64 <= NC_MAX_UINT) return NC_UINT;
    return NC_INT64;
}
````
4. Edit the file dap4_test/Makefile.am and change this line:
````
TESTS += test_hyrax.sh test_thredds.sh
to
#TESTS += test_hyrax.sh test_thredds.sh
````
Note that this change is independent of the other changes.
It may not be needed unless the dap4_test/test_thredds.sh fails.

**Comment by opoplawski** [comment]
Thank you very much.  That seems to build fine and resolve the issue.

**Comment by WardF** [comment]
Merged into `v4.91-wellspring.wif` in preparation for the `v4.9.1` release.  It will be backported into `main` when the release is made.

**Pull request merged**
