### PR TITLE
non controversial parts of last PR

### LINKED ISSUE #1349: --with-chunk-cache-preemption handled twice in configure.ac
This appears twice in configure.ac. I will take one of them out my next PR.

```
# Did the user specify a default cache preemption?
AC_MSG_CHECKING([whether a default cache preemption for HDF5 was specified])
AC_ARG_WITH([chunk-cache-preemption],
              [AS_HELP_STRING([--with-chunk-cache-preemption=<float between 0 and 1 inclusive>],
                              [Specify default file chunk cache preemption policy for HDF5 files (a number between 0 and 1, inclusive).])],
            [CHUNK_CACHE_PREEMPTION=$with_chunk_cache_preemption], [CHUNK_CACHE_PREEMPTION=0.75])
AC_MSG_RESULT([$CHUNK_CACHE_PREEMPTION])
AC_DEFINE_UNQUOTED([CHUNK_CACHE_PREEMPTION], [$CHUNK_CACHE_PREEMPTION], [default file chunk cache preemption policy.])


```

### LINKED ISSUE #1355: Configure option --enable-extra-example-tests does nothing and can be removed
Similar to #634.

The option --enable-extra-example-tests used to do something, but not for a long time.

I will remove it to clean up the configure.ac file and avoid user confusion.

### LINKED ISSUE #1356: ncgen and ncdump tests have set -x enabled and are spewing a lot of output
When I work with master, ncgen and ncdump now seem to have set -x set:

```
make[3]: Leaving directory '/home/ed/tmp/n5/ncdump'
make  check-TESTS
make[3]: Entering directory '/home/ed/tmp/n5/ncdump'
make[4]: Entering directory '/home/ed/tmp/n5/ncdump'
begin ref_ctest.log
begin ref_ctest64.log
end ref_ctest.log
PASS: ref_ctest
end ref_ctest64.log
PASS: ref_ctest64
begin tst_null_byte_padding.log
begin tst_inttags.log
+ top_srcdir=/home/ed/tmp/n5
+ top_builddir=/home/ed/tmp/n5
+ test x. = x
+ pwd
+ builddir=/home/ed/tmp/n5/ncdump
+ execdir=/home/ed/tmp/n5/ncdump
+ basename .
+ thisdir=.
+ pwd
+ WD=/home/ed/tmp/n5/ncdump
+ cd .
+ pwd
+ srcdir=/home/ed/tmp/n5/ncdump
+ cd /home/ed/tmp/n5/ncdump
+ cd /home/ed/tmp/n5
+ pwd
+ top_srcdir=/home/ed/tmp/n5
+ cd /home/ed/tmp/n5/ncdump
+ cd /home/ed/tmp/n5/ncdump
+ pwd
+ builddir=/home/ed/tmp/n5/ncdump
+ cd /home/ed/tmp/n5/ncdump
...
```

### LINKED ISSUE #1357: We have parallel pnetcdf example, but we are running it sequentially
We have a parallel I/O example using pnetcdf, examples/C/parallel_vara.c. But we are only running it sequentially as can be seen from Makefile.am:

```
if USE_PNETCDF
# This is the pnetcdf example.
check_PROGRAMS += parallel_vara
TESTS += parallel_vara
endif #USE_PNETCDF

```

We need to add a shell script to run the test using mpiexec -n 4 in order to get parallel I/O.

### LINKED ISSUE #1358: nc_test4/run_bm_test1 and run_bm_test2 should not attempt to run without utils
These two benchmark tests require ncdump/ncgen but are still trying to run in builds with --disable-utilities.

I will fix in my current PR.

### PR DESCRIPTION
**Pull request by edhartnett**
Here's the non-controversial stuff from the last PR. ;-)

Fixes #1355.
Fixes #1349.
Fixes #1357.
Fixes #1358.
Fixes #1356.

Removed unused config option --enable-extra-example-tests. Also removed redundant option code for --with-chunk-cache-preemption.

Also added a run script to run the pnetcdf example code in parallel. Fix of some Makefile.am issues WRT building without utilities, Clean up of examples/C documentation. Also turned off verbose output of ncdump/ncgen shell script tests.

@WardF if you can point me to a file with a canonical copyright notice I will use it everywhere...

### CODE REVIEW

**Comment by edhartnett** [comment]
@WardF can we get this merged soon? I have the next batch ready to put up...

**Comment by WardF** [comment]
Thanks Ed, reviewing now for inclusion :)

**Comment by edhartnett** [comment]
@WardF can we get this merged soon? As you can see there is much more to do and I have the next PR up and ready.

**Comment by WardF** [comment]
Indeed. Let me review this and merge here shortly.

**Comment by edhartnett** [comment]
Thanks!

**Pull request merged**
