### PR TITLE
Fixed various UBSan warnings about working with NULL pointers

### PR DESCRIPTION
**Pull request by seanm**
Any pointer arithmetic with NULL pointers is technically UB, even if you don't end up dereferencing the pointer.

### CODE REVIEW

**Comment by seanm** [comment]
@DennisHeimbigner @WardF this is the last of https://github.com/Unidata/netcdf-c/pull/2692 split out.

I reformulated it to not use the ternary operator, as per your style.

**Review by DennisHeimbigner — COMMENTED** [review]
I am not sure what do to about this. utf8proc was taken from another site;
Unidata did not create the code. Perhaps we need to see if there is a later
version of utf8prop or find a better replacement.

**Comment by dopplershift** [comment]
Looks like utf8proc is [currently maintained by the Julia project](https://github.com/JuliaStrings/utf8proc). Not sure what it would take to update our internal copy, which looks like it's been manually namespaced with an `nc_` prefix.

**Comment by seanm** [comment]
>I am not sure what do to about this. utf8proc was taken from another site;

I'll split the utf8proc change out of this PR in order to not delay this PR.

Maybe the issue is already fixed upstream.  But we could still use my change in the short term, I think it's a quite conservative change.

**Comment by DennisHeimbigner** [comment]
I don't feel like replacing utf8proc, so fixing it seems like the right way to go.

**Comment by seanm** [comment]
> I don't feel like replacing utf8proc, so fixing it seems like the right way to go.

New PR just for utf8: https://github.com/Unidata/netcdf-c/pull/2803

**Comment by ethanrd** [comment]
@DennisHeimbigner - It looks like utf8proc was pulled into netCDF-C back in February 2017 which would have been Unicode 9. Unicode is currently at version 15.1. Most of the new major versions added thousands of new characters. So, seems like it might be worth looking at a full update to the latest utf8proc at some point.

**Review by WardF — APPROVED** [review]

**Pull request merged**
