### PR TITLE
Isolate code depending on v2 API

### PR DESCRIPTION
**Pull request by gsjaardema**
There are two code segments using the v2 API.  One was protected by `NO_NETCDF_2` ifdef, but that isn't defined in the CMake build.  Better to use the `NC_HAS_NC2` define which is in `netcdf_meta.h`

The second code segment was not protected by any ifdef.

### CODE REVIEW

**Comment by gsjaardema** [comment]
NOTE: Another fix would be to add the NO_NETCDF_2 define to the CMakeLists.txt file in this directory and change the `#if NC_HAS_NC2` to `#ifndef NO_NETCDF_2`.  Not sure which is preferred, but in either case, the second block of code using the V2 API does need to be protected.

**Comment by edhartnett** [comment]
config.h is the canonical location for information about what features of the build are turned on and off. It is already included in this test (as it must be) by nc_tests.h.

So I would strongly suggest that netcdf_meta.h not be included, and that the CMake build should be changed to also define NC_NETCDF_2, or else the configure.ac and config.h.in (and other C code) be changed to use NC_HAS_NC2 everywhere instead of NC_NETCDF_2.

But whatever is used, it should come from config.h.

**Comment by edhartnett** [comment]
This PR should not be merged and can be taken down.

I have applied the V2 fix using config.h on my current branch, currently up as PR #755.

**Comment by edhartnett** [comment]
@gsjaardema or @WardF can you please close this PR?

The fix for the V2 test code (using config.h) is part of the ejh_test_fills branch that I will be merging after the current PR backlog has been cleared. So this PR is no longer needed.

**Pull request closed without merging**
