### PR TITLE
Misc clang-tidy fixes, and added a .clang-tidy config file

### PR DESCRIPTION
**Pull request by seanm**
This fixes some clang-tidy warnings.

Some were fixed automatically by the tool.

Some were fixed manually by me after the tool warned about them.

I've added a clang-tidy config file that results in no warnings (because of my fixes and disabling of other warning options.)

### CODE REVIEW

**Comment by ZedThree** [comment]
It looks like the failing tests timed out -- might be the perennial remote test issues?

**Comment by WardF** [comment]
> It looks like the failing tests timed out -- might be the perennial remote test issues?

Quite possible; let me take a closer look :).

**Comment by WardF** [comment]
@DennisHeimbigner I am reviewing this but before I sign off on it, I notice a couple small changes to files in `libnczarr/`. I know you're working on a major refactor, do the changes in these files interfere?

**Review by DennisHeimbigner — APPROVED** [review]

**Comment by DennisHeimbigner** [comment]
> @DennisHeimbigner I am reviewing this but before I sign off on it, I notice a couple small changes to files in `libnczarr/`. I know you're working on a major refactor, do the changes in these files interfere?

They look benign to me. Go ahead.

**Comment by WardF** [comment]
> > @DennisHeimbigner I am reviewing this but before I sign off on it, I notice a couple small changes to files in `libnczarr/`. I know you're working on a major refactor, do the changes in these files interfere?
> 
> They look benign to me. Go ahead.

Thanks, @DennisHeimbigner !

**Review by WardF — APPROVED** [review]

**Pull request merged**
