### PR TITLE
Improve filter installation process to avoid use of an extra shell script

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
re: https://github.com/Unidata/netcdf-c/issues/2338
re: https://github.com/Unidata/netcdf-c/issues/2294

In issue https://github.com/Unidata/netcdf-c/issues/2338, Ed Hartnett suggested a better way to install filters to a user defined location -- for Automake, anyway.

This PR implements that suggestion. It turns out to be more
complicated than it appears, so there are fair number of changes;
mostly to shell scripts. Most of the change is in plugins/Makefile.am.

NOTE: this PR still does NOT address the use of HDF5_PLUGIN_PATH
as the default; this turns out to be complex when dealing with NCZarr.
So this will be addressed in a subsequent post 4.9.0 PR.

## Misc. Changes
1. Record the occurrences of incomplete codecs in libnczarr so that
   they can be included in _Codecs attribute correctly. This allows
   users to see what missing filters are referenced in the Zarr file.
   Primarily affects libnczarr/zfilter.[ch]. Also required creating a
   new no-effect filter: H5Zunknown.c.
2. Move the unknown filter test to a separate test file.
3. Incorporates PR https://github.com/Unidata/netcdf-c/pull/2343

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Does this instead the plugins so zstandard compression works?

If not, then that needs to be fixed before release. It's quite simple and there is no reason to release with non functional compression.

**Comment by edwardhartnett** [comment]
When I build and test this branch works OK, but when I do make install:

```
make[1]: Entering directory '/home/ed/nd/plugins'
make  install-am
make[2]: Entering directory '/home/ed/nd/plugins'
make[3]: Entering directory '/home/ed/nd/plugins'
make  install-exec-hook
make[4]: Entering directory '/home/ed/nd/plugins'
sh ./stdinstall.sh
sh: 0: Can't open ./stdinstall.sh
make[4]: *** [Makefile:1106: install-exec-hook] Error 127
make[4]: Leaving directory '/home/ed/nd/plugins'
make[3]: *** [Makefile:1008: install-exec-am] Error 2
make[3]: Leaving directory '/home/ed/nd/plugins'
make[2]: *** [Makefile:910: install-am] Error 2
make[2]: Leaving directory '/home/ed/nd/plugins'
make[1]: *** [Makefile:904: install] Error 2
make[1]: Leaving directory '/home/ed/nd/plugins'
make: *** [Makefile:754: install-recursive] Error 1
(base) ed@koko:~/nd$ 
```

**Comment by edwardhartnett** [comment]
I suggest that if zstandard compression is not going to work in the 4.9.0, that nc_def_var_zstandard()/nc_inq_var_zstandard() be removed from netcdf-c until they work. If users are going to need CCR to use zstandard, then having the functions in netcdf-c is pointless and confusing.

4.9.0 should not be released with broken zstandard compression. Either it should work out of the box, or not be included at all. Including broken zstandard compression for netcdf-4 will not help anyone and will simply cause confusion and dismay.

I am somewhat puzzled by this difficulty. CCR easily manages to installs plugins in the correct HDF5_PLUGIN_PATH directory. What is the trouble for netcdf-c?

**Comment by DennisHeimbigner** [comment]
I am confused; I thought I removed stdinstall.sh and I cannot find a reference to it
in any Makefile.am in this PR.

**Comment by edwardhartnett** [comment]
stdinstall.sh is mentioned twice in plugins/Makefile.am.

**Comment by edwardhartnett** [comment]
OK, sorry about the confusion. When I use the correct branch, make install and make distcheck work fine. ;-)

In order to install the plugins where HDF5 will find them, only one line needs to be added to configure.ac:

`with_plugin_dir=${HDF5_PLUGIN_PATH-'/usr/local/hdf5/lib/plugin'}
`
This needs to be added just before:

`AC_MSG_CHECKING([whether and where we should install plugins])`

This tells configure to install the plugins in the default plugin path, unless the user specifies a different location with the --with-plugin-dir option, or by having environment variable HDF5_PLUGIN_PATH set.

Once this PR is merged, I can do a PR adding this one line to configure.ac, and adding a test for the nc_def_var_zstandard()/nc_inq_var_zstandard() functions, which are currently untested.

**Comment by DennisHeimbigner** [comment]
I perceive this as more complex than your fix allows for.

If  the user sets HDF5_PLUGIN_PATH as an env variable, then the fix needs to parse that path to extract the first directory in that path to use.

If you default to /usr/local/hdf5/lib/plugin, and subsequently, the user runs with a different HDF5_PLUGIN_PATH, then I do not know if HDF5 searches the PATH and also /usr/local/hdf5/lib/plugin. I know that NCZarr does not do so at the moment. I am going to check on what HDF5 does.

You should not conflate the builder/installer with the user. You need to tell me what each is expected to know about filters. If they are the same, then presumably the user understands the role of HDF5_PLUGIN_PATH and can set --with-plugin-dir appropriately. If the user is different from the builder, then presumably the user was given some set of instructions *by the builder) about using HDF5_PLUGIN_PATH (or not using it).

My interpretation of your solution is the builder and user are required to use the same HDF5_PLUGIN_PATH or the default install location is used and the user never sets HDF5_PLUGIN_PATH. Is my intepretation correct? What is the norm at NOAA? Have you talked to any users about their knowledge of HDF5_PLUGIN_PATH?

**Comment by DennisHeimbigner** [comment]
I checked the HDF5 1.12.0 code. If HDF5_PLUGIN_PATH environment variable
is set, then it uses that exclusively. If it is not set, then it used /usr/local/lib/plugin
exclusively. So, both user and builder must set same HDF5_PLUGIN_PATH -- as a single directory -- 
or neither must set HDF5_PLUGIN_PATH.

**Comment by edwardhartnett** [comment]
I expect installers and builders to know nothing about filters. That's why it's important for the default to work.

If the builder knows enough about filters to be setting HDF5_PLUGIN_PATH, then they must also set it for the users. Once they start setting their own plugin path, obviously they are responsible for seeing that it works for the users of their system.

It's important to allow installers to override the default, but I suspect that very few will ever do so. That's why it's important that netcdf works out of the box without anyone explicitly setting any plugin path.

If we install to the default plugin directory the user can just use zstandard compression without knowing anything about filters.

**Comment by DennisHeimbigner** [comment]
Good points. This seems a little strong to me.
> I expect installers and builders to know nothing about filters. That's why it's important for the default to work.

Anyone else care to way in on this.

**Comment by edwardhartnett** [comment]
To answer your question about NOAA, we have installed CCR on many NOAA HPCs, always using the default directory. It works well. 

It's necessary for HDF5_PLUGIN_PATH to supercede the default as we use this in tests. (So we can test filter code before it is installed.) But, in general, I would be very surprised if any netcdf user or installer knows much about HDF5 plugins. Why would they?

It makes sense that, by default, we should use the HDF5 default. Otherwise there will be much confusion and support requests.

**Comment by DennisHeimbigner** [comment]
Via support questions, it is clear that e.g. IDL and R both tell uses
about filters and about how to set HDF5_PLUGIN_PATH.
Another issue is that of current workflows that  do their own filter installation
(essentially everyone who uses filters now). Presumably they would not be happy
about having to modify those workflows to add something like "--disable-plugin-dir".
But that would be the case if plugin installation is automatic. This is why I prefer
an explicit --with-plug-dir or equivalent.

**Comment by edwardhartnett** [comment]
I do not understand the objection to using the default plugin directory by default and allowing users to override it if they need to.

**Comment by DennisHeimbigner** [comment]
Now I am confused. Tell me again precisely what options and values the user can or must put
on the ./configure command

**Comment by DennisHeimbigner** [comment]
What I have at the moment is this:
1.  The builder specifies "./configure ... --with-plugin-dir=\<directory\>" or "./configure ... --with-plugin-dir" (i.e. with no argument).
2. In the no argument case, the default is the last directory in the list of directories specified by HDF5_PLUGIN_PATH.
3. If HDF5_PLUGIN_PATH is not defined, then it effectively defaults to /usr/local/hdf5/lib/plugin.
4. If --with-plugin-dir is not used, then filters are not installed.

The rationale is that this gives most of what Ed is suggesting, but still does not break existing workflows because of point 4.

**Comment by edwardhartnett** [comment]
I don't understand how any existing workflows can be broken by using the default plugin directory.

**Comment by DennisHeimbigner** [comment]
Suppose that you are a user who understands filters and HDF5_PLUGIN_PATH.
So you have already installed a set of filters for your use.
But if auto-install is in place, then suddenly, some of the filters you had already
set up get overwritten by our versions via auto-install.

For example, suppose they had installed a Blosc filter that supported more sub-filters than does
our Blosc filter. Suddenly, their workflows  stop working.

This is because  two filters having the same name does not mean they have exactly the same
semantics.

**Comment by edwardhartnett** [comment]
The problem of installing on top of existing libraries is a known problem with all installs. In the exact same way, if someone installs a newer version of libnetcdf.so on top of an old version, and the newer version was built with `--disable-dap`, then all existing netCDF applications that use dap will break. This is just part of the landscape of installing software, and is no different for plugins than for any other binary object. Users and sysadmins have to keep this in mind whenever installing new versions of any software. So this is not a reason not to install plugins in the default directory.

Furthermore, no proposed solution can solve this problem. Making the user specify the directory does not change the result in any way - if the user installs new versions of the plugins in their custom plugin directory, they have the exact same problems as if they were using the default plugin directory. 

Let's consider the installation workflows of interest, from most common to least common.

1 - Most common - used by NOAA everywhere, NCAR everywhere I've seen, and almost all new users:

`./configure --prefix=/some/install/point && make && sudo make install
`

This is the most important and common workflow, and we should ensure it continues to work. But it will not work for zstandard with this PR. Instead, filters will be turned off(?) That's not standard or the usual way I would expect software to work. Filters are a key feature that should be turned on by default. (Incidentally, if filters are off, does that mean zlib will also no longer work? That is certainly unacceptable.)

2 - Much less common - used by those who are knowledgeable about filters:

`
export HDF5_PLUGIN_PATH=/plugin/install/point
./configure --prefix=/some/install/point && make && sudo make install
`

This allows the users and sysadmins to set system-wide HDF5_PLUGIN_PATH for all users. In this case, our install should respect the HDF5_PLUGIN_PATH environment variable and install the plugins there. (I actually don't think parsing HDF5_PLUGIN_PATH is good. If it contains more than one directory, then how do we know which one to install plugins at? Users who want that level of complexity must resort to workflow 3 below, and take full responsibility for their non-default plugin choices.)

3 - Least common, used by those who know about filters, and have some special filter configurations they want to support - perhaps different HDF5_PLUGIN_PATH settings for different applications or versions:

`./configure --prefix=/some/install/point --with-plugin-dir=/plugin/install/point && make && sudo make install
`

This workflow gives the builder 100% control - plugins can be installed anywhere, and it is up to the installer and the user to understand what setting is needed for HDF5_PLUGIN_PATH. It seems like this would support all current users of filters with netcdf-c.

The number of users now using plugins, and installing them in non-default places, is tiny. The number of users using workflow 1 is massive - almost every user in fact. With your proposed solution, zstandard will not work for most users and they will have to either contact support, or figure out what to do and rebuild netcdf-c with the --with-plugin-dir option. This will lead to a lot of confusion. NOAA sysadmins will be able to handle this (because I will tell them about it), but users of NOAA's zstandard-compressed data will find files that they can't open until they reinstall netcdf-c, and put the fitters where they can be found by HDF5.

So I suggest we use the default plugin install location for workflow 1, and give all these poor users a working zstandard compression, right out of the box, without making them contact support to find out how to get it. ;-) 

Workflows 2 will work for users/builders with HDF5_PLUGIN_PATH set, and that's good.

Finally, workflow 3 will work for any user/builder who needs complete control of plugin location. It's fair that users with these needs will have to read the documentation and figure out what to do.

All of this has been worked out and well-tested with CCR for the past several years.

**Comment by DennisHeimbigner** [comment]
I just realized last night the real danger. You can have two HDF5 filters that use exactly the same compression library, but assume a different order for the parameters. Since the parameters are stored in the file, you can write the data using one wrapper and try to read the data later using a different assumed parameter order. This will fail and the user will have no idea why.

**Comment by edwardhartnett** [comment]
Ok but can we get the zeroth order case to work?

**Comment by DennisHeimbigner** [comment]
There is a difference between overwriting our own libraries (in /usr/local/lib, for example) with no warning and overwriting other peoples code with no warning. I think that there needs to be some kind of specific option that must be used so the builder has a chance to avoid the problem. Silent overwriting of other peoples code seems problematic.

**Comment by edwardhartnett** [comment]
Releasing a version that is broken for almost all users seems problematic to me.

**Comment by DennisHeimbigner** [comment]
"Broken" is a pretty strong word.

**Comment by jswhit** [comment]
Could netcdf-c install the plugins in a different default directory (say /usr/local/netcdf/lib/plugin) and then tell HDF5 to look in a different directory by default if HDF5_PLUGIN_PATH is not set?

**Comment by DennisHeimbigner** [comment]
In HDF5 version 1.13.x, it is possible to programmatically set the plugin path, so it could
be done with that version. In earlier versions, I do not think this is possible.

**Comment by edwardhartnett** [comment]
When installed with the most common workflow, zstandard won't succeed. Users will get an error when trying to use it.

Broken is a good word for that.

**Comment by jswhit** [comment]
> In HDF5 version 1.13.x, it is possible to programmatically set the plugin path, so it could be done with that version. In earlier versions, I do not think this is possible.

Could you use setenv to set HDF5_PLUGIN_PATH if it is not already set (for hdf5 < 1.13)?  I suppose this wouldn't work for windows though...

**Comment by DennisHeimbigner** [comment]
setting HDF5_PLUGIN_PATH is tricky because you have to ensure that it  is set before
the HDF5 library reads it. I think I saw an entry on stackoverflow about doing this,
but I cannot seem to find it now.

**Comment by DennisHeimbigner** [comment]
So be it.

**Comment by DennisHeimbigner** [comment]
Jeff;s comment got me to thinking. Since my concern is about overwriting other people's code,
it occurred to me that I can rename the plugin libraries to have special names that are unlikely
to be the same as already existing libraries. So overwrites will only overwrite code that came
from the netcdf build.
The remaining problem is to try to ensure that the HDF5 and Zarr dynamic loaders will
use the netcdf plugins last.
I need to experiment with this to see if it works.

**Comment by DennisHeimbigner** [comment]
Another possibility is this:
1. ALWAYS install the netcdf plugins in /user/local/hdf5/lib/plugins (the HDF5_PLUGIN_DIR default).
2. Assuming that the naive user does not set HDF5_PLUGIN_PATH, then that user will get our filters.
3.  A knowledgeable user will have set HDF5_PLUGIN_PATH  and has the option of doing this:
````export HDF5_PLUGIN_PATH="$HDF5_PLUGIN_PATH:/usr/local/hdf5/lib/plugins"````
if he wants to user our filters. Otherwise he continues to use his original HDF5_PLUGIN_PATH.

**Comment by DennisHeimbigner** [comment]
One other thing I don't understand: who installs libzstd -- the actual compressor library.
Presumably that is beyond the capability of Ed's postulated naive user.
If it is installed by some knowledgeable builder, then presumably that builder
will also install libnetcdf.

**Comment by edwardhartnett** [comment]
Zstandard library can be installed with package manager. So that's easy for everyone. Just like libz...

**Comment by WardF** [comment]
This issue is getting quite complicatedThis issue (or at least, the solution to it) is getting complicated, and I need to get caught up on the conversation.  A few key points that come to mind as I start reviewing this and the associated issues:

* We can't adopt a solution that involves potentially overwriting libraries already installed through a package manager or other process.  Replacing one library being used by other software packages, quietly or loudly, with a new version could be catastrophic in any sort of reproducable-science environment.  Similarly, although it's not our primary community, this could cause havoc in environments where versions are locked as part of a release process.

* Solutions need to work for Windows (MinGW/Filesystem), and Windows (Visual Studio), as well as Linux/MacOS/*nix systems.

* Adopting solutions that require functionality introduced in HDF5 `1.13.x` means we have to make HDF5 `1.13.x` the minimum required version, or turn off the assocated functionality.  Given how much of our community continues to stick with `1.8.x` due to the speed issues seen in `1.10.x+`, I am hesitant to make this leap. 

* The overhead of distributing our own versions of the plugins is significant; we already have to handle security bulletins for other incorporated software, I don't know that we will be able to keep pace if we keep adding things in that we are not maintaining from the ground up.  

Ideally, the solution will be to use pre-installed plugin libraries installed via a common package manager, similar to how we already handle szlib and zip (not a perfect analogy, but similar).  If zstandard is installed, we use it.  If it's not, we don't. But perhaps this won't be possible, or there is a way to accomplish what we're looking to do, that also hits all the marks above (and at least minimizes the final bullet).

**Comment by edwardhartnett** [comment]
CCR has been installing plugins for several years. There have been zero reported issues relating to plugin installation.

If you are not willing to install plugins in a place that will work, then perhaps remove zstandard support from netcdf.  It's pointless to have it in a way that will not work for most users. It will just cause confusion.

Users can install CCR. It works and has for two years now. And we have no hesitation about installing plugins. ;-)

At NOAA they are not willing to wait and are happy with using CCR. They have no particular concern about splitting the netcdf community, because that's not their problem.

So you guys need to decide whether you are willing to support plugins or not. Please make up your minds and take action accordingly.

**Comment by DennisHeimbigner** [comment]
Fair enough. We will make a decision about what to do.

**Comment by edwardhartnett** [comment]
@DennisHeimbigner a NOAA specific RPM is not needed. NOAA is using spack, which easily  builds netcdf and CCR. (And works well for all Unix machines and users.)

When CCR was first released there was some concern (and some hard words) from some Unidites about splintering the netcdf community and releasing files that not everyone can read. Hence my effort to support zstandard in netcdf directly, and my request to John Caron to step in and help with netcdf Java.

Are these concerns no longer valid? Are we now all OK with NOAA releasing netcdf files that cannot be read by most netcdf users?

I have delayed NOAA from adopting zstandard compression until it becomes part of netcdf-c. But supporting the wider netcdf community is not part of the NOAA mission, so that plays no part in their decision making. They have heeded my wishes because I solved their immediate I/O needs and they are currently meeting thier time budget. This will not last! Better compression is coming, whether or not Unidata wants it 

CCR can support these plugins, but its only advantage is greater moxie. Users will not benefit from Unidata reluctance in this area, because CCR has no special answers. CCR is merely more willing to grasp the nettle.

**Comment by dopplershift** [comment]
> Are these concerns no longer valid? Are we now all OK with NOAA releasing netcdf files that cannot be read by most netcdf users?

That is most definitely still a concern. That concern, however, doesn't override the concern about obliterating user files when installing netcdf-c from source.

Can we just take a breath for a minute while the netcdf-c team gives the challenges due consideration and avoids making a hasty and short-sighted decision that causes our users problems?

**Comment by DennisHeimbigner** [comment]
I made a major update to this PR (https://github.com/Unidata/netcdf-c/pull/2348/commits/6ae328970118ce8973176416d1680a74c5704962) with the following changes:

## Overwriting
I think I solved the file overwrite problem by doing light name
mangling of the shared library names. With this change the probability
is very small that installing our filter wrappers in a directory will
overwrite code produced by others.

## Default Install Location
I have setup the --with-plugin-dir option default to install in
the following locations in order of preference

1. If HDF5_PLUGIN_PATH is defined (at build time remember), then the last directory in that path will be where the filter wrapper shared libraries will be installed.
2. Otherwise the default is "/usr/local/hdf5/lib/plugin" (on \*nix\*) or "%ALLUSERSPROFILE%\\hdf5\\lib\\plugin" for Windows or Mingw.

Currently, --with-plugin-dir is disabled by default.
I should note that even if I enable it by default, installing
netcdf-c will still not run "out of the box" because the hypothetical
naive user will not know which compressor libraries need to be
pre-installed before netcdf is installed. Nor will that user have any
way to find out what needs to be installed, unless someone more 
knowledgeable tells them.

**Comment by jswhit** [comment]
I tested the recent updates on macosx with the python interface and it does indeed solve the file overwriting issue - thanks @DennisHeimbigner.  I would suggest enabling --with-plugin-dir by default though - since no external files will be clobbered I don't see any downside to having the plugins installed by default.

**Comment by DennisHeimbigner** [comment]
Thanks for the information.

**Comment by edwardhartnett** [comment]
Although there is more discussion to be had on what the defaults are, and although some additional testing of the install on various systems will be helpful, I believe this PR should be merged. Currently the main branch is not able to complete "make install" so this PR will be a big improvement.

Thanks @DennisHeimbigner for all the hard work bring filters and zstandard compression to netCDF users. NOAA certainly will be making good use of these features.

**Comment by DennisHeimbigner** [comment]
Now that I have apparently solved the code-overwrite problem. I no longer
care if the filter wrapper installation defaults to on or off. I know Ed's and Jeff's
opinion. Anyone else care to weigh in? Ward?

**Comment by WardF** [comment]
I am happy enough with it being turned on, as we don't have to worry about making unannounced, inadvertent changes to users' environments.  A small risk, but potentially big impacts if/when it happens.  I've tweaked the `distcheck` PR, and then will get this one merged in so that we can get 4.9.0 out and netCDF-Fortran 4.6.0 out the door.

**Comment by DennisHeimbigner** [comment]
Ok, give a couple of hours to turn it on by default and check it.

**Comment by WardF** [comment]
@DennisHeimbigner would it make sense to have the default plugin directory be a subdirectory of `--prefix`?  I ran the following on my machine:

    $ ./configure --prefix=$HOME/tmp

and had `make install` fail because it tried to install the plugin directory into `/usr/local`, which was not the behavior I had intuited.  I can make this change, but I wanted to see if there was a reason I was overlooking not to?

**Comment by edwardhartnett** [comment]
The default plugin directory should be /usr/local/hdf5/lib.

Users can change with --with-plugin-dir=

This is similar to the default prefix dir, which is /usr/local.

**Comment by WardF** [comment]
True, but presumably if the user is overriding the default with the prefix dir, they will expect to override the default installation location for all of the files installed by netCDF, not just some of them.  If that's not the behavior they want, they can specify two different locations with `--with-plugin-dir`.  Looking at the relevant automake/cmake files, this is an easy enough change to make, short of a compelling argument not to.

**Comment by WardF** [comment]
(Assuming that no extant `$HDF5_PLUGIN_PATH` environmental variable is found)

**Comment by edwardhartnett** [comment]
The compelling argument not to is that if the plugins are not installed in the place where HDF5 will find them, zstandard compression will not work.

So it makes sense to install the plugins in the default plugin directory, and make the user override this if desired (with --with-plugin-dir or HDF5_PLUGIN_PATH).

**Comment by DennisHeimbigner** [comment]
Ed is right about this. We unfortunately are constrained by the default (/usr/local/hdf5/lib/plugin)
used by libhdf5.

**Comment by WardF** [comment]
Yeah, I was just thinking about this as I ate lunch.  I'll get this merged, thanks @edwardhartnett and @DennisHeimbigner.  Congrats on your successful presentation at EGU, btw, @edwardhartnett !

**Comment by WardF** [comment]
So this looks great, but I'm seeing one last issue to take care of.  I'm seeing failures to compile if `libbz2.[suffix]` and the associated header files are not installed.  I see in the `configure.ac` file that we assume `libbz2` is available, without it being checked for explicitly.  @DennisHeimbigner is there any reason I can't go in and fencepost `libbz2` the same way we check for other compression libraries? Are there any tests that assume libbz2 functionality that will also need to be fenceposted?

Once I get this PR merged in, we should be good to get the release going.

**Comment by DennisHeimbigner** [comment]
That is odd. The situation WRT bzip2 is this. I need a relatively complex
filter for testing. In this case, I chose bzip2. This means that if the user 
did not have libbzip2 installed then I had copies of the source for libbzip2
in the plugin directory so I could build a local version for testing.
So, libbzip2 i effectively supposed to alway be available. Of course
with the local version, that source is compiled directly with H5Zbzip2.c.
So perhaps I forgot a check somewhere. Can you send me the complete
set of build options you are using?

**Comment by WardF** [comment]
Attached is a directory containing logs for a success and a failure.  These were run on a Ubuntu Linux VM, and the difference between the success and failure is whether or not I have the `libbz2-dev` package installed.  I am also seeing a different issue on my MacOS machine, but I need to reconcile why that is failing but the Github Actions CI is passing.  One thing at a time, however.

* [bz2_failure.zip](https://github.com/Unidata/netcdf-c/files/8782735/bz2_failure.zip)

**Comment by WardF** [comment]
To answer your question, I am setting `LDFLAGS` and `CFLAGS` to reflect the development environment; you can see those values in the `config.log` file.  `configure` is invoked very simply:

    $ ./configure

It is worth mentioning that these issues seem to be specific to `autoconf`-based builds; cmake works just fine even in the absence of `libbz2-dev`.

**Comment by DennisHeimbigner** [comment]
I cannot see a failure in build_failure.log; can you point me to it?

**Comment by edwardhartnett** [comment]
WRT testing, (if I understand what @DennisHeimbigner is doing) I think it would be perfectly acceptable to only run the tests if the bzip2 library is available, and then simply make it available on the test systems (i.e. in CI). So if it is not available, then just don't run those tests. This is similar to how many other tests work, for example the szip code is only tested if szip is present.

This means the testing setup has to be a little more careful, but keeps the build system simpler.

**Comment by WardF** [comment]
@DennisHeimbigner As is so often the case, the compilation symptom has disappeared today.  I'm still seeing an issue with `make check`, instead of `make`.  See the attached test-suite.log, which reflects a 'filter not available' error when `libbz2-dev` is not installed.  This issue goes away when I install the `libbz2-dev` package.

It feels like the easiest thing to do as is outlined above, as long as @edwardhartnett is correct and there's no subtle reason not to fencepost these tests around `libbz2` being found.  

Anyways, I've double-checked that the attached file actually reflects the error I'm observing in `nczarr_test/`
[test-suite.log.zip](https://github.com/Unidata/netcdf-c/files/8788426/test-suite.log.zip)

**Comment by DennisHeimbigner** [comment]
Well, until I can solve the problem, it is certainly ok to conditionalize the relevant test.
As near as I can tell, they are as follows:
# nc_test4
* tst_filter.sh tst_filter.sh tst_specific_filters.sh

# nczarr_test
* run_specific_filters.sh
* run_filter.sh

**Comment by DennisHeimbigner** [comment]
I looked at the test-suite log and was surprised to see those
seg faults. This is ubuntu correct?

**Comment by WardF** [comment]
@DennisHeimbigner correct, where the package `libbz2-dev` seems to be the deciding factor, when using `autotools`-based builds.  `CMake`-based builds work regardless of whether or not `libbz2-dev` is installed.

**Comment by DennisHeimbigner** [comment]
I believe I have fixed the problem. Turns out just changing the value of have_bz2
isn't enough to test the local bzip2 case. One needs to actually uninstall libbz2-dev.
Will add a commit to this PR after the tests complete.

**Comment by DennisHeimbigner** [comment]
Looks like the github actions queue is screwed up. Needs restarting.

**Comment by WardF** [comment]
`make distcheck` is failling now because it doesn't have access to the default plugin directory in `/usr/lib`.  I anticipate issues around that from users who regularly run `make distcheck`.  Taking a look at workaround.

**Comment by edwardhartnett** [comment]
@WardF set environment variable DISTCHECK_CONFIGURE_FLAGS to '--with-plugin-dir-/what/you/want' before running make distcheck.

**Comment by WardF** [comment]
@edwardhartnett yeah, I've found that fix, thanks :), I'm just thinking about the "default user experience" and how to minimize "Hey, make distcheck is failing" esupport questions. Thanks!

**Comment by DennisHeimbigner** [comment]
It should be the case that all checks will run even if no default plugin dir is specified.
So looks like I screwed that up.

**Comment by WardF** [comment]
@DennisHeimbigner I'm seeing the following at the end of `make distcheck`

````
make[3]: Entering directory '/home/wfisher/Desktop/gitprojects/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make[4]: Entering directory '/home/wfisher/Desktop/gitprojects/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make[4]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/hdf5/lib/plugin'
/usr/bin/mkdir: cannot create directory ‘/usr/local/hdf5’: Permission denied
make[4]: *** [Makefile:768: install-pluginLTLIBRARIES] Error 1
make[4]: Leaving directory '/home/wfisher/Desktop/gitprojects/netcdf-c/netcdf-c-4.8.2-development/_build/sub/plugins'
make[3]: *** [Makefile:1049: install-am] Error 2
````

**Comment by edwardhartnett** [comment]
I believe the DISTCHECK_CONFIGURE_FLAGS must be set for make distcheck to work in this case.

However, I doubt many users will be running make distcheck. Most will be running make install, so that is the one to make work by default.

**Comment by DennisHeimbigner** [comment]
OK, I see. We would need to do the distcheck under sudo for it to work.
I think it is easier to specifiy the DISTCHECK_FLAG "--without-plugin-dir"

**Comment by WardF** [comment]
@DennisHeimbigner As long as we can set that as part of the default `make check` without the user needing to, that should be fine.  I'll take a look.

**Comment by edwardhartnett** [comment]
Make check will not encounter this problem, it will only happen with the make install that distcheck does.

When the user does make install, he or she must be sudo to install in default location, but that is typically the case so not a problem.

If the user has no sudo powers he must set --prefix and --with-plugin-dir to directories he has write permissions.

**Comment by WardF** [comment]
Added `AM_DISTCHECK_CONFIGURE_FLAGS = --without-plugin-dir` to the top-level `Makefile.am` file in a forked copy of this branch. Everything else looks good, so I will merge this PR as part of an additional PR.  Thanks @DennisHeimbigner and @edwardhartnett !

**Pull request merged**
