### PR TITLE
upgrade CI to use HDF5-1.12.2, turn off remote tests in cmake CI build

### PR DESCRIPTION
**Pull request by edwardhartnett**
Upgrade the HDF5 version in the CI. Let's see how it does...

### CODE REVIEW

**Comment by edwardhartnett** [comment]
This is timing out in tst_remote3. I think that dap tests should be turned off in most of the CI runs.

**Comment by edwardhartnett** [comment]
I also turned off remote tests for the CMake build in the CI...

**Comment by DennisHeimbigner** [comment]
So I just tested this with 1.12.2 on Ubuntu Linux. I did not see
any dap test failures or hangs. What other ./configure options
did you use?

**Comment by edwardhartnett** [comment]
There are DAP timeouts when this is done from the CI, probably because there are so many different builds all trying to do remote tests.

So I have not found any remote test bugs here - just turning off remote tests so it does not overwhelm the CI system...

**Pull request closed without merging**
