### PR TITLE
Fix cmake s3 support.wif

### PR DESCRIPTION
**Pull request by WardF**
A small mistake in logic was resulting in Amazon S3 SDK libraries not being properly linked against, even if found on the system.  There are additional steps required for Windows (Visual Studio) builds, so this PR is not yet ready.  See

* https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html

for reference.

## Todo

* [ ] Add changes required for Windows builds.
* [ ] Update documentation as need be.
* [ ] Update CI to include testing for AWS S3 to catch this sort of thing.

### CODE REVIEW

**Review by DennisHeimbigner — COMMENTED** [review]
The first change to liblib/CMakeLists.txt is incorrect.
It should stay as
> IF(ENABLE_S3_AWS)

**Review by DennisHeimbigner — APPROVED** [review]

**Comment by DennisHeimbigner** [comment]
Please try running again.
I was running the tests myself and realized that it might interfere with you running tests.
I am fixing this, but just in case, you should rerun the tests just to make sure that it was
not interference from me.

**Comment by WardF** [comment]
@DennisHeimbigner Ok, I'm retesting.  Out of curiosity, roughly speaking, how long should I **expect** `nczarr_test/run_chunkcases` to take?  Can the `--with-s3-testing` tests be run in parallel or do they require running in sequence? I run tests in parallel ( `-j 4` ) and if that's a problem, I'll stop.

**Comment by DennisHeimbigner** [comment]
Do not execute the nczarr tests in parallel, there is a significant problem with interference.
Some of the tests can timeout if you run in parallel and others will just fail.

**Comment by WardF** [comment]
I will make the appropriate adjustments so that they run in serial fashion even if the test of the tests are run in parallel. Thanks!

**Comment by WardF** [comment]
@DennisHeimbigner I re-ran the tests in serial fashion, the only one failing now is `nczarr_test/run_interop`.  This is failing with `-DENABLE_S3=TRUE -DENABLE_S3_INTERNAL=TRUE -DWITH_S3_TESTING=TRUE`.  How long should this test take? How long does it take when it passes on your system?

**Comment by DennisHeimbigner** [comment]
Is it failing or timing out?

**Comment by WardF** [comment]
@DennisHeimbigner The test times out after 1500 seconds, resulting in a ctest failure.

**Comment by DennisHeimbigner** [comment]
Ok. Just disable that test. I discovered that error, but it is tied up with unlimited, so forget about it for now.

**Comment by DennisHeimbigner** [comment]
BTW have you been able to tell if the pure awssdk test hangs?

**Comment by WardF** [comment]
@DennisHeimbigner the pure awssdk test does not hang for the AWSSDK I compile myself on Windows.  I'll test the version of the awssdk used in the original python/conda-forge issue next.

**Comment by WardF** [comment]
@DennisHeimbigner I am disabling the run_interop.sh test for now, but I'm concerned this will leave a gap for other issues to creep in.  Is there a specific test in the script that we can disable, or is there overlapping test coverage from other tests we're running?

**Comment by WardF** [comment]
@DennisHeimbigner Rather than disabling `tst_interop` I have, for now, commented out the `S3` tests therein.  That way we can still test interoperability with the local file and zip storage.

**Comment by WardF** [comment]
@DennisHeimbigner Does `unit_tests/run_s3sdk.sh` work for you in your environment? I'm seeing a hang when I attempt to `write`.

**Comment by DennisHeimbigner** [comment]
As far as I know. Certainly under linux, have not tried Windows recently. Want me to run the tests under Windows?

**Comment by WardF** [comment]
It wouldn't hurt.  I'm seeing the hang in `macOS`, I will try under Linux next.

**Comment by WardF** [comment]
WardF/netcdf-c, branch: fix-cmake-s3-support.wif

**Comment by DennisHeimbigner** [comment]
ok. Using your branch with visual studio with cygwin with internal s3,
run_s3sdk.sh passes.

**Comment by WardF** [comment]
How long does it take?

**Comment by DennisHeimbigner** [comment]
15 minutes?

**Comment by DennisHeimbigner** [comment]
BTW, find_package(OpenSSL) fails under cygwin, so I disabled it when building.

**Comment by WardF** [comment]
@DennisHeimbigner How did you disable it? Command line option, or by commenting it out?

**Comment by WardF** [comment]
To get find_package(OpenSSL) to work under MSYS/Windows, I had to specify `-DOPENSSL_USE_STATIC_LIBS=TRUE` when invoking cmake.  Does that work under cygwin, @DennisHeimbigner ?

**Comment by WardF** [comment]
@DennisHeimbigner I will leave it to run for 30 minutes and see what happens. Thanks for the info re: the timing!

**Comment by WardF** [comment]
@DennisHeimbigner I'm seeing the following when running `unit_test/run_s3sdk.sh` under `MacOS`; any suggestions?

```
209: Test command: /opt/homebrew/bin/bash "-c" "export srcdir=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/unit_test;export TOPSRCDIR=/Users/wfisher/Desktop/gh2741-s3/netcdf-c;bash /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/run_s3sdk.sh "
209: Working Directory: /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
209: Test timeout computed to be: 1500
209: Running S3 AWSSDK Unit Tests.
209: 	o Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
209: testbucketexists: exists=1
209: ***PASS
209: 	o Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
209: ***FAIL: (-138) NetCDF: S3 error @ testwrite:224
1/1 Test #209: unit_test_run_s3sdk ..............***Failed  259.18 sec
Running S3 AWSSDK Unit Tests.
	o Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
testbucketexists: exists=1
***PASS
	o Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
***FAIL: (-138) NetCDF: S3 error @ testwrite:224


0% tests passed, 1 tests failed out of 1

Total Test time (real) = 259.20 sec

The following tests FAILED:
	209 - unit_test_run_s3sdk (Failed)
Errors while running CTest
```

**Comment by WardF** [comment]
@DennisHeimbigner Ok, so this error I reported above appears to be an issue with MacOS, somehow.  It works under `debian 12` just fine.

**Comment by WardF** [comment]
@DennisHeimbigner here is the result with `-x` added.

```
    Start 209: unit_test_run_s3sdk

209: Test command: /opt/homebrew/bin/bash "-c" "export srcdir=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/unit_test;export TOPSRCDIR=/Users/wfisher/Desktop/gh2741-s3/netcdf-c;bash /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/run_s3sdk.sh "
209: Working Directory: /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
209: Test timeout computed to be: 1500
209: + URL=https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
209: + isolate testdir_uts3sdk
209: + local rnd
209: + test x = x
209: + ISOPATH=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
209: + ISODIR=testdir_uts3sdk
209: + test xtestdir_uts3sdk '!=' x
209: ++ /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/../libdispatch/ncrandom
209: + rnd=1804289383
209: + ISODIR=testdir_uts3sdk_1804289383
209: + ISOPATH=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
209: + rm -fr /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
209: + mkdir /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
209: + S3ISODIR=testdir_uts3sdk_1804289383
209: + S3ISOPATH=/netcdf-c
209: + S3ISOPATH=/netcdf-c/testdir_uts3sdk_1804289383
209: + test x '!=' xtrue
209: + trap test_cleanup EXIT
209: ++ pwd
209: + THISDIR=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
209: + cd /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
209: + echo -e 'Running S3 AWSSDK Unit Tests.'
209: Running S3 AWSSDK Unit Tests.
209: + echo -e '\to Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists'
209: 	o Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
209: + /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/test_s3sdk -u https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
209: testbucketexists: exists=1
209: ***PASS
209: + echo -e '\to Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data'
209: 	o Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
209: + /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/test_s3sdk -u https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data -k /netcdf-c/testdir_uts3sdk_1804289383/test_s3sdk.txt write
209: ***FAIL: (-138) NetCDF: S3 error @ testwrite:224
209: + test_cleanup
209: + /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/../nczarr_test/s3util -u https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data -k /netcdf-c/testdir_uts3sdk_1804289383 clear
1/1 Test #209: unit_test_run_s3sdk ..............***Failed  259.60 sec
+ URL=https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
+ isolate testdir_uts3sdk
+ local rnd
+ test x = x
+ ISOPATH=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
+ ISODIR=testdir_uts3sdk
+ test xtestdir_uts3sdk '!=' x
++ /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/../libdispatch/ncrandom
+ rnd=1804289383
+ ISODIR=testdir_uts3sdk_1804289383
+ ISOPATH=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
+ rm -fr /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
+ mkdir /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
+ S3ISODIR=testdir_uts3sdk_1804289383
+ S3ISOPATH=/netcdf-c
+ S3ISOPATH=/netcdf-c/testdir_uts3sdk_1804289383
+ test x '!=' xtrue
+ trap test_cleanup EXIT
++ pwd
+ THISDIR=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
+ cd /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/testdir_uts3sdk_1804289383
+ echo -e 'Running S3 AWSSDK Unit Tests.'
Running S3 AWSSDK Unit Tests.
+ echo -e '\to Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists'
	o Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
+ /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/test_s3sdk -u https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
testbucketexists: exists=1
***PASS
+ echo -e '\to Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data'
	o Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
+ /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/test_s3sdk -u https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data -k /netcdf-c/testdir_uts3sdk_1804289383/test_s3sdk.txt write
***FAIL: (-138) NetCDF: S3 error @ testwrite:224
+ test_cleanup
+ /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/../nczarr_test/s3util -u https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data -k /netcdf-c/testdir_uts3sdk_1804289383 clear


0% tests passed, 1 tests failed out of 1

Total Test time (real) = 259.61 sec

The following tests FAILED:
	209 - unit_test_run_s3sdk (Failed)
```

**Comment by DennisHeimbigner** [comment]
Possibly relevant. I tried building under windows again, but using aws-sdk-cpp.
The test ncdump/ref_ctest.c hung.
I was able to run it in visual studio and it indicated that there was exception
thrown in Aws::Monitoring::InitMonitoring inside Aws:InitAPI.

**Comment by DennisHeimbigner** [comment]
ok, try this next:
1. edit run_s3sdk.sh
2.  At about line 30, surround this line:
````
${CMD} ${execdir}/test_s3sdk -u "${URL}" -k "${S3ISOPATH}/test_s3sdk.txt" write
````
with the lines
````
export NCTRACING=15
${CMD} ${execdir}/test_s3sdk -u "${URL}" -k "${S3ISOPATH}/test_s3sdk.txt" write
unset NCTRACING
````
3. Edit the file libnczarr/zdebug.h
4. At about line 8, change
````
#undef ZCATCH
#undef ZTRACING
````
to
````
#define ZCATCH
#define ZTRACING
````
5. rebuild netcdf-c library

**Comment by WardF** [comment]
@DennisHeimbigner the additional output is below:

```
wfisher@shetland:~/Desktop/gh2741-s3/netcdf-c/build$ ctest -R s3sdk -V
UpdateCTestConfiguration  from :/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/DartConfiguration.tcl
Parse Config file:/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/DartConfiguration.tcl
 Add coverage exclude regular expressions.
UpdateCTestConfiguration  from :/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/DartConfiguration.tcl
Parse Config file:/Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/DartConfiguration.tcl
Test project /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 209
    Start 209: unit_test_run_s3sdk

209: Test command: /opt/homebrew/bin/bash "-c" "export srcdir=/Users/wfisher/Desktop/gh2741-s3/netcdf-c/unit_test;export TOPSRCDIR=/Users/wfisher/Desktop/gh2741-s3/netcdf-c;bash /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test/run_s3sdk.sh "
209: Working Directory: /Users/wfisher/Desktop/gh2741-s3/netcdf-c/build/unit_test
209: Test timeout computed to be: 1500
209: Running S3 AWSSDK Unit Tests.
209: 	o Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
209: testbucketexists: exists=1
209: ***PASS
209: 	o Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
209: ***FAIL: (-138) NetCDF: S3 error @ testwrite:224
209: Enter: (6): NCZ_filter_finalize:
209: Exit: (6): NCZ_filter_finalize: 
209: Enter: (6): NCZ_filter_finalize:
209: Exit: (6): NCZ_filter_finalize: 
1/1 Test #209: unit_test_run_s3sdk ..............***Failed  259.27 sec
Running S3 AWSSDK Unit Tests.
	o Checking https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data exists
testbucketexists: exists=1
***PASS
	o Checking write to https://s3.us-east-1.amazonaws.com/unidata-zarr-test-data
***FAIL: (-138) NetCDF: S3 error @ testwrite:224
Enter: (6): NCZ_filter_finalize:
Exit: (6): NCZ_filter_finalize: 
Enter: (6): NCZ_filter_finalize:
Exit: (6): NCZ_filter_finalize: 


0% tests passed, 1 tests failed out of 1

Total Test time (real) = 259.28 sec

The following tests FAILED:
	209 - unit_test_run_s3sdk (Failed)
Errors while running CTest
```

**Comment by DennisHeimbigner** [comment]
Well that did not help any. Oh well.

**Comment by WardF** [comment]
@DennisHeimbigner I think I'm onto something.  I've made some changes and figured out how to enable the Console logging. Following a hunch, I dug into the documentation and then was able to find other, similar issues. Long story short, there appears to be an issue when setting `Aws::S3::PutObjectRequest.SetContentLength()` manually. The suggested fix I've seen is to leave this empty and allow the AWS SDK to compute it automatically.  This may need to be changed elsewhere, but at first glance, it appears to have fixed the issue in the `s3sdk`-related test.  I've more testing to do, but this is concrete progress forward.

**Comment by WardF** [comment]
We are seeing other failures now but I suspect they are string-comparison related, for the most part.

**Comment by WardF** [comment]
Reverted previous changes because I realized that I was using an axe, incorrectly, when I should be using a sample.  The code initially changed is working for other tests, just not the `test_s3sdk.sh` test.  Indicators are currently that there is an issue that manifests when the number of bytes sent does not align with the number of bytes we say we're sending.  This is not obviously the case, and also it works on linux if not MacOS.  Before we can actually sort out Windows, I would like to know that this is all working on MacOS and Linux, to ensure there aren't any weird errors with a common root, manifesting differently depending on platform and compiler.

**Comment by DennisHeimbigner** [comment]
Refresh my memory; what happened when you did not specify a length?

**Comment by DennisHeimbigner** [comment]
BTW, if you set the cmake option -DENABLE_CMAKE_LOGGING=on
then I believe you can see what curl is generating for the length.
I believe it streams the output through the aws logging system.

**Comment by WardF** [comment]
> Refresh my memory; what happened when you did not specify a length?

`test_s3sdk` passed, but a lot of other tests started failing, because the `length` defaulted to `0`.

**Comment by DennisHeimbigner** [comment]
What happens if you set the length to -1 ?

**Comment by WardF** [comment]
@dmh

> What happens if you set the length to -1 ?

All the tests fail

**Comment by WardF** [comment]
@DennisHeimbigner I'd like to get this working with the s3 internal api across platforms, for now, since the issue seems to be specific to the `awssdk-cpp` library.  As of this morning, I'm seeing a new issue with -DENABLE_S3_INTERNAL=TRUE, `Error: Unexpected Element: <ChecksumAlgorithm>`.  This breaks the tests, and `s3util`.  Do you have any idea what happened there?

**Comment by DennisHeimbigner** [comment]
The context is this. ncs3sdk_h5.c makes a ListObject request that returns a complex XML
document. I parse the xml and then walk it to produce internal data structures corresponding
to that XML document. It appears then that the XML document has a ChecksumAlgorithm
element in unexpected place in the XML. What I need is to see the complete XML document
so I can see where the ChecksumAlgorithm element is occurring and then modify my walker
to handle it.
I will review the code and send some instructions so we can see the whole XML document.

**Comment by DennisHeimbigner** [comment]
Ok, I think if you change the following lines in ncs3sdk_h5.c, then it should output the XML document(s).
Lines to change:
````
#undef DEBUG
to
#define DEBUG

**Comment by WardF** [comment]
@DennisHeimbigner for whatever reason, after spending most of the day on this and related issues, it has resolved itself.  I was not running into an issue where I was running the tests in multiple places at the same time, but I did observe failures under Linux and MacOS.  Now, however, things are back where they started, e.g. `-WITH_S3_TESTING=TRUE -DENABLE_S3_INTERNAL=FALSE` hangs on MacOS.

**Comment by DennisHeimbigner** [comment]
Did the ChecksumAlgorithm issue resolve also?

**Comment by WardF** [comment]
@DennisHeimbigner The `ChecksumAlgorithm` issue is resolved; the hang has not.  I think for now, for the sake of expediency, we will need to tell non-linux platforms to use `-DENABLE_S3_INTERNAL=TRUE` until we figure out what, exactly, is going on with the `awssdk-cpp` on other platforms.  I'm still seeing test failures in my `MSYS2`-bash environment, I'll send you a log to see if you have any feedback (I know the current `main` branch works for you under `cygwin`).

**Comment by WardF** [comment]
@DennisHeimbigner it did. 

I think our best bet right now is to use `S3_INTERNAL` on Windows, but I'm seeing other failures that preclude a release.  Does anything leap out at you with these? 

* [cmake-main-failure.zip](https://github.com/Unidata/netcdf-c/files/12754218/cmake-main-failure.zip)

**Comment by DennisHeimbigner** [comment]
Your msys failures are a mystery to me. The first failing test is ncdap_test_tst_ncdap3.
It works for under windows+cygwin and it works on the msys run of github actions.
I can think of a couple of possibilities.
1. the file /home/wardf/netcdf-c/ncdap_test/testdata3/synth1.dds and/or the file /home/wardf/netcdf-c/ncdap_test/testdata3/synth1.das are actually missing. can you check to see if they are there?
2. there is a problem with path conversion, although that path looks ok to me.

**Comment by WardF** [comment]
Merged to date as part of #2755, opening another PR to continue tracking this issue.

**Pull request merged**
