### PR TITLE
deprecate non-relax coord bounds checking, also fix parallel builds for --enable-pnetcdf

### LINKED ISSUE #1206: pnetcdf build has memory leaks
The ASAN build shows that some of the pnetcdf code is leaking memory somewhere.

### LINKED ISSUE #1237: make -j check fails for pnetcdf builds due to test dependencies
I rarely build with pnetcdf, so it took me all this time to notice that parallel build (i.e. make -j builds) fail the pnetcdf tests because of some test dependencies. I will have a PR up shortly.

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #1010 (see discussion there).

Fixes #1237.
Fixes #1206.

In this PR I remove the option to disable relaxed coord bound checking. As discussed in #1010, once coord bound checking is relaxed (as it should be), it must be relaxed everywhere, or else there may be incompatible APIs between different HPC installations. Programs written where coord bounds checking is relaxed will fail on machines where it is not.

As discussed (at length) in #1010 there is no harm or impact in always relaxing coord bound checking in all cases. In that case, there can be no incompatibilities, and all existing code continues to work exactly as it has.

This PR also now enforces that pnetcdf is also built with relaxed coord bound checking. Presumably this will become default in the next pnetcdf release, until then, users must use --enable-relax-coord-bound when building netCDF. @WardF if you have pnetcdf in your CI system I'm afraid you will have to rebuild it with --enable-relax-coord-bound.

Also fixed a pnetcdf test memory leak, and some pnetcdf build issues.

### CODE REVIEW

**Comment by WardF** [comment]
Before I accept this, @wkliao, do you have plans to make relaxed coord bounds the default in upcoming pnetcdf releases?

**Comment by edhartnett** [comment]
@WardF actually this option should be removed before anyone uses it. It's presence is a bug. It creates incompatible netCDF installations on HPC systems when used.

**Comment by edhartnett** [comment]
The original bounds checking code (written by me) was incorrect; it was written without a good understanding of advanced collective I/O programming. It returns an error for parameters that should be allowed, and are necessary in some parallel I/O cases (and harmless in all other cases). Hence the need for relaxed bounds checking.

Allowing users to disable relaxed bounds checking perpetuates this original bug. There is no good reason anyone should want incorrect bounds checking. 

Disabling relaxed bounds checking will cause working (and correctly written) netCDF parallel I/O code to fail. This is clearly a bug. Why do we want users to be able to do this? There's no reasonable way that their existing code can depend on this bug.

For full (and lengthy) discussion see #1010. 

Rather than continue this battle, I will change my PR to allow the user to activate disable relaxed bounds checking, but with a warning that it should not be used and that it may cause valid parallel I/O code to fail. I will also mention that it is deprecated. Then it can be fully-removed after the next release.

@WardF will this be acceptable?

**Comment by WardF** [comment]
Getting caught up here on the tail end of the holidays, Happy NYE everybody.  @edhartnett this works for me, any further objections/thoughts on your end @wkliao ?

**Comment by edhartnett** [comment]
@WardF I will modify this PR as discussed above. I'll wait for your current aggregated PR to get merged...

Thanks~!

**Comment by edhartnett** [comment]
OK this PR has been modified  as discussed and is ready to merge to master.

**Pull request merged**
