### PR TITLE
Use H5Aiterate2 in read_var.

### PR DESCRIPTION
**Pull request by brtnfld**
Changed from discovering attributes and then looping through them to using H5Aiterate2 instead. This was needed to port netcdf-c to work with a Fast-Forward version of HDF5.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Have not looked at this in detail, but remember that there are certain hidden attributes
that may need to be filtered out.

**Comment by WardF** [comment]
Additionally, the travis-ci checks are failing.

**Comment by brtnfld** [comment]
Must have been a glitch with Travis-ci, it passes now.

**Comment by WardF** [comment]
Working through back catalog; running into some compile failures here when working with openmpi.  That is non-exhaustive so far, will test on other platforms.

**Pull request merged**
