### PR TITLE
Fix libraries for CURL and HDF5

### PR DESCRIPTION
**Pull request by paulharris**
CURL_LIBRARY should have always been CURL_LIBRARIES

And always include HDF5_LIBRARIES in case HDF5_C_LIBRARIES is not
available.

There are plenty of other changes that could be made to upgrade to the
newer cmake ... such as linking to CURL::libcurl and HDF5::HDF5 instead.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Are these changes back compatible with earlier versions of libcurl?

**Comment by paulharris** [comment]
I would assume so,
I looked through some of your build logs, and some stackexchange messages about "why can't i build NetCDF",
and amongst the logs were "missing: CURL_LIBRARY"
eg: https://github.com/Unidata/netcdf-c/issues/1865
can't find the other links right now.

It has always been CURL_LIBRARIES, since cmake 3.0:
https://cmake.org/cmake/help/v3.0/module/FindCURL.html
https://cmake.org/cmake/help/latest/module/FindCURL.html

I'm wondering how it has ever worked... perhaps it didn't find the curl library, so it tried to link to the system library -lcurl,
and users had that already installed on their system, so it appeared to work anyway?

Note that conan's recipe has been patching this since v 4.7.4, that is why I'm here.

Are you able to test with older libcurl?
If you want to be on the safe side, maybe we just add `${CURL_LIBRARIES} ${CURL_LIBRARY}`
then if there is some obscure old cmake variant, it'll work the same as before...

**Comment by WardF** [comment]
Thanks for the contribution, modernizing `cmake` is one of many things on the list of stuff that we would like to get to, and should, eventually!  I'll get this merged in.

**Review by WardF — APPROVED** [review]

**Comment by paulharris** [comment]
Thanks!

**Pull request merged**
