### PR TITLE
Add advanced HPC functionality based on PIO library

### LINKED ISSUE #555: Add multi-level parallelism, async writes, and other HPC features from PIO library
# Introduction

This ticket described a plan to include the functions of the PIO library into the netCDF library, so that it may be (optionally) available to all netCDF HPC (High Performance Computing) users. The HPC community is a core component of the Unidata community, and better support of modern supercomputers will allow netCDF to better server these users.

The Parallel I/O library (https://github.com/) as developed at NCAR. It provides advances HPC I/O functionality for netCDF codes, with a netCDF API. The PIO library allows HPC users to make the most of their computational hardware, without waiting on I/O more than is absolutely essential.

The goal of this effort is to make the PIO functionality available to netCDF users, through the NetCDF API.

## Main Features

- Allows user to specify an I/O component, composed of N processors, which performs all I/O.
- Allows users to specify one or more computation components, each containing a specified number of processors.
- When computation components call netCDF functions, I/O is actually performed by I/O component.
- NetCDF variable data may be distributed across processors in a computational component so that each processor only needs to manage its local data space.
- Buffering of I/O in memory of computational components, and memory of I/O components.
- Asynchronous writes of data from computational components.

## Computational Components and I/O Component

In async mode, it is possible for the user to define several computational components, and one (shared) I/O component.

Each component can have an arbitrary number of processors.

In computational components, netCDF calls actually send data to the I/O component, which buffers data and handles disk I/O.

For example, a machine of 500K processors can assign 1K processors to I/O, 250K processors to an atmospheric model, 100K processors to an ocean model, 10K processors to a space weather model, etc., until all 500K processors are used up. Each of the models can do netCDF I/O as usual, but all actual I/O will be channeled through the I/O component. Data are buffered at all stages to improve performance.

## Configuration and Build

The PIO functionality is only included if netCDF is built with --enable-pio. It makes no sense to use PIO on systems without multiple cores, but this is not enforced by the build, and tests will build and pass even on a single core.

The PIO functionality is available through the netCDF internal dispatch system. This allows the use of the netCDF API by various sublibraries (netCDF4, HDF4, pnetCDF, etc.) The PIO functionality is accessed in the same way.

The code for the integrated PIO functionality is in subdirectory libpio.

## Testing of PIO

The pio_test directory contains tests for PIO. These tests will only be run of --enable-parallel-tests is specified.

## Using PIO

In order to use PIO, the user must include the NC_PIO flag in the mode of nc_create/nc_open.

## Additions to the NetCDF Data Model

PIO introduces two new objects to the netCDF data model:

1. the iosystem, which describes the entire current hardware arrangement (how many tasks, which ones to be I/O tasks, which ones to be computational components). Identified with an iosystemid.
2. the decompositon, which describes how the data from one or more vars is to be distributed across processors for distributed read/writes. Identified with ioid.

## New Functions for the API

Several new functions need to be added to the netCDF API to support PIO functionality. However, it is not necessary to add them to the netCDF dispatch table, since other netCDF sub-libraries will never need to implement these functions.

### Initialization

There are two new PIO initialization functions, one for async, one for non-async (The names of these functions will be changed to match the netCDF API). A finalize call must be called at the end of all processing.

```
    int PIOc_Init_Intercomm(int component_count, MPI_Comm peer_comm, MPI_Comm *comp_comms,
                            MPI_Comm io_comm, int *iosysidp);
    int PIOc_init_async(MPI_Comm world, int num_io_procs, int *io_proc_list, int component_count,
                        int *num_procs_per_comp, int **proc_list, MPI_Comm *io_comm, MPI_Comm *comp_comm,
                        int rearranger, int *iosysidp);

   int PIOc_finalize(int iosysid);

```

### Decompositions

Decompositions define how a netCDF variable is distributed across processors on the supercomputer.

```
    /* Init decomposition with 0-based compmap array. */
    int PIOc_init_decomp(int iosysid, int pio_type, int ndims, const int *gdimlen, int maplen,
                         const PIO_Offset *compmap, int *ioidp, int rearranger,
                         const PIO_Offset *iostart, const PIO_Offset *iocount);

    /* Free resources associated with a decomposition. */
    int PIOc_freedecomp(int iosysid, int ioid);
```

For convenience there are also two functions to write/read a netCDF file which records the decomposition information. Use of decomposition files is helpful for debugging, but not generally used in real processing.

```
    /* Write a decomposition file using netCDF. */
    int PIOc_write_nc_decomp(int iosysid, const char *filename, int cmode, int ioid,
                             char *title, char *history, int fortran_order);

    /* Read a netCDF decomposition file. */
    int PIOc_read_nc_decomp(int iosysid, const char *filename, int *ioid, MPI_Comm comm,
                            int pio_type, char *title, char *history, int *fortran_order);

```
### Record Reads/Writes on Distributed Arrays

```
    int PIOc_advanceframe(int ncid, int varid);
    int PIOc_setframe(int ncid, int varid, int frame);
    int PIOc_write_darray(int ncid, int varid, int ioid, PIO_Offset arraylen, void *array,
                          void *fillvalue);
    int PIOc_read_darray(int ncid, int varid, int ioid, PIO_Offset arraylen, void *array);

```

There are read/write functions to read/write a record of a distibuted array. (A record is defined by writing 1 element of the first dimension, and all elements of subsequent dimensions. In a classic netCDF file with an unlimited dimension, this is a record. But with PIO, the first dimension does not have to be unlimited.)

## Schedule

I anticipate the first version of this integration, supporting netCDF classic files, will be ready before the end of 2017. If so, it can be included in the 4.5.1 release of netCDF.

## Work Details

This work can be followed in detail on the GitHub repo:  https://github.com/edhartnett/netcdf-c

### PR DESCRIPTION
**Pull request by edhartnett**
This PR contains the changes needed to get PIO working within the netCDF library.

This brings some very powerful new features for HPC. These features will be very helpful to weather modelers, climate modelers, and anyone else using netCDF on many-core supercomputers.

Documentation is good on a per-function level. Doxygen documentation of PIO is not enabled yet pending merging of another PR I have with many Doxygen changes. Once that PR is merged I will turn on PIO documentation in the Doxyfile.in file.

New functions are added to netcdf_par.h to support the new features. The PIO features are only available on builds which include both netCDF-4 and parallel.

Fixes #555.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Is there any chance of getting a design document?

**Comment by edhartnett** [comment]
Yes, more documentation is coming. Now that I've got everything working, I'll get it documented. ;-)

**Comment by edhartnett** [comment]
OK, there are now two .md files in the libpio directory: using_pio.md for a user-level overview, and developer_docs.md for developer level documentation. These documents will develop over the coming days.

**Comment by edhartnett** [comment]
@DennisHeimbigner take a look at the two docs I added, and most importantly the example examples/C/pio_simple_async.c. This example shows the simplest async arrangement with 1 task doing all IO for 1 computation component, which consists of 3 tasks. The computation component then writes a simple file with one variable, using distributed arrays.

Note that, due to the simplicity of this example the decomposition is created in the midst of the netCDF code that creates the file. In general the decomposition will be created before any files are created, and will be used for many files.

**Comment by edhartnett** [comment]
I am going to take this PR down for a while.

**Pull request closed without merging**
