### PR TITLE
more tests, more internal documentation, minor bug fixes

### LINKED ISSUE #392: Try create a NetCDF4 file using NetCDF ibrary built with --disable-netcdf-4
A question.
When using NC_NETCDF4 mode to create a file using a netCDF library built without netcdf4 enabled (i.e. --disable-netcdf-4), should the nc_create function return NC_EINVAL?

FYI. I tested this using the latest master branch and the file is created without error, but the file is in the classic format.

### LINKED ISSUE #662: Take out old, no-longer-working ming DLL stuff in autotools build, leaving full support for cygwin
Before @WardF came along and wrote the CMake build system, I had attempted to build the netcdf dll with Cygwin and also with ming32.

I had various degrees of success, but it was a real pain, and now I am happy that the CMake build system handles Windows.

However, my attempts left a lot of cruft in the build files. I will remove it as part of my make -j check changes.

### LINKED ISSUE #694: Old test h5_test/tst_h_filters is not being run. Should it be?
There is a test in h5_test called tst_h_filters.c.

At first I thought this was from @DennisHeimbigner, but git log tells me this is mine, from long ago.

Shall I just eliminate this test? Obviously it does not reflect recent filter work, and it has not been run for many years.

### LINKED ISSUE #696: Remove mention of udunits and libcf from autotools build
Back in the old days we used to include udunits and libcf with the netcdf distributions. Now we don't. But there are still some remnants of udunits and libcf in the main Makefile.am and perhaps other places. These can all be eliminated.

### LINKED ISSUE #697: Compile warnings for libsrc/v1hpg.c and nc_test/tst_utf8_validate.c...
With the recent merges, we have cleared almost all compile warnings in the code for gcc -Wall.

However, here's two that have been introduced:

```
v1hpg.c: In function ‘v1h_get_NC_string’:
v1hpg.c:307:9: warning: variable ‘padding’ set but not used [-Wunused-but-set-variable]
  size_t padding = 0, nchars = 0;
         ^~~~~~~

v1hpg.c: In function ‘v1h_get_NC_attrV’:
v1hpg.c:695:15: warning: variable ‘padding’ set but not used [-Wunused-but-set-variable]
  size_t nget, padding;
               ^~~~~~~
```

Easily fixed. I will put fix in my next PR.

Another warning, which has been there for a long time, is this one:

```
tst_utf8_validate.c:98:44: warning: null character(s) preserved in literal
 {0,"2.1.1", "1 byte  (U-00000000)",        " "},

```

In this case we were using '^@' for a null char in a string literal, instead of the equivalent (and gcc-preferred) '/000'. I made the change to eliminate the warning.

### LINKED ISSUE #698: Remove legacy "ftpbin" target from top-level Makefile.am
In the top level Makfile.am we have this target, which I remember putting there years and years ago. It was for producing netCDF binary distributions.

```
# At Unidata, package up binaries.
ftpbin: install
	echo "Getting binaries from ${prefix}"
	ls -l ${prefix}
	echo "These are the binaries for netCDF @PACKAGE_VERSION@." > ${prefix}/README_BINARIES.txt
	echo "For this build: CC=$(CC) CXX=$(CXX)" >> ${prefix}/README_BINARIES.txt
	echo "CFLAGS=$(CFLAGS) CXXFLAGS=$(CXXFLAGS)" >> ${prefix}/README_BINARIES.txt
	echo "FCFLAGS=$(FCFLAGS) F77FLAGS=$(F77FLAGS) $F90FLAGS=$(F90FLAGS)" >> ${prefix}/README_BINARIES.txt
	which tar
	echo "PATH: $(PATH)"
	tar cf @BINFILE_NAME@ -C ${prefix} ${BINFILES}
	gzip -f @BINFILE_NAME@
	zip -j netcdf_${VERSION}.zip ${ZIPBINFILES}
```

@WardF do you still use this target? I believe not, since I see that Unidata no longer distributes binaries (except for Windows, which is done with the CMake build.)

So I will remove this.

### LINKED ISSUE #699: Incorrect testing -- testing against itself
In `/Users/gdsjaar/src/seacas-sems/TPL/netcdf/netcdf-c/oc2/ocnode.c`

```
static OCerror
occorrelater(OCnode* dds, OCnode* dxd)
{
    int i,j;
    OCerror ocstat = OC_NOERR;

    if(dds->octype != dxd->octype) {
	OCTHROWCHK((ocstat = OC_EINVAL)); goto fail;
    }
    if(dxd->name != NULL && dxd->name != NULL
       && strcmp(dxd->name,dds->name) != 0) {
	OCTHROWCHK((ocstat = OC_EINVAL)); goto fail;
    } else if(dxd->name != dxd->name) { /* test NULL==NULL */
	OCTHROWCHK((ocstat = OC_EINVAL)); goto fail;
    }

    if(dxd->array.rank != dds->array.rank) {
	OCTHROWCHK((ocstat = OC_EINVAL)); goto fail;
    }
```

The second if/else if test is testing `dxd` against itself.  I think it should be `dxd` vs `dds`:

```
     if(dds->name != NULL && dxd->name != NULL
       && strcmp(dxd->name,dds->name) != 0) {
	OCTHROWCHK((ocstat = OC_EINVAL)); goto fail;
    } else if(dds->name != dxd->name) { /* test NULL==NULL */
	OCTHROWCHK((ocstat = OC_EINVAL)); goto fail;
    }
```

### LINKED ISSUE #704: Some problems when bad params are passed to nc_def_var()
While increasing test coverage on nc4var.c, I discovered that nc_def_var() does not always respond well to bad parameters.

```
      /* This next attempt is correctly rejected with NC_EBADTYPE, but
       * messes up the file so that VAR_BYTE_NAME cannot be
       * defined. */
      /* if (nc_def_var(ncid, VAR_BYTE_NAME, TEST_VAL_42, 2, dimids, &byte_varid) != NC_EBADTYPE) ERR; */
 
      /* THis causes a core dump, but shouldn't! */
      /* if (nc_def_var(ncid, VAR_BYTE_NAME, NC_BYTE, 2, NULL, &byte_varid)) ERR; */

```

Easy fixes. I will add them.

### LINKED ISSUE #706: Incorrect handling of negative preemption parameter in nc_set_var_chunk_cache_ints()
Negative params are supposed to be ignored, but negative premption causes error. I will fix.

### LINKED ISSUE #707: Trying to def_var_chunking on a scalar var causes seg fault
This causes a seg fault:

```
      if (nc_def_var(ncid, VAR_NAME5_2, NC_INT, 0, NULL, &varid2)) ERR;
      if (nc_def_var_chunking_ints(ncid, varid2, NC_CHUNKED, chunksize_int)) ERR;

```

I will fix.

### LINKED ISSUE #709: In nc4internal.c function nc4_find_g_var_nc() returns incorrect error code for bad ncid
Should return NC_EBADID, but instead returns NC_ENOTVAR.

I will fix.

### LINKED ISSUE #713: Remove unused file libsrc4/n3stub.c
We have a file libsrc4/n3stub.c.

Looks like it was part of the development of the dispatch system which is no longer needed.

It is not used in the build. I will remove it.

### LINKED ISSUE #714: Remove unused function nc_use_parallel_enabled() in libsrc4/nc4file.c
In libsrc4/nc4file.c we have:

```
#ifdef USE_PARALLEL4
int
nc_use_parallel_enabled()
{
   return 0;
}
#endif /* USE_PARALLEL4 */

```

This is both incorrect (since it should return 1) and also completely unused anywhere. I will remove it.

### LINKED ISSUE #716: nc_copy_var()/nc_copy_add() documentation mising
Not only did the functions not have doxygen comments for these functions, but the dcopy.c file was also not being included in the documentation build.

I have fixed these on my current PR.

### PR DESCRIPTION
**Pull request by edhartnett**
More tests for nc4var.c code. Also some minor fixes and a bunch of (internal) documentation.

This gets test coverage of nc4var.c from 70% to ~85%, but there is more to go.

Added or fixed doxygen documentation for all functions in libsrc4.

Also added documentation for a few missing public functions.

Part of #702.
Fixes #704.
Fixes #709.
Fixes #707.
Fixes #706.
Fixes #714.
Fixes #713.
Fixes #716.

From PR #700:

Fixes #699.
Fixes #698.
Fixes #697.
Fixes #696.
Fixes #694.
Fixes #662.

From PR #658:

Fixes #392.

### CODE REVIEW

**Comment by edhartnett** [comment]
I have merged in my other outstanding PRs #700 and #658. Running through CI now.

**Comment by WardF** [comment]
I merged in some changes I made from master and turned on parallel tests for CI. Let me explore that and figure out what's going on, I don't believe this is a 'true' failure.

**Comment by edhartnett** [comment]
I see this branch is passing travis again. Hopefully that means it can now be merged. ;-)

**Comment by WardF** [comment]
Compiler errors in Windows but I don't expect them to be difficult to handle. Will follow up once fixed.

**Comment by WardF** [comment]
Got caught up in another project and then having to update Visual Studio (which has taken quite a while so far), still working on this.

**Comment by WardF** [comment]
At AGU but pursing this now

**Comment by WardF** [comment]
tst_nccopy4 is failing.  I will examine why and follow up.

**Comment by edhartnett** [comment]
Where is it failing? On Windows?

**Comment by edhartnett** [comment]
Hope you are having a good time at AGU. Enjoy the conference, this can wait
until you get back.

At the moment I am deep in some PIO problems. Almost ready to put up a PR
with a fully working PIO built into netCDF. So very excited about that. ;-)

**Comment by WardF** [comment]
When you say built in, do you mean hooks to link against, like pnetcdf? Looking forward to seeing it! Take your time, the WiFi at the convention center is terrible.

**Comment by WardF** [comment]
Oh, it is failing on Windows and I went "too clever" trying to fix it last night.  Still working on it this morning.

**Comment by edhartnett** [comment]
When I say built-in, I mean built in. There is a new directory, libpio, and
a new test directory, pio_test.

It cannot be hooked in like pnetcdf - it is too fundamental.

Best would be if you and Dennis made some time and I can come down and
explain in person.

Ed

**Comment by edhartnett** [comment]
BTW the features of PIO + netcdf are awesome. Worked out even better than I
had hoped. It will really position netcdf as the HPC leader. And it takes
full advantage of netCDF-4, netCDF-4 parallel, and pnetcdf (not yet but
soon).

And the usefulness of the features is already well proven by the CESM model.

On Tue, Dec 12, 2017 at 10:11 AM, Ed Hartnett <edwardjameshartnett@gmail.com

**Comment by DennisHeimbigner** [comment]
Have you had to make significant changes outside of the libpio and pio_test directories?
As per our previous discussion about per-variable pio information, we may be able
to simplify your changes by simple extensions to the netcdf API.

**Comment by edhartnett** [comment]
Some changes in libdispatch/dfile.c in order to invoke things properly for opens/creates. I am isolating most of the changes in functions that will only be built and called if the library is built with PIO.

Otherwise no changes outside the libpio and pio_test directories. Basically the libpio code sits on top of the libsrc/libsrc4 code and calls it as needed.

I added several new functions, which have no analogs elsewhere in the library. This is the complete list:

```
   /* Init decomposition with 0-based compmap array. */
   extern int
   nc_init_decomp(int iosysid, int pio_type, int ndims, const int *gdimlen, int maplen,
                  const PIO_Offset *compmap, int *ioidp, int rearranger,
                  const PIO_Offset *iostart, const PIO_Offset *iocount);

   /* Read a decomposition file. */
   int nc_read_decomp(int iosysid, const char *filename, int *ioidp, MPI_Comm comm,
                      int pio_type, char *title, char *history, int *fortran_order);

   /* Write a decomposition file. */
   int nc_write_decomp(int iosysid, const char *filename, int cmode, int ioid,
                       char *title, char *history, int fortran_order);

   extern int
   nc_init_intracomm(MPI_Comm comp_comm, int num_iotasks, int stride, int base,
                     int rearr, int *iosysidp);

    /* Creates an MPI intracommunicator between a set of IO tasks and
    * one or more sets of computational tasks. */
  extern int
   nc_init_async(MPI_Comm world, int num_io_procs, int *io_proc_list,
                 int component_count, int *num_procs_per_comp, int **proc_list,
                 MPI_Comm *user_io_comm, MPI_Comm *user_comp_comm, int rearranger,
                 int *iosysidp);
   
   extern int
   nc_set_iosystem_error_handling(int iosysid, int method, int *old_method);
   
   extern int
   nc_advanceframe(int ncid, int varid);

   extern int
   nc_setframe(int ncid, int varid, int frame);

   extern int
   nc_write_darray(int ncid, int varid, int ioid, PIO_Offset arraylen, void *array,
                   void *fillvalue);

   extern int
   nc_read_darray(int ncid, int varid, int ioid, PIO_Offset arraylen, void *array);

   /* Free a decomposition map. */
   int nc_free_decomp(int iosysid, int ioid);

   /* Finalize an IO system for PIO. */
   int nc_free_iosystem(int iosysid);

```

I may combine the setframe function into the read/write_darray functions. So there will be some minor churn...

**Comment by DennisHeimbigner** [comment]
That is a lot of changes to the netcdf-c API, which makes me unhappy :-(
The IMO less disruptive alternative is to create data structures that hold, in effect,
the arguments to those functions. Then pass in that data structure
using the existing API and have the necessary code be invoked
inside libpio. This is somewhat similar to the way in-memory and mpi
info is passed.

**Comment by edhartnett** [comment]
This is a maximum. A bunch of functions will go away. I need to get all tests working first. ;-)

PIO introduces two new items to the netCDF data model, IO Systems and decompositions.

IO systems describe the HPC environment, how many cores, how many to do I/O, and which ones do which. They allow the program to adjust at start-up to the number of available cores and how the user wants to divide the computation/IO workload.

Decompositions map netCDF file data space across the available computational cores. For example if a var is 10x10x10 and there are 100 cores, then you could put 10 value per core. The decomposition specifies this.

With IO space I can say that if my program is running on 10K cores, that 1000 of them should be for I/O, and 5K for an atmospheric model and 4K for an ocean model.

With decompositions I say how the 3D and 2D data arrays (each get their own decomposition) are scattered across the 5K atmospheric cores.

Now each of the 5K cores can call nc_write_darray() with their local array, and the 5000 sub-arrays will be automatically transfered to the 1000 I/O cores. Those I/O cores will (later) write that data to disk in the netCDF file. The decompostion(s) and IO system allow the PIO code to do all the donkey-work to make it happen.

So the decomposition and IO system exist independently of any netCDF file. Both might easily be used to create and/or read many netCDF files. In fact, that would be typical. The user will set up the IOSystem and decompositions once for the supercomputer, then all subsequent netCDF file access, reading or writing, will use those.

It's neat, so it's worth a few extra functions. However, after I take my next pass, if you can suggest any further reductions, that would be good.

**Comment by DennisHeimbigner** [comment]
If by extending the data model, you mean
defining structures in a include/netcdf_pio.h file, then fine.
Also, frankly, I doubt that you need all those extra functions as such. Why do you
reject my data-structure-oriented approach? As I said, I am unhappy with this.

**Comment by DennisHeimbigner** [comment]
Never mind. I will wait until you have a functioning system and then Ward and I
will decide what changes need to be made.

**Comment by edhartnett** [comment]
I am open to any changes that will work, but I don't understand how your
data structure idea would work in this case.

Starting with IO systems -

The IO system must be set up before the first nc_create()/nc_open(),
because only some cores will be calling create/open (the computation cores,
trying to write their results). The IO cores already need to be looping in
a message mode, waiting for I/O calls to come in. It has to be initialized
and running before the first nc_create() call.

The code that splits up the work between different sets of cores is, by
necessity, user code. They must write their core Earth model engine. That
Earth model engine initializes the IO system, and then launches component
models on different sets of cores. Those component models contain netCDF
code.

So I believe, at least for I/O systems, that init/free functions are
required.



On Tue, Dec 12, 2017 at 2:10 PM, Dennis Heimbigner <notifications@github.com

**Comment by DennisHeimbigner** [comment]
> The IO system must be set up before the first nc_create()/nc_open(),
We handle this like we do e.g. hdf5 initialization. Namely, nc_create and nc_open
examine internal global variables to see if the necessary pio initialization has been
performed, and if not, do it.

> The code that splits up the work between different sets of cores is, by necessity, user code.
I am certainly not opposed to user provided callback functions, but again,, that can be passed
as data to the existing netcdf-c API functions.

**Comment by DennisHeimbigner** [comment]
In any case, as I said. The important thing is to get a working version in a branch
on our github repo. Then we can consider tweaking the API.

**Comment by edhartnett** [comment]
I'm afraid what you propose will not work for IO systems due to the way MPI
works. (BTW I should add that, as currently written, the PIO integration
requires netCDF be built for parallel, and the new functions are declared
in netcdf_par.h. So this is not really an expansion of the usual netCDF
API, but an expansion of the netCDF parallel API.)

In the example I gave above, when the atmospheric model wants to create a
file, it calls nc_create() on it's 5000 cores. These cores (actually just
core 0) send the parameters to the 1000 IO processing cores (but this must
be set up first). If this is a serial netCDF classic file, that results on
NC3_create() being called on core 0 of the IO cores. The error code is
passed back, first to the 1000 IO cores, then to the 5000 atmospheric model
cores. The other 4000 cores on the machine do not get a nc_create() call at
this time.

So the processors on which nc_create is NOT being called, also must be
initialized. The IO cores must be running the messaging loop before any
netCDF calls are made. The IO System encompasses ALL communicators and must
know about all of them. It is set up at model initialization and knows
about all the existing computational components, and the IO components, and
has their MPI communicators all set up.

It is truly a separate and worth netCDF object, but one that is only needed
on HPC systems.

The PIO library is well-designed to fit into existing Earth system models.
The setup of the model and all the sub-models is already a big thing, as
you can imagine. Lots of science stuff. IO is only a small part of it. So
they will not provide call-back functions. Instead, they will want to
initialize IO as part of their overall initialization. That is where they
decide how many cores to use for each computation component, the IO
component, etc. Then they launch the computational components on their
cores, the IO component on it's cores.

NetCDF/PIO fits into this existing workflow in order to maximize reuse and
make it easy for users to use in their netCDF-based models (which are very
large code bases that are expensive to change.)




On Tue, Dec 12, 2017 at 2:55 PM, Dennis Heimbigner <notifications@github.com

**Comment by DennisHeimbigner** [comment]
I don't follow. You can pass all the info you want about the other cores as the parameter
argument to nc_create.

**Comment by edhartnett** [comment]
OK, as you suggest, let me get a working system up and running, and
eliminate all the obviously unnecessary functions. Then we can discuss the
ones that are left. I am open to anything that can be made to work.

On Tue, Dec 12, 2017 at 4:40 PM, Dennis Heimbigner <notifications@github.com

**Comment by edhartnett** [comment]
But to continue with this example, I need to create MPI communicators on
all cores, and yet nc_create() is only being called on some cores. So even
if I pass all information to those cores that are calling nc_create(), that
still leaves all the other cores, which are not running the correct code.
The init code has to run on *all* cores.

In practice, this happens at init time for the whole model system. Then the
computational components start executing, and they make netCDF calls.

**Comment by wkliao** [comment]
Hi, @edhartnett 
In one of your earlier posts, you mentioned 
> And the usefulness of the features is already well proven by the CESM model.

This sounds interesting. Could you please provide references, publications to this work? Thanks

**Comment by edhartnett** [comment]
@wkliao I don't have any references or publications. I'm a programmer dude, not a scientist. :-)

However, take a look at CESM here: http://www.cesm.ucar.edu/. Probably there are lots of papers about it, but probably none of them mention the "minor" implementation detail of how they do IO. ;-)

Anyway, further discussion of PIO merges should take place on it's newly-created PR #720.

Meanwhile, this PR contains minor cleanup and a bunch of documentation. Hopefully we can get it merged this week.

**Pull request merged**
