### PR TITLE
Add additional path name conversion checks

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
The files libdispatch/dwinpath.c and include/ncwinpath.h
were added to provide a path name converter from e.g. cygwin
paths to e.g. windows paths. This is necessary because
the shell scripts may produce cygwin paths, but the code
may have been compiled with Visual Studio. Similar issues
arise with Mingw.

At appropriate places, and if using Visual Studio or Mingw,
I added calls to the path conversion code.
Apparently I forgot to find all the places where this
conversion was needed. So this pr does the following:
1. Push the calls to the converter to the various libXXX
   directories and out of libdispatch/dfile.c.
2. Add conversion calls to other parts of the code like oc2.

I also turns out that conversion code in dapcvt.c
had a bug when handling DAP Byte type under visual studio.

Notes:
1. there may still be places I missed that need to do path conversion.
2. need to make sure that calls to e.g. H5open also use converted path.

### CODE REVIEW

**Comment by WardF** [comment]
Fails to build on my Windows/Visual Studio/cmake build with the following error.  It appears to be an issue if a developer has a developer kit for Windows 8.1 installed, which seems like something we might need to accommodate? I'm not certain.  I will look into this, we need to get this fix in so that the other pull requests for `4.5` can be tested.

````{.sh}
"G:\netcdf-c\build\liblib\netcdf.vcxproj" (default target) (1) ->
"G:\netcdf-c\build\libdap4\dap4.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2def.h(221): error C2011: 'sockaddr': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2def.h(421): error C2059: syntax error: 'constant' [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2def.h(615): error C2011: 'sockaddr_in': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(136): error C2011: 'fd_set': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(180): error C2011: 'timeval': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(236): error C2011: 'hostent': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(249): error C2011: 'netent': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(256): error C2011: 'servent': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(268): error C2011: 'protoent': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(364): error C2011: 'WSAData': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(462): error C2011: 'sockproto': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(504): error C2011: 'linger': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1650): error C2375: 'accept': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1672): error C2375: 'bind': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1691): error C2375: 'closesocket': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1710): error C2375: 'connect': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1731): error C2375: 'ioctlsocket': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1752): error C2375: 'getpeername': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1773): error C2375: 'getsockname': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1796): error C2375: 'getsockopt': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1817): error C2375: 'htonl': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1834): error C2375: 'htons': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1852): error C2375: 'inet_addr': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1870): error C2375: 'inet_ntoa': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1971): error C2375: 'listen': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(1989): error C2375: 'ntohl': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2006): error C2375: 'ntohs': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2026): error C2375: 'recv': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2051): error C2375: 'recvfrom': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2077): error C2375: 'select': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2101): error C2375: 'send': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2126): error C2375: 'sendto': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2152): error C2375: 'setsockopt': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2174): error C2375: 'shutdown': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2195): error C2375: 'socket': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2220): error C2375: 'gethostbyaddr': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2240): error C2375: 'gethostbyname': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2258): error C2375: 'gethostname': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2298): error C2375: 'getservbyport': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2317): error C2375: 'getservbyname': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2335): error C2375: 'getprotobynumber': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2352): error C2375: 'getprotobyname': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2373): error C2375: 'WSAStartup': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2392): error C2375: 'WSACleanup': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2409): error C2375: 'WSASetLastError': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2426): error C2375: 'WSAGetLastError': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2447): error C2375: 'WSAIsBlocking': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2465): error C2375: 'WSAUnhookBlockingHook': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2483): error C2375: 'WSASetBlockingHook': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2501): error C2375: 'WSACancelBlockingCall': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2524): error C2375: 'WSAAsyncGetServByName': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2552): error C2375: 'WSAAsyncGetServByPort': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2579): error C2375: 'WSAAsyncGetProtoByName': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj                                                 ]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2605): error C2375: 'WSAAsyncGetProtoByNumber': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxpr                                                 oj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2631): error C2375: 'WSAAsyncGetHostByName': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2659): error C2375: 'WSAAsyncGetHostByAddr': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2683): error C2375: 'WSACancelAsyncRequest': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(2704): error C2375: 'WSAAsyncSelect': redefinition; different linkage [G:\netcdf-c\build\libdap4\dap4.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\ws2ipdef.h(715): error C2011: 'ip_mreq': 'struct' type redefinition [G:\netcdf-c\build\libdap4\dap4.vcxproj]
````

**Comment by WardF** [comment]
My fix is going to be roughly as follows. Check for winsock2.h and, if it exists, add the include (previously discussed, I forget what it was exactly, `#define _WINSOCK...`) otherwise don't.

**Comment by WardF** [comment]
I added a check in cmakelists.txt for winsock2.h, and made the `#define _WINSOCKAPI` definition conditional on `#ifdef HAVE_WINSOCK2_H`.  At a glance it fixed the compilation issue I was seeing, running windows tests now.

**Comment by WardF** [comment]
New errors in `tst_ncdap3.sh`:

````{.sh}
$ ./tst_ncdap3.sh
*** Testing DAP to netCDF-3 translation
        Base URL: file:///g/netcdf-c/build/ncdap_test/testdata3
        Client Parameters: [log][cache]
*** Testing: synth1 ; url=[log][cache]file:///g/netcdf-c/build/ncdap_test/testdata3/synth1
command: /g/netcdf-c/build/ncdump/ncdump.exe [log][cache]file:///g/netcdf-c/build/ncdap_test/testdata3/synth1
$dapthrow: err=-125 line=2490 file=G:\netcdf-c\libdap2\ncd2dispatch.c
$dapthrow: err=-125 line=2490 file=G:\netcdf-c\libdap2\ncd2dispatch.c
$dapthrow: err=-43 line=2320 file=G:\netcdf-c\libdap2\ncd2dispatch.c
$dapthrow: err=-43 line=2320 file=G:\netcdf-c\libdap2\ncd2dispatch.c
$dapthrow: err=-43 line=2320 file=G:\netcdf-c\libdap2\ncd2dispatch.c
````

**Comment by WardF** [comment]
Full error here: http://cdash.unidata.ucar.edu/testDetails.php?test=71957&build=3796

**Comment by DennisHeimbigner** [comment]
Are you running this with visual studio or with mingw?

**Comment by WardF** [comment]
Visual Studio

**Comment by WardF** [comment]
I don't use mingw, so I forget to be specific sometimes, but usually when I say 'Windows' what I mean is Visual Studio.

**Comment by DennisHeimbigner** [comment]
I turned off the debug noise so we can see what is really happening. Do a pull

**Comment by WardF** [comment]
Testing now.  Also downloading the VS installer for 2017 so I can try with that.

**Comment by WardF** [comment]
Updated results: http://cdash.unidata.ucar.edu/testDetails.php?test=71967&build=3798

**Comment by DennisHeimbigner** [comment]
Any chance of getting the files /g/netcdf-c/build/Testing/Temporary/*.log

**Comment by WardF** [comment]
Here you go

* [Temporary.zip](https://github.com/Unidata/netcdf-c/files/1149778/Temporary.zip)

**Comment by DennisHeimbigner** [comment]
I give up; I cannot get enough info to see what is going wrong.
This command is failing:
 /g/netcdf-c/build/ncdump/ncdump.exe [log][cache]file:///g/netcdf-c/ncdap_test/testdata3/ber-2002-10-01.nc
but no idea why. ncdump should be outputting an error message somewhere, but I cannot find it.

**Comment by DennisHeimbigner** [comment]
Ok, I added a ber specific test that has (I hope) more debug info.
Need to get that ncdump output somehow. I will also need the
contents of Temporary again after you rerun.

**Comment by WardF** [comment]
Testing now, will post results shortly.

**Comment by WardF** [comment]
Latest failures (2 now, I assume one is a test you added for this):

* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=3886

**Comment by WardF** [comment]
It looks like the file on Windows is failing because it has carriage returns and the 'gold standard' file does not.

**Comment by DennisHeimbigner** [comment]
That would explain the failure. Not sure why only that one is failing. A whole bunch of others
should also fail. Wish there was diff option that ignored line ending differences.

**Comment by DennisHeimbigner** [comment]
Also, why does it appear to work with the community edition? I am very confused.

**Comment by WardF** [comment]
Well, it's failing with the community edition on my end.

**Comment by WardF** [comment]
And the `\r\n` are being captured inside quotes for this file, not at the end of the line itself? I'm not sure if it's like that in other files as well.

**Comment by DennisHeimbigner** [comment]
Also, why does it appear to work with the community edition? I am very confused.
There is an option for diff called  --strip-trailing-cr
but I do not know if all versions of diff support it.

**Comment by DennisHeimbigner** [comment]
Perhaps the issue is that this is an opendap generated file and it just
happens that it is our only test case that contains embedded \r\n.

**Comment by WardF** [comment]
> Perhaps the issue is that this is an opendap generated file and it just
happens that it is our only test case that contains embedded \r\n.

That would explain it, although then I would expect this test to fail on linux.  Also, the 'expected' file would have the embedded `\r\n` as well I'd think?

**Comment by DennisHeimbigner** [comment]
If I do a diff -w on the two files (ber-2002-10-01.nc.dmp)
one with \r and one without, my cygwin diff says they are the same.
Perhaps cygwin diff does equivalent of  --strip-trailing-cr be default.
But if the problem is with diff, then you should be seeing a lot of errors.

**Comment by WardF** [comment]
I would agree, except that we aren't seeing any other failures; in this run, only those 2 tests fail, where the other 166 pass:

* http://cdash.unidata.ucar.edu/viewTest.php?onlypassed&buildid=3886

I'll dig into it more here as well.

**Comment by WardF** [comment]
On OSX, when I run the following command, I end up with a file that only contains newline characters.

    $ ./ncdump [log][cache]file:///Users/wfisher/Desktop/gitprojects/netcdf-c/ncdap_test/testdata3/ber-2002-10-01.nc > tmp

When I run the same command on Windows in an MSYS shell (which is just a CMD shell + bash, unlike the cygwin linux shell), I get a file containing carriage return and newline characters.  

    Ward@livingston MINGW64 /g/netcdf-c/build/ncdump
    $ ./ncdump [log][cache]file:///g/netcdf-c/ncdap_test/testdata3/ber-2002-10-01.nc > tmp2

Running diff with `--strip-trailing-cr` doesn't work in the MSYS shell, I suspect, because the `\r\n` aren't actually trailing, they are contained *within* a string on a line.  E.g:

    <presentationForm>\r\n",
        <CI_PresentationFormCode codeSpace=\"\" codeList=\"\" codeListValue=\"\" />\r\n",

So, something in ncdump + DAP appears to be following platform-native cr/cr+newline rules.

**Comment by WardF** [comment]
I just thought about what I'm seeing, and I'm assuming the XML captured in the attribute `Lineage.History` *should* contain newlines, since it is metadata being intentionally inserted.  The 'normal' newlines at the end of each actual line are as expected; `\n` characters.  So this is specific to the strings embedded in the global attribute that has newlines already present.  Somewhere in the string handling for the attribute, an `\r` is being inserted.

**Comment by DennisHeimbigner** [comment]
Don't be fooled by "...\r\n". Each of those is just two ordinary characters e.g. "\" followed by "r"
and are not the same as an embedded carriage return. They are not the problem. The problem
is any actual crlf characters at the end of a line.

**Comment by DennisHeimbigner** [comment]
I don't know if your editor will show carriage returns or not. In emacs with appropriate
settings, it will show ....^M

**Comment by WardF** [comment]
I disagree, Dennis; that's not what I'm seeing.  The attached screenshot clearly shows that the issue in these lines exist between the quotation marks at each line.   The dos-style line endings also exist, but those are handled by the `-w` flag.  I believe the error is that the strings are different, one captures `\n` at the end of the line and the other captures `\r\n`.

screen shot 2017-07-17 at 2 00 27 pm

**Comment by WardF** [comment]
To clarify: the output from OSX (and I believe Linux) is on the left, the output from the Windows CMD shell is on the right.  And that is output from `ncdump` as outlined above.

**Comment by WardF** [comment]
As a sanity check I ran `dos2unix` on the tmp file generated on my Windows VM to remove the line endings; I then ran diff against the `master` file in `expected3`, and the failure persists.  I also ran meld against it as well (see attached screenshot).  

screen shot 2017-07-17 at 2 04 51 pm

**Comment by DennisHeimbigner** [comment]
I stand corrected. This is more complicated than I thought. When I look at the
generated ber-2002-10-01.nc.dmp and the baseline expected3/ber-2002-10-01.nc.dmp
On my system, neither contains a \r embedded in the strings. but yours clearly do so.
Since neither the \r or \n occurs in the original DAP input (the ber...das file)
this means that the problem is, as you note, either ncdump or the libdap2 code.
Let me investigate who is adding those characters.

**Comment by DennisHeimbigner** [comment]
My current speculation is that I am reading ber-2002-10-01.nc.das as a text file
and if memory serves, that causes windows to convert \n to \r\n. This then propagates
upward to produce the observed error. Apparently the ber file is our only
dap test file that has newlines occurring in a das attribute. All the rest must be single line
strings.
Now if I can just remember what flags I need to set to get windows to read the file as binary
instead of text mode.

**Comment by DennisHeimbigner** [comment]
I added code to force the mode to always be binary. This applies
to visual studio and to cygwin.

**Comment by WardF** [comment]
Feels like we're on the right track, although I'm seeing the same issue still:

* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=3916

**Comment by WardF** [comment]
@DennisHeimbigner can you point me to where the string is being read?  I will step through the debugger and confirm our speculation.

**Comment by WardF** [comment]
It occurs to me that wherever this is occurring, it is specific to the DAP code; we do not see this behavior in Windows with strings in netCDF files read locally.

**Comment by WardF** [comment]
`git bisect` reports `dc9e31df6838d7e95e8a2d8d316bbdae271d2cfc` as the first bad commit.  This is less encouraging as I'd hoped, as the following is in the associated commit notes:

>  1. ncdap_test/tst_ncdap3.sh was using an empty test set.
       restored the testing of datasets.

So, it appears it may not be possible to determine how long this issue has existed.

**Comment by DennisHeimbigner** [comment]
The code that reads a multiline string attribute in DAP is 
in oc2/daplex.c line 136 which should read '	} else if(c == '"') {'
The code processes a dap string constant.
The code is somewhat complicated because the dap spec
is not clear on handling embedded backslash characters (except for \")
The relevant #defines at the front of that file say:
#define DAP2ENCODE
#ifdef DAP2ENCODE
#define KEEPSLASH
#endif
So DAP2ENCODE and KEEPSLASH are enabled.
Perhaps I should modify that code to explicitly suppress \r.


'

**Comment by WardF** [comment]
> So DAP2ENCODE and KEEPSLASH are enabled.
Perhaps I should modify that code to explicitly suppress \r.

My only hesitance there is if the string contains an `\r` intentionally; I wouldn't want to remove that.  I'll take a look at this after the techies brown bag meeting.  Also, this is a failure in the test, but does that mean the behavior itself is incorrect? Would it potentially be ok that we see different behavior like this?  Now that I've thought about it for a moment, probably not; we'd expect ncdump to return the same file regardless of platform.

**Comment by WardF** [comment]
In the short term, it would be easy enough to add a `sed` statement to replace `\r\n`. I do something similar already in some tests, because Windows would print a different number of significant digits for scientific notation.  In this case, however, we're seeing a modification of the underlying data, so I guess the test is actually working as expected and raising an alert about unexpected behavior.

**Comment by DennisHeimbigner** [comment]
Since the dap spec is silent on this issue, perhaps we should just decide what we
want to do, document it, and move on.

**Comment by WardF** [comment]
> Since the dap spec is silent on this issue, perhaps we should just decide what we
want to do, document it, and move on.

That works for me; if it is undocumented and we can do that, I'd say we should replace any trailing `\r\n` pairs contained within/at the end of each line of  a multiline string (the only place we're seeing this I think) with `\n'`.  We can revisit this if it ever becomes an issue.  How does that sound?

**Comment by DennisHeimbigner** [comment]
> we should replace any trailing \r\n pairs contained within/at the end of each line of a
> multiline string (the only place we're seeing this I think) with \n'
That sounds right.
I am beginning to think that my change to force the default mode to be binary
did not work. So I added a change to force binary mode at open.
You might run again and see if that worked.

**Comment by WardF** [comment]
I will give that a test as well and follow up.

**Comment by WardF** [comment]
Sadly, still fails.  I'd say lets do the `\r\n` -> `\n` thing and, once that's in, get the next rc out asap.

**Comment by WardF** [comment]
Any progress on this issue? Once this is in, I will get the rest of the pull requests merged in and rc2 out.

**Comment by DennisHeimbigner** [comment]
I just added a commit to forcibly remove <cr>
when doing comparisons in the ncdap_test tests.
You need to see if this fixes the problem.

**Comment by WardF** [comment]
Still seeing the failures: http://cdash.unidata.ucar.edu/viewTest.php?onlydelta&buildid=4151

**Comment by WardF** [comment]
Ok I think I've got it nailed down. Will close this out when I get it merged in.

**Pull request merged**
