### PR TITLE
Fix for Github issue netcdf-c 300

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
Modified provenance code to allocate the minimal space
needed for _NCProperties attribute in file.  Basically
required using malloc in the provenance code and in ncdump.
Now an empty file is about 66 bytes larger than pre-provenance.
Otherwise should cause no externally visible effects.
Also removed the ENABLE_FILEINFO from configure.ac since
the provenance code is no longer optional.

### CODE REVIEW

**Comment by WardF** [comment]
The non-serial tests are failing but I don't know why yet; looking into it and will report what I find between other meetings today.

**Comment by WardF** [comment]
My mistake. It's not parallel images failing, it appears to be ones which run without netcdf-4 enabled, so it's probably just some option/code/include fenceposting that's needed.

**Comment by DennisHeimbigner** [comment]
When I run by hand with netcdf-4 turned off, it works, both with automake and cmake.
Is there any way to get travis to output more info, I can turn on some debug output flags,
but travis swallows it up.

**Comment by WardF** [comment]
It's possible to open the raw log from travis; when you go in to view the build log, at the top of the output panel on the right there is a button that says 'Raw log'.

The issue is with 32-bit systems.  In `ncdump/tst_ncgen4.sh', the following is shoping up when testing special attributes:

~~~~

*** Testing: ref_tst_special_atts3
*** SUCCEED: ref_tst_special_atts3
*** Testing: ref_tst_special_atts
47c47
< 		:_NCProperties = "version=1|netcdflibversion=4.4.2-development|hdf5libversion=1.8.17�	I" ;
---
> 		:_NCProperties = "version=1|netcdflibversion=4.4.2-development|hdf5libversion=1.8.17I" ;
*** FAIL: ref_tst_special_atts

~~~~

**Comment by DennisHeimbigner** [comment]
Ok, the string is not being null terminated. I will recheck my code.
=Dennis

**Comment by WardF** [comment]
Super thanks Dennis! I'll get these merged ASAP.

**Pull request merged**
