### PR TITLE
A pull request based on Unidata's ghpull-319-arm-wkliao

### PR DESCRIPTION
**Pull request by wkliao**
This is a new pull request built on branch [ghpull-319-arm-wkliao](https://github.com/Unidata/netcdf-c/tree/ghpull-319-arm-wkliao)

### CODE REVIEW

**Comment by WardF** [comment]
Merged into branch `ghpull-375` for evaluation.  Testing across platforms but currently failing to build `nc_test` on Windows w/ Visual Studio.  Output from one such build can be viewed here:

* http://cdash.unidata.ucar.edu/viewBuildError.php?buildid=221

I'm guessing it is an issue with Visual Studio requiring different includes under some circumstances; referring back to the old test_read and test_write files should provide guidance as I don't recall off the top of my head and don't have the time at the moment to look at the new `.m4` files.  I have to switch gears but will come back to this as soon as I can.

**Comment by WardF** [comment]
Reopened; didn't mean to close, clicked wrong button.

**Comment by WardF** [comment]
Confirmed that it is working on ARM; yay, thanks for the help @wkliao .  The Visual Studio issues will be easy enough to sort through I feel, once I have time to sit down and look at it.

**Comment by wkliao** [comment]
The compile error is due to ssize_t requires a different header on Visual Studio, io.h, from most of the Linux compilers, unistd.h. I believe part of your fix [53c018a](https://github.com/Unidata/netcdf-c/commit/53c018a3f67d9399acb642ecab4fae8cf8e2672c) for file test_read.m4 should resolve this error for Visual Studio.

**Comment by WardF** [comment]
One would think, but a fresh checkout from GitHub fails to build.  I will pursue this later this week when I get a chance.  

* http://cdash.unidata.ucar.edu/viewBuildError.php?buildid=255

**Comment by wkliao** [comment]
From libsrc/memio.c, I am seeing io.h is included in two places. One is within the if defined macro of #if defined (_WIN32) || defined (_WIN64) and the other is #ifdef _MSC_VER.
Maybe you need to do the same for test_read.m4.

**Comment by wkliao** [comment]
Hi, Ward,
In 80d2b91, the following lines added in nc_test/test_read.m4 should be moved to after include<tests.h>, which includes config.h defining HAVE_SSIZE_T.
36 +#ifndef HAVE_SSIZE_T
37 +typedef int ssize_t;
38 +#endif

**Comment by WardF** [comment]
The `_WIN32`,`_WIN64` conditionals were originally added to accommodate cross-compiled builds, before we had Visual Studio/cmake support.  I have no doubt there are a lot of places where things like that can be collapsed into the (usually) nearby `_MSC_VER` conditionals, but it can be tricky.  It will need done at some point.  Thanks for pointing out the `HAVE_SSIZE_T` conditional, I caught that too.  Doing a couple last tests across various platforms now.

**Comment by WardF** [comment]
Seeing test failures on 32-bit parallel platforms. Investigating.

**Comment by WardF** [comment]
In addition to the various 64-bit platforms tested, the branch works fine on 32-bit serial and 32-bit parallel when `libmpich` is used. 32-bit parallel with `openmpi` (version 1.10.2-8ubuntu1) fails.  The 4 failures can be seen here:

* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=322

Of the 4 failures, `t_nc` generates the most interesting error message:

> Error Size of MPI_Offset or MPI_Aint too small for requested format  in file /home/tester/netcdf-c/nc_test/t_nc.c at line 374

I'm not super familiar with MPI development, but this seems to be the most interesting of the errors.  I will pursue this later, but I need to spend some time on another project that is languishing.

**Comment by wkliao** [comment]
I suspect that MPI_Offset is of size 4 bytes on the 32-bit system in testing. When MPI_Offset is of size 4 bytes, PnetCDF turns off the support for CDF-2 and CDF-5 files. Is there a way to see PnetCDF's config.log file on CDash to check whether this is the case?

Does NetCDF support CDF-2 format when off_t is of size 4 bytes?

**Comment by WardF** [comment]
> Does NetCDF support CDF-2 format when off_t is of size 4 bytes?

To the best of my knowledge it does; I would have to do some research to confirm that but it is my understanding that the 'machine independent' aspect of netCDF would apply here; there are no (to my knowledge) limitations on particular formats only supported on particular architectures, reading *or* writing.   I don't expect this would have been knowingly introduced in this pull request (as you mention this specifically in the context of pnetcdf); am I correct?

> Is there a way to see PnetCDF's config.log file on CDash to check whether this is the case?

Not easily, but I am attaching it here.  

Thanks!


[pnetcdf_1.8.1_config.log.zip](https://github.com/Unidata/netcdf-c/files/849681/pnetcdf_1.8.1_config.log.zip)

**Comment by wkliao** [comment]
Checking the latest OpenMPI 1.10.6 and 2.0.2, I found that MPI_Offset is of size 4 bytes on 32-bit machines. But in MPICH, it is of size 8 bytes. I posted a question on OpenMPI to check whether this is intended. [3195](https://github.com/open-mpi/ompi/issues/3195)

From your PnetCDF configure log, I can see the support for CDF-2 and 5 was turned off due to the size of MPI_Offset being 4 bytes. I suggest we add a check in configure.ac and CMakeLists.txt to check whether PnetCDF supports CDF-2 and 5 so to disable/enable their tests in nc_test accordingly.

As far as I know, most of the modern OSs support "Large File Support (LFS)" on 32-bit machines. So off_t can be changed from 4 bytes to 8 bytes if the correct compiler flag is used, e.g. -D_FILE_OFFSET_BITS=64. Autoconf macro AC_SYS_LARGEFILE can detect and enable LFS automatically (which is used in both NetCDF and PnetCDF.) I guess today it is hard to find a 32bit machine running an OS that does not support LFS.

Given the above OpenMPI's behavior, I wonder have you used it to build HDF5 and then NetCDF on a 32bit machine and created/accessed a NetCDF-4 file that is lager then 4GB size?

**Comment by wkliao** [comment]
My analysis is when MPI_Offset is 4 bytes, MPI-IO functions will not be able to access file location with offsets greater than 4GB, which should failed NetCDF to access large NetCDF-4 files. For classical 64BIT_OFFSET files, NetCDF should also have fail to access offsets greater then 4GB as lseek() would fail (when using POSIX I/O.)

I built HDF5 1.8.15 using OpenMPI 2.0.2 on the 32-bit machine where MPI_Offset is of 4 bytes.
Running HDF5 "make check" shows the message below in several parallel tests.
"Skipped GB file range test because MPI_Offset cannot support it"

When using that HDF5 to build NetCDF, "make check" failed for nc_test4/tst_parallel3 with error message: "Sorry! Unexpected result, /homes/wkliao/NetCDF/GIT/WKLIAO/netcdf-c/nc_test4/tst_parallel3.c, line: 105" etc. and error message from HDF5:"H5MM.c:62: H5MM_malloc: Assertion `size' failed."

**Comment by WardF** [comment]
Thank you for the information; I'm setting up a 32-bit environment now as well to run the large file tests in.  I have run them in the past on 32-bit, but not when parallel IO is supported.  I appreciate your insight into this, and will see what I can sort out; if the platform cannot support the test that is fine, but it should not manifest as an unexpected failure, so I will want to clean that up.

**Comment by wkliao** [comment]
After an internal discussion with @rsth and @roblatham00, we decided not to support MPI libraries whose MPI_Offset is of size 4 bytes. This is because PnetCDF uses MPI_Offset everywhere. With a 4-byte MPI_Offset, PnetCDF cannot even support CDF-1 classic format, e.g. when CDF-1 files are larger than 4GB, legal on 32-bit machines supporting LFS. In the future releases of PnetCDF, the build process will be aborted when 4-byte MPI_Offset is detected.

As for NetCDF, I suggest not to use OpenMPI on 32-bit machines (and on cdash test). MPICH should be just fine. In addition, you may want to add a note in INSTALL.

From the discussion on OpeMPI issue 3195, the fix in OpenMPI, if there will be one, may not come out soon.

**Comment by WardF** [comment]
That sounds good and, as always, I appreciate your insights into the world of MPI.  I believe we have the pull request in a working state; I need to attend to a different project for a bit but then we will do a review and make sure everything is squared away.  The large file tests issue I mentioned previously is separate from this pull request and will have its own issue.

Thanks again; I'll add something to INSTALL and the release notes that pnetcdf is not supported under 32-bit w/ openmpi, requiring mpich instead.

**Comment by roblatham00** [comment]
There could be some configurations of MPICH that do not have an 8 byte
MPI_Offset -- I think some Solaris environments will not expose the 8 byte
off_t type if MPICH  requests strict c89 standards compliance.  I don't
think many deployments will use that in practice, but MPICH uses
--enable-strict to catch any portability issues during development.

So either MPICH or OpenMPI might in some configurations have a problem with
a small MPI_Offset.

**Comment by DennisHeimbigner** [comment]
I think we should send a note asking about this (4 vs 8 byte)
on the netcdf mailing list.

**Comment by WardF** [comment]
I agree; I'm also adding a section to the documentation about this, easily discoverable.  This way our user community should be able to find it pretty easily, and in a year I can avoid having to diagnose this problem from scratch again.

**Comment by DennisHeimbigner** [comment]
This is a large change; can we review this at the next netcdf meeting?

**Comment by WardF** [comment]
Yes; we had reviewed at a previous meeting and had come to some conclusions that were then sidelined until we could get the various tests working.  Now that the tests are working I'm starting a review of the changes (to refresh my memory) so that I'll be prepared to discuss the changes.  

At the very minimum it will be good to get the changes in allowing pnetcdf 1.8.1 to work with netCDF; currently the latest version that passes the tests is 1.6.1.  We can discuss the other changes again at the next meeting.

**Comment by WardF** [comment]
The upstream branch containing the changes in #319 and #375 has been merged; closing this pull request out, as it wasn't automatically detected as merged.

**Pull request closed without merging**
