### PR TITLE
check szip parameters for validity, plus all other outstanding szip work...

### LINKED ISSUE #1473: Allow parallel IO with filters ...
As of version HDF5 1.10.2, it is possible to use MPI and filters together.
We should probably modify our checks to allow this.

### LINKED ISSUE #1612: nc_def_var_filter() should say in docs that it will cause vars to be switched to chunking
Filters only work with chunked data.

nc_def_var_filter() needs to check that a var is chunked and return NC_EINVAL when an attempt is made to set a filter on a contiguous (or compact) variable.

I have a fix and will put a PR up shortly.

### LINKED ISSUE #1615: should check to prevent szip error: "potential pixels per block greater than total number of elements in the chunk"
When using szip compression, it's possible to specify incorrect parameters, which result in HDF5 error when the write is attempted (i.e. not at the time the settings are set, unfortunately).

For example, this (fortran) code causes the failure, if the variable identified by varid(1) has a size of less than 32 elements:

```
C     Turn on szip compression for var 1.
      retval = nf_def_var_szip(ncid, varid(1), 32, 32)
      if (retval .ne. 0) stop 3

```

In this case, we get the following output from HDF5:

```
ERROR: file nc4hdf.c, line 1054.
NetCDF: HDF error
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: H5D.c line 151 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 337 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1592 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1833 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1639 in H5L__link_cb(): unable to create object
    major: Links
    minor: Unable to initialize object
  #007: H5Oint.c line 2460 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: H5Doh.c line 300 in H5O__dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #009: H5Dint.c line 1233 in H5D__create(): unable to set local filter parameters
    major: Dataset
    minor: Unable to initialize object
  #010: H5Z.c line 925 in H5Z_set_local(): local filter parameters not set
    major: Data filters
    minor: Error from filter 'set local' callback
  #011: H5Z.c line 854 in H5Z_prepare_prelude_callback_dcpl(): unable to apply filter
    major: Data filters
    minor: Error from filter 'can apply' callback
  #012: H5Z.c line 769 in H5Z_prelude_callback(): error during user callback
    major: Data filters
    minor: Error from filter 'set local' callback
  #013: H5Zszip.c line 213 in H5Z_set_local_szip(): pixels per block greater than total number of elements in the chunk
    major: Invalid arguments to routine
    minor: Bad value

```

This would also occur if the chunksize was set to < 32 for that dim in that var. (That;'s what is happening behind the scenes, the dim length is only 22, so that ends up being the chunksize on that dim, and that's < 32).

One challenge here is that we often don't know the chunksizes when szip compression is turned on. 

However, some things that can easily be done:
* Check against the size of the var dims, which is known, and would have caught this case.
* Document this clearly in C and Fortran docs for szip compression.
* We can detect this error at the time that metadata are written (i.e. enddef) rather than waiting for an attempted write to the variable and then failing.

I am working on szip in netcdf-fortran now; once I get that sorted I will swing back around and fix this issue.

### LINKED ISSUE #1616: need better handling of case when both szip and zlib are chosen for compression
If the user tries to turn on both zlib and szip compression, zlib silently wins.

But instead, each should check if the other has already been selected, and return an error.

So if nc_def_var_szip() has been called on a var, then a future call to nc_def_var_deflate() should return an error, and vice versa. This should also be documented in both functions.

### LINKED ISSUE #1618: nc_inq_var_szip() does not have a way to tell user that szip compression is not in use, but it needs to
The prototype for nc_inq_var_deflate() is:
```
EXTERNL int
nc_inq_var_deflate(int ncid, int varid, int *shufflep,
                   int *deflatep, int *deflate_levelp);

```
The deflatep pointer allows netcdf to return a 0 if the zlib filter is not in use on this var. This same convention is used with shuffle filter and fletcher32. But not szip.

The prototype for nc_inq_var_szip() lacks this extra parameter:

```
EXTERNL int
nc_inq_var_szip(int ncid, int varid, int *options_maskp, int *pixels_per_blockp);

```

Well this is my mistake, I didn't include a parameter to pass back whether the szip filter was in use or not, just its parameters.

In this case I will use the options_maskp for this purpose. The options mask is never 0 when szip is in use, so I will return a 0 in the options_maskp pointer (if not NULL) and that will allow the user (and my tests) to know that the var does not have szip compression on. I will then document this.

Currently the code returns NC_EFILTER if szip is not in use on the var. That's not how we handle this in the case of deflate, fletcher32, or shuffle filter, or any other inq function, so I am going to make szip work like deflate in this regard. That is, it will return NC_NOERR for a var without szip compression, but will set options_maskp to point at 0.

### LINKED ISSUE #1622: nc_inq_var_szip() fails before enddef for szip filter
This is a pretty minor issue, but it stands in the way of several other szip issues.

When setting the szip filter (with nc_def_var_filter() or nc_def_var_szip()), subsequent calls to nc_inq_var_szip() before enddef will fail to find that szip is set. From test_szip.c:

```
    szip_params[0] = H5_SZIP_NN_OPTION_MASK;
    szip_params[1] = H5_SZIP_MAX_PIXELS_PER_BLOCK_IN;
    { int stat = nc_def_var_filter(ncid, varid, HDF5_FILTER_SZIP, 2, szip_params);
       if(stat) {
         fprintf(stderr,"XXX: %d %s\b",stat,nc_strerror(stat));
         ERR;
       }
    }
    if(nc_inq_var_szip(ncid, varid, &options_mask_in, &pixels_per_block_in)) ERR;
    if(!(options_mask_in & H5_SZIP_NN_OPTION_MASK)) ERR;

```
I added the last two lines of code, and the second fails, because of this code in nc_inq_var_szip() (in dvarinq.c):

```
    if(id != H5Z_FILTER_SZIP || nparams != 4) 
         return NC_EFILTER; /* not szip or bad # params */ 

```
The problem is that szip has only 2 parameters until it is set by HDF5, then the number becomes 4. ;-)

Once enddef happens, the filter info is written to the dataset on disk, and from then on, nc_inq_var_szip() works correctly.

I will have a fix up shortly.

### PR DESCRIPTION
**Pull request by edwardhartnett**
There are some invalid parameters for szip that HDF5 will only report at enddef time. This is not very nice for users! ;-)

So now setting szip with invalid parameters will be detected by netcdf-c, and the user will get a NC_EINVAL, and all will be right with the world again.

This PR includes all other outstanding szip PRs, which are required to get to this point. ;-)

Fixes #1615
Fixes #1622
Fixes #1473
Fixes #1618
Fixes #1616
Fixes #1612

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@WardF this is ready to merge. It has passed all your CI and all my CI! ;-)

This will complete the szip work and close all szip related issues.

**Comment by edwardhartnett** [comment]
@WardF can we get this PR merged soon? It contains a lot of important changes and I don't want the PR to go stale. ;-)

Thanks,Ed

**Comment by DennisHeimbigner** [comment]
I concur with Ed, but for a different reason. The multifilter code
I built is going to mess strongly with Ed's szip-related changes.
So I need it be in the master as a stable base against which
to modify the multifilter code to match his changes.

**Comment by WardF** [comment]
Thanks, both of you!

**Comment by edwardhartnett** [comment]
Well @DennisHeimbigner that makes me nervous! ;-)

But I have changed the szip code to use nc_def_var_filter(), so hopefully that will make some of your changes easier.

**Comment by DennisHeimbigner** [comment]
Adding support for multiple filters turned out to be a big change.
In order to avoid a lot of special casing, I chose to bring szip and deflate
into the more general framework.

**Pull request merged**
