### PR TITLE
CMake: Use helper libraries for nczarr tests

### PR DESCRIPTION
**Pull request by ZedThree**
Avoids rebuilding the same files multiple times. This cuts down on duplicated warnings, and gives a little bit of a speedup to the build (~5-10%)

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
I am surprised the speed up is as much as you say. IMO the files are not very big.

**Comment by ZedThree** [comment]
Yes, me too! I suspect it's actually mostly from not printing the warnings many times rather than a significant build speed up

**Review by WardF — APPROVED** [review]

**Comment by WardF** [comment]
Great change, thanks! I'm working through all these great PR's we've seen. As backlogs go, I'm happier to have these improvements than not.  Thanks!

-Ward

**Comment by WardF** [comment]
There does appear to be an issue under Visual Studio, but I'll take a look at that and push a fix if required.

**Comment by WardF** [comment]
The import/export mechanic required by dynamic shared libraries on Windows is complicating this a fair bit; the common helper library mechanism introduced is (as exists in the PR) insufficient, insofar as there are unresolved symbols when linking via Visual Studio.

**Comment by ZedThree** [comment]
Ah, didn't even think about that! Would making it `STATIC` help? Or failing that, is there a flag to export all symbols?

**Comment by WardF** [comment]
Setting `STATIC` is the fix I'm testing now, although I had to tweak a couple other minor things. This is why we have the Windows CI at least :).  Adding `STATIC` has fixed the issue reported, I'm running through the compile/run test loop locally now, then I'll make sure I haven't introduced anything strange/unexpected under Linux.

**Comment by WardF** [comment]
There was also some fiddling with setting `-DDLL_NETCDF` and `-DDLL_EXPORT` as needed; nothing major, just the fiddly cross-platform bits that we (the Unidata folk) are obliged to worry about so that others can... worry less about it XD.  Thanks though,  hopefully this will get merged in short order.

**Comment by WardF** [comment]
Speaking of, thanks for this and all the other PR's you've put up recently.  They'll all have to be looked at under similar lenses, and I know it's taking a bit of time to get to them, but they're sitting there staring at me where I can't accidentally forget about them XD. Lots to do, I'm sure you understand.

**Comment by ZedThree** [comment]
> Speaking of, thanks for this and all the other PR's you've put up recently. They'll all have to be looked at under similar lenses, and I know it's taking a bit of time to get to them, but they're sitting there staring at me where I can't accidentally forget about them XD. Lots to do, I'm sure you understand.

Yep, no worries -- netCDF is pretty crucial in our field, so I appreciate all your work, and I'm just happy to be able to give something back! As a heads up, I'm intending to get netCDF to zero warnings over the next month or so, so there are more PRs incoming I'm afraid! I figured you would rather lots of smaller PRs than one big enormous one :smile:

**Comment by WardF** [comment]
Sounds good; just bear in mind we support Windows (Visual Studio), 32-bit *and* 64-bit hardware, and Big Endian machines as well as Little. All that is to say, sometimes the warnings are a bit trickier than they initially appear :).

**Pull request merged**
