### PR TITLE
The coord dimids should be written for all variables

### PR DESCRIPTION
**Pull request by gsjaardema**
See discussion in #1279

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I think this is a good change...

**Comment by gsjaardema** [comment]
Here is some testing on this change with the `mix-nc4.g` file attached to #1279 
```
1. read nc4, no1ddimid, write nc4:  14.668
2. read nc4, no1ddimid, write nc3:  11.131
3. read nc3,            write nc3:   0.296
4. read nc4, all dimid, write nc4:   6.917
5. read nc4, all dimid, write nc3:   3.339
6. read nc3,            write nc4:   3.714


Estimated time to read a nc4, no1ddimid: 11 seconds (2) and (1) - (6)
Estimated time to read a nc4, all dimid: 3.2 seconds(5) and (4) - (6)
```

The `mix-nc4.g` file does not have the coordinate dimid for 1D variables, so bullets 1 and 2 measure the reading of that file and then writing it out to either a netcdf-3 or netcdf-4 format file using nccopy.

Based on these timings, the difference in reading the file with and without the 1D variables having the coordinate dimid can be estimated and it looks like there is a reduction of time from ~11 seconds down to ~3.2 seconds  which is significant for a file with lots of 1D variables.  It is a little disheartining to see the overhead of the netcdf-4 format, but this test probably amplifies that situation a little more than normal.  I do have cases where the netcdf-4 output is faster or at least comparable.

**Comment by edwardhartnett** [comment]
Not sure what is failing here...

**Comment by gsjaardema** [comment]
@edwardhartnett The test that is failing is the rename variable test on line 554 of `nc_test4/tst_vars2.c`  I'm not sure yet why it is failing.  It fails on the `H5Lmove` call in `hdf5var.c`   It seems to be failing deep down in HDF5 under`H5G__traverse_real` in `H5L__move_cb` with "unable to follow symbolic link".  The name at this point is the new name of the variable and it is trying to "insert the link into its new position".

I don't know if the attributes need to be deleted before the variable can be renamed... I will check if there is a test of a 2D variable renaming and see if that works or does anything special...

But I think that is the one and only test failing...

**Comment by gsjaardema** [comment]
OK, I have a test that renames a 2D variable.  It seems to run correctly with no errors, but at the end, the file throws an HDF error if you try to ncdump it.  This is with an unmodified NetCDF file.  Can you run this and see if you see the same results... Or tell me what I did wrong...
[test-rename.c.txt](https://github.com/Unidata/netcdf-c/files/6957749/test-rename.c.txt)

**Comment by gsjaardema** [comment]
I think this PR is ready for merging.  There is one test failing, but that is a netCDF-4 variable renaming test and #2070 shows that variable renamings do not work correctly in netCDF-4 files if they have the coordinate dimid attribute attached.  This PR makes all variables have the coordinate dimid attribute (previously 1D variables didn't), so I don't think this change can be fixed to make the test fix without rewriting the variable renaming code...

**Comment by gsjaardema** [comment]
Does this need anything more from me to be considered for the upcoming 4.8.1 release?  It definitely speeds up the reading of our complex files...

**Comment by WardF** [comment]
Looks great, merged into 4.8.1 wellspring, the merge back into main development branch will be forthcoming.

**Pull request merged**
