### PR TITLE
Manage project version with cmake

### PR DESCRIPTION
**Pull request by K20shores**
This PR defines the version in the cmake `project` call. CMake will automatically parse the major, minor, and patch versions.

The [version](https://cmake.org/cmake/help/latest/command/project.html#options) option defines a set of variables useable in the project, including configured files. For example, the major version is available using a mix of the project name (`netCDF`) and the part of the version you want: `netCDF_VERSION_MAJOR`

### CODE REVIEW

**Comment by WardF** [comment]
Thanks @K20shores! There's a CLA button to click, too, that enables things on our end.  It's an organizational thing, but clearly not across the entire organization XD.

**Review by WardF — COMMENTED** [review]
Can you update `configure.ac` to change the variable name for consistency? As it stands, `configure`-based builds will fail to properly generate `netcdf_meta.h` since it will create `NC_VERSION_x` variables.

**Comment by K20shores** [comment]
@WardF I made that change. Again, if you'd prefer, I can use the variables that cmake sets to recreate the `NC_*` version variables; I figured that it's probably at least a little better to put the version in the `project` command so that cmake has the version information which can affect downstream projects.

**Review by WardF — APPROVED** [review]

**Comment by WardF** [comment]
Looks good @K20shores, thanks!

**Pull request merged**
