### PR TITLE
cleaned up version of ncid-changing functions for PIO integration...

### PR DESCRIPTION
**Pull request by edhartnett**
This is a cleaned up version of #1483. There has been a long discussion there about what this PR is about.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@WardF this has been cleaned up and approved by @DennisHeimbigner and is ready to merge. It would be great if it could get in this week.

**Comment by WardF** [comment]
No problem; now that we squashed the issue with netCDF-C and
netCDF-Fortran, returning to PR's in the C branch is next on the list.

**Comment by WardF** [comment]
Thanks for providing this abbreviated PR, Ed! Tagging @DennisHeimbigner for his input as well.

**Comment by edwardhartnett** [comment]
Thanks!

**Pull request merged**
