### PR TITLE
Primary change: add dap4 support

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
Specific changes:
1. Add dap4 code: libdap4 and dap4_test.
   Note that until the d4ts server problem is solved, dap4 is turned off.
2. Modify various files to support dap4 flags:
	configure.ac, Makefile.am, CMakeLists.txt, etc.
3. Add nc_test/test_common.sh. This centralizes
   the handling of the locations of various
   things in the build tree: e.g. where is
   ncgen.exe located. See nc_test/test_common.sh
   for details.
4. Modify .sh files to use test_common.sh
5. Obsolete separate oc2 by moving it to be part of
   netcdf-c. This means replacing code with netcdf-c
   equivalents.
5. Add --with-testserver to configure.ac to allow
   override of the servers to be used for --enable-dap-remote-tests.
6. There were multiple versions of nctypealignment code. Try to
   centralize in libdispatch/doffset.c and include/ncoffsets.h
7. Add a unit test for the ncuri code because of its complexity.
8. Move the findserver code out of libdispatch and into
   a separate, self contained program in ncdap_test and dap4_test.
9. Move the dispatch header files (nc{3,4}dispatch.h) to
   .../include because they are now shared by modules.
10. Revamp the handling of TOPSRCDIR and TOPBUILDDIR for shell scripts.
11. Make use of MREMAP if available
12. Misc. minor changes e.g.
	- #include <config.h> -> #include "config.h"
	- Add some no-install headers to /include
	- extern -> EXTERNL and vice versa as needed
	- misc header cleanup
	- clean up checking for misc. unix vs microsoft functions
13. Change copyright decls in some files to point to LICENSE file.
14. Add notes to RELEASENOTES.md

### CODE REVIEW

**Comment by WardF** [comment]
Seeing a failure on OSX; in `test_common.sh`, `uname -o` fails.  `-o` isn't a legal argument to uname on OSX it seems.  I don't have access to a cygwin environment at the moment;  is the `-o` strictly required?

**Comment by DennisHeimbigner** [comment]
The -o is supposed to return the operating system name.
Is there an OSX equivalent?

**Comment by WardF** [comment]
Ah; the equivalent on OSX is `-s`, or `uname` with no arguments.

**Comment by DennisHeimbigner** [comment]
Wht do you get under OSX if you use this command?
	uname | cut -d '_'  -f 1
=Dennis

**Comment by WardF** [comment]
:~$ uname | cut -d '_'  -f 1
    Darwin
    :~$

**Comment by WardF** [comment]
I'll merge this next ASAP so that we can quit worrying about merge failures.

**Comment by WardF** [comment]
4 of the tests failed; it wasn't across the board. I've restarted the failed ones to see if it was something on their side.  Travis is currently reporting 2 issues, although I haven't checked to see what they are.  If those failures persist I'll take a look at what those configurations are and see if there's an obvious reason for the tests to fail.

**Comment by WardF** [comment]
Checks have passed.  Running it through on OSX, ARM and Windows next.

**Comment by WardF** [comment]
Still seeing a failure due to a call to `uname -o` in `tests_common.sh`.  Did the fix for that get properly committed?

**Comment by DennisHeimbigner** [comment]
I believe it is fixed (modulo typos). The primary problems were as follows.
1. When running using visual studio under cygwin, it is possible to get visual-studio
   code trying to open a cygwin path  (e.g. /cygdrive/...) and this causes an  error.
   Fix is to add code tp to examine the incoming path for this situation and do a  conversion.
   This was ocurring in libdap4/d4read.c, but may occur elsewhere.
2. Shell scripts in the git repo are not being  checked-out with the executable mode set. Had
   core.filemode set to false.  Was a major hassle to fix.

**Comment by WardF** [comment]
Seeing some failures on Visual Studio where bash is available on the path; there are some problems with the shell scripts it looks like.  The results are viewable here:

* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=885

I will take a look at this and see what is going on.  I know when I was first porting netCDF to Visual Studio/Windows, I encountered a number of issues stemming from how paths are determined in cygwin/linux vs. path substitution under an msys shell.

**Comment by WardF** [comment]
On OSX with an autotools-based build, I'm seeing the following compilation failure:

> libtool: link: gcc -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libnetcdf.11.dylib .libs/libnetcdf_la-nc_initialize.o   -Wl,-force_load,../libdispatch/.libs/libnetcdf2.a -Wl,-force_load,../libdispatch/.libs/libdispatch.a -Wl,-force_load,../libsrc/.libs/libnetcdf3.a -Wl,-force_load,../libdap2/.libs/libdap2.a -Wl,-force_load,../oc2/.libs/liboc.a -Wl,-force_load,../libdap4/.libs/libdap4.a -Wl,-force_load,../libsrc4/.libs/libnetcdf4.a  -L/Users/wfisher/local-serial/lib /Users/wfisher/local-serial/lib/libhdf5_hl.dylib /Users/wfisher/local-serial/lib/libhdf5.dylib -ldl -lm -lz -lcurl    -install_name  /usr/local/lib/libnetcdf.11.dylib -compatibility_version 12 -current_version 12.4 -Wl,-single_module
duplicate symbol _nc_utf8proc_utf8class in:
    ../libdispatch/.libs/libdispatch.a(libdispatch_la-dutf8.o)
    ../libdispatch/.libs/libdispatch.a(libdispatch_la-utf8proc.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am not observing this on Linux, or cmake-based builds under OSX.  I tested with both `gcc` and `clang` on both platforms, in case it was compiler-specific optimization, but the results were the ame.

**Comment by DennisHeimbigner** [comment]
I have discovered that there is a problem when
using visual studio in a cygwin environment.
This is because you can sometimes pass /cygdrive/d/...
paths to e.g. open instead of d:/...
Could this be what you are seeing?
=Dennis

**Comment by DennisHeimbigner** [comment]
RE OSX and utf8, what happened to the new utf8 code?

**Comment by WardF** [comment]
> RE OSX and utf8, what happened to the new utf8 code?

Nothing that I'm aware of or that was explicitly done.  I *assume* it's still in there, although now I'm questioning that based on your comment.

**Comment by WardF** [comment]
Ok the utf8 issue on OSX isn't specific to this pull request it's in the master branch too. Fixing.

**Comment by WardF** [comment]
Got almost all of the tests working but there is still one failing, dap4_test/test_raw.sh.  Details here:

* http://cdash.unidata.ucar.edu/testDetails.php?test=23046&build=950

The fix is not obvious to me and I'm uncertain how to address this. It works on other platforms.

**Comment by DennisHeimbigner** [comment]
can you give the full commit # for 8c48ac9
I cannot seem to find it.

**Comment by DennisHeimbigner** [comment]
Ok, the proximate problem for the test_raw case is that the path
> [dap4]file:/g/netcdf-c/dap4_test/daptestfiles/test_anon_dim.2.syn
is apparently converted somewhere to this (judging by the error message):
>  [dap4]file;g:\netcdf-c\dap4_test\daptestfiles\test_anon_dim.2.syn
Note the change of 'file:/g/...' to 'file;g\...' ; where is that semicolon coming from?
It must be the path change code I added in libdap4/d4read.c
 It appears that the mingw compiler (and runtime?) is being used, correct?
But what is the Operating system: windows? Linux?

**Comment by WardF** [comment]
It is Windows but in an MSYS environment; I believe the issue is the same one I alluded to at our last meeting, i.e. path expansion by the underlying system. Cygwin does it one way, bash via MSYS does it a different way.  I *was* able to work around this though, but that was in my first 6 months so it has been a while and I don't recall exactly how.

**Comment by DennisHeimbigner** [comment]
I should be able to fix d4read.c but I need two
compile or runtime flags to test for:
1. running under windows os -- presumably __WIN32 will do this
2. compiled under mingw -- what flag is available for this?

Also, need the path form that mingw provides" It looks like
g:\... is provided by mingw as /g/... correct?
=Dennis

**Comment by WardF** [comment]
Dennis, It appears I left my external drive with my windows VM on it at home, so I will confirm my answers later and answer as best I can now.

The path expansion isn't mingw specific, but a side effect of the underlying environment, so the /g/ expansion we are seeing is a function of the `MSYS` environment.  That said, mingw is a fork of gcc so you could check for that perhaps?  

The rules and examples of MSYS path expansion are outlined here:

* http://www.mingw.org/wiki/Posix_path_conversion

Running under Windows can be checked with `__WIN32`, and Visual Studio specifically can be checked with `_MSC_VER`.

**Comment by DennisHeimbigner** [comment]
ok, As near as I can tell there is no MSYS equivalent to the __CYGWIN__
flag, so I guess I will have to assume that __MINGW32__ => MSYS

**Comment by DennisHeimbigner** [comment]
ok, the problem is how it treats file:/... urls. If the URL
is of the form file:///..., it should work ok. So initially,
I am going tp make that fix.

**Comment by DennisHeimbigner** [comment]
The changes you made to test_common.in are incorrect. It breaks the use of visual studio
as the compiler. You clearly have a situation in which VS (e.g. /Debug) should
not be part of the path. If so, then we need to test specifically for that case.
Can you characterize what case you have?

**Comment by WardF** [comment]
In what way is it broken? It works properly across my various visual studio installs. Appending '/Debug', '/Release',etc and updating cmakelists.txt to use these directories fixes test_common.in but breaks every other test script insofar as they look for '../ncdump/ncdump', not '../ncdump/[build type]/ncdump'.

**Comment by DennisHeimbigner** [comment]
That is why the macros ${NCDUMP}, ${NCGEN}, etc are defined
in test_common
so they isolate the test scripts. I thought I changed
all the test scripts to use e.g. ${NCDUM} instead of
e.g. ../ncdump/ncdump; did you undo those changes?
=Dennis

**Comment by WardF** [comment]
I did not. I'm still confused why test_common.sh is appending the build type to the path; the build type directory structure format has been suppressed for quite a while; since Russ was here at least. The reason I removed it  is that since the convention is unused in both Visual Studio builds and *nix builds, I wasn't sure what purpose it served.

**Comment by DennisHeimbigner** [comment]
My bad for not explaining.
When I use visual studio under cmake
in a cygwin environment, the e.g. /Debug
or /RelWithDgInfo directory is where compiled
executables end up. I know that it is unused
by cmake when using gcc (and I speculate mingw).
I infer from what you are saying that there is some
way to tell visual studio not to use the mode
as part of the path, correct?
=Dennis

**Comment by DennisHeimbigner** [comment]
Ok, I did a general cleanup of test_common including
your changes. Hope this gets things back on track.

**Comment by WardF** [comment]
I ran with the debug output you incorporated; you can see it here:

* http://cdash.unidata.ucar.edu/testDetails.php?test=25536&build=1063

I'll follow up, but does anything leap out at you?

**Comment by DennisHeimbigner** [comment]
The only thing I can figure is that the /g/... prefix is not
being interpreted as the equivalent of (I assume) g:/...
Does it fail in same way if you run
g:\netcdf-c\build\ncdump\ncdump.exe 
'[dap4]file:///g/netcdf-c/dap4_test/daptestfiles/test_anon_dim.2.syn'
directly on the command line?
I wonder if changing the path to
'[dap4]file:///g:/netcdf-c/dap4_test/daptestfiles/test_anon_dim.2.syn'
would work?
=Dennis

**Comment by WardF** [comment]
Error in readfile(), line ~168, failure at fd=open(filename,flags);.

> filename	0x00000220948817a0 "/g/netcdf-c/dap4_test/daptestfiles/test_anon_dim.2.syn.dap"	char *

fd is -1.

**Comment by WardF** [comment]
The following works:

> ncdump.exe [dap4]file://g:\\netcdf-c\\dap4_test\\daptestfiles\\test_anon_dim.2.syn

also,

> ncdump.exe "[dap4]file://g:\netcdf-c\dap4_test\daptestfiles\test_anon_dim.2.syn"

works in the MSYS shell as well.

Is there a way to force the windows-style path, in the shell script? I'm having a bit of trouble unravelling the shell scripts at a glance and might not have time to dive into it tomorrow, but I can investigate this as well.

**Comment by DennisHeimbigner** [comment]
ok that is progress; Will it still work if those backslashes are 
converted to forward slashes e.g.
ncdump.exe 
'[dap4]file://g:/netcdf-c/dap4_test/daptestfiles/test_anon_dim.2.syn'

**Comment by DennisHeimbigner** [comment]
ILooking at this page,
http://stackoverflow.com/questions/12015348/msys-path-conversion-or-cygpath-for-msys
it claims that MSYS2 has a version
of cygpath  that might resolve this problem.

**Comment by WardF** [comment]
It looks like cygpath is an msys2 thing, which I was not not aware of.  I'm installing now to give this a try.

**Comment by DennisHeimbigner** [comment]
Does that mean you have been using msys and not msys2?
=Dennis

**Comment by WardF** [comment]
Ok. Running from the msys2 shell causes more failures, but running the same tests from the same directory (using the code built with msys2) in msys1 doesn't fail.  I'll try to sort this out soon.  In regards to `cygpath`, however, it is very useful.  It generates a windows-style path which can then be passed and should work based on what we've already seen (I'll confirm that shortly).

**Comment by WardF** [comment]
ok. So I've confirmed that the following works in msys1 and I'll assume msys2 for now:

> $ ../ncdump/ncdump [dap4]file://$(cygpath -w /g/netcdf-c/build/dap4_test/daptestfiles/test_vlen8.nc)

So how to codify this? Currently, the shell scripts only run if `bash` is available. If we can determine that the environment msys *and* `cygpath` exists (in addition to `bash` being available) then run the test, otherwise don't.

Running `uname -a` in msys1 and msys2 gives the following, respectively:

> MINGW32_NT-6.2 LIVINGSTON 1.0.19(0.48/3/2) 2016-07-13 17:45 i686 Msys
> MINGW64_NT-10.0 livingston 2.7.0(0.306/5/3) 2017-02-14 08:57 x86_64 Msys

So perhaps a conditional on Msys in uname?

**Comment by WardF** [comment]
ddap4 worked, is it all inclusive of dap4.dmh?

**Comment by DennisHeimbigner** [comment]
I think so; I can just mergeit into dap4.dmhif you want.
=Dennis

**Comment by DennisHeimbigner** [comment]
Ok, I merged dap4.dmh into ddap4 so you can
either merge ddap4 back to dap4.dmh or just use ddap4
=Dennis

**Comment by WardF** [comment]
Merged; congratulations Dennis, this is great to get this into netcdf-c!  I appreciate all your help getting things working.  I should have asked, does netCDF-Java support DAP4 yet?

**Comment by DennisHeimbigner** [comment]
Yes, the java side should be working. But more important
is that the c code can talk to the thredds server.
=Dennis

**Pull request merged**
