### PR TITLE
Split HDF5 code from libsrc4 code

### LINKED ISSUE #856: Separate internal netCDF-4 data model from HDF5 code
As discussed in PR #849, it will soon be possible to separate the internal netCDF-4 data model code (i.e. lists of atts, vars, and dims, and the functions that manipulate them) from the HDF5 code. I add this issue so that there is a place to discuss the worthiness and possible implementation of this goal.

This would enable user-defined formats (#177) and the HDF4 layer to work without HDF5. It would also be a useful simplification of the code which would make the libsrc4 code smaller and easier to maintain.

*After* this ticket has been accomplished several other opportunities present themselves:

* DAP has it's own internal data model (I believe), and at some point it could be simplified by using the common data model.

* The classic code in libsrc uses a separate but related implementation of the data model. This too could eventually be removed, so that all parts of the library were using the same internal data structs.

### LINKED ISSUE #926: nc_delete_mp() uses NC3_DATA macro, but is not a dispatch table function
Here's something I ran into while doing the HDF5/libsrc4 conversion. I also have the easy fix.

In libsrc/nc3internal.c we have:

```
/**************************************************/
int
nc_delete_mp(const char * path, int basepe)
{
	NC *nc;
	NC3_INFO* nc3;
	int status;
	int ncid;
	size_t chunk = 512;

	status = nc_open(path,NC_NOWRITE,&ncid);
        if(status) return status;

	status = NC_check_id(ncid,&nc);
        if(status) return status;
	nc3 = NC3_DATA(nc);

	nc3->chunk = chunk;

#if defined(LOCKNUMREC) /* && _CRAYMPP */
	if (status = NC_init_pe(nc3, basepe)) {
		return status;
	}
#else
	/*
	 * !_CRAYMPP, only pe 0 is valid
	 */
	if(basepe != 0)
		return NC_EINVAL;
#endif

	(void) nc_close(ncid);
	if(unlink(path) == -1) {
	    return NC_EIO;	/* No more specific error code is appropriate */
	}
	return NC_NOERR;
}
```

Note that we are applying NC3_DATA macro, and then modifying the "chunk" field within it.

Problem is, this is not a dispatch function. ;-) So it is also called by nc_test when testing netCDF-4 files. The setting of nc3->chunk changes some random part of the netcdf-4 structure, which happens to have no effect (or didn't, until I did the HDF5/libsrc4 conversion, and encountered this error).

The fix is simple - there is no reason to be messing with nc3->chunk, as the file is about to be deleted. I simply removed the two lines of code.

```
	nc3 = NC3_DATA(nc);
	nc3->chunk = chunk;

```

The fix for this will be part of my PR for #856. I wanted to high-light this change since it is in the classic code, outside the libsrc4 directory where all the rest of the #856 changes will be found.

### PR DESCRIPTION
**Pull request by edhartnett**
This has been discussed a lot already, so I will summarize: the goal is to split the HDF5 code from the libsrc4 code. This is to support user-defined formats. The user-defined formats will use the libsrc4 code, but not the HDF5 code.

Fixes #926.
Fixes #856.
Part of #177.

### CODE REVIEW

**Comment by edhartnett** [comment]
The travis failure here was the HDF5 plugin copy problem.

**Comment by DennisHeimbigner** [comment]
This change will take a lot of time to review. So you will have to wait a bit.

**Comment by edhartnett** [comment]
@DennisHeimbigner I tried to make minimum changes to achieve the goal, but there were quite a few.

These changes were suggested by, and helpful to, user-defined formats, but are not actually required. I can also submit the user-defined format changes as a separate PR. However I don't want to overload you guys with changes so I will wait a bit for that.

**Comment by edhartnett** [comment]
I have brought this PR up to date with master, including merging in changes from PR #934.

**Comment by edhartnett** [comment]
@DennisHeimbigner any progress on taking a look at this? I would like to get it merged and put up my user-defined formats PR. Thanks.

**Comment by edhartnett** [comment]
I believe I must take this down and re-do it, in light of all the changes to the code since I submitted it.

@DennisHeimbigner do you have any more libsrc4 changes underway? I would like the next time I re-do this to be the final time, if that's OK.

**Comment by DennisHeimbigner** [comment]
I can hold off until your mod is completed.
I assume that, for now, the form of the split off fields
of NC_HDF5_FILE_INFO are left as in in the new split off
structure so that at least you do not have to do anything more
than changes some occurrences of NC_HDF5_FILE_INFO
to be the new structure type.

**Comment by edhartnett** [comment]
@DennisHeimbigner I have retreated from my giant PR and will present these changes in more manageable bites.

In my first PR I move some files and create the new libhdf5 directory. in the next PR I will add all the other new files needed, and move some functions around.

Once those changes are merged, the rest of the changes will be much less sensitive to others making changes on the code. When a function is moved to a new file in another directory, git loses all track of it.

Thanks!

**Pull request closed without merging**
