### PR TITLE
Attempt to fix the problem of ftp failing when getting the hdf4 from our ftp site.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
Solution used here is to repeat the request
and to use the wget -c flag so we do not
start over on every retry.

### CODE REVIEW

**Comment by WardF** [comment]
I'm seeing a failure in `tst_remote3`.  Details here:

* http://cdash.unidata.ucar.edu/testDetails.php?test=59828&build=1585

**Comment by WardF** [comment]
I'm also seeing a failure in `tst_fileinfo.sh` when running `make check` with an 
autoconf-based build.

**Comment by WardF** [comment]
The test failure in `tst_remote3.sh` appears to be OSX only.

**Comment by WardF** [comment]
I think I have the issue resolved.

**Comment by DennisHeimbigner** [comment]
We probably need to get this integrated ASAP since travis is failing on the
get of the hdf4 test files pretty often.

**Pull request merged**
