### PR TITLE
Add --is-parallel option and output to nc-config

### PR DESCRIPTION
**Pull request by gsjaardema**
It is useful to be able to determine whether the netcdf library has parallel capabilities enabled.  Currently can look at netcdf_meta.h, but would be useful be able to get information from nc-config since that is how most other options settings are displayed.

### CODE REVIEW

**Comment by WardF** [comment]
Looks good and makes sense, thanks Greg! We already have the pnetcdf related option, so in conjunction there should be enough information provided to determine whether or not the parallel is netcdf3 or netcdf4.

**Comment by gsjaardema** [comment]
Thanks, sorry for typo in pull request name should be "--has-parallel" instead of "--is-parallel"

**Comment by WardF** [comment]
Updating the `nc-config.in` file for autotools-based builds, and then will merge into v4.5.0-release-branch

**Comment by WardF** [comment]
This was merged manually by hand and is in `master`; thank you very much!

**Pull request closed without merging**
