### PR TITLE
CI: Add Cygwin CMake run

### PR DESCRIPTION
**Pull request by DWesl**
Largely copied from MehdiChinoune's MSYS CMake CI run (#2917).

Doesn't enable DAP, and skips nc_test4_tst_filter due to a failure I don't understand and can't reproduce locally.

Largely in line with the Autotools build otherwise, except the skipped test works under Autotools (it's marked XFAIL for MINGW there).

### CODE REVIEW

**Comment by DWesl** [comment]
I suspect the DAP failure in libcurl on Linux is unrelated.

**Comment by WardF** [comment]
Still trying to figure out what's going on here, as the DAP issue (whether related or not) is not occurring on other branches.

**Comment by DWesl** [comment]
The Ubuntu failure looks like a network issue, and the MacOS failures passed on the re-run, so I'm not sure what's going on there.  On the other hand, the DAP/libcurl issue seems to have gone away.

**Comment by WardF** [comment]
Yeah. This is all very puzzling and not exactly a confidence builder in Github Actions.

**Review by WardF — APPROVED** [review]

**Pull request merged**
