### PR TITLE
nczarr phase 1 checkpoint

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
This branch/PR provides an initial checkpoint for the nczarr code.

* The basic code base follows along the path setup by Ed
  when he split libhdf5 from libsrc4.
	- libsrc4 manages the implementation-independent meta-data
	- libhdf5 annotates the meta-data data structures of libsrc4
          and communicates with HDF5.

* The libnczarr code base was constructed by:
  1. copying libhdf5 to libnczarr
  2. remove the HDF5 specific code to be replaced with nczarr-specific code.
  3. refactor to futher separate the nczarr code from the netcdf4 support code.

* libnczarr defines a "zmap" API which supports what is essentially a
  an abstraction of the Amazon S3 API
  1. Implements tree-structured keys mapping to "objects"
	e.g. /x/y/g => object containing data
  2. Implement read/write of object contents
  3. Provide separate read/write of "metadata" objects vs data objects.
  4. Serves as the lowest level IO API for read/write to cloud/file/etc.

* For testing, implement a version of zmap that simulates S3 using
  a netcdf-4 file
  1. Each object is stored as a netcdf-4 group whose full-path is the
     key of that object.
  2. Meta-data is stored as an attribute of the group/object so that
     ncdump will show it for testing
  3. Data is stored as a ubyte-valued variable to store the data of
     the object.

* Zarr metadata objects
  - .zgroup - Json Dict marking zarr group objects
  - .zarray - Json Dict containing array (== variable) information
  - .zattrs - Json Dict containing the values of attributes both at
              group and variable level.

* Extra netcdf-4 meta-data is stored in additional objects
  - _nczarr - Dict that serves as a "superblock" to store global information
  - _nczgroup - Dict that stores netcdf-4 information for a group
	-- dims - list of dimension names defined in the specified group
	-- vars - list of variable names defined in the specified group
	-- grps - list of subgroup names defined in the specified group
        [Goal is to avoid S3 level searches]
  - _nczvar - Stores extra netcdf-4 info about variables
	-- dimrefs - Stores the fullpath names of the dimensions referenced
                  by a variable(.zarray). This is necessary since .zarray
                  only stores the dimension sizes.
	-- contiguous - stores the contiguous flag since it is unclear
                        if nczarr supports notion of NC_CONTIGUOUS.
  - _nczattr - Stores extra netcdf-4 info about per-group or per-variable
               sets of attributes.
	-- types - stores the types for attributes sets:
		dict of attrname X type

* Issues:
  1. lazy attribute reading is tricky because in the zarr format
     it is all or nothing.
     - so the extra info (_ncz...) is not stored as a zarr attribute
       so that attribute lazy reading can occur.
     - attributes like _FillValue require some special handling
	(still not quite right)

* Limitations
  1. only implements netcdf-4 atomic types except NC_STRING.
     => more or less the CDF5 type system
  2. NC_STRING and user defined types are completely ignored until
     zarr v3 addresses the issue.
  3. Filters and Compressions are not implemented.
  4. No unlimited dimensions

* Support for pure zarr
  * Requires producing simulated data when _nczXXX objects is missing:
    - simulated _nczarr: get the zarr version from the root group, use library
                         built-in value for nczarr_version
    - simulated _nczcontent: Assume we have a group whose key is e.g. /y/z/g
	dims: All variables whose shape is, say, (m,n),
	      create dimensions in the root group of form dim_m=m and dim_n=n
	vars: collect values of X for all keys of form "/y/z/g/X/.zarray"
	grps: collect values of X for all keys of form "/y/z/g/X/.zgroup"
    - simulated _nczvar - contains netcdf-4 specific information for a variable
	- dimrefs: Using the shape of the variable to figure out the dim names
	- contiguous is always false
    - simulated _nczattr: infer attribute type from the values of the attribute
		   (process is somewhat complex and is similar to algorithm
                    in ncgen)
* Partial list of TBD:
  - get/put_vara/vars
  - various uncommon API functions:
	- e.g. meta-data renaming and attribute deletion

* Specifying nczarr files to ncgen and ncdump
  - use fragment mode: e.g. file:///x.ncz#mode=nczarr

* Status
  1. Meta data is being properly written and read
  2. The content data of variables is not yet supported.
  3. ncgen and ncdump -h work with some limitations
  4. Much testing is needed
	- move and modify tests from the ncdump and the nc_test4
          directies to nczarr_test

### CODE REVIEW

**Comment by WardF** [comment]
Thanks Dennis.  There are a few conflicts but I'll take a look at them.

**Comment by WardF** [comment]
Working in a different branch now on the Unidata repo to resolve conflicts and test.  @DennisHeimbigner do we want to merge this in to `master` at this point, once this is resolved? Or do we want to maintain a side branch in `Unidata/netcdf-c`?

**Comment by DennisHeimbigner** [comment]
I think we decided to keep it as a side branch fornow.

**Comment by WardF** [comment]
Sounds good. I've got a branch, `nczarr-merge.wif`, that has these changes merged in and the conflicts are fixed.  You might pull those back up in to your fork, and I will close this out!

**Pull request closed without merging**
