### PR TITLE
Changed attribute case in documentation

### LINKED ISSUE #2481: "coordinates" attribute spelling should be lowercase in NUG
Not to be too pedantic, but....the NUG [documentation](https://docs.unidata.ucar.edu/netcdf-c/current/attribute_conventions.html) in Appendix A spells the `coordinates` attribute name with an uppercase `C` where it is defined. The CF conventions, on which this attribute is based, always uses (AFAICT) lowercase for this attribute. I think the attribute case is non-negotiable so I suggest this one-character change be made in the NUG to avoid confusion. Also this give you a chance to go into the weekend knowing you've solved at least one issue today.

### PR DESCRIPTION
**Pull request by WardF**
Fixes #2481

### CODE REVIEW

**Comment by dopplershift** [comment]
Does this need to go to Unidata/netcdf as well?

**Comment by WardF** [comment]
A good question; also, @ethanrd how do we stand migrating over from the old doxygen-style NUG to the new format you've been working towards? We can probably do with a refresh of the published NUG, but in the meantime, it's unclear where to put changes :)

**Comment by ethanrd** [comment]
Oops! Sorry! Missed this when it came in.

I'm not sure why but "Coordinates" has always been an outlier in terms of case (along with "_FillValue" and a few others). However, it has been this way for a very long time and there are many, many existing datasets and tools that deal with the capitalization as it has been. So, while consistency might have us leaning towards changing it, I really don't think we should.

**Comment by ethanrd** [comment]
Oops! Sorry again!

I was thinking of "Conventions". Yes, "coordinates" is used widely in its uncapitalized form.

**Pull request merged**
