### PR TITLE
Fix common typos

### PR DESCRIPTION
**Pull request by tbeu**
Detected by https://github.com/vlajos/misspell_fixer

### CODE REVIEW

**Comment by WardF** [comment]
Thank you for this; I thought I had merged it.  I'll review it again and then take care if it.  Thanks!

**Comment by tbeu** [comment]
Yes, please review. I tried to be very carefully, espc. with those lines ```"Leave hieght misspelled ...```

**Comment by WardF** [comment]
I'm trying to merge this, but it appears that the repository is no longer available, and the patch it refers me to is empty.  Is this pull request still available on your end?

**Comment by tbeu** [comment]
It is here again [tbeu/netcdf-c](https://github.com/tbeu/netcdf-c/tree/fix-typos). Sorry for the delay.

**Comment by WardF** [comment]
Not at all! I apologize for the delay in getting to this.  We are a bit resource-constrained, but I didn't mean to take so long to review it.  Thanks for putting it back, I'll merge it shortly (famous last words).  I reviewed the changes yesterday and there were a couple of replacements I'll need to reject, but for the most part it looks great.  I didn't know about the misspell_fixer, so that's a great resource for my other projects!

**Pull request merged**
