### PR TITLE
S3 Mode url reconstruction defaults to wrong server type

### PR DESCRIPTION
**Pull request by mannreis**
We faced an issue when using ncdump to read Zarr from a S3 instance that is not hosted by AWS or Google.
```
ncdump -h https://bucket.s3.region.example.com/cmip6/CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r1i1p1f1/day/tasmin/gn/v20181015/#mode=zarr,s3
```
Noting the "dummy" host on the url of the command above, unfortunately it works. This is because on this [NC_s3urlrebuild](https://github.com/Unidata/netcdf-c/blob/main/libdispatch/dinfermodel.c#L908) call, `uri->host` is overwritten to the default: `storage.googleapis.com`.

In this PR:
- [NCS3SVC](https://github.com/Unidata/netcdf-c/pull/2947/commits/9b570f37e39009e5c2cbbfcabe32dfac2bfbd6e6) is re-declared, so that `NCS3UNK != NCS3GS` - fixing the issue.
- [Optional](https://github.com/Unidata/netcdf-c/pull/2947/commits/e6a26a28b3dea0885acc2d96c2f5bf5bf2ddf5f6): Added support to use the `host` of a `url` to infer `bucket` and `region` inference, similar to AWS.
- [Optional](https://github.com/Unidata/netcdf-c/pull/2947/commits/b010c57e10304110eef4f9ae682437b6b07e8b18): Unit test NC_s3urlrebuild

(edit: links)

### CODE REVIEW

**Review by WardF — APPROVED** [review]
Approved pending tests passing.

**Comment by WardF** [comment]
The failures appear unrelated to the PR, and are part of an issue we're fixing on the Unidata side. This looks good and will be merged shortly.

**Comment by WardF** [comment]
The certificate issue on our end is resolved so I'm re-running the jobs; hopefully this should all pass, and we'll get this merged! Thanks!

**Comment by DennisHeimbigner** [comment]
Thanks fo this. We did not support this case because we could find a test site.

**Review by DennisHeimbigner — APPROVED** [review]

**Comment by WardF** [comment]
The current failure is the result of a combination of two different PRs which both passed checks, but combined, are resulting in a strange error. Once we get that fixed we can re-run the checks and merge this. @DennisHeimbigner this is related to the anonymous dimension issue I reached out about.

**Pull request merged**
