### PR TITLE
Github issue 152: https://github.com/Unidata/netcdf-c/issues/152

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
User request to have all orphaned DAP2 attributes kept as netcdf
global attributes. This is primarily a change in the oc code
plus testcase dataset changes.

Result may be inconsistent with netcdf-Java output.

### CODE REVIEW

**Comment by WardF** [comment]
I can't merge this because the branch `issue152` was deleted.  Was this intentional and we no longer want to merge this?  Or should I restore the branch and handle the merge request?

**Comment by WardF** [comment]
I've restored the branch because GitHub presented a button to do it; if the button went away I'm not sure how to go about it.  But let me know if you intended to drop this pull request.

**Comment by DennisHeimbigner** [comment]
no, kill it; I discovered a major problem with it.
=Dennis

**Comment by WardF** [comment]
Done

**Pull request closed without merging**
