### PR TITLE
Enable metadata_perf test in CMake build

### PR DESCRIPTION
**Pull request by gsjaardema**
Currently defaults to enabled, can change top-level
CMakeLists.txt file to change default to disabled

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
I am a bit confused. I think it makes sense to make this test be off by default.
But looking at the code changes , it looks like it is being set to enabled by default.

**Comment by gsjaardema** [comment]
Not sure why cal is now not sign d. Has been on all previous PR. I try to sign again and doesn’t work.  Just gives me a page all filled out with no submit or other way to do anything.

**Comment by gsjaardema** [comment]
As best I can tell, I have signed the CLA multiple times and it has been working for a couple years up until this commit.

screen shot 2018-07-11 at 10 28 46 am

**Comment by WardF** [comment]
Yeah. This is weird.  I'll contact our admin on our end and see what's going on.

**Comment by WardF** [comment]
@gsjaardema there is a link under the CLA comment above: "Signed the CLA already but status is still pending? Let us recheck it".  Will you click the 'recheck' link and see what happens?

**Comment by gsjaardema** [comment]
@WardF I have clicked the `recheck` link before and just now and it doesn't seem to change anything.

**Comment by gsjaardema** [comment]
OK, I think the commits were made by "gdsjaar" insted of "gsjaardema" which is probably confusing the CLA.  I will try to fix...

**Comment by gsjaardema** [comment]
Redoing with correct commit address #1059

**Pull request closed without merging**
