### PR TITLE
nccopy must use defaulting when there are no -c parameters

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes https://github.com/Unidata/netcdf-c/issues/1436

It used to be that when no -c parameters were specified
(and the input was some variant of netcdf-3) that nccopy
let the netcdf-c library decide on any default chunking.
Now, it attempts to do it itself and is not doing it
correctly when unlimited dimensions are involved.

So fix is to revert to previous behavior.

Note: The chunking rules are getting too complicated; consider revising.

### CODE REVIEW

**Comment by WardF** [comment]
@DennisHeimbigner Would you mind updating the RELEASE_NOTES.md with a note regarding this? I can also merge it and then update the file if that's easier. Thanks!

**Comment by DennisHeimbigner** [comment]
ok, will do.

**Comment by DennisHeimbigner** [comment]
Ok, Updated RELEASE_NOTES

**Comment by WardF** [comment]
Well, merging after travis succeeds.  It had succeeded before, not sure why it failed now, restarted the tests.

**Pull request merged**
