### PR TITLE
adjust tests and utils for split of libsrc4 and libhdf5

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #856.

Now getting tests and utils to deal with split of libsrc4 and libhdf5.

With --disable-hdf5, libsrc4 still builds, but not libhdf5, h5_test, and nc_test4. Essentially this is the same as --disable-netcdf-4, but it will be possible to build with HDF4 and not HDF5.

Also it seems that DAP4 should work without HDF5. But right now it does not. In builds where --disable-hdf5 is used, I have automatically turned off DAP4. I would like to change that eventually, so the user could build with dap4 but without HDF5. (@DennisHeimbigner that should be possible, correct?)

The problem now is that ncdump is used for the tests, and it is not yet handling enhanced model features in the absence of HDF5. In many cases the pre-processor macro USE_NETCDF4 needs to be changed to USE_HDF5 in the ncdump code. 

This PR is in the queue behind #1231 and includes that PR as well.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
WRT DAP4, I have been waiting for you to finish the split.

**Comment by edhartnett** [comment]
@DennisHeimbigner OK, awesome! ;-) With this PR, the split is complete. Automake conditionals USE_HDF5 and USE_NETCDF4 are available, as are preprocessor defines in config.h.

**Comment by edhartnett** [comment]
@WardF can we get this merged soon? It is the last step in separating libsrc4 and libhdf5. Thanks.

**Comment by edhartnett** [comment]
Thanks @WardF !

**Pull request merged**
