### PR TITLE
Avoid optionaly depends on zip for NCZarr

### PR DESCRIPTION
**Pull request by mwestphal**

### CODE REVIEW

**Comment by WardF** [comment]
Thanks for this; we'll need to make the appropriate changes in `configure.ac` as well, to cover our bases for both build systems we support, but this looks good, thanks!

**Comment by mwestphal** [comment]
@WardF It looks like I need to sign a CLA, however, the CLA in the link is for an individual. Do you have a CLA for an entity ?

**Comment by WardF** [comment]
@dopplershift Do we have a CLA for entities?

**Comment by WardF** [comment]
@mwestphal Thanks, that's a good question, and the first time (to my knowledge) we've been asked.  Stand by while I get an answer for you :)

**Comment by WardF** [comment]
Thanks @dopplershift !  @mwestphal, the link to our entity CLA has been linked, [and again, here.](https://gist.github.com/dopplershift/957a0b9d1c713ad1ad765c8e4a79e3c1)

**Comment by mwestphal** [comment]
Here is the signed CLA, waiting for your signature. 
[CLA-UCAR.docx.pdf](https://github.com/Unidata/netcdf-c/files/10546912/CLA-UCAR.docx.pdf)

**Comment by WardF** [comment]
Thanks! Reviewing the PR's now that I've got a lingering issue taken care of and need to get caught up on PR's.  @dopplershift, the signed organizational CLA was provided above. What's our next step?

**Review by DennisHeimbigner — CHANGES_REQUESTED** [review]
It occurs to me that this change is not what I would expect.
The case I am concerned with is:
1. ENABLE_NCZARR_ZIP is on (which is the default)
2. libzip is not available.

The current code makes libzip required in this case, which I assume will cause
an error. I think that is inconsistent with our current practice.
It probably should remove the required flag and if the find_package(zip)
fails, then report a warning, but do not cause the build to fail.

**Comment by mwestphal** [comment]
This is indeed my intent. If a user require an option but the project can't provide it, an error is expected imo. But I'll let you the judge of it.

**Comment by mwestphal** [comment]
that is fair to turn it off by default imo.

**Pull request merged**
