### PR TITLE
Add provenance info for netcdf-4 files.

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
This consists of a persistent attribute named
_NCProperties plus two computed attributes
_IsNetcdf4 and _SuperblockVersion.
See the 'Provenance Attributes' section
of docs/attribute_conventions.md for details.

### CODE REVIEW

**Comment by WardF** [comment]
We're having a small problem with netcdf3-only builds; they're failing on some NC4 symbols.  Other than that it looks great, and thanks very much for updating the documentation! I've added a new stanza to the travis-ci config to run nc3-only tests as well as the nc4 tests, to catch this sort of link error in the future.

**Comment by DennisHeimbigner** [comment]
I always forget to check nc3 only and minus dap case. This time I remembered
to try cmake. let me take a look.

**Comment by DennisHeimbigner** [comment]
Ok, I think I fixed the nc3 only case. May be some parallel problems
since I have trouble testing those.

**Comment by WardF** [comment]
The tests are still failing for nc3-only, but I'll take a look and see if I can see what's going on; I'm sure it's just a simple fenceposting of nc4 stuff.  I'd like to get the new RC out Monday at the latest.  Thanks!

**Comment by DennisHeimbigner** [comment]
Weird; it works on my machine. Can you tell what configurations(s)
are failing?
=Dennis

**Comment by WardF** [comment]
The overview is here:

* https://travis-ci.org/Unidata/netcdf-c/builds/128162296

But rather than wade through that, the first 8 (the failing ones) are all being built with `-DENABLE_NETCDF_4=OFF`.  The failure being seen is

````
[ 42%] Building C object libdispatch/CMakeFiles/dispatch.dir/dv2i.c.o
[ 42%] Built target dap2
/root/netcdf-c/libdispatch/dv2i.c: In function 'ncvarputg':
/root/netcdf-c/libdispatch/dv2i.c:883:3: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
   imp = (ptrdiff_t*) malloc(ndims * sizeof(ptrdiff_t));
   ^
/root/netcdf-c/libdispatch/dv2i.c: In function 'ncvargetg':
/root/netcdf-c/libdispatch/dv2i.c:940:3: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
   imp = (ptrdiff_t*) malloc(ndims * sizeof(ptrdiff_t));
   ^
/root/netcdf-c/libdispatch/dv2i.c: In function 'ncattput':
/root/netcdf-c/libdispatch/dv2i.c:997:2: warning: conversion to 'size_t' from 'int' may change the sign of the result [-Wsign-conversion]
  const int status = nc_put_att(ncid, varid, name, datatype, len, value);
  ^
[ 42%] Built target netcdf3
[ 42%] Built target dispatch
Scanning dependencies of target netcdf
[ 42%] Building C object liblib/CMakeFiles/netcdf.dir/nc_initialize.c.o
Linking C shared library libnetcdf.so
CMakeFiles/netcdf.dir/nc_initialize.c.o: In function `nc_initialize':
/root/netcdf-c/liblib/nc_initialize.c:73: undefined reference to `NC4_fileinfo_init'
collect2: error: ld returned 1 exit status
make[2]: *** [liblib/libnetcdf.so.12.0.0] Error 1
make[1]: *** [liblib/CMakeFiles/netcdf.dir/all] Error 2
make: *** [all] Error 2
Error Caught: 2
````

The only thing I can think of is that it's either cmake-specific (which I'll check) or perhaps something hasn't been pushed to GitHub?

**Comment by DennisHeimbigner** [comment]
I bet I know what it is . ENABLE_FILEINFO should only be set if USE_NETCDF4 is set.
I bet I forgot to put that check in cmake.

**Comment by DennisHeimbigner** [comment]
BTW, the reason I forget cmake testing is because it basically does not work for
me so I have to rely on travis to do those checks.

**Comment by WardF** [comment]
It looks like there is something going on with Visual Studio-based builds; everything else looks great. I'll sort out what's going on with VS asap and get things merged.

**Comment by WardF** [comment]
There were some Visual Studio specific things that needed to be tweaked, but they were due to idiosyncrasies in VS.  Merged!

**Pull request merged**
