### PR TITLE
Better detection of corrupt hdf5, second take. 

### PR DESCRIPTION
**Pull request by WardF**
Merge in magic.dmh . See #405 for details.  Original pull request was merged then reverted, so a second pull request for the branch is the easiest way to handle merging it, once parallel test failures are fixed.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
To be sure I understand, we should be making the fixes to this pr/branch, correct?

**Comment by DennisHeimbigner** [comment]
So, I set up parallel hdf5 under centos using virtualbox.
Then I ran the magic.dmh branch (with the v4.5 branch merged).
One test fails: nc_test4/run_par_test.sh.
It apparently fails at nc_open_par in tst_parallel3.

**Comment by WardF** [comment]
Did you enable pnetcdf as well? I saw failures there too.

**Comment by DennisHeimbigner** [comment]
ok, I tried it using pnetcdf 1.8.1.
It failed on this (inside run_parallel_test.sh)
mpiexec -n 2 ./tst_parallel2
at line 171 (nc_open_par).

**Comment by DennisHeimbigner** [comment]
I did find one unitialized variable error in the code and fixed it in magic3.dmh.
Unfortunately, it does not appear to fix the errors.

**Comment by DennisHeimbigner** [comment]
Did you merge magic.dmh or magic3.dmh?

**Comment by WardF** [comment]
The original pull request was for `magic.dmh`.  I haven't looked at `magic3.dmh` at all.

**Comment by DennisHeimbigner** [comment]
Merged magic3.dmh changes back into magic.dmh

**Comment by RDorsman** [comment]
I am the original submitter of this issue, and I am hoping it will be included in the next official release.

I was investigating the 4.5.0-rc3 release, but I cannot find the improvements introduced in the magic.dmh and magic3.dmh branches in the release. This seems strange as the pull request is registered as being completed.

It looks like something went wrong and only one commit (out of the 7) was merged. To be specific: commit 999a41c which resolves the issue does not seem to be merged into the release branch.

Is this fix still on track for being included in the final 4.5.0 release?

**Comment by WardF** [comment]
Evaluating `magic.dmh` now to refresh my memory; `git log` shows that `999a41c` is part of that branch.  Depending on how things look it may go into 4.5.0 or it may be pushed to 4.5.1; we need to get 4.5.0 out fairly quickly.

**Pull request merged**
