### PR TITLE
improve parallel builds, fixed SEGFAULT for NULL parameter for nc_inq_format(), added testing, documentation

### LINKED ISSUE #616: Code commented out of nc_test4/tst_h_files3.c
This whole file is commented out. Not much point in having a test if it is just commented out.

I will uncomment this code and see if it runs, and if there is any reason it should not run every time tests are run.

### LINKED ISSUE #667: Compile warnings in libsrc
Some easy to fix warnings:

```
putget.c: In function ‘putNCvx_char_char’:
putget.c:892:15: warning: unused variable ‘fillp’ [-Wunused-variable]
         void *fillp=NULL;
               ^~~~~
attr.c: In function ‘dup_NC_attr’:
attr.c:149:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(attrp->xvalue != NULL && rattrp->xvalue != NULL)
     ^~
attr.c:151:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  return attrp;
  ^~~~~~

nc4var.c: In function ‘NC4_def_var_filter’:
nc4var.c:1155:19: warning: unused variable ‘dim’ [-Wunused-variable]
    NC_DIM_INFO_T *dim;
                   ^~~
ocread.c: In function ‘readfile’:
ocread.c:209:9: warning: unused variable ‘flags’ [-Wunused-variable]
     int flags = 0;
         ^~~~~
ocread.c:207:10: warning: unused variable ‘buf’ [-Wunused-variable]
     char buf[1024];
          ^~~
ocnode.c:9:27: warning: ‘MAX_UINT’ defined but not used [-Wunused-const-variable=]
 static const unsigned int MAX_UINT = 0xffffffff;
                           ^~~~~~~~
cvt.c: In function ‘convertFilterID’:
cvt.c:651:22: warning: unused variable ‘f’ [-Wunused-variable]
     struct FilterID* f;
                      ^
nctrunc.c: In function ‘main’:
nctrunc.c:15:10: warning: unused variable ‘pos’ [-Wunused-variable]
     long pos = 0;
          ^~~
driver.c: In function ‘main’:
driver.c:60:8: warning: unused variable ‘f’ [-Wunused-variable]
    int f = 0;
        ^
```

### LINKED ISSUE #670: Clean up for include/err_macros.h
I removed all the EXTRA_MEM_DEBUG stuff recently but missed a little in err_macros.h. I will remove.

### LINKED ISSUE #677: Improve testing for libsrc4/ncfunc.c
This code file has only 67% code coverage for testing, the lowest in the directory.

I will improve...

### LINKED ISSUE #678: nc_inq_format segfaults when passed a NULL for formatp
I found this while increasing test coverage in ncfunc.c under #677. When I try this code:

`      if (nc_inq_format(ncid, NULL) != NC_EBADID) ERR;
`

I get:
```

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b312a8 in NC3_inq_format (ncid=65578, formatp=0x0) at nc3internal.c:1599
1599		    *formatp = NC_FORMAT_CLASSIC;
```

I will fix.

### LINKED ISSUE #681: h5_test/tst_h_rd_cmp can be combined with tst_h_wrt_cmp to eliminate dependency
The test file h5_test/tst_h_rd_cmp.c used the output from tst_h_wrt_cmp.c. This creates a dependency between the tests. These are short code files, so no need to have this test in two code files. The read test simply reads what the write test produces.

I will combine these tests and eliminate tst_h_rd_cmp.

### LINKED ISSUE #682: ncdap_test fails when built with --disable-utilities
This turned up on my jenkins CI matrix, a feature I just discovered, which is AWESOME.

Anyway, it turns out that some tests in ncdap_test use the utilities, but are not protected in the Makefile.am in case the utilities are not built. Easy fix. I will add it to my current PR.

### LINKED ISSUE #684: Clear up dependency between ncdump tests tst_netcdf4.sh and run_ncgen_tests.sh
Recently we cleared up a bunch of dependencies in the ncdump testing. This allows us to use parallel builds. Now that the clutter has been cleared away, I can see that many of the remaining dependencies can also easily be eliminated. This is advantageous because each dependency must be tracked in both the autotools and cmake builds.

On casual inspection, I believe the dependency between tst_netcdf4.sh and run_ncgen_tests.sh is now reduced to the fact that they both create a test file c0.nc.

If I change the name of the test file in tst_netcdf4.sh, then I believe these two tests would be independent. I will check it out.

### LINKED ISSUE #685: Use build_bin_test_no_prefix on C tests in ncdump directory in CMake build
I recently changed the autotools build ncdump tests so that the test C programs are called from the shell scripts, instead of being directly called from the makefile.

In the CMake build I did not know how to stop cmake from running the C code as tests (i.e. in addition to the shell tests that are now running them.)

But studying some code of @WardF I now understand that I should be using build_bin_test_no_prefix() for the C test codes in the ncdump dir. This will shorten the build time by eliminating an unnecessary extra run of these C programs.

### LINKED ISSUE #687: Large file test issues in nc_test4/Makefile.am
In nc_test4/Makefile.am we have:

# Add these if large file tests are turned on.
```
if LARGE_FILE_TESTS
check_PROGRAMS += tst_large tst_large2
endif

```
Then, later in the file:
```
if LARGE_FILE_TESTS
check_PROGRAMS += tst_large
TESTS += tst_large
endif # LARGE_FILE_TESTS

```
So tst_large2 is being built but not run as a test. I will take a look.

### LINKED ISSUE #688: Remove dependency between run_utf8_nc4_tests.sh and run_utf8_tests.sh in ncdump
This will be another easy to remove dependency. run_utf8_nc4_tests.sh is reusing the same file names. Given unique names, these tests can easily run in parallel.

### LINKED ISSUE #689: tst_ncgen4.sh rerunning tests on classic format already run by tst_ncgen4_classic.sh
Same tests being run twice. I will eliminate the second run. The classic tests must remain in their own shell script to support non-netcdf4 builds, so I will change tst_ncgen4.sh so that it does not rerun the classic tests.

### LINKED ISSUE #690: Other dependency reduction in ncdump testing
Instead of entering each instance as an issue, here are some of the remaining dependencies that can now be removed in ncdump testing, cleaning up the autotools and cmake build and speeding up the build as well.

* tst_formatx4.sh and tst_formatx3.sh now use different test output names (since the last merge). I believe they are no longer needed in any dependency list.
* run_ncgen_tests.sh and run_ncgen_nc4_tests.sh use the same output file names. Changing them will remove dependencies.
* tst_ncgen_cycle.sh and tst_ncgen_diff.sh are neat scripts that are reused in several tests. They create .nc and .cdl files from a set of test files. Slight changes so that they use unique file names based on the process id ($$) will allow them to run in parallel.
* tst_outputs.sh uses the outputs from the very short run_ctest.sh. These two scripts can combined, removing a test script and a dependency.

In the end, the only dependencies that really make sense are that tst_nccopy.sh and tst_nccopy4.sh run after a bunch of the other tests. These tests use nccopy to copy around a list of files, and those files are produced by other tests.

Otherwise, all dependencies can be eliminated.

### LINKED ISSUE #693: ncdap_test fails for parallel builds
It's not noticed in our testing, but ncdap_test fails for parallel builds sometimes due to some dependencies between tests.

But travis has --disable-dap-remote-tests so doesn't see this. ;-)

I will take a look and see what I can do to make ncdap_test work with make -j check.

### LINKED ISSUE #695: Compile warnings for some large file tests.
With large file testing turned on, I see these warings:

```
../../../nc_test/tst_big_var6.c:88:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
      printf("error on start[0..2]: %d,%d,%d  j: %d, expected %d got %d\n",
                                    ~^
                                    %ld
      start[0], start[1], start[2], j, FIRST_VAL, data[j]);
      ~~~~~~~~                        
../../../nc_test/tst_big_var6.c:88:40: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
      printf("error on start[0..2]: %d,%d,%d  j: %d, expected %d got %d\n",
                                       ~^
                                       %ld
      start[0], start[1], start[2], j, FIRST_VAL, data[j]);
                ~~~~~~~~                 
../../../nc_test/tst_big_var6.c:88:43: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
      printf("error on start[0..2]: %d,%d,%d  j: %d, expected %d got %d\n",
                                          ~^
                                          %ld
      start[0], start[1], start[2], j, FIRST_VAL, data[j]);
                          ~~~~~~~~          
../../../nc_test/tst_big_var6.c:52:15: warning: unused variable ‘k’ [-Wunused-variable]
     int i, j, k;
               ^
../../../nc_test/tst_big_var6.c:52:9: warning: unused variable ‘i’ [-Wunused-variable]
     int i, j, k;
         ^
../../../nc_test/tst_big_var2.c: In function ‘test_big_var’:
../../../nc_test/tst_big_var2.c:95:31: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("error on start[0]: %d i: %d j: %d expected %d got %d\n",
                              ~^
                              %ld
          start[0], i, j, 42, data[i][j]);
          ~~~~~~~~              
../../../nc_test/tst_big_var2.c:109:36: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
        printf("error on start[0]: %d i: %d j: %d expected %d got %d\n",
                                   ~^
                                   %ld
        start[0], i, j, 19, data[i][j]);
        ~~~~~~~~                     
../../../nc_test/tst_big_var2.c:50:9: warning: unused variable ‘nval_in’ [-Wunused-variable]
     int nval_in;
         ^~~~~~~
../../../nc_test/tst_big_var2.c:49:9: warning: unused variable ‘nval’ [-Wunused-variable]
     int nval = 99;
         ^~~~
../../../nc_test/tst_big_var2.c:48:12: warning: unused variable ‘index’ [-Wunused-variable]
     size_t index[NUMDIMS];
            ^~~~~
```

All easy to fix. I will put fixes in my current open PR.

### PR DESCRIPTION
**Pull request by edhartnett**
This PR started with adding some testing for ncfunc.c, which revealed a SEGFAULT when a NULL parameter is passed to nc_inq_format(). This is fixed in this PR.

Also I continued work on autotools build system for smoother parallel builds. Many test dependencies are eliminated by ensuring that all tests use unique file names for test output. Parallel builds now work for builds with dap remote tests, and buildfiles are simplified by removal of unneeded dependencies.

Also took out some dead code and added doxygen documentation for the functions I touched.

Fixes #678.
Fixes #677.
Fixes #682.
Fixes #681.
Fixes #670.
Fixes #616.
Fixes #667.
Fixes #687.
Fixes #685.
Fixes #689.
Fixes #688.
Fixes #684.
Fixes #690.
Fixes #695.
Fixes #693.

### CODE REVIEW

**Comment by WardF** [comment]
Why did you remove tst_filters? That's part of the new code added by Dennis for multiple compression filters, I believe.  @DennisHeimbigner is that correct?

**Comment by edhartnett** [comment]
Sorry, didn't remove tst_filters, remove tst_formats. Just mistyped it in git commit comment. ;-)

I added tst_formats.c and am having some trouble getting it to work with travis. I also added a ref_.hdf4 file, and that seems to be part of the trouble. I will keep working it until I figure it out...

**Comment by DennisHeimbigner** [comment]
The file test_filters is part of the filter_test directory.
There is a specific ./configure flag to control if the tests
in filter_test are attempted: --enable-filter-tests
This defaults to off because this test is a bit tricky to run
automatically and as far as I recall, I was never able to get it to
run under cmake.
It looks like the equivalent option is not defined in CMakeLists.txt.
It should be and it should default to off. The relevant place it hould be used
is in nc_test4/filter_test/CMakeLists.txt.
See  how it is used in nc_test4/filter_test/Makefile.am.

**Comment by edhartnett** [comment]
OK, this is now working for both autotools and cmake builds.

As noted above, I did NOT remove tst_filters, just mistyped "tst_formats" in a commit comment. No tests were harmed in the production of this pull request.

The new tst_foramats is added to test nc_inq_foramt() and nc_inq_format_extended().

**Comment by edhartnett** [comment]
This PR is also passing my ARM-based testing.

**Comment by edhartnett** [comment]
I just merged in two other open PRs and closed them, to combine code for testing.

Re-running all tests now...

**Comment by WardF** [comment]
Evaluating now, thanks!

**Comment by WardF** [comment]
CMake configuration breaks using my automated scripts on Windows, but probably something basic.  I'll investigate.

**Comment by edhartnett** [comment]
OK, keep me in the loop. I am happy to revert some files to eliminate the problem and get the rest of the changes through, then I can circle back around to the problem area.

Unfortunately windows is the one giant gap in my CI. I don't have a windows machine with visual studio. Not sure if there is a free version I can use or whether I need to buy one...

**Comment by WardF** [comment]
The issue is only on Windows, so I'm sure it's pretty straightforward; I'll outline what I find and if it's something I can't fix myself. First avenue of investigation is my automated tools to see if they're doing something they shouldn't, now.

**Comment by DennisHeimbigner** [comment]
Ed, FYI the community edition of Visual Studio is free.

**Comment by edhartnett** [comment]
I have found an old windows laptop. I will fire it up and see what I can manage wrt visual studio community edition. ;-)

**Comment by WardF** [comment]
No prob I had to set this aside suddenly yesterday (son sick at school) but sitting down to it now:)

**Comment by WardF** [comment]
I found the issue, it's no big deal, when MSVC is true a property is being set that doesn't need to be set.  This is from some older cmake code that could do with cleaning up; cmake has come a long way since we started using it, plus I can refine a lot of what's been done.  I'll take care of it and get this merged, thanks!

**Comment by WardF** [comment]
Also FWIW I do my debugging/testing for Windows in a Win10 VM using VirtualBox, with no ill effects.

**Comment by edhartnett** [comment]
Well the problem with virtual machines is: when you get mad, what do you
kick? ;-)

**Comment by edhartnett** [comment]
@WardF hope your son is feeling better. ;-(

Meanwhile I have been working on PIO issues all day so still have not yet set up a test environment...

**Comment by WardF** [comment]
Running mpich parallel tests and then will merge.  @edhartnett one thing our (docker-based) regression testing does is it tests the Fortran, C++ and Python interfaces, as well as NCO (for non parallel builds) and parallel-netcdf (for parallel builds) against the particular C library being generated.  I don't know if that's something your Jenkins build is set up to do, and to be honestly it only rarely finds an issue, but it is pretty handy when it does.  

Thanks!

**Pull request merged**
