### PR TITLE
Fix HDF5_ZLIB check

### PR DESCRIPTION
**Pull request by avalentino**
It seems that the include path for HDF5 is not correctly set when checking for ZLIB support so the test fails even if ZLIB support is actually available in HDF5.

The check is performed via `CHECK_C_SOURCE_COMPILES` setting 
`CMAKE_REQUIRED_INCLUDES` to the value of `HAVE_HDF5_H`.
The problem is that `HAVE_HDF5_H` seems to be a flag that evaluates `ON`.
In this case using `HDF5_INCLUDE_DIR` should be the right thing IMHO.

### CODE REVIEW

**Comment by WardF** [comment]
Thanks! When the CI changes complete, I'll get this merged.

**Comment by WardF** [comment]
Looks like travis is stalled; I'll try to break up the logjam.

**Comment by avalentino** [comment]
It seems that the test on travis has been completed successfully [1].
Maybe it is just a sync problem with github.

[1] https://travis-ci.org/github/Unidata/netcdf-c/builds/689265705

**Comment by avalentino** [comment]
@WardF any news on this?

**Pull request merged**
