### PR TITLE
AUTOTOOLS BUGFIX: fixed BUILT_SOURCES dependency problem breaking make distcheck

### LINKED ISSUE #606: Improper handling of BUILT_SOURCES in ncdump/Makefile.am
I have been having troubles getting distcheck builds working on my Jenkins server, because of this issue.

In ncdump we have:
`BUILT_SOURCES = ctest.c ctest64.c
`

These are two tests either copied from another directory or generated with ncgen, depending on the value of EXTRA_TESTS.

As documented here https://www.gnu.org/software/automake/manual/html_node/Built-Sources-Example.html#Built-Sources-Example, we must mark these two files with a nodist_ qualifier, so that the automake system knows that they will not be part of the distibution:

```
nodist_ctest_SOURCES = ctest.c
nodist_ctest64_SOURCES = ctest64.c

```

The two files must also be added to the CLEANFILES macro so that they are properly cleaned up.

With these changes, make distcheck works fine under my Jenkins server.

I will put up a PR as soon as it runs through my CI testing...

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #606.

This PR fixes some missing dependency info in ncdump/Makefile.am. These missing dependencies are causing some of my make distcheck builds to fail, so should be fixed.

I have used emacs M-q to clean up indentation and white space of some lists in Makefile.am.

@WardF after this fix you should be able to use "make distcheck" in your travis testing, where you are now using "make all check distclean". Distcheck is much stricter, so better for testing.

### CODE REVIEW

**Comment by edhartnett** [comment]
This PR is failing because after the CMake build, travis is building the autotools build like this:

```
../../configure \
     \
    --enable-hdf4 --enable-extra-tests --enable-mmap  \
    --srcdir=../.. --prefix="$dc_install_base" \
```

I need to turn off --enable-extra-tests. How do I do that?

**Comment by DennisHeimbigner** [comment]
Ward is the expert, but you might try modifying .travis.yml

**Comment by WardF** [comment]
I would need to modify the docker container, or maybe it is in the .travis.yml file. Cmake is also turning on extra tests I believe, I’m surprised it is failing for one but not the other. But I’m also on my phone in Denver so can’t check the details at the

**Comment by WardF** [comment]
Moment. Didn’t mean to reopen sorry.

**Comment by edhartnett** [comment]
I have found a better way to do this. PR up tomorrow...

**Pull request closed without merging**
