### PR TITLE
After this PR, nc_set_log_level() will always be defined

### LINKED ISSUE #341: nc_set_log_level() should always be defined, but a no-op if logging is not enabled.
I regret the way that I implemented the nc_set_log_level() function. It is not included in the library unless logging is enabled.

This means that every client library has to keep track of whether this function is present or not, or provide a (no-op) version of the function to stop their links from breaking. 

This is happening to me right now with the PIO library:

CMakeFiles/pio_unit_test.dir/nc_set_log_level2.c.o: In function `nc_set_log_level2_':
/home/ed/pio3/ParallelIO/tests/unit/nc_set_log_level2.c:7: undefined reference to `nc_set_log_level'
collect2: error: ld returned 1 exit status

What I did with the PIO logging function, and what would make more sense with the netcdf one, is to always define the function, but just have it do nothing if logging is not defined. Then user code could use logging in development, and then just move the code to production without taking out the call to nc_set_log_level().

This is already the case with the LOG() macro (that is, it can be used in code, and will evaluate to nothing of logging is not enabled). But this is not true of the nc_set_log_level() function.

To execute the change is trivial, and I can submit a PR, but I wanted to see what the netcdf team thinks.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #341.

Now nc_set_log_level() is always defined, but a no-op when --enable-logging is not used.

Users who have defined their own copy of nc_set_log_level() to get around linking errors should drop their copy. If they don't want to, for some reason, --disable-set-log-level-func will cause behavior to continue in the old way - nc_set_log_level() will not be defined if logging is not used.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
It probably should be the case that all the #ifdefs in netcdf.h should be self-
contained in that they not depend on configuration options.
So, aside from #ifdef LOGGING, I also see these:
> #ifndef ncvarcpy
> #ifndef NO_NETCDF_2
> #ifndef NC_HAVE_RENAME_GRP
and
> #ifndef NC_HAVE_INQ_FORMAT_EXTENDED

**Comment by DennisHeimbigner** [comment]
Not obvious to me why we need the 
ENABLE_SET_LOG_LEVEL_FUNC
option. I assume that any user defined version
will have the same signature as ours, so having it
defined in netcdf.h should not be a problem.
If we do not have that option, what bad things happen?

**Comment by edhartnett** [comment]
@DennisHeimbigner I agree about the ifdefs in netcdf.h. I have entered a separate issue to address them.

The reason for EnABLE_SET_LOG_LEVEL_FUNC is to give a workaround in case users have defined their own nc_set_log_level(). It's not netcdf.h that is the problem, it is that nc_set_log_level will be defined in two places, and that will give a link error.

**Comment by DennisHeimbigner** [comment]
I see. I would think that the simplest solution is to just it to define/undefine
a macro renaming the uses of nc_set_log_level in our code only.

**Comment by edhartnett** [comment]
@DennisHeimbigner we do that in our test code.

The easiest thing to do for the user is just to delete their own definition of nc_set_log_level() and trust netcdf to provide it. The workaround is only present because if it were not, then there would always be that one user that asks for it...

**Comment by edhartnett** [comment]
I will take this down until some more important PRs get merged, so as not to clutter up the process.

**Comment by edhartnett** [comment]
@WardF can we get this one merged? I would like to put up the vara/vars changes next...

Thanks!

**Pull request merged**
