### PR TITLE
make UDF0 not require NC_NETCDF4

### PR DESCRIPTION
**Pull request by jedwards4b**
Offered as an alternative to #2585 this PR frees NC_UDF0 of the NC_NETCDF4 requirement and 
addresses the issue in #2582.   Note that I did not change the NC_UDF1.

### CODE REVIEW

**Review by WardF — DISMISSED** [review]

**Comment by WardF** [comment]
@DennisHeimbigner For some reason I can't tag you as a reviewer, so I'll ask more informally, any thoughts on this? :)

**Comment by DennisHeimbigner** [comment]
Basically we have two options:
1. remove the |= NC_NETCDF4 in libdispatch for UDF0 &/or UDF1 in dinfermodel.c 
2. add a new UDF2 that has no NC_NETCDF4 flag set.

I am not sure which option is the best.

**Comment by jedwards4b** [comment]
What is the status of this PR?  I can modify UDF1 as well if you like?   I've been continuing parallelio development based on this branch - just want some reassurance this will be accepted.

**Comment by DennisHeimbigner** [comment]
I think the right solution is to remove the NC_NETCDF4 flag from both UDF0 and UDF1 in ddispatch.c.,
and forget about adding UDF2.
Given the PIO situation, I think the possibility of back incompatibility is extremely small.

**Comment by jedwards4b** [comment]
While adding the UFD1 I discovered a problem in the magic number test.  I chose to handle this by not allowing user defined magic numbers with netcdf3 formats.  parallelio doesn't need any special magic numbers and other users of udf are probably defining new formats and not simply using a new dispatch table with the existing formats as I am.

**Comment by DennisHeimbigner** [comment]
I see that a lot of the changes are spacing changes,
which is unfortunate since it clutters up the diffs
and makes reading difficult.

**Comment by jedwards4b** [comment]
Sorry, I'll try to clean that up.

**Comment by jedwards4b** [comment]
The failing tests here are in dap.   I'm going to assume that my changes are not the cause - can you confirm?

**Comment by DennisHeimbigner** [comment]
Probably. They look like they are all caused by timeouts,
which probably means the remotetest server is slow.
You might try running the tests again to see if it goes away.

**Comment by jedwards4b** [comment]
I don't think that I have permission to rerun in your repo - can you trigger them please?

**Comment by DennisHeimbigner** [comment]
The simplest way is make a minor change in some file, RELEASENOTES.md for example
and then push that change. That will trigger a rebuild.

**Comment by dopplershift** [comment]
I'll retrigger, no need to run all 78 jobs.

**Review by WardF — APPROVED** [review]

**Comment by WardF** [comment]
Thanks @jedwards4b for the PR, thanks @DennisHeimbigner and @dopplershift for the help!

**Pull request merged**
