### PR TITLE
fixed H5O_info_t incompatiblity with H5Oget_info_by_idx3

### PR DESCRIPTION
**Pull request by brtnfld**
H5O_info_t should be H5O_info2_t when using H5Oget_info_by_idx3, otherwise tst_h_atts3 fails with HDF5 1.12

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
Does this work for CMake?

**Comment by brtnfld** [comment]
Yes, it's independent of the build system.

**Review by edwardhartnett — APPROVED** [review]

**Comment by brtnfld** [comment]
Is there something additional needed for this?

**Comment by WardF** [comment]
Nope, thanks!

**Pull request merged**
