### PR TITLE
Specify correct plugin suffix

### PR DESCRIPTION
**Pull request by gsjaardema**
CMake by default uses the ".so" suffix for libraries with the `MODULE` attribute.  Specify the desired suffix by setting the `SUFFIX` property explicitly on the plugin targets.  Fixes plugin install issue on Macs.

### CODE REVIEW

**Comment by gsjaardema** [comment]
NOTE: This should be included in 4.9.0

**Comment by DennisHeimbigner** [comment]
Thanks. I knew about the prefix, but did not realize that it also did suffix.

**Comment by DennisHeimbigner** [comment]
I just did a build under visual studio with cmake and indeed, the resulting
libraries have the .dll extension, so what specific problem did you encounter
where the extension was wrong?

**Comment by gsjaardema** [comment]
On my mac it was creating the plugins with the ".so" extension when the `MODULE` type was used in the `add_library` command.  It seems to give the correct suffix when `SHARED` is used; incorrect when `MODULE` used.

**Comment by DennisHeimbigner** [comment]
Ok. Well this fix should be implemented since it should not cause any problems.

**Comment by WardF** [comment]
Interesting to know, thanks!

**Pull request merged**
